import { mkdir, readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'

import { VE2_CONTRACT_ROOT } from './constants.mjs'
import { resetContractRegistryCache } from '../generate-ve-theme/contract-registry.mjs'
import { cssVarNameToSymbol } from '../generate-ve-theme/css-utils.mjs'

const GENERATED_VARS = path.join(VE2_CONTRACT_ROOT, 'utilities', 'generated', '_vars.css.ts')

export function collectUnmappedCssVars(skippedEntries) {
	const vars = new Set()
	for (const { warning } of skippedEntries) {
		const m = warning.match(/^\[UNMAPPED_VAR\] (--bs-[\w-]+)$/)
		if (m) vars.add(m[1])
	}
	return [...vars].sort()
}

function symbolForCssVar(cssVar, usedSymbols) {
	let symbol = cssVarNameToSymbol(cssVar)
	if (!usedSymbols.has(symbol)) {
		usedSymbols.add(symbol)
		return symbol
	}
	let n = 2
	while (usedSymbols.has(`${symbol}${n}`)) n++
	symbol = `${symbol}${n}`
	usedSymbols.add(symbol)
	return symbol
}

async function readExistingVarEntries() {
	const entries = new Map()
	try {
		const source = await readFile(GENERATED_VARS, 'utf8')
		const re = /export const (\w+) = createVar\(\)\s*(?:\/\/\s*(--bs-[\w-]+))?/g
		let match
		while ((match = re.exec(source)) !== null) {
			const cssVar = match[2] ?? null
			if (cssVar) entries.set(cssVar, match[1])
		}
	} catch {
		// no file
	}
	return entries
}

export async function ensureAutoVars(cssVars) {
	if (cssVars.length === 0) return { added: 0 }

	await mkdir(path.dirname(GENERATED_VARS), { recursive: true })
	const entries = await readExistingVarEntries()
	const usedSymbols = new Set(entries.values())
	const newVars = []

	for (const cssVar of cssVars) {
		if (entries.has(cssVar)) continue
		const symbol = symbolForCssVar(cssVar, usedSymbols)
		entries.set(cssVar, symbol)
		newVars.push({ cssVar, symbol })
	}

	if (newVars.length === 0) return { added: 0 }

	const lines = [
		"import { createVar } from '@vanilla-extract/css'",
		'',
		'// AUTO-GENERATED by generate-ve-theme-literal — unmapped --bs-* custom properties.',
		'',
	]

	const sorted = [...entries.entries()].sort((a, b) => a[0].localeCompare(b[0]))
	for (const [cssVar, symbol] of sorted) {
		lines.push(`export const ${symbol} = createVar() // ${cssVar}`)
	}

	await writeFile(GENERATED_VARS, `${lines.join('\n')}\n`, 'utf8')
	resetContractRegistryCache()
	return { added: newVars.length }
}
