import { createVar } from '@vanilla-extract/css'

export const varBsCardSpacerY = createVar()
export const varBsCardSpacerX = createVar()
export const varBsCardTitleSpacerY = createVar()
export const varBsCardTitleColor = createVar()
export const varBsCardSubtitleColor = createVar()
export const varBsCardBorderWidth = createVar()
export const varBsCardBorderColor = createVar()
export const varBsCardBorderRadius = createVar()
export const varBsCardBoxShadow = createVar()
export const varBsCardInnerBorderRadius = createVar()
export const varBsCardCapPaddingY = createVar()
export const varBsCardCapPaddingX = createVar()
export const varBsCardCapBg = createVar()
export const varBsCardCapColor = createVar()
export const varBsCardHeight = createVar()
export const varBsCardColor = createVar()
export const varBsCardBg = createVar()
export const varBsCardImgOverlayPadding = createVar()
export const varBsCardGroupMargin = createVar()
