// GERADO por scripts/gen-public-vars.mjs — NÃO editar à mão.
import { globalStyle } from '@vanilla-extract/css'
import { simplexScope } from './scope.css'
import { varBsBlackRgb, varBsBodyBgRgb, varBsBodyColorRgb, varBsBorderColor, varBsBorderRadius, varBsBorderRadiusLg, varBsBorderRadiusPill, varBsBorderRadiusSm, varBsBorderRadiusXl, varBsBorderRadiusXxl, varBsBorderStyle, varBsBorderWidth, varBsBoxShadow, varBsBoxShadowLg, varBsBoxShadowSm, varBsDangerBgSubtle, varBsDangerBorderSubtle, varBsDangerRgb, varBsDangerTextEmphasis, varBsDarkBgSubtle, varBsDarkBorderSubtle, varBsDarkRgb, varBsDarkTextEmphasis, varBsEmphasisColor, varBsEmphasisColorRgb, varBsFocusRingColor, varBsFocusRingOpacity, varBsFontMonospace, varBsGradient, varBsInfoBgSubtle, varBsInfoBorderSubtle, varBsInfoRgb, varBsInfoTextEmphasis, varBsLightBgSubtle, varBsLightBorderSubtle, varBsLightRgb, varBsLightTextEmphasis, varBsLinkColorRgb, varBsPrimaryBgSubtle, varBsPrimaryBorderSubtle, varBsPrimaryRgb, varBsPrimaryTextEmphasis, varBsSecondaryBgRgb, varBsSecondaryBgSubtle, varBsSecondaryBorderSubtle, varBsSecondaryColor, varBsSecondaryRgb, varBsSecondaryTextEmphasis, varBsSuccessBgSubtle, varBsSuccessBorderSubtle, varBsSuccessRgb, varBsSuccessTextEmphasis, varBsTertiaryBgRgb, varBsTertiaryColor, varBsWarningBgSubtle, varBsWarningBorderSubtle, varBsWarningRgb, varBsWarningTextEmphasis, varBsWhiteRgb } from '../../theme-contract/_public-vars.css'

globalStyle(simplexScope, {
	vars: {
		[varBsBlackRgb]: "0, 0, 0",
		[varBsBodyBgRgb]: "252, 252, 252",
		[varBsBodyColorRgb]: "33, 37, 41",
		[varBsBorderColor]: "#ccc",
		[varBsBorderRadius]: "0.375rem",
		[varBsBorderRadiusLg]: "0.5rem",
		[varBsBorderRadiusPill]: "50rem",
		[varBsBorderRadiusSm]: "0.25rem",
		[varBsBorderRadiusXl]: "1rem",
		[varBsBorderRadiusXxl]: "2rem",
		[varBsBorderStyle]: "solid",
		[varBsBorderWidth]: "1px",
		[varBsBoxShadow]: "0 0.5rem 1rem rgba(0, 0, 0, 0.15)",
		[varBsBoxShadowLg]: "0 1rem 3rem rgba(0, 0, 0, 0.175)",
		[varBsBoxShadowSm]: "0 0.125rem 0.25rem rgba(0, 0, 0, 0.075)",
		[varBsDangerBgSubtle]: "#ebdaec",
		[varBsDangerBorderSubtle]: "#d7b5d9",
		[varBsDangerRgb]: "155, 71, 159",
		[varBsDangerTextEmphasis]: "#3e1c40",
		[varBsDarkBgSubtle]: "#bbb",
		[varBsDarkBorderSubtle]: "#adb5bd",
		[varBsDarkRgb]: "55, 58, 60",
		[varBsDarkTextEmphasis]: "#444",
		[varBsEmphasisColor]: "#000",
		[varBsEmphasisColorRgb]: "0, 0, 0",
		[varBsFocusRingColor]: "rgba(217, 35, 15, 0.25)",
		[varBsFocusRingOpacity]: "0.25",
		[varBsFontMonospace]: "SFMono-Regular, Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace",
		[varBsGradient]: "linear-gradient(180deg, rgba(255, 255, 255, 0.15), rgba(255, 255, 255, 0))",
		[varBsInfoBgSubtle]: "#ccebf5",
		[varBsInfoBorderSubtle]: "#9ad7ec",
		[varBsInfoRgb]: "2, 154, 207",
		[varBsInfoTextEmphasis]: "#013e53",
		[varBsLightBgSubtle]: "#fcfcfd",
		[varBsLightBorderSubtle]: "#ddd",
		[varBsLightRgb]: "255, 255, 255",
		[varBsLightTextEmphasis]: "#444",
		[varBsLinkColorRgb]: "217, 35, 15",
		[varBsPrimaryBgSubtle]: "#f7d3cf",
		[varBsPrimaryBorderSubtle]: "#f0a79f",
		[varBsPrimaryRgb]: "217, 35, 15",
		[varBsPrimaryTextEmphasis]: "#570e06",
		[varBsSecondaryBgRgb]: "221, 221, 221",
		[varBsSecondaryBgSubtle]: "white",
		[varBsSecondaryBorderSubtle]: "white",
		[varBsSecondaryColor]: "rgba(33, 37, 41, 0.75)",
		[varBsSecondaryRgb]: "255, 255, 255",
		[varBsSecondaryTextEmphasis]: "#666666",
		[varBsSuccessBgSubtle]: "#daeace",
		[varBsSuccessBorderSubtle]: "#b5d49c",
		[varBsSuccessRgb]: "70, 148, 8",
		[varBsSuccessTextEmphasis]: "#1c3b03",
		[varBsTertiaryBgRgb]: "248, 249, 250",
		[varBsTertiaryColor]: "rgba(33, 37, 41, 0.5)",
		[varBsWarningBgSubtle]: "#f7e6d2",
		[varBsWarningBorderSubtle]: "#f0cda5",
		[varBsWarningRgb]: "217, 131, 31",
		[varBsWarningTextEmphasis]: "#57340c",
		[varBsWhiteRgb]: "255, 255, 255",
	},
})
