import { globalStyle, style } from '@vanilla-extract/css'
import {
	varBsBlack,
	varBsBlackRgb,
	varBsBlue,
	varBsBodyBg,
	varBsBodyBgRgb,
	varBsBodyColor,
	varBsBodyColorRgb,
	varBsBodyFontFamily,
	varBsBodyFontSize,
	varBsBodyFontWeight,
	varBsBodyLineHeight,
	varBsBorderColor,
	varBsBorderColorTranslucent,
	varBsBorderRadius,
	varBsBorderRadiusLg,
	varBsBorderRadiusPill,
	varBsBorderRadiusSm,
	varBsBorderRadiusXl,
	varBsBorderRadiusXxl,
	varBsBorderStyle,
	varBsBorderWidth,
	varBsBoxShadow,
	varBsBoxShadowInset,
	varBsBoxShadowLg,
	varBsBoxShadowSm,
	varBsBtnCloseFilter,
	varBsCarouselCaptionColor,
	varBsCarouselControlIconFilter,
	varBsCarouselIndicatorActiveBg,
	varBsCodeColor,
	varBsCyan,
	varBsDanger,
	varBsDangerBgSubtle,
	varBsDangerBorderSubtle,
	varBsDangerRgb,
	varBsDangerTextEmphasis,
	varBsDark,
	varBsDarkBgSubtle,
	varBsDarkBorderSubtle,
	varBsDarkRgb,
	varBsDarkTextEmphasis,
	varBsEmphasisColor,
	varBsEmphasisColorRgb,
	varBsFocusRingColor,
	varBsFocusRingOpacity,
	varBsFocusRingWidth,
	varBsFontMonospace,
	varBsFontSansSerif,
	varBsGradient,
	varBsGray,
	varBsGrayDark,
	varBsGreen,
	varBsHeadingColor,
	varBsHighlightBg,
	varBsHighlightColor,
	varBsIndigo,
	varBsInfo,
	varBsInfoBgSubtle,
	varBsInfoBorderSubtle,
	varBsInfoRgb,
	varBsInfoTextEmphasis,
	varBsLight,
	varBsLightBgSubtle,
	varBsLightBorderSubtle,
	varBsLightRgb,
	varBsLightTextEmphasis,
	varBsLinkColor,
	varBsLinkColorRgb,
	varBsLinkDecoration,
	varBsLinkHoverColor,
	varBsLinkHoverColorRgb,
	varBsOrange,
	varBsPink,
	varBsPrimary,
	varBsPrimaryBgSubtle,
	varBsPrimaryBorderSubtle,
	varBsPrimaryRgb,
	varBsPrimaryTextEmphasis,
	varBsPurple,
	varBsRed,
	varBsSecondary,
	varBsSecondaryBg,
	varBsSecondaryBgSubtle,
	varBsSecondaryBorderSubtle,
	varBsSecondaryColor,
	varBsSecondaryRgb,
	varBsSecondaryTextEmphasis,
	varBsSuccess,
	varBsSuccessBgSubtle,
	varBsSuccessBorderSubtle,
	varBsSuccessRgb,
	varBsSuccessTextEmphasis,
	varBsTeal,
	varBsTertiaryBg,
	varBsTertiaryColor,
	varBsWarning,
	varBsWarningBgSubtle,
	varBsWarningBorderSubtle,
	varBsWarningRgb,
	varBsWarningTextEmphasis,
	varBsWhite,
	varBsWhiteRgb,
	varBsYellow,
} from '../../theme-contract/_vars.css'
import {
	varBsFormInvalidBorderColor,
	varBsFormInvalidColor,
	varBsFormValidBorderColor,
	varBsFormValidColor,
} from '../../theme-contract/forms/_vars.css'
import { bodyFrame, bodyText, vars } from '../../theme-contract/theme-contract.css'
import { modalOpenHook } from '../../theme-contract/ui/modal/contract.css'

// Simplex theme scope class.
// Zero-style identifier used as a stable selector prefix.
export const simplexScope = style({})

// Global Bootstrap CSS custom properties (`--bs-*`) are assigned on the
// dedicated vars contract class to keep root var hosting separate from body
// layout/background styles.
globalStyle(`${simplexScope}${vars}`, {
	vars: {
		[varBsBlue]: "#007bff",
		[varBsIndigo]: "#6610f2",
		[varBsPurple]: "#9b479f",
		[varBsPink]: "#e83e8c",
		[varBsRed]: "#d9230f",
		[varBsOrange]: "#d9831f",
		[varBsYellow]: "#ffc107",
		[varBsGreen]: "#469408",
		[varBsTeal]: "#20c997",
		[varBsCyan]: "#029acf",
		[varBsBlack]: "#000",
		[varBsWhite]: "#fff",
		[varBsGray]: "#777",
		[varBsGrayDark]: "#373a3c",
		[varBsPrimary]: "#d9230f",
		[varBsSecondary]: "#fff",
		[varBsSuccess]: "#469408",
		[varBsInfo]: "#029acf",
		[varBsWarning]: "#d9831f",
		[varBsDanger]: "#9b479f",
		[varBsLight]: "#fff",
		[varBsDark]: "#373a3c",
		[varBsPrimaryRgb]: "217, 35, 15",
		[varBsSecondaryRgb]: "255, 255, 255",
		[varBsSuccessRgb]: "70, 148, 8",
		[varBsInfoRgb]: "2, 154, 207",
		[varBsWarningRgb]: "217, 131, 31",
		[varBsDangerRgb]: "155, 71, 159",
		[varBsLightRgb]: "255, 255, 255",
		[varBsDarkRgb]: "55, 58, 60",
		[varBsPrimaryTextEmphasis]: "#570e06",
		[varBsSecondaryTextEmphasis]: "#666666",
		[varBsSuccessTextEmphasis]: "#1c3b03",
		[varBsInfoTextEmphasis]: "#013e53",
		[varBsWarningTextEmphasis]: "#57340c",
		[varBsDangerTextEmphasis]: "#3e1c40",
		[varBsLightTextEmphasis]: "#444",
		[varBsDarkTextEmphasis]: "#444",
		[varBsPrimaryBgSubtle]: "#f7d3cf",
		[varBsSecondaryBgSubtle]: "white",
		[varBsSuccessBgSubtle]: "#daeace",
		[varBsInfoBgSubtle]: "#ccebf5",
		[varBsWarningBgSubtle]: "#f7e6d2",
		[varBsDangerBgSubtle]: "#ebdaec",
		[varBsLightBgSubtle]: "#fcfcfd",
		[varBsDarkBgSubtle]: "#bbb",
		[varBsPrimaryBorderSubtle]: "#f0a79f",
		[varBsSecondaryBorderSubtle]: "white",
		[varBsSuccessBorderSubtle]: "#b5d49c",
		[varBsInfoBorderSubtle]: "#9ad7ec",
		[varBsWarningBorderSubtle]: "#f0cda5",
		[varBsDangerBorderSubtle]: "#d7b5d9",
		[varBsLightBorderSubtle]: "#ddd",
		[varBsDarkBorderSubtle]: "#adb5bd",
		[varBsWhiteRgb]: "255, 255, 255",
		[varBsBlackRgb]: "0, 0, 0",
		[varBsFontSansSerif]: "\"Open Sans\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif, \"Apple Color Emoji\", \"Segoe UI Emoji\", \"Segoe UI Symbol\"",
		[varBsFontMonospace]: "SFMono-Regular, Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace",
		[varBsGradient]: "linear-gradient(180deg, rgba(255, 255, 255, 0.15), rgba(255, 255, 255, 0))",
		[varBsBodyFontFamily]: varBsFontSansSerif,
		[varBsBodyFontSize]: "1rem",
		[varBsBodyFontWeight]: 400,
		[varBsBodyLineHeight]: 1.5,
		[varBsBodyColor]: "#212529",
		[varBsBodyColorRgb]: "33, 37, 41",
		[varBsBodyBg]: "#fcfcfc",
		[varBsBodyBgRgb]: "252, 252, 252",
		[varBsEmphasisColor]: "#000",
		[varBsEmphasisColorRgb]: "0, 0, 0",
		[varBsSecondaryColor]: "rgba(33, 37, 41, 0.75)",
		[varBsSecondaryBg]: "#ddd",
		[varBsTertiaryColor]: "rgba(33, 37, 41, 0.5)",
		[varBsTertiaryBg]: "#f8f9fa",
		[varBsHeadingColor]: "inherit",
		[varBsLinkColor]: "#d9230f",
		[varBsLinkColorRgb]: "217, 35, 15",
		[varBsLinkDecoration]: "underline",
		[varBsLinkHoverColor]: "#ae1c0c",
		[varBsLinkHoverColorRgb]: "174, 28, 12",
		[varBsCodeColor]: "#e83e8c",
		[varBsHighlightColor]: "#212529",
		[varBsHighlightBg]: "#fff3cd",
		[varBsBorderWidth]: "1px",
		[varBsBorderStyle]: "solid",
		[varBsBorderColor]: "#ccc",
		[varBsBorderColorTranslucent]: "rgba(0, 0, 0, 0.175)",
		[varBsBorderRadius]: "0.375rem",
		[varBsBorderRadiusSm]: "0.25rem",
		[varBsBorderRadiusLg]: "0.5rem",
		[varBsBorderRadiusXl]: "1rem",
		[varBsBorderRadiusXxl]: "2rem",
		[varBsBorderRadiusPill]: "50rem",
		[varBsBoxShadow]: "0 0.5rem 1rem rgba(0, 0, 0, 0.15)",
		[varBsBoxShadowSm]: "0 0.125rem 0.25rem rgba(0, 0, 0, 0.075)",
		[varBsBoxShadowLg]: "0 1rem 3rem rgba(0, 0, 0, 0.175)",
		[varBsBoxShadowInset]: "inset 0 1px 2px rgba(0, 0, 0, 0.075)",
		[varBsFocusRingWidth]: "0.25rem",
		[varBsFocusRingOpacity]: 0.25,
		[varBsFocusRingColor]: "rgba(217, 35, 15, 0.25)",
		[varBsBtnCloseFilter]: "",
		[varBsCarouselIndicatorActiveBg]: "#fff",
		[varBsCarouselCaptionColor]: "#fff",
		[varBsCarouselControlIconFilter]: "",
		[varBsFormValidColor]: "#469408",
		[varBsFormValidBorderColor]: "#469408",
		[varBsFormInvalidColor]: "#9b479f",
		[varBsFormInvalidBorderColor]: "#9b479f",
	},
})

// ── Root / body styles ────────────────────────────────────────────────────────
// bodyText = typography; bodyFrame = page canvas (Ve2Shell). Do not add padding
// here — baseline screenshots have no padded wrapper around bd-example.

globalStyle(`${simplexScope}${bodyText}`, {
	fontFamily: varBsBodyFontFamily,
	fontSize: varBsBodyFontSize,
	fontWeight: varBsBodyFontWeight,
	lineHeight: varBsBodyLineHeight,
	color: varBsBodyColor,
})

globalStyle(`${simplexScope}${bodyFrame}`, {
	backgroundColor: varBsBodyBg,
	margin: 0,
	minHeight: '100vh',
})

// Bootstrap Modal JS adds modalOpenHook to <body> without theme scope.
globalStyle(`${modalOpenHook}`, {
	fontFamily: varBsBodyFontFamily,
	fontSize: varBsBodyFontSize,
	fontWeight: varBsBodyFontWeight,
	lineHeight: varBsBodyLineHeight,
	color: varBsBodyColor,
	backgroundColor: varBsBodyBg,
	margin: 0,
})
