// GERADO por scripts/gen-public-vars.mjs — NÃO editar à mão.
import { globalStyle } from '@vanilla-extract/css'
import { solarScope } from './scope.css'
import { varBsBlackRgb, varBsBodyBgRgb, varBsBodyColorRgb, varBsBorderColor, varBsBorderRadius, varBsBorderRadiusLg, varBsBorderRadiusPill, varBsBorderRadiusSm, varBsBorderRadiusXl, varBsBorderRadiusXxl, varBsBorderStyle, varBsBorderWidth, varBsBoxShadow, varBsBoxShadowLg, varBsBoxShadowSm, varBsDangerBgSubtle, varBsDangerBorderSubtle, varBsDangerRgb, varBsDangerTextEmphasis, varBsDarkBgSubtle, varBsDarkBorderSubtle, varBsDarkRgb, varBsDarkTextEmphasis, varBsEmphasisColor, varBsEmphasisColorRgb, varBsFocusRingColor, varBsFocusRingOpacity, varBsFontMonospace, varBsGradient, varBsInfoBgSubtle, varBsInfoBorderSubtle, varBsInfoRgb, varBsInfoTextEmphasis, varBsLightBgSubtle, varBsLightBorderSubtle, varBsLightRgb, varBsLightTextEmphasis, varBsLinkColorRgb, varBsPrimaryBgSubtle, varBsPrimaryBorderSubtle, varBsPrimaryRgb, varBsPrimaryTextEmphasis, varBsSecondaryBgRgb, varBsSecondaryBgSubtle, varBsSecondaryBorderSubtle, varBsSecondaryColor, varBsSecondaryRgb, varBsSecondaryTextEmphasis, varBsSuccessBgSubtle, varBsSuccessBorderSubtle, varBsSuccessRgb, varBsSuccessTextEmphasis, varBsTertiaryBgRgb, varBsTertiaryColor, varBsWarningBgSubtle, varBsWarningBorderSubtle, varBsWarningRgb, varBsWarningTextEmphasis, varBsWhiteRgb } from '../../theme-contract/_public-vars.css'

globalStyle(solarScope, {
	vars: {
		[varBsBlackRgb]: "0, 0, 0",
		[varBsBodyBgRgb]: "0, 43, 54",
		[varBsBodyColorRgb]: "131, 148, 150",
		[varBsBorderColor]: "#dee2e6",
		[varBsBorderRadius]: "0.375rem",
		[varBsBorderRadiusLg]: "0.5rem",
		[varBsBorderRadiusPill]: "50rem",
		[varBsBorderRadiusSm]: "0.25rem",
		[varBsBorderRadiusXl]: "1rem",
		[varBsBorderRadiusXxl]: "2rem",
		[varBsBorderStyle]: "solid",
		[varBsBorderWidth]: "1px",
		[varBsBoxShadow]: "0 0.5rem 1rem rgba(0, 0, 0, 0.15)",
		[varBsBoxShadowLg]: "0 1rem 3rem rgba(0, 0, 0, 0.175)",
		[varBsBoxShadowSm]: "0 0.125rem 0.25rem rgba(0, 0, 0, 0.075)",
		[varBsDangerBgSubtle]: "#f6d7e6",
		[varBsDangerBorderSubtle]: "#edafcd",
		[varBsDangerRgb]: "211, 54, 130",
		[varBsDangerTextEmphasis]: "#541634",
		[varBsDarkBgSubtle]: "#ced4da",
		[varBsDarkBorderSubtle]: "#adb5bd",
		[varBsDarkRgb]: "7, 54, 66",
		[varBsDarkTextEmphasis]: "#495057",
		[varBsEmphasisColor]: "#000",
		[varBsEmphasisColorRgb]: "0, 0, 0",
		[varBsFocusRingColor]: "rgba(181, 137, 0, 0.25)",
		[varBsFocusRingOpacity]: "0.25",
		[varBsFontMonospace]: "SFMono-Regular, Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace",
		[varBsGradient]: "linear-gradient(180deg, rgba(255, 255, 255, 0.15), rgba(255, 255, 255, 0))",
		[varBsInfoBgSubtle]: "#d4e8f6",
		[varBsInfoBorderSubtle]: "#a8d1ed",
		[varBsInfoRgb]: "38, 139, 210",
		[varBsInfoTextEmphasis]: "#0f3854",
		[varBsLightBgSubtle]: "#fefbf1",
		[varBsLightBorderSubtle]: "#eee8d5",
		[varBsLightRgb]: "253, 246, 227",
		[varBsLightTextEmphasis]: "#495057",
		[varBsLinkColorRgb]: "42, 161, 152",
		[varBsPrimaryBgSubtle]: "#f0e7cc",
		[varBsPrimaryBorderSubtle]: "#e1d099",
		[varBsPrimaryRgb]: "181, 137, 0",
		[varBsPrimaryTextEmphasis]: "#483700",
		[varBsSecondaryBgRgb]: "238, 232, 213",
		[varBsSecondaryBgSubtle]: "#e6eaea",
		[varBsSecondaryBorderSubtle]: "#cdd4d5",
		[varBsSecondaryColor]: "rgba(131, 148, 150, 0.75)",
		[varBsSecondaryRgb]: "131, 148, 150",
		[varBsSecondaryTextEmphasis]: "#343b3c",
		[varBsSuccessBgSubtle]: "#d4ecea",
		[varBsSuccessBorderSubtle]: "#aad9d6",
		[varBsSuccessRgb]: "42, 161, 152",
		[varBsSuccessTextEmphasis]: "#11403d",
		[varBsTertiaryBgRgb]: "253, 246, 227",
		[varBsTertiaryColor]: "rgba(131, 148, 150, 0.5)",
		[varBsWarningBgSubtle]: "#f5dbd0",
		[varBsWarningBorderSubtle]: "#eab7a2",
		[varBsWarningRgb]: "203, 75, 22",
		[varBsWarningTextEmphasis]: "#511e09",
		[varBsWhiteRgb]: "255, 255, 255",
	},
})
