import { globalStyle, style } from '@vanilla-extract/css'
import {
	varBsBlack,
	varBsBlackRgb,
	varBsBlue,
	varBsBodyBg,
	varBsBodyBgRgb,
	varBsBodyColor,
	varBsBodyColorRgb,
	varBsBodyFontFamily,
	varBsBodyFontSize,
	varBsBodyFontWeight,
	varBsBodyLineHeight,
	varBsBorderColor,
	varBsBorderColorTranslucent,
	varBsBorderRadius,
	varBsBorderRadiusLg,
	varBsBorderRadiusPill,
	varBsBorderRadiusSm,
	varBsBorderRadiusXl,
	varBsBorderRadiusXxl,
	varBsBorderStyle,
	varBsBorderWidth,
	varBsBoxShadow,
	varBsBoxShadowInset,
	varBsBoxShadowLg,
	varBsBoxShadowSm,
	varBsCarouselCaptionColor,
	varBsCarouselIndicatorActiveBg,
	varBsCodeColor,
	varBsCyan,
	varBsDanger,
	varBsDangerBgSubtle,
	varBsDangerBorderSubtle,
	varBsDangerRgb,
	varBsDangerTextEmphasis,
	varBsDark,
	varBsDarkBgSubtle,
	varBsDarkBorderSubtle,
	varBsDarkRgb,
	varBsDarkTextEmphasis,
	varBsEmphasisColor,
	varBsEmphasisColorRgb,
	varBsFocusRingColor,
	varBsFocusRingOpacity,
	varBsFocusRingWidth,
	varBsFontMonospace,
	varBsFontSansSerif,
	varBsGradient,
	varBsGray,
	varBsGrayDark,
	varBsGreen,
	varBsHeadingColor,
	varBsHighlightBg,
	varBsHighlightColor,
	varBsIndigo,
	varBsInfo,
	varBsInfoBgSubtle,
	varBsInfoBorderSubtle,
	varBsInfoRgb,
	varBsInfoTextEmphasis,
	varBsLight,
	varBsLightBgSubtle,
	varBsLightBorderSubtle,
	varBsLightRgb,
	varBsLightTextEmphasis,
	varBsLinkColor,
	varBsLinkColorRgb,
	varBsLinkDecoration,
	varBsLinkHoverColor,
	varBsLinkHoverColorRgb,
	varBsOrange,
	varBsPink,
	varBsPrimary,
	varBsPrimaryBgSubtle,
	varBsPrimaryBorderSubtle,
	varBsPrimaryRgb,
	varBsPrimaryTextEmphasis,
	varBsPurple,
	varBsRed,
	varBsSecondary,
	varBsSecondaryBg,
	varBsSecondaryBgSubtle,
	varBsSecondaryBorderSubtle,
	varBsSecondaryColor,
	varBsSecondaryRgb,
	varBsSecondaryTextEmphasis,
	varBsSuccess,
	varBsSuccessBgSubtle,
	varBsSuccessBorderSubtle,
	varBsSuccessRgb,
	varBsSuccessTextEmphasis,
	varBsTeal,
	varBsTertiaryBg,
	varBsTertiaryColor,
	varBsWarning,
	varBsWarningBgSubtle,
	varBsWarningBorderSubtle,
	varBsWarningRgb,
	varBsWarningTextEmphasis,
	varBsWhite,
	varBsWhiteRgb,
	varBsYellow,
} from '../../theme-contract/_vars.css'
import {
	varBsFormInvalidBorderColor,
	varBsFormInvalidColor,
	varBsFormValidBorderColor,
	varBsFormValidColor,
} from '../../theme-contract/forms/_vars.css'
import { body, bodyText, vars } from '../../theme-contract/theme-contract.css'

// Solar theme scope class.
// Zero-style identifier used as a stable selector prefix.
export const solarScope = style({})

// Global Bootstrap CSS custom properties (`--bs-*`) are assigned on the
// dedicated vars contract class to keep root var hosting separate from body
// layout/background styles.
globalStyle(`${solarScope}${vars}`, {
	vars: {
		[varBsBlue]: "#b58900",
		[varBsIndigo]: "#6610f2",
		[varBsPurple]: "#6f42c1",
		[varBsPink]: "#e83e8c",
		[varBsRed]: "#d33682",
		[varBsOrange]: "#fd7e14",
		[varBsYellow]: "#cb4b16",
		[varBsGreen]: "#2aa198",
		[varBsTeal]: "#20c997",
		[varBsCyan]: "#268bd2",
		[varBsBlack]: "#000",
		[varBsWhite]: "#fff",
		[varBsGray]: "#839496",
		[varBsGrayDark]: "#073642",
		[varBsPrimary]: "#b58900",
		[varBsSecondary]: "#839496",
		[varBsSuccess]: "#2aa198",
		[varBsInfo]: "#268bd2",
		[varBsWarning]: "#cb4b16",
		[varBsDanger]: "#d33682",
		[varBsLight]: "#fdf6e3",
		[varBsDark]: "#073642",
		[varBsPrimaryRgb]: "181, 137, 0",
		[varBsSecondaryRgb]: "131, 148, 150",
		[varBsSuccessRgb]: "42, 161, 152",
		[varBsInfoRgb]: "38, 139, 210",
		[varBsWarningRgb]: "203, 75, 22",
		[varBsDangerRgb]: "211, 54, 130",
		[varBsLightRgb]: "253, 246, 227",
		[varBsDarkRgb]: "7, 54, 66",
		[varBsPrimaryTextEmphasis]: "#483700",
		[varBsSecondaryTextEmphasis]: "#343b3c",
		[varBsSuccessTextEmphasis]: "#11403d",
		[varBsInfoTextEmphasis]: "#0f3854",
		[varBsWarningTextEmphasis]: "#511e09",
		[varBsDangerTextEmphasis]: "#541634",
		[varBsLightTextEmphasis]: "#495057",
		[varBsDarkTextEmphasis]: "#495057",
		[varBsPrimaryBgSubtle]: "#f0e7cc",
		[varBsSecondaryBgSubtle]: "#e6eaea",
		[varBsSuccessBgSubtle]: "#d4ecea",
		[varBsInfoBgSubtle]: "#d4e8f6",
		[varBsWarningBgSubtle]: "#f5dbd0",
		[varBsDangerBgSubtle]: "#f6d7e6",
		[varBsLightBgSubtle]: "#fefbf1",
		[varBsDarkBgSubtle]: "#ced4da",
		[varBsPrimaryBorderSubtle]: "#e1d099",
		[varBsSecondaryBorderSubtle]: "#cdd4d5",
		[varBsSuccessBorderSubtle]: "#aad9d6",
		[varBsInfoBorderSubtle]: "#a8d1ed",
		[varBsWarningBorderSubtle]: "#eab7a2",
		[varBsDangerBorderSubtle]: "#edafcd",
		[varBsLightBorderSubtle]: "#eee8d5",
		[varBsDarkBorderSubtle]: "#adb5bd",
		[varBsWhiteRgb]: "255, 255, 255",
		[varBsBlackRgb]: "0, 0, 0",
		[varBsFontSansSerif]: "\"Source Sans Pro\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif, \"Apple Color Emoji\", \"Segoe UI Emoji\", \"Segoe UI Symbol\"",
		[varBsFontMonospace]: "SFMono-Regular, Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace",
		[varBsGradient]: "linear-gradient(180deg, rgba(255, 255, 255, 0.15), rgba(255, 255, 255, 0))",
		[varBsBodyFontFamily]: varBsFontSansSerif,
		[varBsBodyFontSize]: "1rem",
		[varBsBodyFontWeight]: 400,
		[varBsBodyLineHeight]: 1.5,
		[varBsBodyColor]: "#839496",
		[varBsBodyColorRgb]: "131, 148, 150",
		[varBsBodyBg]: "#002b36",
		[varBsBodyBgRgb]: "0, 43, 54",
		[varBsEmphasisColor]: "#000",
		[varBsEmphasisColorRgb]: "0, 0, 0",
		[varBsSecondaryColor]: "rgba(131, 148, 150, 0.75)",
		[varBsSecondaryBg]: "#eee8d5",
		[varBsTertiaryColor]: "rgba(131, 148, 150, 0.5)",
		[varBsTertiaryBg]: "#fdf6e3",
		[varBsHeadingColor]: "inherit",
		[varBsLinkColor]: "#2aa198",
		[varBsLinkColorRgb]: "42, 161, 152",
		[varBsLinkDecoration]: "underline",
		[varBsLinkHoverColor]: "#2aa198",
		[varBsLinkHoverColorRgb]: "42, 161, 152",
		[varBsCodeColor]: "#e83e8c",
		[varBsHighlightColor]: "#839496",
		[varBsHighlightBg]: "#f5dbd0",
		[varBsBorderWidth]: "1px",
		[varBsBorderStyle]: "solid",
		[varBsBorderColor]: "#dee2e6",
		[varBsBorderColorTranslucent]: "rgba(0, 0, 0, 0.175)",
		[varBsBorderRadius]: "0.375rem",
		[varBsBorderRadiusSm]: "0.25rem",
		[varBsBorderRadiusLg]: "0.5rem",
		[varBsBorderRadiusXl]: "1rem",
		[varBsBorderRadiusXxl]: "2rem",
		[varBsBorderRadiusPill]: "50rem",
		[varBsBoxShadow]: "0 0.5rem 1rem rgba(0, 0, 0, 0.15)",
		[varBsBoxShadowSm]: "0 0.125rem 0.25rem rgba(0, 0, 0, 0.075)",
		[varBsBoxShadowLg]: "0 1rem 3rem rgba(0, 0, 0, 0.175)",
		[varBsBoxShadowInset]: "inset 0 1px 2px rgba(0, 0, 0, 0.075)",
		[varBsFocusRingWidth]: "0.25rem",
		[varBsFocusRingOpacity]: 0.25,
		[varBsFocusRingColor]: "rgba(181, 137, 0, 0.25)",
		[varBsCarouselIndicatorActiveBg]: "#fff",
		[varBsCarouselCaptionColor]: "#fff",
	},
})

// ── Root / body styles ────────────────────────────────────────────────────────

globalStyle(`${solarScope}${bodyText}`, {
	fontFamily: varBsBodyFontFamily,
	fontSize: varBsBodyFontSize,
	fontWeight: varBsBodyFontWeight,
	lineHeight: varBsBodyLineHeight,
	color: varBsBodyColor,
})

globalStyle(`${solarScope}${body}`, {
	backgroundColor: varBsBodyBg,
	padding: '1rem',
	display: 'block',
})
