import { style } from '@vanilla-extract/css'

export const actionsRow = style({})
export const justifyContentBetween = style({})
export const flexWrap = style({})
export const fade = style({})
export const modalOpenHook = style({})
export const modalShowHook = style({})
export const modalBackdrop = style({})
export const modal = style({})
export const modalFade = style({})
export const modalDialog = style({})
export const modalDialogScrollable = style({})
export const modalDialogCentered = style({})
export const modalFullscreen = style({})
export const modalContent = style({})
export const modalHeader = style({})
export const modalTitle = style({})
export const modalBody = style({})
export const modalFooter = style({})
