// GERADO por scripts/gen-public-vars.mjs — NÃO editar à mão.
import { globalStyle } from '@vanilla-extract/css'
import { flatlyScope } from './scope.css'
import { varBsBlackRgb, varBsBodyBgRgb, varBsBodyColorRgb, varBsBorderColor, varBsBorderRadius, varBsBorderRadiusLg, varBsBorderRadiusPill, varBsBorderRadiusSm, varBsBorderRadiusXl, varBsBorderRadiusXxl, varBsBorderStyle, varBsBorderWidth, varBsBoxShadow, varBsBoxShadowLg, varBsBoxShadowSm, varBsDangerBgSubtle, varBsDangerBorderSubtle, varBsDangerRgb, varBsDangerTextEmphasis, varBsDarkBgSubtle, varBsDarkBorderSubtle, varBsDarkRgb, varBsDarkTextEmphasis, varBsEmphasisColor, varBsEmphasisColorRgb, varBsFocusRingColor, varBsFocusRingOpacity, varBsFontMonospace, varBsGradient, varBsInfoBgSubtle, varBsInfoBorderSubtle, varBsInfoRgb, varBsInfoTextEmphasis, varBsLightBgSubtle, varBsLightBorderSubtle, varBsLightRgb, varBsLightTextEmphasis, varBsLinkColorRgb, varBsPrimaryBgSubtle, varBsPrimaryBorderSubtle, varBsPrimaryRgb, varBsPrimaryTextEmphasis, varBsSecondaryBgRgb, varBsSecondaryBgSubtle, varBsSecondaryBorderSubtle, varBsSecondaryColor, varBsSecondaryRgb, varBsSecondaryTextEmphasis, varBsSuccessBgSubtle, varBsSuccessBorderSubtle, varBsSuccessRgb, varBsSuccessTextEmphasis, varBsTertiaryBgRgb, varBsTertiaryColor, varBsWarningBgSubtle, varBsWarningBorderSubtle, varBsWarningRgb, varBsWarningTextEmphasis, varBsWhiteRgb } from '../../theme-contract/_public-vars.css'

globalStyle(flatlyScope, {
	vars: {
		[varBsBlackRgb]: "0, 0, 0",
		[varBsBodyBgRgb]: "255, 255, 255",
		[varBsBodyColorRgb]: "33, 37, 41",
		[varBsBorderColor]: "#dee2e6",
		[varBsBorderRadius]: "0.375rem",
		[varBsBorderRadiusLg]: "0.5rem",
		[varBsBorderRadiusPill]: "50rem",
		[varBsBorderRadiusSm]: "0.25rem",
		[varBsBorderRadiusXl]: "1rem",
		[varBsBorderRadiusXxl]: "2rem",
		[varBsBorderStyle]: "solid",
		[varBsBorderWidth]: "1px",
		[varBsBoxShadow]: "0 0.5rem 1rem rgba(0, 0, 0, 0.15)",
		[varBsBoxShadowLg]: "0 1rem 3rem rgba(0, 0, 0, 0.175)",
		[varBsBoxShadowSm]: "0 0.125rem 0.25rem rgba(0, 0, 0, 0.075)",
		[varBsDangerBgSubtle]: "#fadbd8",
		[varBsDangerBorderSubtle]: "#f5b7b1",
		[varBsDangerRgb]: "231, 76, 60",
		[varBsDangerTextEmphasis]: "#5c1e18",
		[varBsDarkBgSubtle]: "#ced4da",
		[varBsDarkBorderSubtle]: "#b4bcc2",
		[varBsDarkRgb]: "123, 138, 139",
		[varBsDarkTextEmphasis]: "#7b8a8b",
		[varBsEmphasisColor]: "#000",
		[varBsEmphasisColorRgb]: "0, 0, 0",
		[varBsFocusRingColor]: "rgba(44, 62, 80, 0.25)",
		[varBsFocusRingOpacity]: "0.25",
		[varBsFontMonospace]: "SFMono-Regular, Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace",
		[varBsGradient]: "linear-gradient(180deg, rgba(255, 255, 255, 0.15), rgba(255, 255, 255, 0))",
		[varBsInfoBgSubtle]: "#d6eaf8",
		[varBsInfoBorderSubtle]: "#aed6f1",
		[varBsInfoRgb]: "52, 152, 219",
		[varBsInfoTextEmphasis]: "#153d58",
		[varBsLightBgSubtle]: "#fcfcfd",
		[varBsLightBorderSubtle]: "#ecf0f1",
		[varBsLightRgb]: "236, 240, 241",
		[varBsLightTextEmphasis]: "#7b8a8b",
		[varBsLinkColorRgb]: "24, 188, 156",
		[varBsPrimaryBgSubtle]: "#d5d8dc",
		[varBsPrimaryBorderSubtle]: "#abb2b9",
		[varBsPrimaryRgb]: "44, 62, 80",
		[varBsPrimaryTextEmphasis]: "#121920",
		[varBsSecondaryBgRgb]: "236, 240, 241",
		[varBsSecondaryBgSubtle]: "#eaeded",
		[varBsSecondaryBorderSubtle]: "#d5dbdb",
		[varBsSecondaryColor]: "rgba(33, 37, 41, 0.75)",
		[varBsSecondaryRgb]: "149, 165, 166",
		[varBsSecondaryTextEmphasis]: "#3c4242",
		[varBsSuccessBgSubtle]: "#d1f2eb",
		[varBsSuccessBorderSubtle]: "#a3e4d7",
		[varBsSuccessRgb]: "24, 188, 156",
		[varBsSuccessTextEmphasis]: "#0a4b3e",
		[varBsTertiaryBgRgb]: "248, 249, 250",
		[varBsTertiaryColor]: "rgba(33, 37, 41, 0.5)",
		[varBsWarningBgSubtle]: "#fdebd0",
		[varBsWarningBorderSubtle]: "#fad7a0",
		[varBsWarningRgb]: "243, 156, 18",
		[varBsWarningTextEmphasis]: "#613e07",
		[varBsWhiteRgb]: "255, 255, 255",
	},
})
