import { globalStyle, style } from '@vanilla-extract/css'
import {
	varBsBlack,
	varBsBlackRgb,
	varBsBlue,
	varBsBodyBg,
	varBsBodyBgRgb,
	varBsBodyColor,
	varBsBodyColorRgb,
	varBsBodyFontFamily,
	varBsBodyFontSize,
	varBsBodyFontWeight,
	varBsBodyLineHeight,
	varBsBorderColor,
	varBsBorderColorTranslucent,
	varBsBorderRadius,
	varBsBorderRadiusLg,
	varBsBorderRadiusPill,
	varBsBorderRadiusSm,
	varBsBorderRadiusXl,
	varBsBorderRadiusXxl,
	varBsBorderStyle,
	varBsBorderWidth,
	varBsBoxShadow,
	varBsBoxShadowInset,
	varBsBoxShadowLg,
	varBsBoxShadowSm,
	varBsBtnCloseFilter,
	varBsCarouselCaptionColor,
	varBsCarouselControlIconFilter,
	varBsCarouselIndicatorActiveBg,
	varBsCodeColor,
	varBsCyan,
	varBsDanger,
	varBsDangerBgSubtle,
	varBsDangerBorderSubtle,
	varBsDangerRgb,
	varBsDangerTextEmphasis,
	varBsDark,
	varBsDarkBgSubtle,
	varBsDarkBorderSubtle,
	varBsDarkRgb,
	varBsDarkTextEmphasis,
	varBsEmphasisColor,
	varBsEmphasisColorRgb,
	varBsFocusRingColor,
	varBsFocusRingOpacity,
	varBsFocusRingWidth,
	varBsFontMonospace,
	varBsFontSansSerif,
	varBsGradient,
	varBsGray,
	varBsGrayDark,
	varBsGreen,
	varBsHeadingColor,
	varBsHighlightBg,
	varBsHighlightColor,
	varBsIndigo,
	varBsInfo,
	varBsInfoBgSubtle,
	varBsInfoBorderSubtle,
	varBsInfoRgb,
	varBsInfoTextEmphasis,
	varBsLight,
	varBsLightBgSubtle,
	varBsLightBorderSubtle,
	varBsLightRgb,
	varBsLightTextEmphasis,
	varBsLinkColor,
	varBsLinkColorRgb,
	varBsLinkDecoration,
	varBsLinkHoverColor,
	varBsLinkHoverColorRgb,
	varBsOrange,
	varBsPink,
	varBsPrimary,
	varBsPrimaryBgSubtle,
	varBsPrimaryBorderSubtle,
	varBsPrimaryRgb,
	varBsPrimaryTextEmphasis,
	varBsPurple,
	varBsRed,
	varBsSecondary,
	varBsSecondaryBg,
	varBsSecondaryBgSubtle,
	varBsSecondaryBorderSubtle,
	varBsSecondaryColor,
	varBsSecondaryRgb,
	varBsSecondaryTextEmphasis,
	varBsSuccess,
	varBsSuccessBgSubtle,
	varBsSuccessBorderSubtle,
	varBsSuccessRgb,
	varBsSuccessTextEmphasis,
	varBsTeal,
	varBsTertiaryBg,
	varBsTertiaryColor,
	varBsWarning,
	varBsWarningBgSubtle,
	varBsWarningBorderSubtle,
	varBsWarningRgb,
	varBsWarningTextEmphasis,
	varBsWhite,
	varBsWhiteRgb,
	varBsYellow,
} from '../../theme-contract/_vars.css'
import {
	varBsFormInvalidBorderColor,
	varBsFormInvalidColor,
	varBsFormValidBorderColor,
	varBsFormValidColor,
} from '../../theme-contract/forms/_vars.css'
import { bodyFrame, bodyText, vars } from '../../theme-contract/theme-contract.css'
import { modalOpenHook } from '../../theme-contract/ui/modal/contract.css'

// Flatly theme scope class.
// Zero-style identifier used as a stable selector prefix.
export const flatlyScope = style({})

// Global Bootstrap CSS custom properties (`--bs-*`) are assigned on the
// dedicated vars contract class to keep root var hosting separate from body
// layout/background styles.
globalStyle(`${flatlyScope}${vars}`, {
	vars: {
		[varBsBlue]: "#2c3e50",
		[varBsIndigo]: "#6610f2",
		[varBsPurple]: "#6f42c1",
		[varBsPink]: "#e83e8c",
		[varBsRed]: "#e74c3c",
		[varBsOrange]: "#fd7e14",
		[varBsYellow]: "#f39c12",
		[varBsGreen]: "#18bc9c",
		[varBsTeal]: "#20c997",
		[varBsCyan]: "#3498db",
		[varBsBlack]: "#000",
		[varBsWhite]: "#fff",
		[varBsGray]: "#95a5a6",
		[varBsGrayDark]: "#343a40",
		[varBsPrimary]: "#2c3e50",
		[varBsSecondary]: "#95a5a6",
		[varBsSuccess]: "#18bc9c",
		[varBsInfo]: "#3498db",
		[varBsWarning]: "#f39c12",
		[varBsDanger]: "#e74c3c",
		[varBsLight]: "#ecf0f1",
		[varBsDark]: "#7b8a8b",
		[varBsPrimaryRgb]: "44, 62, 80",
		[varBsSecondaryRgb]: "149, 165, 166",
		[varBsSuccessRgb]: "24, 188, 156",
		[varBsInfoRgb]: "52, 152, 219",
		[varBsWarningRgb]: "243, 156, 18",
		[varBsDangerRgb]: "231, 76, 60",
		[varBsLightRgb]: "236, 240, 241",
		[varBsDarkRgb]: "123, 138, 139",
		[varBsPrimaryTextEmphasis]: "#121920",
		[varBsSecondaryTextEmphasis]: "#3c4242",
		[varBsSuccessTextEmphasis]: "#0a4b3e",
		[varBsInfoTextEmphasis]: "#153d58",
		[varBsWarningTextEmphasis]: "#613e07",
		[varBsDangerTextEmphasis]: "#5c1e18",
		[varBsLightTextEmphasis]: "#7b8a8b",
		[varBsDarkTextEmphasis]: "#7b8a8b",
		[varBsPrimaryBgSubtle]: "#d5d8dc",
		[varBsSecondaryBgSubtle]: "#eaeded",
		[varBsSuccessBgSubtle]: "#d1f2eb",
		[varBsInfoBgSubtle]: "#d6eaf8",
		[varBsWarningBgSubtle]: "#fdebd0",
		[varBsDangerBgSubtle]: "#fadbd8",
		[varBsLightBgSubtle]: "#fcfcfd",
		[varBsDarkBgSubtle]: "#ced4da",
		[varBsPrimaryBorderSubtle]: "#abb2b9",
		[varBsSecondaryBorderSubtle]: "#d5dbdb",
		[varBsSuccessBorderSubtle]: "#a3e4d7",
		[varBsInfoBorderSubtle]: "#aed6f1",
		[varBsWarningBorderSubtle]: "#fad7a0",
		[varBsDangerBorderSubtle]: "#f5b7b1",
		[varBsLightBorderSubtle]: "#ecf0f1",
		[varBsDarkBorderSubtle]: "#b4bcc2",
		[varBsWhiteRgb]: "255, 255, 255",
		[varBsBlackRgb]: "0, 0, 0",
		[varBsFontSansSerif]: "Lato, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif, \"Apple Color Emoji\", \"Segoe UI Emoji\", \"Segoe UI Symbol\"",
		[varBsFontMonospace]: "SFMono-Regular, Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace",
		[varBsGradient]: "linear-gradient(180deg, rgba(255, 255, 255, 0.15), rgba(255, 255, 255, 0))",
		[varBsBodyFontFamily]: varBsFontSansSerif,
		[varBsBodyFontSize]: "1rem",
		[varBsBodyFontWeight]: 400,
		[varBsBodyLineHeight]: 1.5,
		[varBsBodyColor]: "#212529",
		[varBsBodyColorRgb]: "33, 37, 41",
		[varBsBodyBg]: "#fff",
		[varBsBodyBgRgb]: "255, 255, 255",
		[varBsEmphasisColor]: "#000",
		[varBsEmphasisColorRgb]: "0, 0, 0",
		[varBsSecondaryColor]: "rgba(33, 37, 41, 0.75)",
		[varBsSecondaryBg]: "#ecf0f1",
		[varBsTertiaryColor]: "rgba(33, 37, 41, 0.5)",
		[varBsTertiaryBg]: "#f8f9fa",
		[varBsHeadingColor]: "inherit",
		[varBsLinkColor]: "#18bc9c",
		[varBsLinkColorRgb]: "24, 188, 156",
		[varBsLinkDecoration]: "underline",
		[varBsLinkHoverColor]: "#13967d",
		[varBsLinkHoverColorRgb]: "19, 150, 125",
		[varBsCodeColor]: "#e83e8c",
		[varBsHighlightColor]: "#212529",
		[varBsHighlightBg]: "#fdebd0",
		[varBsBorderWidth]: "1px",
		[varBsBorderStyle]: "solid",
		[varBsBorderColor]: "#dee2e6",
		[varBsBorderColorTranslucent]: "rgba(0, 0, 0, 0.175)",
		[varBsBorderRadius]: "0.375rem",
		[varBsBorderRadiusSm]: "0.25rem",
		[varBsBorderRadiusLg]: "0.5rem",
		[varBsBorderRadiusXl]: "1rem",
		[varBsBorderRadiusXxl]: "2rem",
		[varBsBorderRadiusPill]: "50rem",
		[varBsBoxShadow]: "0 0.5rem 1rem rgba(0, 0, 0, 0.15)",
		[varBsBoxShadowSm]: "0 0.125rem 0.25rem rgba(0, 0, 0, 0.075)",
		[varBsBoxShadowLg]: "0 1rem 3rem rgba(0, 0, 0, 0.175)",
		[varBsBoxShadowInset]: "inset 0 1px 2px rgba(0, 0, 0, 0.075)",
		[varBsFocusRingWidth]: "0.25rem",
		[varBsFocusRingOpacity]: 0.25,
		[varBsFocusRingColor]: "rgba(44, 62, 80, 0.25)",
		[varBsBtnCloseFilter]: "",
		[varBsCarouselIndicatorActiveBg]: "#fff",
		[varBsCarouselCaptionColor]: "#fff",
		[varBsCarouselControlIconFilter]: "",
		[varBsFormValidColor]: "#18bc9c",
		[varBsFormValidBorderColor]: "#18bc9c",
		[varBsFormInvalidColor]: "#e74c3c",
		[varBsFormInvalidBorderColor]: "#e74c3c",
	},
})

// ── Root / body styles ────────────────────────────────────────────────────────
// bodyText = typography; bodyFrame = page canvas (Ve2Shell). Do not add padding
// here — baseline screenshots have no padded wrapper around bd-example.

globalStyle(`${flatlyScope}${bodyText}`, {
	fontFamily: varBsBodyFontFamily,
	fontSize: varBsBodyFontSize,
	fontWeight: varBsBodyFontWeight,
	lineHeight: varBsBodyLineHeight,
	color: varBsBodyColor,
})

globalStyle(`${flatlyScope}${bodyFrame}`, {
	backgroundColor: varBsBodyBg,
	margin: 0,
	minHeight: '100vh',
})

// Bootstrap Modal JS adds modalOpenHook to <body> without theme scope.
globalStyle(`${modalOpenHook}`, {
	fontFamily: varBsBodyFontFamily,
	fontSize: varBsBodyFontSize,
	fontWeight: varBsBodyFontWeight,
	lineHeight: varBsBodyLineHeight,
	color: varBsBodyColor,
	backgroundColor: varBsBodyBg,
	margin: 0,
})
