import { globalStyle, style } from '@vanilla-extract/css'
import {
	varBsAccordionBtnActiveIcon,
	varBsAccordionBtnIcon,
	varBsBlack,
	varBsBlackRgb,
	varBsBlue,
	varBsBodyBg,
	varBsBodyBgRgb,
	varBsBodyColor,
	varBsBodyColorRgb,
	varBsBodyFontFamily,
	varBsBodyFontSize,
	varBsBodyFontWeight,
	varBsBodyLineHeight,
	varBsBorderColor,
	varBsBorderColorTranslucent,
	varBsBorderRadius,
	varBsBorderRadiusLg,
	varBsBorderRadiusPill,
	varBsBorderRadiusSm,
	varBsBorderRadiusXl,
	varBsBorderRadiusXxl,
	varBsBorderStyle,
	varBsBorderWidth,
	varBsBoxShadow,
	varBsBoxShadowInset,
	varBsBoxShadowLg,
	varBsBoxShadowSm,
	varBsCarouselCaptionColor,
	varBsCarouselControlIconFilter,
	varBsCarouselIndicatorActiveBg,
	varBsCodeColor,
	varBsCyan,
	varBsDanger,
	varBsDangerBgSubtle,
	varBsDangerBorderSubtle,
	varBsDangerRgb,
	varBsDangerTextEmphasis,
	varBsDark,
	varBsDarkBgSubtle,
	varBsDarkBorderSubtle,
	varBsDarkRgb,
	varBsDarkTextEmphasis,
	varBsEmphasisColor,
	varBsEmphasisColorRgb,
	varBsFocusRingColor,
	varBsFocusRingOpacity,
	varBsFocusRingWidth,
	varBsFontMonospace,
	varBsFontSansSerif,
	varBsGradient,
	varBsGray,
	varBsGrayDark,
	varBsGreen,
	varBsHeadingColor,
	varBsHighlightBg,
	varBsHighlightColor,
	varBsIndigo,
	varBsInfo,
	varBsInfoBgSubtle,
	varBsInfoBorderSubtle,
	varBsInfoRgb,
	varBsInfoTextEmphasis,
	varBsLight,
	varBsLightBgSubtle,
	varBsLightBorderSubtle,
	varBsLightRgb,
	varBsLightTextEmphasis,
	varBsLinkColor,
	varBsLinkColorRgb,
	varBsLinkDecoration,
	varBsLinkHoverColor,
	varBsLinkHoverColorRgb,
	varBsNavbarActiveColor,
	varBsNavbarBrandColor,
	varBsNavbarBrandHoverColor,
	varBsNavbarColor,
	varBsNavbarDisabledColor,
	varBsNavbarHoverColor,
	varBsNavbarTogglerBorderColor,
	varBsNavbarTogglerIconBg,
	varBsOrange,
	varBsPink,
	varBsPrimary,
	varBsPrimaryBgSubtle,
	varBsPrimaryBorderSubtle,
	varBsPrimaryRgb,
	varBsPrimaryTextEmphasis,
	varBsPurple,
	varBsRed,
	varBsSecondary,
	varBsSecondaryBg,
	varBsSecondaryBgSubtle,
	varBsSecondaryBorderSubtle,
	varBsSecondaryColor,
	varBsSecondaryRgb,
	varBsSecondaryTextEmphasis,
	varBsSuccess,
	varBsSuccessBgSubtle,
	varBsSuccessBorderSubtle,
	varBsSuccessRgb,
	varBsSuccessTextEmphasis,
	varBsTeal,
	varBsTertiaryBg,
	varBsTertiaryColor,
	varBsWarning,
	varBsWarningBgSubtle,
	varBsWarningBorderSubtle,
	varBsWarningRgb,
	varBsWarningTextEmphasis,
	varBsWhite,
	varBsWhiteRgb,
	varBsYellow,
} from '../../theme-contract/_vars.css'
import {
	varBsFormInvalidBorderColor,
	varBsFormInvalidColor,
	varBsFormSelectBgImg,
	varBsFormSwitchBg,
	varBsFormValidBorderColor,
	varBsFormValidColor,
} from '../../theme-contract/forms/_vars.css'
import { body, bodyText, vars } from '../../theme-contract/theme-contract.css'

// Flatly theme scope class.
// Zero-style identifier used as a stable selector prefix.
export const flatlyScope = style({})

// Global Bootstrap CSS custom properties (`--bs-*`) are assigned on the
// dedicated vars contract class to keep root var hosting separate from body
// layout/background styles.
globalStyle(`${flatlyScope}${vars}`, {
	vars: {
		[varBsBlue]: "#2c3e50",
		[varBsIndigo]: "#6610f2",
		[varBsPurple]: "#6f42c1",
		[varBsPink]: "#e83e8c",
		[varBsRed]: "#e74c3c",
		[varBsOrange]: "#fd7e14",
		[varBsYellow]: "#f39c12",
		[varBsGreen]: "#18bc9c",
		[varBsTeal]: "#20c997",
		[varBsCyan]: "#3498db",
		[varBsBlack]: "#000",
		[varBsWhite]: "#fff",
		[varBsGray]: "#95a5a6",
		[varBsGrayDark]: "#343a40",
		[varBsPrimary]: "#2c3e50",
		[varBsSecondary]: "#95a5a6",
		[varBsSuccess]: "#18bc9c",
		[varBsInfo]: "#3498db",
		[varBsWarning]: "#f39c12",
		[varBsDanger]: "#e74c3c",
		[varBsLight]: "#ecf0f1",
		[varBsDark]: "#7b8a8b",
		[varBsPrimaryRgb]: "44, 62, 80",
		[varBsSecondaryRgb]: "149, 165, 166",
		[varBsSuccessRgb]: "24, 188, 156",
		[varBsInfoRgb]: "52, 152, 219",
		[varBsWarningRgb]: "243, 156, 18",
		[varBsDangerRgb]: "231, 76, 60",
		[varBsLightRgb]: "236, 240, 241",
		[varBsDarkRgb]: "123, 138, 139",
		[varBsPrimaryTextEmphasis]: "#808b96",
		[varBsSecondaryTextEmphasis]: "#bfc9ca",
		[varBsSuccessTextEmphasis]: "#74d7c4",
		[varBsInfoTextEmphasis]: "#85c1e9",
		[varBsWarningTextEmphasis]: "#f8c471",
		[varBsDangerTextEmphasis]: "#f1948a",
		[varBsLightTextEmphasis]: "#f8f9fa",
		[varBsDarkTextEmphasis]: "#dee2e6",
		[varBsPrimaryBgSubtle]: "#090c10",
		[varBsSecondaryBgSubtle]: "#1e2121",
		[varBsSuccessBgSubtle]: "#05261f",
		[varBsInfoBgSubtle]: "#0a1e2c",
		[varBsWarningBgSubtle]: "#311f04",
		[varBsDangerBgSubtle]: "#2e0f0c",
		[varBsLightBgSubtle]: "#343a40",
		[varBsDarkBgSubtle]: "#1a1d20",
		[varBsPrimaryBorderSubtle]: "#1a2530",
		[varBsSecondaryBorderSubtle]: "#596364",
		[varBsSuccessBorderSubtle]: "#0e715e",
		[varBsInfoBorderSubtle]: "#1f5b83",
		[varBsWarningBorderSubtle]: "#925e0b",
		[varBsDangerBorderSubtle]: "#8b2e24",
		[varBsLightBorderSubtle]: "#7b8a8b",
		[varBsDarkBorderSubtle]: "#343a40",
		[varBsWhiteRgb]: "255, 255, 255",
		[varBsBlackRgb]: "0, 0, 0",
		[varBsFontSansSerif]: "Lato, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif, \"Apple Color Emoji\", \"Segoe UI Emoji\", \"Segoe UI Symbol\"",
		[varBsFontMonospace]: "SFMono-Regular, Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace",
		[varBsGradient]: "linear-gradient(180deg, rgba(255, 255, 255, 0.15), rgba(255, 255, 255, 0))",
		[varBsBodyFontFamily]: varBsFontSansSerif,
		[varBsBodyFontSize]: "1rem",
		[varBsBodyFontWeight]: 400,
		[varBsBodyLineHeight]: 1.5,
		[varBsBodyColor]: "#dee2e6",
		[varBsBodyColorRgb]: "222, 226, 230",
		[varBsBodyBg]: "#212529",
		[varBsBodyBgRgb]: "33, 37, 41",
		[varBsEmphasisColor]: "#fff",
		[varBsEmphasisColorRgb]: "255, 255, 255",
		[varBsSecondaryColor]: "rgba(222, 226, 230, 0.75)",
		[varBsSecondaryBg]: "#343a40",
		[varBsTertiaryColor]: "rgba(222, 226, 230, 0.5)",
		[varBsTertiaryBg]: "#2b3035",
		[varBsHeadingColor]: "inherit",
		[varBsLinkColor]: "#808b96",
		[varBsLinkColorRgb]: "128, 139, 150",
		[varBsLinkDecoration]: "underline",
		[varBsLinkHoverColor]: "#99a2ab",
		[varBsLinkHoverColorRgb]: "153, 162, 171",
		[varBsCodeColor]: "#f18bba",
		[varBsHighlightColor]: "#dee2e6",
		[varBsHighlightBg]: "#613e07",
		[varBsBorderWidth]: "1px",
		[varBsBorderStyle]: "solid",
		[varBsBorderColor]: "#7b8a8b",
		[varBsBorderColorTranslucent]: "rgba(255, 255, 255, 0.15)",
		[varBsBorderRadius]: "0.375rem",
		[varBsBorderRadiusSm]: "0.25rem",
		[varBsBorderRadiusLg]: "0.5rem",
		[varBsBorderRadiusXl]: "1rem",
		[varBsBorderRadiusXxl]: "2rem",
		[varBsBorderRadiusPill]: "50rem",
		[varBsBoxShadow]: "0 0.5rem 1rem rgba(0, 0, 0, 0.15)",
		[varBsBoxShadowSm]: "0 0.125rem 0.25rem rgba(0, 0, 0, 0.075)",
		[varBsBoxShadowLg]: "0 1rem 3rem rgba(0, 0, 0, 0.175)",
		[varBsBoxShadowInset]: "inset 0 1px 2px rgba(0, 0, 0, 0.075)",
		[varBsFocusRingWidth]: "0.25rem",
		[varBsFocusRingOpacity]: 0.25,
		[varBsFocusRingColor]: "rgba(44, 62, 80, 0.25)",
		[varBsNavbarColor]: "#fff",
		[varBsNavbarHoverColor]: "#18bc9c",
		[varBsNavbarDisabledColor]: "rgba(255, 255, 255, 0.25)",
		[varBsNavbarActiveColor]: "#18bc9c",
		[varBsNavbarBrandColor]: "#fff",
		[varBsNavbarBrandHoverColor]: "#18bc9c",
		[varBsNavbarTogglerBorderColor]: "rgba(255, 255, 255, 0.1)",
		[varBsNavbarTogglerIconBg]: "url(\"data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 30 30'%3e%3cpath stroke='%23fff' stroke-linecap='round' stroke-miterlimit='10' stroke-width='2' d='M4 7h22M4 15h22M4 23h22'/%3e%3c/svg%3e\")",
		[varBsAccordionBtnIcon]: "url(\"data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16' fill='%23808b96'%3e%3cpath fill-rule='evenodd' d='M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708'/%3e%3c/svg%3e\")",
		[varBsAccordionBtnActiveIcon]: "url(\"data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16' fill='%23808b96'%3e%3cpath fill-rule='evenodd' d='M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708'/%3e%3c/svg%3e\")",
		[varBsCarouselIndicatorActiveBg]: "#000",
		[varBsCarouselCaptionColor]: "#000",
		[varBsCarouselControlIconFilter]: "invert(1) grayscale(100)",
	},
})

// ── Root / body styles ────────────────────────────────────────────────────────

globalStyle(`${flatlyScope}${bodyText}`, {
	fontFamily: varBsBodyFontFamily,
	fontSize: varBsBodyFontSize,
	fontWeight: varBsBodyFontWeight,
	lineHeight: varBsBodyLineHeight,
	color: varBsBodyColor,
})

globalStyle(`${flatlyScope}${body}`, {
	backgroundColor: varBsBodyBg,
	padding: '1rem',
	display: 'block',
})
