// GERADO por scripts/gen-public-vars.mjs — NÃO editar à mão.
import { globalStyle } from '@vanilla-extract/css'
import { pulseScope } from './scope.css'
import { varBsBlackRgb, varBsBodyBgRgb, varBsBodyColorRgb, varBsBorderColor, varBsBorderRadius, varBsBorderRadiusLg, varBsBorderRadiusPill, varBsBorderRadiusSm, varBsBorderRadiusXl, varBsBorderRadiusXxl, varBsBorderStyle, varBsBorderWidth, varBsBoxShadow, varBsBoxShadowLg, varBsBoxShadowSm, varBsDangerBgSubtle, varBsDangerBorderSubtle, varBsDangerRgb, varBsDangerTextEmphasis, varBsDarkBgSubtle, varBsDarkBorderSubtle, varBsDarkRgb, varBsDarkTextEmphasis, varBsEmphasisColor, varBsEmphasisColorRgb, varBsFocusRingColor, varBsFocusRingOpacity, varBsFontMonospace, varBsGradient, varBsInfoBgSubtle, varBsInfoBorderSubtle, varBsInfoRgb, varBsInfoTextEmphasis, varBsLightBgSubtle, varBsLightBorderSubtle, varBsLightRgb, varBsLightTextEmphasis, varBsLinkColorRgb, varBsPrimaryBgSubtle, varBsPrimaryBorderSubtle, varBsPrimaryRgb, varBsPrimaryTextEmphasis, varBsSecondaryBgRgb, varBsSecondaryBgSubtle, varBsSecondaryBorderSubtle, varBsSecondaryColor, varBsSecondaryRgb, varBsSecondaryTextEmphasis, varBsSuccessBgSubtle, varBsSuccessBorderSubtle, varBsSuccessRgb, varBsSuccessTextEmphasis, varBsTertiaryBgRgb, varBsTertiaryColor, varBsWarningBgSubtle, varBsWarningBorderSubtle, varBsWarningRgb, varBsWarningTextEmphasis, varBsWhiteRgb } from '../../theme-contract/_public-vars.css'

globalStyle(pulseScope, {
	vars: {
		[varBsBlackRgb]: "0, 0, 0",
		[varBsBodyBgRgb]: "255, 255, 255",
		[varBsBodyColorRgb]: "68, 68, 68",
		[varBsBorderColor]: "#ededed",
		[varBsBorderRadius]: "0.375rem",
		[varBsBorderRadiusLg]: "0.5rem",
		[varBsBorderRadiusPill]: "50rem",
		[varBsBorderRadiusSm]: "0.25rem",
		[varBsBorderRadiusXl]: "1rem",
		[varBsBorderRadiusXxl]: "2rem",
		[varBsBorderStyle]: "solid",
		[varBsBorderWidth]: "1px",
		[varBsBoxShadow]: "0 0.5rem 1rem rgba(0, 0, 0, 0.15)",
		[varBsBoxShadowLg]: "0 1rem 3rem rgba(0, 0, 0, 0.175)",
		[varBsBoxShadowSm]: "0 0.125rem 0.25rem rgba(0, 0, 0, 0.075)",
		[varBsDangerBgSubtle]: "#fed7d7",
		[varBsDangerBorderSubtle]: "#feb0b0",
		[varBsDangerRgb]: "252, 57, 57",
		[varBsDangerTextEmphasis]: "#651717",
		[varBsDarkBgSubtle]: "#cbc8d0",
		[varBsDarkBorderSubtle]: "#adb5bd",
		[varBsDarkRgb]: "23, 20, 31",
		[varBsDarkTextEmphasis]: "#444",
		[varBsEmphasisColor]: "#000",
		[varBsEmphasisColorRgb]: "0, 0, 0",
		[varBsFocusRingColor]: "rgba(89, 49, 150, 0.25)",
		[varBsFocusRingOpacity]: "0.25",
		[varBsFontMonospace]: "SFMono-Regular, Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace",
		[varBsGradient]: "linear-gradient(180deg, rgba(255, 255, 255, 0.15), rgba(255, 255, 255, 0))",
		[varBsInfoBgSubtle]: "#ccebf8",
		[varBsInfoBorderSubtle]: "#99d7f1",
		[varBsInfoRgb]: "0, 156, 220",
		[varBsInfoTextEmphasis]: "#003e58",
		[varBsLightBgSubtle]: "#fdfdfd",
		[varBsLightBorderSubtle]: "#f9f8fc",
		[varBsLightRgb]: "249, 248, 252",
		[varBsLightTextEmphasis]: "#444",
		[varBsLinkColorRgb]: "89, 49, 150",
		[varBsPrimaryBgSubtle]: "#ded6ea",
		[varBsPrimaryBorderSubtle]: "#bdadd5",
		[varBsPrimaryRgb]: "89, 49, 150",
		[varBsPrimaryTextEmphasis]: "#24143c",
		[varBsSecondaryBgRgb]: "249, 248, 252",
		[varBsSecondaryBgSubtle]: "#eee9f6",
		[varBsSecondaryBorderSubtle]: "#ddd3ee",
		[varBsSecondaryColor]: "rgba(68, 68, 68, 0.75)",
		[varBsSecondaryRgb]: "169, 145, 212",
		[varBsSecondaryTextEmphasis]: "#443a55",
		[varBsSuccessBgSubtle]: "#d0f1dd",
		[varBsSuccessBorderSubtle]: "#a1e3bb",
		[varBsSuccessRgb]: "19, 185, 85",
		[varBsSuccessTextEmphasis]: "#084a22",
		[varBsTertiaryBgRgb]: "250, 250, 250",
		[varBsTertiaryColor]: "rgba(68, 68, 68, 0.5)",
		[varBsWarningBgSubtle]: "#fcedd2",
		[varBsWarningBorderSubtle]: "#f9daa5",
		[varBsWarningRgb]: "239, 163, 29",
		[varBsWarningTextEmphasis]: "#60410c",
		[varBsWhiteRgb]: "255, 255, 255",
	},
})
