import { globalStyle, style } from '@vanilla-extract/css'
import {
	varBsBlack,
	varBsBlackRgb,
	varBsBlue,
	varBsBodyBg,
	varBsBodyBgRgb,
	varBsBodyColor,
	varBsBodyColorRgb,
	varBsBodyFontFamily,
	varBsBodyFontSize,
	varBsBodyFontWeight,
	varBsBodyLineHeight,
	varBsBorderColor,
	varBsBorderColorTranslucent,
	varBsBorderRadius,
	varBsBorderRadiusLg,
	varBsBorderRadiusPill,
	varBsBorderRadiusSm,
	varBsBorderRadiusXl,
	varBsBorderRadiusXxl,
	varBsBorderStyle,
	varBsBorderWidth,
	varBsBoxShadow,
	varBsBoxShadowInset,
	varBsBoxShadowLg,
	varBsBoxShadowSm,
	varBsBtnCloseFilter,
	varBsCarouselCaptionColor,
	varBsCarouselControlIconFilter,
	varBsCarouselIndicatorActiveBg,
	varBsCodeColor,
	varBsCyan,
	varBsDanger,
	varBsDangerBgSubtle,
	varBsDangerBorderSubtle,
	varBsDangerRgb,
	varBsDangerTextEmphasis,
	varBsDark,
	varBsDarkBgSubtle,
	varBsDarkBorderSubtle,
	varBsDarkRgb,
	varBsDarkTextEmphasis,
	varBsEmphasisColor,
	varBsEmphasisColorRgb,
	varBsFocusRingColor,
	varBsFocusRingOpacity,
	varBsFocusRingWidth,
	varBsFontMonospace,
	varBsFontSansSerif,
	varBsGradient,
	varBsGray,
	varBsGrayDark,
	varBsGreen,
	varBsHeadingColor,
	varBsHighlightBg,
	varBsHighlightColor,
	varBsIndigo,
	varBsInfo,
	varBsInfoBgSubtle,
	varBsInfoBorderSubtle,
	varBsInfoRgb,
	varBsInfoTextEmphasis,
	varBsLight,
	varBsLightBgSubtle,
	varBsLightBorderSubtle,
	varBsLightRgb,
	varBsLightTextEmphasis,
	varBsLinkColor,
	varBsLinkColorRgb,
	varBsLinkDecoration,
	varBsLinkHoverColor,
	varBsLinkHoverColorRgb,
	varBsOrange,
	varBsPink,
	varBsPrimary,
	varBsPrimaryBgSubtle,
	varBsPrimaryBorderSubtle,
	varBsPrimaryRgb,
	varBsPrimaryTextEmphasis,
	varBsPurple,
	varBsRed,
	varBsSecondary,
	varBsSecondaryBg,
	varBsSecondaryBgSubtle,
	varBsSecondaryBorderSubtle,
	varBsSecondaryColor,
	varBsSecondaryRgb,
	varBsSecondaryTextEmphasis,
	varBsSuccess,
	varBsSuccessBgSubtle,
	varBsSuccessBorderSubtle,
	varBsSuccessRgb,
	varBsSuccessTextEmphasis,
	varBsTeal,
	varBsTertiaryBg,
	varBsTertiaryColor,
	varBsWarning,
	varBsWarningBgSubtle,
	varBsWarningBorderSubtle,
	varBsWarningRgb,
	varBsWarningTextEmphasis,
	varBsWhite,
	varBsWhiteRgb,
	varBsYellow,
} from '../../theme-contract/_vars.css'
import {
	varBsFormInvalidBorderColor,
	varBsFormInvalidColor,
	varBsFormValidBorderColor,
	varBsFormValidColor,
} from '../../theme-contract/forms/_vars.css'
import { bodyFrame, bodyText, vars } from '../../theme-contract/theme-contract.css'
import { modalOpenHook } from '../../theme-contract/ui/modal/contract.css'

// Pulse theme scope class.
// Zero-style identifier used as a stable selector prefix.
export const pulseScope = style({})

// Global Bootstrap CSS custom properties (`--bs-*`) are assigned on the
// dedicated vars contract class to keep root var hosting separate from body
// layout/background styles.
globalStyle(`${pulseScope}${vars}`, {
	vars: {
		[varBsBlue]: "#007bff",
		[varBsIndigo]: "#6610f2",
		[varBsPurple]: "#593196",
		[varBsPink]: "#e83e8c",
		[varBsRed]: "#fc3939",
		[varBsOrange]: "#fd7e14",
		[varBsYellow]: "#efa31d",
		[varBsGreen]: "#13b955",
		[varBsTeal]: "#20c997",
		[varBsCyan]: "#009cdc",
		[varBsBlack]: "#000",
		[varBsWhite]: "#fff",
		[varBsGray]: "#868e96",
		[varBsGrayDark]: "#343a40",
		[varBsPrimary]: "#593196",
		[varBsSecondary]: "#a991d4",
		[varBsSuccess]: "#13b955",
		[varBsInfo]: "#009cdc",
		[varBsWarning]: "#efa31d",
		[varBsDanger]: "#fc3939",
		[varBsLight]: "#f9f8fc",
		[varBsDark]: "#17141f",
		[varBsPrimaryRgb]: "89, 49, 150",
		[varBsSecondaryRgb]: "169, 145, 212",
		[varBsSuccessRgb]: "19, 185, 85",
		[varBsInfoRgb]: "0, 156, 220",
		[varBsWarningRgb]: "239, 163, 29",
		[varBsDangerRgb]: "252, 57, 57",
		[varBsLightRgb]: "249, 248, 252",
		[varBsDarkRgb]: "23, 20, 31",
		[varBsPrimaryTextEmphasis]: "#24143c",
		[varBsSecondaryTextEmphasis]: "#443a55",
		[varBsSuccessTextEmphasis]: "#084a22",
		[varBsInfoTextEmphasis]: "#003e58",
		[varBsWarningTextEmphasis]: "#60410c",
		[varBsDangerTextEmphasis]: "#651717",
		[varBsLightTextEmphasis]: "#444",
		[varBsDarkTextEmphasis]: "#444",
		[varBsPrimaryBgSubtle]: "#ded6ea",
		[varBsSecondaryBgSubtle]: "#eee9f6",
		[varBsSuccessBgSubtle]: "#d0f1dd",
		[varBsInfoBgSubtle]: "#ccebf8",
		[varBsWarningBgSubtle]: "#fcedd2",
		[varBsDangerBgSubtle]: "#fed7d7",
		[varBsLightBgSubtle]: "#fdfdfd",
		[varBsDarkBgSubtle]: "#cbc8d0",
		[varBsPrimaryBorderSubtle]: "#bdadd5",
		[varBsSecondaryBorderSubtle]: "#ddd3ee",
		[varBsSuccessBorderSubtle]: "#a1e3bb",
		[varBsInfoBorderSubtle]: "#99d7f1",
		[varBsWarningBorderSubtle]: "#f9daa5",
		[varBsDangerBorderSubtle]: "#feb0b0",
		[varBsLightBorderSubtle]: "#f9f8fc",
		[varBsDarkBorderSubtle]: "#adb5bd",
		[varBsWhiteRgb]: "255, 255, 255",
		[varBsBlackRgb]: "0, 0, 0",
		[varBsFontSansSerif]: "system-ui, -apple-system, \"Segoe UI\", Roboto, \"Helvetica Neue\", \"Noto Sans\", \"Liberation Sans\", Arial, sans-serif, \"Apple Color Emoji\", \"Segoe UI Emoji\", \"Segoe UI Symbol\", \"Noto Color Emoji\"",
		[varBsFontMonospace]: "SFMono-Regular, Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace",
		[varBsGradient]: "linear-gradient(180deg, rgba(255, 255, 255, 0.15), rgba(255, 255, 255, 0))",
		[varBsBodyFontFamily]: varBsFontSansSerif,
		[varBsBodyFontSize]: "1rem",
		[varBsBodyFontWeight]: 400,
		[varBsBodyLineHeight]: 1.5,
		[varBsBodyColor]: "#444",
		[varBsBodyColorRgb]: "68, 68, 68",
		[varBsBodyBg]: "#fff",
		[varBsBodyBgRgb]: "255, 255, 255",
		[varBsEmphasisColor]: "#000",
		[varBsEmphasisColorRgb]: "0, 0, 0",
		[varBsSecondaryColor]: "rgba(68, 68, 68, 0.75)",
		[varBsSecondaryBg]: "#f9f8fc",
		[varBsTertiaryColor]: "rgba(68, 68, 68, 0.5)",
		[varBsTertiaryBg]: "#fafafa",
		[varBsHeadingColor]: "inherit",
		[varBsLinkColor]: "#593196",
		[varBsLinkColorRgb]: "89, 49, 150",
		[varBsLinkDecoration]: "underline",
		[varBsLinkHoverColor]: "#593196",
		[varBsLinkHoverColorRgb]: "89, 49, 150",
		[varBsCodeColor]: "#e83e8c",
		[varBsHighlightColor]: "#444",
		[varBsHighlightBg]: "#fcedd2",
		[varBsBorderWidth]: "1px",
		[varBsBorderStyle]: "solid",
		[varBsBorderColor]: "#ededed",
		[varBsBorderColorTranslucent]: "rgba(0, 0, 0, 0.175)",
		[varBsBorderRadius]: "0.375rem",
		[varBsBorderRadiusSm]: "0.25rem",
		[varBsBorderRadiusLg]: "0.5rem",
		[varBsBorderRadiusXl]: "1rem",
		[varBsBorderRadiusXxl]: "2rem",
		[varBsBorderRadiusPill]: "50rem",
		[varBsBoxShadow]: "0 0.5rem 1rem rgba(0, 0, 0, 0.15)",
		[varBsBoxShadowSm]: "0 0.125rem 0.25rem rgba(0, 0, 0, 0.075)",
		[varBsBoxShadowLg]: "0 1rem 3rem rgba(0, 0, 0, 0.175)",
		[varBsBoxShadowInset]: "inset 0 1px 2px rgba(0, 0, 0, 0.075)",
		[varBsFocusRingWidth]: "0.25rem",
		[varBsFocusRingOpacity]: 0.25,
		[varBsFocusRingColor]: "rgba(89, 49, 150, 0.25)",
		[varBsBtnCloseFilter]: "",
		[varBsCarouselIndicatorActiveBg]: "#fff",
		[varBsCarouselCaptionColor]: "#fff",
		[varBsCarouselControlIconFilter]: "",
		[varBsFormValidColor]: "#13b955",
		[varBsFormValidBorderColor]: "#13b955",
		[varBsFormInvalidColor]: "#fc3939",
		[varBsFormInvalidBorderColor]: "#fc3939",
	},
})

// ── Root / body styles ────────────────────────────────────────────────────────
// bodyText = typography; bodyFrame = page canvas (Ve2Shell). Do not add padding
// here — baseline screenshots have no padded wrapper around bd-example.

globalStyle(`${pulseScope}${bodyText}`, {
	fontFamily: varBsBodyFontFamily,
	fontSize: varBsBodyFontSize,
	fontWeight: varBsBodyFontWeight,
	lineHeight: varBsBodyLineHeight,
	color: varBsBodyColor,
})

globalStyle(`${pulseScope}${bodyFrame}`, {
	backgroundColor: varBsBodyBg,
	margin: 0,
	minHeight: '100vh',
})

// Bootstrap Modal JS adds modalOpenHook to <body> without theme scope.
globalStyle(`${modalOpenHook}`, {
	fontFamily: varBsBodyFontFamily,
	fontSize: varBsBodyFontSize,
	fontWeight: varBsBodyFontWeight,
	lineHeight: varBsBodyLineHeight,
	color: varBsBodyColor,
	backgroundColor: varBsBodyBg,
	margin: 0,
})
