import { globalStyle, style } from '@vanilla-extract/css'
import {
	varBsAccordionBtnActiveIcon,
	varBsAccordionBtnIcon,
	varBsBlack,
	varBsBlackRgb,
	varBsBlue,
	varBsBodyBg,
	varBsBodyBgRgb,
	varBsBodyColor,
	varBsBodyColorRgb,
	varBsBodyFontFamily,
	varBsBodyFontSize,
	varBsBodyFontWeight,
	varBsBodyLineHeight,
	varBsBorderColor,
	varBsBorderColorTranslucent,
	varBsBorderRadius,
	varBsBorderRadiusLg,
	varBsBorderRadiusPill,
	varBsBorderRadiusSm,
	varBsBorderRadiusXl,
	varBsBorderRadiusXxl,
	varBsBorderStyle,
	varBsBorderWidth,
	varBsBoxShadow,
	varBsBoxShadowInset,
	varBsBoxShadowLg,
	varBsBoxShadowSm,
	varBsCarouselCaptionColor,
	varBsCarouselControlIconFilter,
	varBsCarouselIndicatorActiveBg,
	varBsCodeColor,
	varBsCyan,
	varBsDanger,
	varBsDangerBgSubtle,
	varBsDangerBorderSubtle,
	varBsDangerRgb,
	varBsDangerTextEmphasis,
	varBsDark,
	varBsDarkBgSubtle,
	varBsDarkBorderSubtle,
	varBsDarkRgb,
	varBsDarkTextEmphasis,
	varBsEmphasisColor,
	varBsEmphasisColorRgb,
	varBsFocusRingColor,
	varBsFocusRingOpacity,
	varBsFocusRingWidth,
	varBsFontMonospace,
	varBsFontSansSerif,
	varBsGradient,
	varBsGray,
	varBsGrayDark,
	varBsGreen,
	varBsHeadingColor,
	varBsHighlightBg,
	varBsHighlightColor,
	varBsIndigo,
	varBsInfo,
	varBsInfoBgSubtle,
	varBsInfoBorderSubtle,
	varBsInfoRgb,
	varBsInfoTextEmphasis,
	varBsLight,
	varBsLightBgSubtle,
	varBsLightBorderSubtle,
	varBsLightRgb,
	varBsLightTextEmphasis,
	varBsLinkColor,
	varBsLinkColorRgb,
	varBsLinkDecoration,
	varBsLinkHoverColor,
	varBsLinkHoverColorRgb,
	varBsNavbarActiveColor,
	varBsNavbarBrandColor,
	varBsNavbarBrandHoverColor,
	varBsNavbarColor,
	varBsNavbarDisabledColor,
	varBsNavbarHoverColor,
	varBsNavbarTogglerBorderColor,
	varBsNavbarTogglerIconBg,
	varBsOrange,
	varBsPink,
	varBsPrimary,
	varBsPrimaryBgSubtle,
	varBsPrimaryBorderSubtle,
	varBsPrimaryRgb,
	varBsPrimaryTextEmphasis,
	varBsPurple,
	varBsRed,
	varBsSecondary,
	varBsSecondaryBg,
	varBsSecondaryBgSubtle,
	varBsSecondaryBorderSubtle,
	varBsSecondaryColor,
	varBsSecondaryRgb,
	varBsSecondaryTextEmphasis,
	varBsSuccess,
	varBsSuccessBgSubtle,
	varBsSuccessBorderSubtle,
	varBsSuccessRgb,
	varBsSuccessTextEmphasis,
	varBsTeal,
	varBsTertiaryBg,
	varBsTertiaryColor,
	varBsWarning,
	varBsWarningBgSubtle,
	varBsWarningBorderSubtle,
	varBsWarningRgb,
	varBsWarningTextEmphasis,
	varBsWhite,
	varBsWhiteRgb,
	varBsYellow,
} from '../../theme-contract/_vars.css'
import {
	varBsFormInvalidBorderColor,
	varBsFormInvalidColor,
	varBsFormSelectBgImg,
	varBsFormSwitchBg,
	varBsFormValidBorderColor,
	varBsFormValidColor,
} from '../../theme-contract/forms/_vars.css'
import { body, bodyText, vars } from '../../theme-contract/theme-contract.css'

// Pulse theme scope class.
// Zero-style identifier used as a stable selector prefix.
export const pulseScope = style({})

// Global Bootstrap CSS custom properties (`--bs-*`) are assigned on the
// dedicated vars contract class to keep root var hosting separate from body
// layout/background styles.
globalStyle(`${pulseScope}${vars}`, {
	vars: {
		[varBsBlue]: "#007bff",
		[varBsIndigo]: "#6610f2",
		[varBsPurple]: "#593196",
		[varBsPink]: "#e83e8c",
		[varBsRed]: "#fc3939",
		[varBsOrange]: "#fd7e14",
		[varBsYellow]: "#efa31d",
		[varBsGreen]: "#13b955",
		[varBsTeal]: "#20c997",
		[varBsCyan]: "#009cdc",
		[varBsBlack]: "#000",
		[varBsWhite]: "#fff",
		[varBsGray]: "#868e96",
		[varBsGrayDark]: "#343a40",
		[varBsPrimary]: "#593196",
		[varBsSecondary]: "#a991d4",
		[varBsSuccess]: "#13b955",
		[varBsInfo]: "#009cdc",
		[varBsWarning]: "#efa31d",
		[varBsDanger]: "#fc3939",
		[varBsLight]: "#f9f8fc",
		[varBsDark]: "#17141f",
		[varBsPrimaryRgb]: "89, 49, 150",
		[varBsSecondaryRgb]: "169, 145, 212",
		[varBsSuccessRgb]: "19, 185, 85",
		[varBsInfoRgb]: "0, 156, 220",
		[varBsWarningRgb]: "239, 163, 29",
		[varBsDangerRgb]: "252, 57, 57",
		[varBsLightRgb]: "249, 248, 252",
		[varBsDarkRgb]: "23, 20, 31",
		[varBsPrimaryTextEmphasis]: "#9b83c0",
		[varBsSecondaryTextEmphasis]: "#cbbde5",
		[varBsSuccessTextEmphasis]: "#71d599",
		[varBsInfoTextEmphasis]: "#66c4ea",
		[varBsWarningTextEmphasis]: "#f5c877",
		[varBsDangerTextEmphasis]: "#fd8888",
		[varBsLightTextEmphasis]: "#fafafa",
		[varBsDarkTextEmphasis]: "#ededed",
		[varBsPrimaryBgSubtle]: "#120a1e",
		[varBsSecondaryBgSubtle]: "#221d2a",
		[varBsSuccessBgSubtle]: "#042511",
		[varBsInfoBgSubtle]: "#001f2c",
		[varBsWarningBgSubtle]: "#302106",
		[varBsDangerBgSubtle]: "#320b0b",
		[varBsLightBgSubtle]: "#343a40",
		[varBsDarkBgSubtle]: "#1a1d20",
		[varBsPrimaryBorderSubtle]: "#351d5a",
		[varBsSecondaryBorderSubtle]: "#65577f",
		[varBsSuccessBorderSubtle]: "#0b6f33",
		[varBsInfoBorderSubtle]: "#005e84",
		[varBsWarningBorderSubtle]: "#8f6211",
		[varBsDangerBorderSubtle]: "#972222",
		[varBsLightBorderSubtle]: "#444",
		[varBsDarkBorderSubtle]: "#343a40",
		[varBsWhiteRgb]: "255, 255, 255",
		[varBsBlackRgb]: "0, 0, 0",
		[varBsFontSansSerif]: "system-ui, -apple-system, \"Segoe UI\", Roboto, \"Helvetica Neue\", \"Noto Sans\", \"Liberation Sans\", Arial, sans-serif, \"Apple Color Emoji\", \"Segoe UI Emoji\", \"Segoe UI Symbol\", \"Noto Color Emoji\"",
		[varBsFontMonospace]: "SFMono-Regular, Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace",
		[varBsGradient]: "linear-gradient(180deg, rgba(255, 255, 255, 0.15), rgba(255, 255, 255, 0))",
		[varBsBodyFontFamily]: varBsFontSansSerif,
		[varBsBodyFontSize]: "1rem",
		[varBsBodyFontWeight]: 400,
		[varBsBodyLineHeight]: 1.5,
		[varBsBodyColor]: "#ededed",
		[varBsBodyColorRgb]: "237, 237, 237",
		[varBsBodyBg]: "#17141f",
		[varBsBodyBgRgb]: "23, 20, 31",
		[varBsEmphasisColor]: "#fff",
		[varBsEmphasisColorRgb]: "255, 255, 255",
		[varBsSecondaryColor]: "rgba(237, 237, 237, 0.75)",
		[varBsSecondaryBg]: "#343a40",
		[varBsTertiaryColor]: "rgba(237, 237, 237, 0.5)",
		[varBsTertiaryBg]: "#262730",
		[varBsHeadingColor]: "inherit",
		[varBsLinkColor]: "#9b83c0",
		[varBsLinkColorRgb]: "155, 131, 192",
		[varBsLinkDecoration]: "underline",
		[varBsLinkHoverColor]: "#af9ccd",
		[varBsLinkHoverColorRgb]: "175, 156, 205",
		[varBsCodeColor]: "#f18bba",
		[varBsHighlightColor]: "#ededed",
		[varBsHighlightBg]: "#60410c",
		[varBsBorderWidth]: "1px",
		[varBsBorderStyle]: "solid",
		[varBsBorderColor]: "#444",
		[varBsBorderColorTranslucent]: "rgba(255, 255, 255, 0.15)",
		[varBsBorderRadius]: "0.375rem",
		[varBsBorderRadiusSm]: "0.25rem",
		[varBsBorderRadiusLg]: "0.5rem",
		[varBsBorderRadiusXl]: "1rem",
		[varBsBorderRadiusXxl]: "2rem",
		[varBsBorderRadiusPill]: "50rem",
		[varBsBoxShadow]: "0 0.5rem 1rem rgba(0, 0, 0, 0.15)",
		[varBsBoxShadowSm]: "0 0.125rem 0.25rem rgba(0, 0, 0, 0.075)",
		[varBsBoxShadowLg]: "0 1rem 3rem rgba(0, 0, 0, 0.175)",
		[varBsBoxShadowInset]: "inset 0 1px 2px rgba(0, 0, 0, 0.075)",
		[varBsFocusRingWidth]: "0.25rem",
		[varBsFocusRingOpacity]: 0.25,
		[varBsFocusRingColor]: "rgba(89, 49, 150, 0.25)",
		[varBsNavbarColor]: "rgba(255, 255, 255, 0.55)",
		[varBsNavbarHoverColor]: "rgba(255, 255, 255, 0.75)",
		[varBsNavbarDisabledColor]: "rgba(255, 255, 255, 0.25)",
		[varBsNavbarActiveColor]: "#fff",
		[varBsNavbarBrandColor]: "#fff",
		[varBsNavbarBrandHoverColor]: "#fff",
		[varBsNavbarTogglerBorderColor]: "rgba(255, 255, 255, 0.1)",
		[varBsNavbarTogglerIconBg]: "url(\"data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 30 30'%3e%3cpath stroke='rgba%28255, 255, 255, 0.55%29' stroke-linecap='round' stroke-miterlimit='10' stroke-width='2' d='M4 7h22M4 15h22M4 23h22'/%3e%3c/svg%3e\")",
		[varBsAccordionBtnIcon]: "url(\"data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16' fill='%239b83c0'%3e%3cpath fill-rule='evenodd' d='M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708'/%3e%3c/svg%3e\")",
		[varBsAccordionBtnActiveIcon]: "url(\"data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16' fill='%239b83c0'%3e%3cpath fill-rule='evenodd' d='M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708'/%3e%3c/svg%3e\")",
		[varBsCarouselIndicatorActiveBg]: "#000",
		[varBsCarouselCaptionColor]: "#000",
		[varBsCarouselControlIconFilter]: "invert(1) grayscale(100)",
	},
})

// ── Root / body styles ────────────────────────────────────────────────────────

globalStyle(`${pulseScope}${bodyText}`, {
	fontFamily: varBsBodyFontFamily,
	fontSize: varBsBodyFontSize,
	fontWeight: varBsBodyFontWeight,
	lineHeight: varBsBodyLineHeight,
	color: varBsBodyColor,
})

globalStyle(`${pulseScope}${body}`, {
	backgroundColor: varBsBodyBg,
	padding: '1rem',
	display: 'block',
})
