// GERADO por scripts/gen-public-vars.mjs — NÃO editar à mão.
import { globalStyle } from '@vanilla-extract/css'
import { vaporScope } from './scope.css'
import { varBsBlackRgb, varBsBodyBgRgb, varBsBodyColorRgb, varBsBorderColor, varBsBorderRadius, varBsBorderRadiusLg, varBsBorderRadiusPill, varBsBorderRadiusSm, varBsBorderRadiusXl, varBsBorderRadiusXxl, varBsBorderStyle, varBsBorderWidth, varBsBoxShadow, varBsBoxShadowLg, varBsBoxShadowSm, varBsDangerBgSubtle, varBsDangerBorderSubtle, varBsDangerRgb, varBsDangerTextEmphasis, varBsDarkBgSubtle, varBsDarkBorderSubtle, varBsDarkRgb, varBsDarkTextEmphasis, varBsEmphasisColor, varBsEmphasisColorRgb, varBsFocusRingColor, varBsFocusRingOpacity, varBsFontMonospace, varBsGradient, varBsInfoBgSubtle, varBsInfoBorderSubtle, varBsInfoRgb, varBsInfoTextEmphasis, varBsLightBgSubtle, varBsLightBorderSubtle, varBsLightRgb, varBsLightTextEmphasis, varBsLinkColorRgb, varBsPrimaryBgSubtle, varBsPrimaryBorderSubtle, varBsPrimaryRgb, varBsPrimaryTextEmphasis, varBsSecondaryBgRgb, varBsSecondaryBgSubtle, varBsSecondaryBorderSubtle, varBsSecondaryColor, varBsSecondaryRgb, varBsSecondaryTextEmphasis, varBsSuccessBgSubtle, varBsSuccessBorderSubtle, varBsSuccessRgb, varBsSuccessTextEmphasis, varBsTertiaryBgRgb, varBsTertiaryColor, varBsWarningBgSubtle, varBsWarningBorderSubtle, varBsWarningRgb, varBsWarningTextEmphasis, varBsWhiteRgb } from '../../theme-contract/_public-vars.css'

globalStyle(vaporScope, {
	vars: {
		[varBsBlackRgb]: "0, 0, 0",
		[varBsBodyBgRgb]: "26, 9, 51",
		[varBsBodyColorRgb]: "50, 251, 226",
		[varBsBorderColor]: "#dee2e6",
		[varBsBorderRadius]: "0.15rem",
		[varBsBorderRadiusLg]: "0.5rem",
		[varBsBorderRadiusPill]: "50rem",
		[varBsBorderRadiusSm]: "0.05rem",
		[varBsBorderRadiusXl]: "1rem",
		[varBsBorderRadiusXxl]: "2rem",
		[varBsBorderStyle]: "solid",
		[varBsBorderWidth]: "0",
		[varBsBoxShadow]: "0 0.5rem 1rem rgba(0, 0, 0, 0.15)",
		[varBsBoxShadowLg]: "0 1rem 3rem rgba(0, 0, 0, 0.175)",
		[varBsBoxShadowSm]: "0 0.125rem 0.25rem rgba(0, 0, 0, 0.075)",
		[varBsDangerBgSubtle]: "#fadbdd",
		[varBsDangerBorderSubtle]: "#f4b7bb",
		[varBsDangerRgb]: "228, 76, 85",
		[varBsDangerTextEmphasis]: "#5b1e22",
		[varBsDarkBgSubtle]: "#ced4da",
		[varBsDarkBorderSubtle]: "#adb5bd",
		[varBsDarkRgb]: "23, 2, 41",
		[varBsDarkTextEmphasis]: "#495057",
		[varBsEmphasisColor]: "#000",
		[varBsEmphasisColorRgb]: "0, 0, 0",
		[varBsFocusRingColor]: "rgba(111, 66, 193, 0.25)",
		[varBsFocusRingOpacity]: "0.25",
		[varBsFontMonospace]: "SFMono-Regular, Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace",
		[varBsGradient]: "linear-gradient(180deg, rgba(255, 255, 255, 0.15), rgba(255, 255, 255, 0))",
		[varBsInfoBgSubtle]: "#d1ecfd",
		[varBsInfoBorderSubtle]: "#a4dafb",
		[varBsInfoRgb]: "27, 162, 246",
		[varBsInfoTextEmphasis]: "#0b4162",
		[varBsLightBgSubtle]: "#fcfcfd",
		[varBsLightBorderSubtle]: "#e9ecef",
		[varBsLightRgb]: "68, 217, 232",
		[varBsLightTextEmphasis]: "#495057",
		[varBsLinkColorRgb]: "50, 251, 226",
		[varBsPrimaryBgSubtle]: "#e2d9f3",
		[varBsPrimaryBorderSubtle]: "#c5b3e6",
		[varBsPrimaryRgb]: "111, 66, 193",
		[varBsPrimaryTextEmphasis]: "#2c1a4d",
		[varBsSecondaryBgRgb]: "233, 236, 239",
		[varBsSecondaryBgSubtle]: "#fbd7f1",
		[varBsSecondaryBorderSubtle]: "#f7b0e3",
		[varBsSecondaryColor]: "rgba(50, 251, 226, 0.75)",
		[varBsSecondaryRgb]: "234, 57, 184",
		[varBsSecondaryTextEmphasis]: "#5e174a",
		[varBsSuccessBgSubtle]: "#d8fce6",
		[varBsSuccessBorderSubtle]: "#b1facd",
		[varBsSuccessRgb]: "60, 242, 129",
		[varBsSuccessTextEmphasis]: "#186134",
		[varBsTertiaryBgRgb]: "248, 249, 250",
		[varBsTertiaryColor]: "rgba(50, 251, 226, 0.5)",
		[varBsWarningBgSubtle]: "#fff3cd",
		[varBsWarningBorderSubtle]: "#ffe69c",
		[varBsWarningRgb]: "255, 193, 7",
		[varBsWarningTextEmphasis]: "#664d03",
		[varBsWhiteRgb]: "255, 255, 255",
	},
})
