import { globalStyle, style } from '@vanilla-extract/css'
import {
	varBsBlack,
	varBsBlackRgb,
	varBsBlue,
	varBsBodyBg,
	varBsBodyBgRgb,
	varBsBodyColor,
	varBsBodyColorRgb,
	varBsBodyFontFamily,
	varBsBodyFontSize,
	varBsBodyFontWeight,
	varBsBodyLineHeight,
	varBsBorderColor,
	varBsBorderColorTranslucent,
	varBsBorderRadius,
	varBsBorderRadiusLg,
	varBsBorderRadiusPill,
	varBsBorderRadiusSm,
	varBsBorderRadiusXl,
	varBsBorderRadiusXxl,
	varBsBorderStyle,
	varBsBorderWidth,
	varBsBoxShadow,
	varBsBoxShadowInset,
	varBsBoxShadowLg,
	varBsBoxShadowSm,
	varBsCarouselCaptionColor,
	varBsCarouselIndicatorActiveBg,
	varBsCodeColor,
	varBsCyan,
	varBsDanger,
	varBsDangerBgSubtle,
	varBsDangerBorderSubtle,
	varBsDangerRgb,
	varBsDangerTextEmphasis,
	varBsDark,
	varBsDarkBgSubtle,
	varBsDarkBorderSubtle,
	varBsDarkRgb,
	varBsDarkTextEmphasis,
	varBsEmphasisColor,
	varBsEmphasisColorRgb,
	varBsFocusRingColor,
	varBsFocusRingOpacity,
	varBsFocusRingWidth,
	varBsFontMonospace,
	varBsFontSansSerif,
	varBsGradient,
	varBsGray,
	varBsGrayDark,
	varBsGreen,
	varBsHeadingColor,
	varBsHighlightBg,
	varBsHighlightColor,
	varBsIndigo,
	varBsInfo,
	varBsInfoBgSubtle,
	varBsInfoBorderSubtle,
	varBsInfoRgb,
	varBsInfoTextEmphasis,
	varBsLight,
	varBsLightBgSubtle,
	varBsLightBorderSubtle,
	varBsLightRgb,
	varBsLightTextEmphasis,
	varBsLinkColor,
	varBsLinkColorRgb,
	varBsLinkDecoration,
	varBsLinkHoverColor,
	varBsLinkHoverColorRgb,
	varBsOrange,
	varBsPink,
	varBsPrimary,
	varBsPrimaryBgSubtle,
	varBsPrimaryBorderSubtle,
	varBsPrimaryRgb,
	varBsPrimaryTextEmphasis,
	varBsPurple,
	varBsRed,
	varBsSecondary,
	varBsSecondaryBg,
	varBsSecondaryBgSubtle,
	varBsSecondaryBorderSubtle,
	varBsSecondaryColor,
	varBsSecondaryRgb,
	varBsSecondaryTextEmphasis,
	varBsSuccess,
	varBsSuccessBgSubtle,
	varBsSuccessBorderSubtle,
	varBsSuccessRgb,
	varBsSuccessTextEmphasis,
	varBsTeal,
	varBsTertiaryBg,
	varBsTertiaryColor,
	varBsWarning,
	varBsWarningBgSubtle,
	varBsWarningBorderSubtle,
	varBsWarningRgb,
	varBsWarningTextEmphasis,
	varBsWhite,
	varBsWhiteRgb,
	varBsYellow,
} from '../../theme-contract/_vars.css'
import {
	varBsFormInvalidBorderColor,
	varBsFormInvalidColor,
	varBsFormValidBorderColor,
	varBsFormValidColor,
} from '../../theme-contract/forms/_vars.css'
import { body, bodyText, vars } from '../../theme-contract/theme-contract.css'

// Vapor theme scope class.
// Zero-style identifier used as a stable selector prefix.
export const vaporScope = style({})

// Global Bootstrap CSS custom properties (`--bs-*`) are assigned on the
// dedicated vars contract class to keep root var hosting separate from body
// layout/background styles.
globalStyle(`${vaporScope}${vars}`, {
	vars: {
		[varBsBlue]: "#1ba2f6",
		[varBsIndigo]: "#6610f2",
		[varBsPurple]: "#6f42c1",
		[varBsPink]: "#ea39b8",
		[varBsRed]: "#e44c55",
		[varBsOrange]: "#f1b633",
		[varBsYellow]: "#ffc107",
		[varBsGreen]: "#3cf281",
		[varBsTeal]: "#3f81a2",
		[varBsCyan]: "#32fbe2",
		[varBsBlack]: "#000",
		[varBsWhite]: "#fff",
		[varBsGray]: "#6c757d",
		[varBsGrayDark]: "#343a40",
		[varBsPrimary]: "#6f42c1",
		[varBsSecondary]: "#ea39b8",
		[varBsSuccess]: "#3cf281",
		[varBsInfo]: "#1ba2f6",
		[varBsWarning]: "#ffc107",
		[varBsDanger]: "#e44c55",
		[varBsLight]: "#44d9e8",
		[varBsDark]: "#170229",
		[varBsPrimaryRgb]: "111, 66, 193",
		[varBsSecondaryRgb]: "234, 57, 184",
		[varBsSuccessRgb]: "60, 242, 129",
		[varBsInfoRgb]: "27, 162, 246",
		[varBsWarningRgb]: "255, 193, 7",
		[varBsDangerRgb]: "228, 76, 85",
		[varBsLightRgb]: "68, 217, 232",
		[varBsDarkRgb]: "23, 2, 41",
		[varBsPrimaryTextEmphasis]: "#2c1a4d",
		[varBsSecondaryTextEmphasis]: "#5e174a",
		[varBsSuccessTextEmphasis]: "#186134",
		[varBsInfoTextEmphasis]: "#0b4162",
		[varBsWarningTextEmphasis]: "#664d03",
		[varBsDangerTextEmphasis]: "#5b1e22",
		[varBsLightTextEmphasis]: "#495057",
		[varBsDarkTextEmphasis]: "#495057",
		[varBsPrimaryBgSubtle]: "#e2d9f3",
		[varBsSecondaryBgSubtle]: "#fbd7f1",
		[varBsSuccessBgSubtle]: "#d8fce6",
		[varBsInfoBgSubtle]: "#d1ecfd",
		[varBsWarningBgSubtle]: "#fff3cd",
		[varBsDangerBgSubtle]: "#fadbdd",
		[varBsLightBgSubtle]: "#fcfcfd",
		[varBsDarkBgSubtle]: "#ced4da",
		[varBsPrimaryBorderSubtle]: "#c5b3e6",
		[varBsSecondaryBorderSubtle]: "#f7b0e3",
		[varBsSuccessBorderSubtle]: "#b1facd",
		[varBsInfoBorderSubtle]: "#a4dafb",
		[varBsWarningBorderSubtle]: "#ffe69c",
		[varBsDangerBorderSubtle]: "#f4b7bb",
		[varBsLightBorderSubtle]: "#e9ecef",
		[varBsDarkBorderSubtle]: "#adb5bd",
		[varBsWhiteRgb]: "255, 255, 255",
		[varBsBlackRgb]: "0, 0, 0",
		[varBsFontSansSerif]: "Lato, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif, \"Apple Color Emoji\", \"Segoe UI Emoji\", \"Segoe UI Symbol\"",
		[varBsFontMonospace]: "SFMono-Regular, Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace",
		[varBsGradient]: "linear-gradient(180deg, rgba(255, 255, 255, 0.15), rgba(255, 255, 255, 0))",
		[varBsBodyFontFamily]: varBsFontSansSerif,
		[varBsBodyFontSize]: "1rem",
		[varBsBodyFontWeight]: 400,
		[varBsBodyLineHeight]: 1.5,
		[varBsBodyColor]: "#32fbe2",
		[varBsBodyColorRgb]: "50, 251, 226",
		[varBsBodyBg]: "#1a0933",
		[varBsBodyBgRgb]: "26, 9, 51",
		[varBsEmphasisColor]: "#000",
		[varBsEmphasisColorRgb]: "0, 0, 0",
		[varBsSecondaryColor]: "rgba(50, 251, 226, 0.75)",
		[varBsSecondaryBg]: "#e9ecef",
		[varBsTertiaryColor]: "rgba(50, 251, 226, 0.5)",
		[varBsTertiaryBg]: "#f8f9fa",
		[varBsHeadingColor]: "inherit",
		[varBsLinkColor]: "#32fbe2",
		[varBsLinkColorRgb]: "50, 251, 226",
		[varBsLinkDecoration]: "underline",
		[varBsLinkHoverColor]: "#28c9b5",
		[varBsLinkHoverColorRgb]: "40, 201, 181",
		[varBsCodeColor]: "#ea39b8",
		[varBsHighlightColor]: "#32fbe2",
		[varBsHighlightBg]: "#fff3cd",
		[varBsBorderWidth]: 0,
		[varBsBorderStyle]: "solid",
		[varBsBorderColor]: "#dee2e6",
		[varBsBorderColorTranslucent]: "rgba(0, 0, 0, 0.175)",
		[varBsBorderRadius]: "0.15rem",
		[varBsBorderRadiusSm]: "0.05rem",
		[varBsBorderRadiusLg]: "0.5rem",
		[varBsBorderRadiusXl]: "1rem",
		[varBsBorderRadiusXxl]: "2rem",
		[varBsBorderRadiusPill]: "50rem",
		[varBsBoxShadow]: "0 0.5rem 1rem rgba(0, 0, 0, 0.15)",
		[varBsBoxShadowSm]: "0 0.125rem 0.25rem rgba(0, 0, 0, 0.075)",
		[varBsBoxShadowLg]: "0 1rem 3rem rgba(0, 0, 0, 0.175)",
		[varBsBoxShadowInset]: "inset 0 1px 2px rgba(0, 0, 0, 0.075)",
		[varBsFocusRingWidth]: "0.25rem",
		[varBsFocusRingOpacity]: 0.25,
		[varBsFocusRingColor]: "rgba(111, 66, 193, 0.25)",
		[varBsCarouselIndicatorActiveBg]: "#fff",
		[varBsCarouselCaptionColor]: "#fff",
	},
})

// ── Root / body styles ────────────────────────────────────────────────────────

globalStyle(`${vaporScope}${bodyText}`, {
	fontFamily: varBsBodyFontFamily,
	fontSize: varBsBodyFontSize,
	fontWeight: varBsBodyFontWeight,
	lineHeight: varBsBodyLineHeight,
	color: varBsBodyColor,
})

globalStyle(`${vaporScope}${body}`, {
	backgroundColor: varBsBodyBg,
	padding: '1rem',
	display: 'block',
})
