// GERADO por scripts/gen-public-vars.mjs — NÃO editar à mão.
import { globalStyle } from '@vanilla-extract/css'
import { luxScope } from './scope.css'
import { varBsBlackRgb, varBsBodyBgRgb, varBsBodyColorRgb, varBsBorderColor, varBsBorderRadius, varBsBorderRadiusLg, varBsBorderRadiusPill, varBsBorderRadiusSm, varBsBorderRadiusXl, varBsBorderRadiusXxl, varBsBorderStyle, varBsBorderWidth, varBsBoxShadow, varBsBoxShadowLg, varBsBoxShadowSm, varBsDangerBgSubtle, varBsDangerBorderSubtle, varBsDangerRgb, varBsDangerTextEmphasis, varBsDarkBgSubtle, varBsDarkBorderSubtle, varBsDarkRgb, varBsDarkTextEmphasis, varBsEmphasisColor, varBsEmphasisColorRgb, varBsFocusRingColor, varBsFocusRingOpacity, varBsFontMonospace, varBsGradient, varBsInfoBgSubtle, varBsInfoBorderSubtle, varBsInfoRgb, varBsInfoTextEmphasis, varBsLightBgSubtle, varBsLightBorderSubtle, varBsLightRgb, varBsLightTextEmphasis, varBsLinkColorRgb, varBsPrimaryBgSubtle, varBsPrimaryBorderSubtle, varBsPrimaryRgb, varBsPrimaryTextEmphasis, varBsSecondaryBgRgb, varBsSecondaryBgSubtle, varBsSecondaryBorderSubtle, varBsSecondaryColor, varBsSecondaryRgb, varBsSecondaryTextEmphasis, varBsSuccessBgSubtle, varBsSuccessBorderSubtle, varBsSuccessRgb, varBsSuccessTextEmphasis, varBsTertiaryBgRgb, varBsTertiaryColor, varBsWarningBgSubtle, varBsWarningBorderSubtle, varBsWarningRgb, varBsWarningTextEmphasis, varBsWhiteRgb } from '../../theme-contract/_public-vars.css'

globalStyle(luxScope, {
	vars: {
		[varBsBlackRgb]: "0, 0, 0",
		[varBsBodyBgRgb]: "255, 255, 255",
		[varBsBodyColorRgb]: "85, 89, 92",
		[varBsBorderColor]: "#e0e1e2",
		[varBsBorderRadius]: "0.375rem",
		[varBsBorderRadiusLg]: "0.5rem",
		[varBsBorderRadiusPill]: "50rem",
		[varBsBorderRadiusSm]: "0.25rem",
		[varBsBorderRadiusXl]: "1rem",
		[varBsBorderRadiusXxl]: "2rem",
		[varBsBorderStyle]: "solid",
		[varBsBorderWidth]: "1px",
		[varBsBoxShadow]: "0 0.5rem 1rem rgba(0, 0, 0, 0.15)",
		[varBsBoxShadowLg]: "0 1rem 3rem rgba(0, 0, 0, 0.175)",
		[varBsBoxShadowSm]: "0 0.125rem 0.25rem rgba(0, 0, 0, 0.075)",
		[varBsDangerBgSubtle]: "#f7dddc",
		[varBsDangerBorderSubtle]: "#f0bab9",
		[varBsDangerRgb]: "217, 83, 79",
		[varBsDangerTextEmphasis]: "#572120",
		[varBsDarkBgSubtle]: "#cdcecf",
		[varBsDarkBorderSubtle]: "#adb5bd",
		[varBsDarkRgb]: "52, 58, 64",
		[varBsDarkTextEmphasis]: "#55595c",
		[varBsEmphasisColor]: "#000",
		[varBsEmphasisColorRgb]: "0, 0, 0",
		[varBsFocusRingColor]: "rgba(26, 26, 26, 0.25)",
		[varBsFocusRingOpacity]: "0.25",
		[varBsFontMonospace]: "SFMono-Regular, Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace",
		[varBsGradient]: "linear-gradient(180deg, rgba(255, 255, 255, 0.15), rgba(255, 255, 255, 0))",
		[varBsInfoBgSubtle]: "#d2ebf5",
		[varBsInfoBorderSubtle]: "#a5d7ec",
		[varBsInfoRgb]: "31, 155, 207",
		[varBsInfoTextEmphasis]: "#0c3e53",
		[varBsLightBgSubtle]: "#fcfcfd",
		[varBsLightBorderSubtle]: "#f0f1f2",
		[varBsLightRgb]: "240, 241, 242",
		[varBsLightTextEmphasis]: "#55595c",
		[varBsLinkColorRgb]: "26, 26, 26",
		[varBsPrimaryBgSubtle]: "#d1d1d1",
		[varBsPrimaryBorderSubtle]: "#a3a3a3",
		[varBsPrimaryRgb]: "26, 26, 26",
		[varBsPrimaryTextEmphasis]: "#0a0a0a",
		[varBsSecondaryBgRgb]: "240, 241, 242",
		[varBsSecondaryBgSubtle]: "white",
		[varBsSecondaryBorderSubtle]: "white",
		[varBsSecondaryColor]: "rgba(85, 89, 92, 0.75)",
		[varBsSecondaryRgb]: "255, 255, 255",
		[varBsSecondaryTextEmphasis]: "#666666",
		[varBsSuccessBgSubtle]: "#dbf2e3",
		[varBsSuccessBorderSubtle]: "#b7e5c7",
		[varBsSuccessRgb]: "75, 191, 115",
		[varBsSuccessTextEmphasis]: "#1e4c2e",
		[varBsTertiaryBgRgb]: "248, 249, 250",
		[varBsTertiaryColor]: "rgba(85, 89, 92, 0.5)",
		[varBsWarningBgSubtle]: "#fcefdc",
		[varBsWarningBorderSubtle]: "#f9deb8",
		[varBsWarningRgb]: "240, 173, 78",
		[varBsWarningTextEmphasis]: "#60451f",
		[varBsWhiteRgb]: "255, 255, 255",
	},
})
