import { globalStyle, style } from '@vanilla-extract/css'
import {
	varBsBlack,
	varBsBlackRgb,
	varBsBlue,
	varBsBodyBg,
	varBsBodyBgRgb,
	varBsBodyColor,
	varBsBodyColorRgb,
	varBsBodyFontFamily,
	varBsBodyFontSize,
	varBsBodyFontWeight,
	varBsBodyLineHeight,
	varBsBorderColor,
	varBsBorderColorTranslucent,
	varBsBorderRadius,
	varBsBorderRadiusLg,
	varBsBorderRadiusPill,
	varBsBorderRadiusSm,
	varBsBorderRadiusXl,
	varBsBorderRadiusXxl,
	varBsBorderStyle,
	varBsBorderWidth,
	varBsBoxShadow,
	varBsBoxShadowInset,
	varBsBoxShadowLg,
	varBsBoxShadowSm,
	varBsBtnCloseFilter,
	varBsCarouselCaptionColor,
	varBsCarouselControlIconFilter,
	varBsCarouselIndicatorActiveBg,
	varBsCodeColor,
	varBsCyan,
	varBsDanger,
	varBsDangerBgSubtle,
	varBsDangerBorderSubtle,
	varBsDangerRgb,
	varBsDangerTextEmphasis,
	varBsDark,
	varBsDarkBgSubtle,
	varBsDarkBorderSubtle,
	varBsDarkRgb,
	varBsDarkTextEmphasis,
	varBsEmphasisColor,
	varBsEmphasisColorRgb,
	varBsFocusRingColor,
	varBsFocusRingOpacity,
	varBsFocusRingWidth,
	varBsFontMonospace,
	varBsFontSansSerif,
	varBsGradient,
	varBsGray,
	varBsGrayDark,
	varBsGreen,
	varBsHeadingColor,
	varBsHighlightBg,
	varBsHighlightColor,
	varBsIndigo,
	varBsInfo,
	varBsInfoBgSubtle,
	varBsInfoBorderSubtle,
	varBsInfoRgb,
	varBsInfoTextEmphasis,
	varBsLight,
	varBsLightBgSubtle,
	varBsLightBorderSubtle,
	varBsLightRgb,
	varBsLightTextEmphasis,
	varBsLinkColor,
	varBsLinkColorRgb,
	varBsLinkDecoration,
	varBsLinkHoverColor,
	varBsLinkHoverColorRgb,
	varBsOrange,
	varBsPink,
	varBsPrimary,
	varBsPrimaryBgSubtle,
	varBsPrimaryBorderSubtle,
	varBsPrimaryRgb,
	varBsPrimaryTextEmphasis,
	varBsPurple,
	varBsRed,
	varBsSecondary,
	varBsSecondaryBg,
	varBsSecondaryBgSubtle,
	varBsSecondaryBorderSubtle,
	varBsSecondaryColor,
	varBsSecondaryRgb,
	varBsSecondaryTextEmphasis,
	varBsSuccess,
	varBsSuccessBgSubtle,
	varBsSuccessBorderSubtle,
	varBsSuccessRgb,
	varBsSuccessTextEmphasis,
	varBsTeal,
	varBsTertiaryBg,
	varBsTertiaryColor,
	varBsWarning,
	varBsWarningBgSubtle,
	varBsWarningBorderSubtle,
	varBsWarningRgb,
	varBsWarningTextEmphasis,
	varBsWhite,
	varBsWhiteRgb,
	varBsYellow,
} from '../../theme-contract/_vars.css'
import {
	varBsFormInvalidBorderColor,
	varBsFormInvalidColor,
	varBsFormValidBorderColor,
	varBsFormValidColor,
} from '../../theme-contract/forms/_vars.css'
import { bodyFrame, bodyText, vars } from '../../theme-contract/theme-contract.css'
import { modalOpenHook } from '../../theme-contract/ui/modal/contract.css'

// Lux theme scope class.
// Zero-style identifier used as a stable selector prefix.
export const luxScope = style({})

// Global Bootstrap CSS custom properties (`--bs-*`) are assigned on the
// dedicated vars contract class to keep root var hosting separate from body
// layout/background styles.
globalStyle(`${luxScope}${vars}`, {
	vars: {
		[varBsBlue]: "#007bff",
		[varBsIndigo]: "#6610f2",
		[varBsPurple]: "#6f42c1",
		[varBsPink]: "#e83e8c",
		[varBsRed]: "#d9534f",
		[varBsOrange]: "#fd7e14",
		[varBsYellow]: "#f0ad4e",
		[varBsGreen]: "#4bbf73",
		[varBsTeal]: "#20c997",
		[varBsCyan]: "#1f9bcf",
		[varBsBlack]: "#000",
		[varBsWhite]: "#fff",
		[varBsGray]: "#919aa1",
		[varBsGrayDark]: "#343a40",
		[varBsPrimary]: "#1a1a1a",
		[varBsSecondary]: "#fff",
		[varBsSuccess]: "#4bbf73",
		[varBsInfo]: "#1f9bcf",
		[varBsWarning]: "#f0ad4e",
		[varBsDanger]: "#d9534f",
		[varBsLight]: "#f0f1f2",
		[varBsDark]: "#343a40",
		[varBsPrimaryRgb]: "26, 26, 26",
		[varBsSecondaryRgb]: "255, 255, 255",
		[varBsSuccessRgb]: "75, 191, 115",
		[varBsInfoRgb]: "31, 155, 207",
		[varBsWarningRgb]: "240, 173, 78",
		[varBsDangerRgb]: "217, 83, 79",
		[varBsLightRgb]: "240, 241, 242",
		[varBsDarkRgb]: "52, 58, 64",
		[varBsPrimaryTextEmphasis]: "#0a0a0a",
		[varBsSecondaryTextEmphasis]: "#666666",
		[varBsSuccessTextEmphasis]: "#1e4c2e",
		[varBsInfoTextEmphasis]: "#0c3e53",
		[varBsWarningTextEmphasis]: "#60451f",
		[varBsDangerTextEmphasis]: "#572120",
		[varBsLightTextEmphasis]: "#55595c",
		[varBsDarkTextEmphasis]: "#55595c",
		[varBsPrimaryBgSubtle]: "#d1d1d1",
		[varBsSecondaryBgSubtle]: "white",
		[varBsSuccessBgSubtle]: "#dbf2e3",
		[varBsInfoBgSubtle]: "#d2ebf5",
		[varBsWarningBgSubtle]: "#fcefdc",
		[varBsDangerBgSubtle]: "#f7dddc",
		[varBsLightBgSubtle]: "#fcfcfd",
		[varBsDarkBgSubtle]: "#cdcecf",
		[varBsPrimaryBorderSubtle]: "#a3a3a3",
		[varBsSecondaryBorderSubtle]: "white",
		[varBsSuccessBorderSubtle]: "#b7e5c7",
		[varBsInfoBorderSubtle]: "#a5d7ec",
		[varBsWarningBorderSubtle]: "#f9deb8",
		[varBsDangerBorderSubtle]: "#f0bab9",
		[varBsLightBorderSubtle]: "#f0f1f2",
		[varBsDarkBorderSubtle]: "#adb5bd",
		[varBsWhiteRgb]: "255, 255, 255",
		[varBsBlackRgb]: "0, 0, 0",
		[varBsFontSansSerif]: "\"Nunito Sans\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif, \"Apple Color Emoji\", \"Segoe UI Emoji\", \"Segoe UI Symbol\"",
		[varBsFontMonospace]: "SFMono-Regular, Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace",
		[varBsGradient]: "linear-gradient(180deg, rgba(255, 255, 255, 0.15), rgba(255, 255, 255, 0))",
		[varBsBodyFontFamily]: varBsFontSansSerif,
		[varBsBodyFontSize]: "1rem",
		[varBsBodyFontWeight]: 300,
		[varBsBodyLineHeight]: 1.5,
		[varBsBodyColor]: "#55595c",
		[varBsBodyColorRgb]: "85, 89, 92",
		[varBsBodyBg]: "#fff",
		[varBsBodyBgRgb]: "255, 255, 255",
		[varBsEmphasisColor]: "#000",
		[varBsEmphasisColorRgb]: "0, 0, 0",
		[varBsSecondaryColor]: "rgba(85, 89, 92, 0.75)",
		[varBsSecondaryBg]: "#f0f1f2",
		[varBsTertiaryColor]: "rgba(85, 89, 92, 0.5)",
		[varBsTertiaryBg]: "#f8f9fa",
		[varBsHeadingColor]: "#1a1a1a",
		[varBsLinkColor]: "#1a1a1a",
		[varBsLinkColorRgb]: "26, 26, 26",
		[varBsLinkDecoration]: "underline",
		[varBsLinkHoverColor]: "#151515",
		[varBsLinkHoverColorRgb]: "21, 21, 21",
		[varBsCodeColor]: "#e83e8c",
		[varBsHighlightColor]: "#55595c",
		[varBsHighlightBg]: "#fcefdc",
		[varBsBorderWidth]: 0,
		[varBsBorderStyle]: "solid",
		[varBsBorderColor]: "#e0e1e2",
		[varBsBorderColorTranslucent]: "rgba(0, 0, 0, 0.175)",
		[varBsBorderRadius]: "0.375rem",
		[varBsBorderRadiusSm]: "0.25rem",
		[varBsBorderRadiusLg]: "0.5rem",
		[varBsBorderRadiusXl]: "1rem",
		[varBsBorderRadiusXxl]: "2rem",
		[varBsBorderRadiusPill]: "50rem",
		[varBsBoxShadow]: "0 0.5rem 1rem rgba(0, 0, 0, 0.15)",
		[varBsBoxShadowSm]: "0 0.125rem 0.25rem rgba(0, 0, 0, 0.075)",
		[varBsBoxShadowLg]: "0 1rem 3rem rgba(0, 0, 0, 0.175)",
		[varBsBoxShadowInset]: "inset 0 1px 2px rgba(0, 0, 0, 0.075)",
		[varBsFocusRingWidth]: "0.25rem",
		[varBsFocusRingOpacity]: 0.25,
		[varBsFocusRingColor]: "rgba(26, 26, 26, 0.25)",
		[varBsBtnCloseFilter]: "",
		[varBsCarouselIndicatorActiveBg]: "#fff",
		[varBsCarouselCaptionColor]: "#fff",
		[varBsCarouselControlIconFilter]: "",
		[varBsFormValidColor]: "#4bbf73",
		[varBsFormValidBorderColor]: "#4bbf73",
		[varBsFormInvalidColor]: "#d9534f",
		[varBsFormInvalidBorderColor]: "#d9534f",
	},
})

// ── Root / body styles ────────────────────────────────────────────────────────
// bodyText = typography; bodyFrame = page canvas (Ve2Shell). Do not add padding
// here — baseline screenshots have no padded wrapper around bd-example.

globalStyle(`${luxScope}${bodyText}`, {
	fontFamily: varBsBodyFontFamily,
	fontSize: varBsBodyFontSize,
	fontWeight: varBsBodyFontWeight,
	lineHeight: varBsBodyLineHeight,
	color: varBsBodyColor,
})

globalStyle(`${luxScope}${bodyFrame}`, {
	backgroundColor: varBsBodyBg,
	margin: 0,
	minHeight: '100vh',
})

// Bootstrap Modal JS adds modalOpenHook to <body> without theme scope.
globalStyle(`${modalOpenHook}`, {
	fontFamily: varBsBodyFontFamily,
	fontSize: varBsBodyFontSize,
	fontWeight: varBsBodyFontWeight,
	lineHeight: varBsBodyLineHeight,
	color: varBsBodyColor,
	backgroundColor: varBsBodyBg,
	margin: 0,
})
