import { globalStyle, style } from '@vanilla-extract/css'
import {
	varBsBlack,
	varBsBlackRgb,
	varBsBlue,
	varBsBodyBg,
	varBsBodyBgRgb,
	varBsBodyColor,
	varBsBodyColorRgb,
	varBsBodyFontFamily,
	varBsBodyFontSize,
	varBsBodyFontWeight,
	varBsBodyLineHeight,
	varBsBorderColor,
	varBsBorderColorTranslucent,
	varBsBorderRadius,
	varBsBorderRadiusLg,
	varBsBorderRadiusPill,
	varBsBorderRadiusSm,
	varBsBorderRadiusXl,
	varBsBorderRadiusXxl,
	varBsBorderStyle,
	varBsBorderWidth,
	varBsBoxShadow,
	varBsBoxShadowInset,
	varBsBoxShadowLg,
	varBsBoxShadowSm,
	varBsCarouselCaptionColor,
	varBsCarouselIndicatorActiveBg,
	varBsCodeColor,
	varBsCyan,
	varBsDanger,
	varBsDangerBgSubtle,
	varBsDangerBorderSubtle,
	varBsDangerRgb,
	varBsDangerTextEmphasis,
	varBsDark,
	varBsDarkBgSubtle,
	varBsDarkBorderSubtle,
	varBsDarkRgb,
	varBsDarkTextEmphasis,
	varBsEmphasisColor,
	varBsEmphasisColorRgb,
	varBsFocusRingColor,
	varBsFocusRingOpacity,
	varBsFocusRingWidth,
	varBsFontMonospace,
	varBsFontSansSerif,
	varBsGradient,
	varBsGray,
	varBsGrayDark,
	varBsGreen,
	varBsHeadingColor,
	varBsHighlightBg,
	varBsHighlightColor,
	varBsIndigo,
	varBsInfo,
	varBsInfoBgSubtle,
	varBsInfoBorderSubtle,
	varBsInfoRgb,
	varBsInfoTextEmphasis,
	varBsLight,
	varBsLightBgSubtle,
	varBsLightBorderSubtle,
	varBsLightRgb,
	varBsLightTextEmphasis,
	varBsLinkColor,
	varBsLinkColorRgb,
	varBsLinkDecoration,
	varBsLinkHoverColor,
	varBsLinkHoverColorRgb,
	varBsOrange,
	varBsPink,
	varBsPrimary,
	varBsPrimaryBgSubtle,
	varBsPrimaryBorderSubtle,
	varBsPrimaryRgb,
	varBsPrimaryTextEmphasis,
	varBsPurple,
	varBsRed,
	varBsSecondary,
	varBsSecondaryBg,
	varBsSecondaryBgSubtle,
	varBsSecondaryBorderSubtle,
	varBsSecondaryColor,
	varBsSecondaryRgb,
	varBsSecondaryTextEmphasis,
	varBsSuccess,
	varBsSuccessBgSubtle,
	varBsSuccessBorderSubtle,
	varBsSuccessRgb,
	varBsSuccessTextEmphasis,
	varBsTeal,
	varBsTertiaryBg,
	varBsTertiaryColor,
	varBsWarning,
	varBsWarningBgSubtle,
	varBsWarningBorderSubtle,
	varBsWarningRgb,
	varBsWarningTextEmphasis,
	varBsWhite,
	varBsWhiteRgb,
	varBsYellow,
} from '../../theme-contract/_vars.css'
import {
	varBsFormInvalidBorderColor,
	varBsFormInvalidColor,
	varBsFormValidBorderColor,
	varBsFormValidColor,
} from '../../theme-contract/forms/_vars.css'
import { bodyFrame, bodyText, vars } from '../../theme-contract/theme-contract.css'

// Brite theme scope class.
// Zero-style identifier used as a stable selector prefix.
export const briteScope = style({})

// Global Bootstrap CSS custom properties (`--bs-*`) are assigned on the
// dedicated vars contract class to keep root var hosting separate from body
// layout/background styles.
globalStyle(`${briteScope}${vars}`, {
	vars: {
		[varBsBlue]: "#61bcff",
		[varBsIndigo]: "#828df9",
		[varBsPurple]: "#be82fa",
		[varBsPink]: "#ea4998",
		[varBsRed]: "#f56565",
		[varBsOrange]: "#fa984a",
		[varBsYellow]: "#ffc700",
		[varBsGreen]: "#68d391",
		[varBsTeal]: "#2ed3be",
		[varBsCyan]: "#22d2ed",
		[varBsBlack]: "#000",
		[varBsWhite]: "#fff",
		[varBsGray]: "#868e96",
		[varBsGrayDark]: "#343a40",
		[varBsPrimary]: "#a2e436",
		[varBsSecondary]: "#fff",
		[varBsSuccess]: "#68d391",
		[varBsInfo]: "#22d2ed",
		[varBsWarning]: "#ffc700",
		[varBsDanger]: "#f56565",
		[varBsLight]: "#e9ecef",
		[varBsDark]: "#000",
		[varBsPrimaryRgb]: "162, 228, 54",
		[varBsSecondaryRgb]: "255, 255, 255",
		[varBsSuccessRgb]: "104, 211, 145",
		[varBsInfoRgb]: "34, 210, 237",
		[varBsWarningRgb]: "255, 199, 0",
		[varBsDangerRgb]: "245, 101, 101",
		[varBsLightRgb]: "233, 236, 239",
		[varBsDarkRgb]: "0, 0, 0",
		[varBsPrimaryTextEmphasis]: "#415b16",
		[varBsSecondaryTextEmphasis]: "#666666",
		[varBsSuccessTextEmphasis]: "#2a543a",
		[varBsInfoTextEmphasis]: "#0e545f",
		[varBsWarningTextEmphasis]: "#665000",
		[varBsDangerTextEmphasis]: "#622828",
		[varBsLightTextEmphasis]: "#495057",
		[varBsDarkTextEmphasis]: "#495057",
		[varBsPrimaryBgSubtle]: "#ecfad7",
		[varBsSecondaryBgSubtle]: "white",
		[varBsSuccessBgSubtle]: "#e1f6e9",
		[varBsInfoBgSubtle]: "#d3f6fb",
		[varBsWarningBgSubtle]: "#fff4cc",
		[varBsDangerBgSubtle]: "#fde0e0",
		[varBsLightBgSubtle]: "#fcfcfd",
		[varBsDarkBgSubtle]: "#ced4da",
		[varBsPrimaryBorderSubtle]: "#daf4af",
		[varBsSecondaryBorderSubtle]: "white",
		[varBsSuccessBorderSubtle]: "#c3edd3",
		[varBsInfoBorderSubtle]: "#a7edf8",
		[varBsWarningBorderSubtle]: "#ffe999",
		[varBsDangerBorderSubtle]: "#fbc1c1",
		[varBsLightBorderSubtle]: "#e9ecef",
		[varBsDarkBorderSubtle]: "#adb5bd",
		[varBsWhiteRgb]: "255, 255, 255",
		[varBsBlackRgb]: "0, 0, 0",
		[varBsFontSansSerif]: "system-ui, -apple-system, \"Segoe UI\", Roboto, \"Helvetica Neue\", \"Noto Sans\", \"Liberation Sans\", Arial, sans-serif, \"Apple Color Emoji\", \"Segoe UI Emoji\", \"Segoe UI Symbol\", \"Noto Color Emoji\"",
		[varBsFontMonospace]: "SFMono-Regular, Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace",
		[varBsGradient]: "linear-gradient(180deg, rgba(255, 255, 255, 0.15), rgba(255, 255, 255, 0))",
		[varBsBodyFontFamily]: varBsFontSansSerif,
		[varBsBodyFontSize]: "0.875rem",
		[varBsBodyFontWeight]: 400,
		[varBsBodyLineHeight]: 1.5,
		[varBsBodyColor]: "#212529",
		[varBsBodyColorRgb]: "33, 37, 41",
		[varBsBodyBg]: "#fff",
		[varBsBodyBgRgb]: "255, 255, 255",
		[varBsEmphasisColor]: "#000",
		[varBsEmphasisColorRgb]: "0, 0, 0",
		[varBsSecondaryColor]: "rgba(33, 37, 41, 0.75)",
		[varBsSecondaryBg]: "#e9ecef",
		[varBsTertiaryColor]: "rgba(33, 37, 41, 0.5)",
		[varBsTertiaryBg]: "#f8f9fa",
		[varBsHeadingColor]: "inherit",
		[varBsLinkColor]: "#000",
		[varBsLinkColorRgb]: "0, 0, 0",
		[varBsLinkDecoration]: "underline",
		[varBsLinkHoverColor]: "black",
		[varBsLinkHoverColorRgb]: "0, 0, 0",
		[varBsCodeColor]: "#ea4998",
		[varBsHighlightColor]: "#212529",
		[varBsHighlightBg]: "#fff4cc",
		[varBsBorderWidth]: "2px",
		[varBsBorderStyle]: "solid",
		[varBsBorderColor]: "#000",
		[varBsBorderColorTranslucent]: "rgba(0, 0, 0, 0.175)",
		[varBsBorderRadius]: "0.375rem",
		[varBsBorderRadiusSm]: "0.25rem",
		[varBsBorderRadiusLg]: "0.5rem",
		[varBsBorderRadiusXl]: "1rem",
		[varBsBorderRadiusXxl]: "2rem",
		[varBsBorderRadiusPill]: "50rem",
		[varBsBoxShadow]: "0 0.5rem 1rem rgba(0, 0, 0, 0.15)",
		[varBsBoxShadowSm]: "0 0.125rem 0.25rem rgba(0, 0, 0, 0.075)",
		[varBsBoxShadowLg]: "0 1rem 3rem rgba(0, 0, 0, 0.175)",
		[varBsBoxShadowInset]: "inset 0 1px 2px rgba(0, 0, 0, 0.075)",
		[varBsFocusRingWidth]: "1px",
		[varBsFocusRingOpacity]: 1,
		[varBsFocusRingColor]: "#000",
		[varBsCarouselIndicatorActiveBg]: "#fff",
		[varBsCarouselCaptionColor]: "#fff",
	},
})

// ── Root / body styles ────────────────────────────────────────────────────────
// bodyText = typography; bodyFrame = page canvas (Ve2Shell). Do not add padding
// here — baseline screenshots have no padded wrapper around bd-example.

globalStyle(`${briteScope}${bodyText}`, {
	fontFamily: varBsBodyFontFamily,
	fontSize: varBsBodyFontSize,
	fontWeight: varBsBodyFontWeight,
	lineHeight: varBsBodyLineHeight,
	color: varBsBodyColor,
})

globalStyle(`${briteScope}${bodyFrame}`, {
	backgroundColor: varBsBodyBg,
	margin: 0,
})
