// GERADO por scripts/gen-public-vars.mjs — NÃO editar à mão.
import { globalStyle } from '@vanilla-extract/css'
import { unitedScope } from './scope.css'
import { varBsBlackRgb, varBsBodyBgRgb, varBsBodyColorRgb, varBsBorderColor, varBsBorderRadius, varBsBorderRadiusLg, varBsBorderRadiusPill, varBsBorderRadiusSm, varBsBorderRadiusXl, varBsBorderRadiusXxl, varBsBorderStyle, varBsBorderWidth, varBsBoxShadow, varBsBoxShadowLg, varBsBoxShadowSm, varBsDangerBgSubtle, varBsDangerBorderSubtle, varBsDangerRgb, varBsDangerTextEmphasis, varBsDarkBgSubtle, varBsDarkBorderSubtle, varBsDarkRgb, varBsDarkTextEmphasis, varBsEmphasisColor, varBsEmphasisColorRgb, varBsFocusRingColor, varBsFocusRingOpacity, varBsFontMonospace, varBsGradient, varBsInfoBgSubtle, varBsInfoBorderSubtle, varBsInfoRgb, varBsInfoTextEmphasis, varBsLightBgSubtle, varBsLightBorderSubtle, varBsLightRgb, varBsLightTextEmphasis, varBsLinkColorRgb, varBsPrimaryBgSubtle, varBsPrimaryBorderSubtle, varBsPrimaryRgb, varBsPrimaryTextEmphasis, varBsSecondaryBgRgb, varBsSecondaryBgSubtle, varBsSecondaryBorderSubtle, varBsSecondaryColor, varBsSecondaryRgb, varBsSecondaryTextEmphasis, varBsSuccessBgSubtle, varBsSuccessBorderSubtle, varBsSuccessRgb, varBsSuccessTextEmphasis, varBsTertiaryBgRgb, varBsTertiaryColor, varBsWarningBgSubtle, varBsWarningBorderSubtle, varBsWarningRgb, varBsWarningTextEmphasis, varBsWhiteRgb } from '../../theme-contract/_public-vars.css'

globalStyle(unitedScope, {
	vars: {
		[varBsBlackRgb]: "0, 0, 0",
		[varBsBodyBgRgb]: "255, 255, 255",
		[varBsBodyColorRgb]: "51, 51, 51",
		[varBsBorderColor]: "#dee2e6",
		[varBsBorderRadius]: "0.375rem",
		[varBsBorderRadiusLg]: "0.5rem",
		[varBsBorderRadiusPill]: "50rem",
		[varBsBorderRadiusSm]: "0.25rem",
		[varBsBorderRadiusXl]: "1rem",
		[varBsBorderRadiusXxl]: "2rem",
		[varBsBorderStyle]: "solid",
		[varBsBorderWidth]: "1px",
		[varBsBoxShadow]: "0 0.5rem 1rem rgba(0, 0, 0, 0.15)",
		[varBsBoxShadowLg]: "0 1rem 3rem rgba(0, 0, 0, 0.175)",
		[varBsBoxShadowSm]: "0 0.125rem 0.25rem rgba(0, 0, 0, 0.075)",
		[varBsDangerBgSubtle]: "#f9d7d5",
		[varBsDangerBorderSubtle]: "#f2afab",
		[varBsDangerRgb]: "223, 56, 44",
		[varBsDangerTextEmphasis]: "#591612",
		[varBsDarkBgSubtle]: "#ced4da",
		[varBsDarkBorderSubtle]: "#aea79f",
		[varBsDarkRgb]: "119, 41, 83",
		[varBsDarkTextEmphasis]: "#495057",
		[varBsEmphasisColor]: "#000",
		[varBsEmphasisColorRgb]: "0, 0, 0",
		[varBsFocusRingColor]: "rgba(233, 84, 32, 0.25)",
		[varBsFocusRingOpacity]: "0.25",
		[varBsFontMonospace]: "SFMono-Regular, Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace",
		[varBsGradient]: "linear-gradient(180deg, rgba(255, 255, 255, 0.15), rgba(255, 255, 255, 0))",
		[varBsInfoBgSubtle]: "#d1ecf1",
		[varBsInfoBorderSubtle]: "#a2dae3",
		[varBsInfoRgb]: "23, 162, 184",
		[varBsInfoTextEmphasis]: "#09414a",
		[varBsLightBgSubtle]: "#fcfcfd",
		[varBsLightBorderSubtle]: "#e9ecef",
		[varBsLightRgb]: "233, 236, 239",
		[varBsLightTextEmphasis]: "#495057",
		[varBsLinkColorRgb]: "233, 84, 32",
		[varBsPrimaryBgSubtle]: "#fbddd2",
		[varBsPrimaryBorderSubtle]: "#f6bba6",
		[varBsPrimaryRgb]: "233, 84, 32",
		[varBsPrimaryTextEmphasis]: "#5d220d",
		[varBsSecondaryBgRgb]: "233, 236, 239",
		[varBsSecondaryBgSubtle]: "#efedec",
		[varBsSecondaryBorderSubtle]: "#dfdcd9",
		[varBsSecondaryColor]: "rgba(51, 51, 51, 0.75)",
		[varBsSecondaryRgb]: "174, 167, 159",
		[varBsSecondaryTextEmphasis]: "#464340",
		[varBsSuccessBgSubtle]: "#d7f0db",
		[varBsSuccessBorderSubtle]: "#afe1b7",
		[varBsSuccessRgb]: "56, 180, 74",
		[varBsSuccessTextEmphasis]: "#16481e",
		[varBsTertiaryBgRgb]: "248, 249, 250",
		[varBsTertiaryColor]: "rgba(51, 51, 51, 0.5)",
		[varBsWarningBgSubtle]: "#fcf1d8",
		[varBsWarningBorderSubtle]: "#f9e2b2",
		[varBsWarningRgb]: "239, 183, 62",
		[varBsWarningTextEmphasis]: "#604919",
		[varBsWhiteRgb]: "255, 255, 255",
	},
})
