import { globalStyle, style } from '@vanilla-extract/css'
import {
	varBsAccordionBtnActiveIcon,
	varBsAccordionBtnIcon,
	varBsBlack,
	varBsBlackRgb,
	varBsBlue,
	varBsBodyBg,
	varBsBodyBgRgb,
	varBsBodyColor,
	varBsBodyColorRgb,
	varBsBodyFontFamily,
	varBsBodyFontSize,
	varBsBodyFontWeight,
	varBsBodyLineHeight,
	varBsBorderColor,
	varBsBorderColorTranslucent,
	varBsBorderRadius,
	varBsBorderRadiusLg,
	varBsBorderRadiusPill,
	varBsBorderRadiusSm,
	varBsBorderRadiusXl,
	varBsBorderRadiusXxl,
	varBsBorderStyle,
	varBsBorderWidth,
	varBsBoxShadow,
	varBsBoxShadowInset,
	varBsBoxShadowLg,
	varBsBoxShadowSm,
	varBsCarouselCaptionColor,
	varBsCarouselControlIconFilter,
	varBsCarouselIndicatorActiveBg,
	varBsCodeColor,
	varBsCyan,
	varBsDanger,
	varBsDangerBgSubtle,
	varBsDangerBorderSubtle,
	varBsDangerRgb,
	varBsDangerTextEmphasis,
	varBsDark,
	varBsDarkBgSubtle,
	varBsDarkBorderSubtle,
	varBsDarkRgb,
	varBsDarkTextEmphasis,
	varBsEmphasisColor,
	varBsEmphasisColorRgb,
	varBsFocusRingColor,
	varBsFocusRingOpacity,
	varBsFocusRingWidth,
	varBsFontMonospace,
	varBsFontSansSerif,
	varBsGradient,
	varBsGray,
	varBsGrayDark,
	varBsGreen,
	varBsHeadingColor,
	varBsHighlightBg,
	varBsHighlightColor,
	varBsIndigo,
	varBsInfo,
	varBsInfoBgSubtle,
	varBsInfoBorderSubtle,
	varBsInfoRgb,
	varBsInfoTextEmphasis,
	varBsLight,
	varBsLightBgSubtle,
	varBsLightBorderSubtle,
	varBsLightRgb,
	varBsLightTextEmphasis,
	varBsLinkColor,
	varBsLinkColorRgb,
	varBsLinkDecoration,
	varBsLinkHoverColor,
	varBsLinkHoverColorRgb,
	varBsNavbarActiveColor,
	varBsNavbarBrandColor,
	varBsNavbarBrandHoverColor,
	varBsNavbarColor,
	varBsNavbarDisabledColor,
	varBsNavbarHoverColor,
	varBsNavbarTogglerBorderColor,
	varBsNavbarTogglerIconBg,
	varBsOrange,
	varBsPink,
	varBsPrimary,
	varBsPrimaryBgSubtle,
	varBsPrimaryBorderSubtle,
	varBsPrimaryRgb,
	varBsPrimaryTextEmphasis,
	varBsPurple,
	varBsRed,
	varBsSecondary,
	varBsSecondaryBg,
	varBsSecondaryBgSubtle,
	varBsSecondaryBorderSubtle,
	varBsSecondaryColor,
	varBsSecondaryRgb,
	varBsSecondaryTextEmphasis,
	varBsSuccess,
	varBsSuccessBgSubtle,
	varBsSuccessBorderSubtle,
	varBsSuccessRgb,
	varBsSuccessTextEmphasis,
	varBsTeal,
	varBsTertiaryBg,
	varBsTertiaryColor,
	varBsWarning,
	varBsWarningBgSubtle,
	varBsWarningBorderSubtle,
	varBsWarningRgb,
	varBsWarningTextEmphasis,
	varBsWhite,
	varBsWhiteRgb,
	varBsYellow,
} from '../../theme-contract/_vars.css'
import {
	varBsFormInvalidBorderColor,
	varBsFormInvalidColor,
	varBsFormSelectBgImg,
	varBsFormSwitchBg,
	varBsFormValidBorderColor,
	varBsFormValidColor,
} from '../../theme-contract/forms/_vars.css'
import { body, bodyText, vars } from '../../theme-contract/theme-contract.css'

// United theme scope class.
// Zero-style identifier used as a stable selector prefix.
export const unitedScope = style({})

// Global Bootstrap CSS custom properties (`--bs-*`) are assigned on the
// dedicated vars contract class to keep root var hosting separate from body
// layout/background styles.
globalStyle(`${unitedScope}${vars}`, {
	vars: {
		[varBsBlue]: "#007bff",
		[varBsIndigo]: "#6610f2",
		[varBsPurple]: "#772953",
		[varBsPink]: "#e83e8c",
		[varBsRed]: "#df382c",
		[varBsOrange]: "#e95420",
		[varBsYellow]: "#efb73e",
		[varBsGreen]: "#38b44a",
		[varBsTeal]: "#20c997",
		[varBsCyan]: "#17a2b8",
		[varBsBlack]: "#000",
		[varBsWhite]: "#fff",
		[varBsGray]: "#868e96",
		[varBsGrayDark]: "#333",
		[varBsPrimary]: "#e95420",
		[varBsSecondary]: "#aea79f",
		[varBsSuccess]: "#38b44a",
		[varBsInfo]: "#17a2b8",
		[varBsWarning]: "#efb73e",
		[varBsDanger]: "#df382c",
		[varBsLight]: "#e9ecef",
		[varBsDark]: "#772953",
		[varBsPrimaryRgb]: "233, 84, 32",
		[varBsSecondaryRgb]: "174, 167, 159",
		[varBsSuccessRgb]: "56, 180, 74",
		[varBsInfoRgb]: "23, 162, 184",
		[varBsWarningRgb]: "239, 183, 62",
		[varBsDangerRgb]: "223, 56, 44",
		[varBsLightRgb]: "233, 236, 239",
		[varBsDarkRgb]: "119, 41, 83",
		[varBsPrimaryTextEmphasis]: "#f29879",
		[varBsSecondaryTextEmphasis]: "#cecac5",
		[varBsSuccessTextEmphasis]: "#88d292",
		[varBsInfoTextEmphasis]: "#74c7d4",
		[varBsWarningTextEmphasis]: "#f5d48b",
		[varBsDangerTextEmphasis]: "#ec8880",
		[varBsLightTextEmphasis]: "#f8f9fa",
		[varBsDarkTextEmphasis]: "#dee2e6",
		[varBsPrimaryBgSubtle]: "#2f1106",
		[varBsSecondaryBgSubtle]: "#232120",
		[varBsSuccessBgSubtle]: "#0b240f",
		[varBsInfoBgSubtle]: "#052025",
		[varBsWarningBgSubtle]: "#30250c",
		[varBsDangerBgSubtle]: "#2d0b09",
		[varBsLightBgSubtle]: "#333",
		[varBsDarkBgSubtle]: "#1a1a1a",
		[varBsPrimaryBorderSubtle]: "#8c3213",
		[varBsSecondaryBorderSubtle]: "#68645f",
		[varBsSuccessBorderSubtle]: "#226c2c",
		[varBsInfoBorderSubtle]: "#0e616e",
		[varBsWarningBorderSubtle]: "#8f6e25",
		[varBsDangerBorderSubtle]: "#86221a",
		[varBsLightBorderSubtle]: "#495057",
		[varBsDarkBorderSubtle]: "#333",
		[varBsWhiteRgb]: "255, 255, 255",
		[varBsBlackRgb]: "0, 0, 0",
		[varBsFontSansSerif]: "Ubuntu, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif, \"Apple Color Emoji\", \"Segoe UI Emoji\", \"Segoe UI Symbol\"",
		[varBsFontMonospace]: "SFMono-Regular, Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace",
		[varBsGradient]: "linear-gradient(180deg, rgba(255, 255, 255, 0.15), rgba(255, 255, 255, 0))",
		[varBsBodyFontFamily]: varBsFontSansSerif,
		[varBsBodyFontSize]: "1rem",
		[varBsBodyFontWeight]: 400,
		[varBsBodyLineHeight]: 1.5,
		[varBsBodyColor]: "#dee2e6",
		[varBsBodyColorRgb]: "222, 226, 230",
		[varBsBodyBg]: "#212529",
		[varBsBodyBgRgb]: "33, 37, 41",
		[varBsEmphasisColor]: "#fff",
		[varBsEmphasisColorRgb]: "255, 255, 255",
		[varBsSecondaryColor]: "rgba(222, 226, 230, 0.75)",
		[varBsSecondaryBg]: "#333",
		[varBsTertiaryColor]: "rgba(222, 226, 230, 0.5)",
		[varBsTertiaryBg]: "#2a2c2e",
		[varBsHeadingColor]: "inherit",
		[varBsLinkColor]: "#f29879",
		[varBsLinkColorRgb]: "242, 152, 121",
		[varBsLinkDecoration]: "underline",
		[varBsLinkHoverColor]: "#f5ad94",
		[varBsLinkHoverColorRgb]: "245, 173, 148",
		[varBsCodeColor]: "#f18bba",
		[varBsHighlightColor]: "#dee2e6",
		[varBsHighlightBg]: "#604919",
		[varBsBorderWidth]: "1px",
		[varBsBorderStyle]: "solid",
		[varBsBorderColor]: "#495057",
		[varBsBorderColorTranslucent]: "rgba(255, 255, 255, 0.15)",
		[varBsBorderRadius]: "0.375rem",
		[varBsBorderRadiusSm]: "0.25rem",
		[varBsBorderRadiusLg]: "0.5rem",
		[varBsBorderRadiusXl]: "1rem",
		[varBsBorderRadiusXxl]: "2rem",
		[varBsBorderRadiusPill]: "50rem",
		[varBsBoxShadow]: "0 0.5rem 1rem rgba(0, 0, 0, 0.15)",
		[varBsBoxShadowSm]: "0 0.125rem 0.25rem rgba(0, 0, 0, 0.075)",
		[varBsBoxShadowLg]: "0 1rem 3rem rgba(0, 0, 0, 0.175)",
		[varBsBoxShadowInset]: "inset 0 1px 2px rgba(0, 0, 0, 0.075)",
		[varBsFocusRingWidth]: "0.25rem",
		[varBsFocusRingOpacity]: 0.25,
		[varBsFocusRingColor]: "rgba(233, 84, 32, 0.25)",
		[varBsNavbarColor]: "rgba(255, 255, 255, 0.55)",
		[varBsNavbarHoverColor]: "rgba(255, 255, 255, 0.75)",
		[varBsNavbarDisabledColor]: "rgba(255, 255, 255, 0.25)",
		[varBsNavbarActiveColor]: "#fff",
		[varBsNavbarBrandColor]: "#fff",
		[varBsNavbarBrandHoverColor]: "#fff",
		[varBsNavbarTogglerBorderColor]: "rgba(255, 255, 255, 0.1)",
		[varBsNavbarTogglerIconBg]: "url(\"data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 30 30'%3e%3cpath stroke='rgba%28255, 255, 255, 0.55%29' stroke-linecap='round' stroke-miterlimit='10' stroke-width='2' d='M4 7h22M4 15h22M4 23h22'/%3e%3c/svg%3e\")",
		[varBsAccordionBtnIcon]: "url(\"data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16' fill='%23f29879'%3e%3cpath fill-rule='evenodd' d='M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708'/%3e%3c/svg%3e\")",
		[varBsAccordionBtnActiveIcon]: "url(\"data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16' fill='%23f29879'%3e%3cpath fill-rule='evenodd' d='M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708'/%3e%3c/svg%3e\")",
		[varBsCarouselIndicatorActiveBg]: "#000",
		[varBsCarouselCaptionColor]: "#000",
		[varBsCarouselControlIconFilter]: "invert(1) grayscale(100)",
	},
})

// ── Root / body styles ────────────────────────────────────────────────────────

globalStyle(`${unitedScope}${bodyText}`, {
	fontFamily: varBsBodyFontFamily,
	fontSize: varBsBodyFontSize,
	fontWeight: varBsBodyFontWeight,
	lineHeight: varBsBodyLineHeight,
	color: varBsBodyColor,
})

globalStyle(`${unitedScope}${body}`, {
	backgroundColor: varBsBodyBg,
	padding: '1rem',
	display: 'block',
})
