import { globalStyle, style } from '@vanilla-extract/css'
import {
	varBsBlack,
	varBsBlackRgb,
	varBsBlue,
	varBsBodyBg,
	varBsBodyBgRgb,
	varBsBodyColor,
	varBsBodyColorRgb,
	varBsBodyFontFamily,
	varBsBodyFontSize,
	varBsBodyFontWeight,
	varBsBodyLineHeight,
	varBsBorderColor,
	varBsBorderColorTranslucent,
	varBsBorderRadius,
	varBsBorderRadiusLg,
	varBsBorderRadiusPill,
	varBsBorderRadiusSm,
	varBsBorderRadiusXl,
	varBsBorderRadiusXxl,
	varBsBorderStyle,
	varBsBorderWidth,
	varBsBoxShadow,
	varBsBoxShadowInset,
	varBsBoxShadowLg,
	varBsBoxShadowSm,
	varBsBtnCloseFilter,
	varBsCarouselCaptionColor,
	varBsCarouselControlIconFilter,
	varBsCarouselIndicatorActiveBg,
	varBsCodeColor,
	varBsCyan,
	varBsDanger,
	varBsDangerBgSubtle,
	varBsDangerBorderSubtle,
	varBsDangerRgb,
	varBsDangerTextEmphasis,
	varBsDark,
	varBsDarkBgSubtle,
	varBsDarkBorderSubtle,
	varBsDarkRgb,
	varBsDarkTextEmphasis,
	varBsEmphasisColor,
	varBsEmphasisColorRgb,
	varBsFocusRingColor,
	varBsFocusRingOpacity,
	varBsFocusRingWidth,
	varBsFontMonospace,
	varBsFontSansSerif,
	varBsGradient,
	varBsGray,
	varBsGrayDark,
	varBsGreen,
	varBsHeadingColor,
	varBsHighlightBg,
	varBsHighlightColor,
	varBsIndigo,
	varBsInfo,
	varBsInfoBgSubtle,
	varBsInfoBorderSubtle,
	varBsInfoRgb,
	varBsInfoTextEmphasis,
	varBsLight,
	varBsLightBgSubtle,
	varBsLightBorderSubtle,
	varBsLightRgb,
	varBsLightTextEmphasis,
	varBsLinkColor,
	varBsLinkColorRgb,
	varBsLinkDecoration,
	varBsLinkHoverColor,
	varBsLinkHoverColorRgb,
	varBsOrange,
	varBsPink,
	varBsPrimary,
	varBsPrimaryBgSubtle,
	varBsPrimaryBorderSubtle,
	varBsPrimaryRgb,
	varBsPrimaryTextEmphasis,
	varBsPurple,
	varBsRed,
	varBsSecondary,
	varBsSecondaryBg,
	varBsSecondaryBgSubtle,
	varBsSecondaryBorderSubtle,
	varBsSecondaryColor,
	varBsSecondaryRgb,
	varBsSecondaryTextEmphasis,
	varBsSuccess,
	varBsSuccessBgSubtle,
	varBsSuccessBorderSubtle,
	varBsSuccessRgb,
	varBsSuccessTextEmphasis,
	varBsTeal,
	varBsTertiaryBg,
	varBsTertiaryColor,
	varBsWarning,
	varBsWarningBgSubtle,
	varBsWarningBorderSubtle,
	varBsWarningRgb,
	varBsWarningTextEmphasis,
	varBsWhite,
	varBsWhiteRgb,
	varBsYellow,
} from '../../theme-contract/_vars.css'
import {
	varBsFormInvalidBorderColor,
	varBsFormInvalidColor,
	varBsFormValidBorderColor,
	varBsFormValidColor,
} from '../../theme-contract/forms/_vars.css'
import { bodyFrame, bodyText, vars } from '../../theme-contract/theme-contract.css'
import { modalOpenHook } from '../../theme-contract/ui/modal/contract.css'

// United theme scope class.
// Zero-style identifier used as a stable selector prefix.
export const unitedScope = style({})

// Global Bootstrap CSS custom properties (`--bs-*`) are assigned on the
// dedicated vars contract class to keep root var hosting separate from body
// layout/background styles.
globalStyle(`${unitedScope}${vars}`, {
	vars: {
		[varBsBlue]: "#007bff",
		[varBsIndigo]: "#6610f2",
		[varBsPurple]: "#772953",
		[varBsPink]: "#e83e8c",
		[varBsRed]: "#df382c",
		[varBsOrange]: "#e95420",
		[varBsYellow]: "#efb73e",
		[varBsGreen]: "#38b44a",
		[varBsTeal]: "#20c997",
		[varBsCyan]: "#17a2b8",
		[varBsBlack]: "#000",
		[varBsWhite]: "#fff",
		[varBsGray]: "#868e96",
		[varBsGrayDark]: "#333",
		[varBsPrimary]: "#e95420",
		[varBsSecondary]: "#aea79f",
		[varBsSuccess]: "#38b44a",
		[varBsInfo]: "#17a2b8",
		[varBsWarning]: "#efb73e",
		[varBsDanger]: "#df382c",
		[varBsLight]: "#e9ecef",
		[varBsDark]: "#772953",
		[varBsPrimaryRgb]: "233, 84, 32",
		[varBsSecondaryRgb]: "174, 167, 159",
		[varBsSuccessRgb]: "56, 180, 74",
		[varBsInfoRgb]: "23, 162, 184",
		[varBsWarningRgb]: "239, 183, 62",
		[varBsDangerRgb]: "223, 56, 44",
		[varBsLightRgb]: "233, 236, 239",
		[varBsDarkRgb]: "119, 41, 83",
		[varBsPrimaryTextEmphasis]: "#5d220d",
		[varBsSecondaryTextEmphasis]: "#464340",
		[varBsSuccessTextEmphasis]: "#16481e",
		[varBsInfoTextEmphasis]: "#09414a",
		[varBsWarningTextEmphasis]: "#604919",
		[varBsDangerTextEmphasis]: "#591612",
		[varBsLightTextEmphasis]: "#495057",
		[varBsDarkTextEmphasis]: "#495057",
		[varBsPrimaryBgSubtle]: "#fbddd2",
		[varBsSecondaryBgSubtle]: "#efedec",
		[varBsSuccessBgSubtle]: "#d7f0db",
		[varBsInfoBgSubtle]: "#d1ecf1",
		[varBsWarningBgSubtle]: "#fcf1d8",
		[varBsDangerBgSubtle]: "#f9d7d5",
		[varBsLightBgSubtle]: "#fcfcfd",
		[varBsDarkBgSubtle]: "#ced4da",
		[varBsPrimaryBorderSubtle]: "#f6bba6",
		[varBsSecondaryBorderSubtle]: "#dfdcd9",
		[varBsSuccessBorderSubtle]: "#afe1b7",
		[varBsInfoBorderSubtle]: "#a2dae3",
		[varBsWarningBorderSubtle]: "#f9e2b2",
		[varBsDangerBorderSubtle]: "#f2afab",
		[varBsLightBorderSubtle]: "#e9ecef",
		[varBsDarkBorderSubtle]: "#aea79f",
		[varBsWhiteRgb]: "255, 255, 255",
		[varBsBlackRgb]: "0, 0, 0",
		[varBsFontSansSerif]: "Ubuntu, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif, \"Apple Color Emoji\", \"Segoe UI Emoji\", \"Segoe UI Symbol\"",
		[varBsFontMonospace]: "SFMono-Regular, Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace",
		[varBsGradient]: "linear-gradient(180deg, rgba(255, 255, 255, 0.15), rgba(255, 255, 255, 0))",
		[varBsBodyFontFamily]: varBsFontSansSerif,
		[varBsBodyFontSize]: "1rem",
		[varBsBodyFontWeight]: 400,
		[varBsBodyLineHeight]: 1.5,
		[varBsBodyColor]: "#333",
		[varBsBodyColorRgb]: "51, 51, 51",
		[varBsBodyBg]: "#fff",
		[varBsBodyBgRgb]: "255, 255, 255",
		[varBsEmphasisColor]: "#000",
		[varBsEmphasisColorRgb]: "0, 0, 0",
		[varBsSecondaryColor]: "rgba(51, 51, 51, 0.75)",
		[varBsSecondaryBg]: "#e9ecef",
		[varBsTertiaryColor]: "rgba(51, 51, 51, 0.5)",
		[varBsTertiaryBg]: "#f8f9fa",
		[varBsHeadingColor]: "inherit",
		[varBsLinkColor]: "#e95420",
		[varBsLinkColorRgb]: "233, 84, 32",
		[varBsLinkDecoration]: "underline",
		[varBsLinkHoverColor]: "#ba431a",
		[varBsLinkHoverColorRgb]: "186, 67, 26",
		[varBsCodeColor]: "#e83e8c",
		[varBsHighlightColor]: "#333",
		[varBsHighlightBg]: "#fcf1d8",
		[varBsBorderWidth]: "1px",
		[varBsBorderStyle]: "solid",
		[varBsBorderColor]: "#dee2e6",
		[varBsBorderColorTranslucent]: "rgba(0, 0, 0, 0.175)",
		[varBsBorderRadius]: "0.375rem",
		[varBsBorderRadiusSm]: "0.25rem",
		[varBsBorderRadiusLg]: "0.5rem",
		[varBsBorderRadiusXl]: "1rem",
		[varBsBorderRadiusXxl]: "2rem",
		[varBsBorderRadiusPill]: "50rem",
		[varBsBoxShadow]: "0 0.5rem 1rem rgba(0, 0, 0, 0.15)",
		[varBsBoxShadowSm]: "0 0.125rem 0.25rem rgba(0, 0, 0, 0.075)",
		[varBsBoxShadowLg]: "0 1rem 3rem rgba(0, 0, 0, 0.175)",
		[varBsBoxShadowInset]: "inset 0 1px 2px rgba(0, 0, 0, 0.075)",
		[varBsFocusRingWidth]: "0.25rem",
		[varBsFocusRingOpacity]: 0.25,
		[varBsFocusRingColor]: "rgba(233, 84, 32, 0.25)",
		[varBsBtnCloseFilter]: "",
		[varBsCarouselIndicatorActiveBg]: "#fff",
		[varBsCarouselCaptionColor]: "#fff",
		[varBsCarouselControlIconFilter]: "",
		[varBsFormValidColor]: "#38b44a",
		[varBsFormValidBorderColor]: "#38b44a",
		[varBsFormInvalidColor]: "#df382c",
		[varBsFormInvalidBorderColor]: "#df382c",
	},
})

// ── Root / body styles ────────────────────────────────────────────────────────
// bodyText = typography; bodyFrame = page canvas (Ve2Shell). Do not add padding
// here — baseline screenshots have no padded wrapper around bd-example.

globalStyle(`${unitedScope}${bodyText}`, {
	fontFamily: varBsBodyFontFamily,
	fontSize: varBsBodyFontSize,
	fontWeight: varBsBodyFontWeight,
	lineHeight: varBsBodyLineHeight,
	color: varBsBodyColor,
})

globalStyle(`${unitedScope}${bodyFrame}`, {
	backgroundColor: varBsBodyBg,
	margin: 0,
	minHeight: '100vh',
})

// Bootstrap Modal JS adds modalOpenHook to <body> without theme scope.
globalStyle(`${modalOpenHook}`, {
	fontFamily: varBsBodyFontFamily,
	fontSize: varBsBodyFontSize,
	fontWeight: varBsBodyFontWeight,
	lineHeight: varBsBodyLineHeight,
	color: varBsBodyColor,
	backgroundColor: varBsBodyBg,
	margin: 0,
})
