import { createVar } from '@vanilla-extract/css'

export const varAlertBg = createVar()
export const varAlertPaddingX = createVar()
export const varAlertPaddingY = createVar()
export const varAlertMarginBottom = createVar()
export const varAlertColor = createVar()
export const varAlertBorderColor = createVar()
export const varAlertBorder = createVar()
export const varAlertBorderRadius = createVar()
export const varAlertLinkColor = createVar()
export const varBsBtnCloseColor = createVar()
export const varBsBtnCloseBg = createVar()
export const varBsBtnCloseOpacity = createVar()
export const varBsBtnCloseHoverOpacity = createVar()
export const varBsBtnCloseFocusShadow = createVar()
export const varBsBtnCloseFocusOpacity = createVar()
export const varBsBtnCloseDisabledOpacity = createVar()
export const varBsBtnCloseFilter = createVar()
