import { createVar } from '@vanilla-extract/css'

export const varBsListGroupColor = createVar()
export const varBsListGroupBg = createVar()
export const varBsListGroupBorderColor = createVar()
export const varBsListGroupBorderWidth = createVar()
export const varBsListGroupBorderRadius = createVar()
export const varBsListGroupItemPaddingX = createVar()
export const varBsListGroupItemPaddingY = createVar()
export const varBsListGroupActionColor = createVar()
export const varBsListGroupActionHoverColor = createVar()
export const varBsListGroupActionHoverBg = createVar()
export const varBsListGroupActionActiveColor = createVar()
export const varBsListGroupActionActiveBg = createVar()
export const varBsListGroupDisabledColor = createVar()
export const varBsListGroupDisabledBg = createVar()
export const varBsListGroupActiveColor = createVar()
export const varBsListGroupActiveBg = createVar()
export const varBsListGroupActiveBorderColor = createVar()
