// GERADO por scripts/gen-public-vars.mjs — NÃO editar à mão.
import { globalStyle } from '@vanilla-extract/css'
import { darklyScope } from './scope.css'
import { varBsBlackRgb, varBsBodyBgRgb, varBsBodyColorRgb, varBsBorderColor, varBsBorderRadius, varBsBorderRadiusLg, varBsBorderRadiusPill, varBsBorderRadiusSm, varBsBorderRadiusXl, varBsBorderRadiusXxl, varBsBorderStyle, varBsBorderWidth, varBsBoxShadow, varBsBoxShadowLg, varBsBoxShadowSm, varBsDangerBgSubtle, varBsDangerBorderSubtle, varBsDangerRgb, varBsDangerTextEmphasis, varBsDarkBgSubtle, varBsDarkBorderSubtle, varBsDarkRgb, varBsDarkTextEmphasis, varBsEmphasisColor, varBsEmphasisColorRgb, varBsFocusRingColor, varBsFocusRingOpacity, varBsFontMonospace, varBsGradient, varBsInfoBgSubtle, varBsInfoBorderSubtle, varBsInfoRgb, varBsInfoTextEmphasis, varBsLightBgSubtle, varBsLightBorderSubtle, varBsLightRgb, varBsLightTextEmphasis, varBsLinkColorRgb, varBsPrimaryBgSubtle, varBsPrimaryBorderSubtle, varBsPrimaryRgb, varBsPrimaryTextEmphasis, varBsSecondaryBgRgb, varBsSecondaryBgSubtle, varBsSecondaryBorderSubtle, varBsSecondaryColor, varBsSecondaryRgb, varBsSecondaryTextEmphasis, varBsSuccessBgSubtle, varBsSuccessBorderSubtle, varBsSuccessRgb, varBsSuccessTextEmphasis, varBsTertiaryBgRgb, varBsTertiaryColor, varBsWarningBgSubtle, varBsWarningBorderSubtle, varBsWarningRgb, varBsWarningTextEmphasis, varBsWhiteRgb } from '../../theme-contract/_public-vars.css'

globalStyle(darklyScope, {
	vars: {
		[varBsBlackRgb]: "0, 0, 0",
		[varBsBodyBgRgb]: "34, 34, 34",
		[varBsBodyColorRgb]: "255, 255, 255",
		[varBsBorderColor]: "#dee2e6",
		[varBsBorderRadius]: "0.375rem",
		[varBsBorderRadiusLg]: "0.5rem",
		[varBsBorderRadiusPill]: "50rem",
		[varBsBorderRadiusSm]: "0.25rem",
		[varBsBorderRadiusXl]: "1rem",
		[varBsBorderRadiusXxl]: "2rem",
		[varBsBorderStyle]: "solid",
		[varBsBorderWidth]: "1px",
		[varBsBoxShadow]: "0 0.5rem 1rem rgba(0, 0, 0, 0.15)",
		[varBsBoxShadowLg]: "0 1rem 3rem rgba(0, 0, 0, 0.175)",
		[varBsBoxShadowSm]: "0 0.125rem 0.25rem rgba(0, 0, 0, 0.075)",
		[varBsDangerBgSubtle]: "#fadbd8",
		[varBsDangerBorderSubtle]: "#f5b7b1",
		[varBsDangerRgb]: "231, 76, 60",
		[varBsDangerTextEmphasis]: "#5c1e18",
		[varBsDarkBgSubtle]: "#ced4da",
		[varBsDarkBorderSubtle]: "#adb5bd",
		[varBsDarkRgb]: "48, 48, 48",
		[varBsDarkTextEmphasis]: "#444",
		[varBsEmphasisColor]: "#000",
		[varBsEmphasisColorRgb]: "0, 0, 0",
		[varBsFocusRingColor]: "rgba(55, 90, 127, 0.25)",
		[varBsFocusRingOpacity]: "0.25",
		[varBsFontMonospace]: "SFMono-Regular, Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace",
		[varBsGradient]: "linear-gradient(180deg, rgba(255, 255, 255, 0.15), rgba(255, 255, 255, 0))",
		[varBsInfoBgSubtle]: "#d6eaf8",
		[varBsInfoBorderSubtle]: "#aed6f1",
		[varBsInfoRgb]: "52, 152, 219",
		[varBsInfoTextEmphasis]: "#153d58",
		[varBsLightBgSubtle]: "#fcfcfd",
		[varBsLightBorderSubtle]: "#ebebeb",
		[varBsLightRgb]: "173, 181, 189",
		[varBsLightTextEmphasis]: "#444",
		[varBsLinkColorRgb]: "0, 188, 140",
		[varBsPrimaryBgSubtle]: "#d7dee5",
		[varBsPrimaryBorderSubtle]: "#afbdcc",
		[varBsPrimaryRgb]: "55, 90, 127",
		[varBsPrimaryTextEmphasis]: "#162433",
		[varBsSecondaryBgRgb]: "235, 235, 235",
		[varBsSecondaryBgSubtle]: "#dadada",
		[varBsSecondaryBorderSubtle]: "#b4b4b4",
		[varBsSecondaryColor]: "rgba(255, 255, 255, 0.75)",
		[varBsSecondaryRgb]: "68, 68, 68",
		[varBsSecondaryTextEmphasis]: "#1b1b1b",
		[varBsSuccessBgSubtle]: "#ccf2e8",
		[varBsSuccessBorderSubtle]: "#99e4d1",
		[varBsSuccessRgb]: "0, 188, 140",
		[varBsSuccessTextEmphasis]: "#004b38",
		[varBsTertiaryBgRgb]: "248, 249, 250",
		[varBsTertiaryColor]: "rgba(255, 255, 255, 0.5)",
		[varBsWarningBgSubtle]: "#fdebd0",
		[varBsWarningBorderSubtle]: "#fad7a0",
		[varBsWarningRgb]: "243, 156, 18",
		[varBsWarningTextEmphasis]: "#613e07",
		[varBsWhiteRgb]: "255, 255, 255",
	},
})
