import { globalStyle, style } from '@vanilla-extract/css'
import {
	varBsAccordionBtnActiveIcon,
	varBsAccordionBtnIcon,
	varBsBlack,
	varBsBlackRgb,
	varBsBlue,
	varBsBodyBg,
	varBsBodyBgRgb,
	varBsBodyColor,
	varBsBodyColorRgb,
	varBsBodyFontFamily,
	varBsBodyFontSize,
	varBsBodyFontWeight,
	varBsBodyLineHeight,
	varBsBorderColor,
	varBsBorderColorTranslucent,
	varBsBorderRadius,
	varBsBorderRadiusLg,
	varBsBorderRadiusPill,
	varBsBorderRadiusSm,
	varBsBorderRadiusXl,
	varBsBorderRadiusXxl,
	varBsBorderStyle,
	varBsBorderWidth,
	varBsBoxShadow,
	varBsBoxShadowInset,
	varBsBoxShadowLg,
	varBsBoxShadowSm,
	varBsCarouselCaptionColor,
	varBsCarouselControlIconFilter,
	varBsCarouselIndicatorActiveBg,
	varBsCodeColor,
	varBsCyan,
	varBsDanger,
	varBsDangerBgSubtle,
	varBsDangerBorderSubtle,
	varBsDangerRgb,
	varBsDangerTextEmphasis,
	varBsDark,
	varBsDarkBgSubtle,
	varBsDarkBorderSubtle,
	varBsDarkRgb,
	varBsDarkTextEmphasis,
	varBsEmphasisColor,
	varBsEmphasisColorRgb,
	varBsFocusRingColor,
	varBsFocusRingOpacity,
	varBsFocusRingWidth,
	varBsFontMonospace,
	varBsFontSansSerif,
	varBsGradient,
	varBsGray,
	varBsGrayDark,
	varBsGreen,
	varBsHeadingColor,
	varBsHighlightBg,
	varBsHighlightColor,
	varBsIndigo,
	varBsInfo,
	varBsInfoBgSubtle,
	varBsInfoBorderSubtle,
	varBsInfoRgb,
	varBsInfoTextEmphasis,
	varBsLight,
	varBsLightBgSubtle,
	varBsLightBorderSubtle,
	varBsLightRgb,
	varBsLightTextEmphasis,
	varBsLinkColor,
	varBsLinkColorRgb,
	varBsLinkDecoration,
	varBsLinkHoverColor,
	varBsLinkHoverColorRgb,
	varBsNavbarActiveColor,
	varBsNavbarBrandColor,
	varBsNavbarBrandHoverColor,
	varBsNavbarColor,
	varBsNavbarDisabledColor,
	varBsNavbarHoverColor,
	varBsNavbarTogglerBorderColor,
	varBsNavbarTogglerIconBg,
	varBsOrange,
	varBsPink,
	varBsPrimary,
	varBsPrimaryBgSubtle,
	varBsPrimaryBorderSubtle,
	varBsPrimaryRgb,
	varBsPrimaryTextEmphasis,
	varBsPurple,
	varBsRed,
	varBsSecondary,
	varBsSecondaryBg,
	varBsSecondaryBgSubtle,
	varBsSecondaryBorderSubtle,
	varBsSecondaryColor,
	varBsSecondaryRgb,
	varBsSecondaryTextEmphasis,
	varBsSuccess,
	varBsSuccessBgSubtle,
	varBsSuccessBorderSubtle,
	varBsSuccessRgb,
	varBsSuccessTextEmphasis,
	varBsTeal,
	varBsTertiaryBg,
	varBsTertiaryColor,
	varBsWarning,
	varBsWarningBgSubtle,
	varBsWarningBorderSubtle,
	varBsWarningRgb,
	varBsWarningTextEmphasis,
	varBsWhite,
	varBsWhiteRgb,
	varBsYellow,
} from '../../theme-contract/_vars.css'
import {
	varBsFormInvalidBorderColor,
	varBsFormInvalidColor,
	varBsFormSelectBgImg,
	varBsFormSwitchBg,
	varBsFormValidBorderColor,
	varBsFormValidColor,
} from '../../theme-contract/forms/_vars.css'
import { bodyFrame, bodyText, vars } from '../../theme-contract/theme-contract.css'
import { modalOpenHook } from '../../theme-contract/ui/modal/contract.css'

// Darkly theme scope class.
// Zero-style identifier used as a stable selector prefix.
export const darklyScope = style({})

// Global Bootstrap CSS custom properties (`--bs-*`) are assigned on the
// dedicated vars contract class to keep root var hosting separate from body
// layout/background styles.
globalStyle(`${darklyScope}${vars}`, {
	vars: {
		[varBsBlue]: "#375a7f",
		[varBsIndigo]: "#6610f2",
		[varBsPurple]: "#6f42c1",
		[varBsPink]: "#e83e8c",
		[varBsRed]: "#e74c3c",
		[varBsOrange]: "#fd7e14",
		[varBsYellow]: "#f39c12",
		[varBsGreen]: "#00bc8c",
		[varBsTeal]: "#20c997",
		[varBsCyan]: "#3498db",
		[varBsBlack]: "#000",
		[varBsWhite]: "#fff",
		[varBsGray]: "#888",
		[varBsGrayDark]: "#303030",
		[varBsPrimary]: "#375a7f",
		[varBsSecondary]: "#444",
		[varBsSuccess]: "#00bc8c",
		[varBsInfo]: "#3498db",
		[varBsWarning]: "#f39c12",
		[varBsDanger]: "#e74c3c",
		[varBsLight]: "#adb5bd",
		[varBsDark]: "#303030",
		[varBsPrimaryRgb]: "55, 90, 127",
		[varBsSecondaryRgb]: "68, 68, 68",
		[varBsSuccessRgb]: "0, 188, 140",
		[varBsInfoRgb]: "52, 152, 219",
		[varBsWarningRgb]: "243, 156, 18",
		[varBsDangerRgb]: "231, 76, 60",
		[varBsLightRgb]: "173, 181, 189",
		[varBsDarkRgb]: "48, 48, 48",
		[varBsPrimaryTextEmphasis]: "#879cb2",
		[varBsSecondaryTextEmphasis]: "#8f8f8f",
		[varBsSuccessTextEmphasis]: "#66d7ba",
		[varBsInfoTextEmphasis]: "#85c1e9",
		[varBsWarningTextEmphasis]: "#f8c471",
		[varBsDangerTextEmphasis]: "#f1948a",
		[varBsLightTextEmphasis]: "#f8f9fa",
		[varBsDarkTextEmphasis]: "#dee2e6",
		[varBsPrimaryBgSubtle]: "#0b1219",
		[varBsSecondaryBgSubtle]: "#0e0e0e",
		[varBsSuccessBgSubtle]: "#00261c",
		[varBsInfoBgSubtle]: "#0a1e2c",
		[varBsWarningBgSubtle]: "#311f04",
		[varBsDangerBgSubtle]: "#2e0f0c",
		[varBsLightBgSubtle]: "#303030",
		[varBsDarkBgSubtle]: "#181818",
		[varBsPrimaryBorderSubtle]: "#21364c",
		[varBsSecondaryBorderSubtle]: "#292929",
		[varBsSuccessBorderSubtle]: "#007154",
		[varBsInfoBorderSubtle]: "#1f5b83",
		[varBsWarningBorderSubtle]: "#925e0b",
		[varBsDangerBorderSubtle]: "#8b2e24",
		[varBsLightBorderSubtle]: "#444",
		[varBsDarkBorderSubtle]: "#303030",
		[varBsWhiteRgb]: "255, 255, 255",
		[varBsBlackRgb]: "0, 0, 0",
		[varBsFontSansSerif]: "Lato, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif, \"Apple Color Emoji\", \"Segoe UI Emoji\", \"Segoe UI Symbol\"",
		[varBsFontMonospace]: "SFMono-Regular, Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace",
		[varBsGradient]: "linear-gradient(180deg, rgba(255, 255, 255, 0.15), rgba(255, 255, 255, 0))",
		[varBsBodyFontFamily]: varBsFontSansSerif,
		[varBsBodyFontSize]: "1rem",
		[varBsBodyFontWeight]: 400,
		[varBsBodyLineHeight]: 1.5,
		[varBsBodyColor]: "#dee2e6",
		[varBsBodyColorRgb]: "222, 226, 230",
		[varBsBodyBg]: "#222",
		[varBsBodyBgRgb]: "34, 34, 34",
		[varBsEmphasisColor]: "#fff",
		[varBsEmphasisColorRgb]: "255, 255, 255",
		[varBsSecondaryColor]: "rgba(222, 226, 230, 0.75)",
		[varBsSecondaryBg]: "#303030",
		[varBsTertiaryColor]: "rgba(222, 226, 230, 0.5)",
		[varBsTertiaryBg]: "#292929",
		[varBsHeadingColor]: "inherit",
		[varBsLinkColor]: "#879cb2",
		[varBsLinkColorRgb]: "135, 156, 178",
		[varBsLinkDecoration]: "underline",
		[varBsLinkHoverColor]: "#9fb0c1",
		[varBsLinkHoverColorRgb]: "159, 176, 193",
		[varBsCodeColor]: "#f18bba",
		[varBsHighlightColor]: "#dee2e6",
		[varBsHighlightBg]: "#613e07",
		[varBsBorderWidth]: "1px",
		[varBsBorderStyle]: "solid",
		[varBsBorderColor]: "#444",
		[varBsBorderColorTranslucent]: "rgba(255, 255, 255, 0.15)",
		[varBsBorderRadius]: "0.375rem",
		[varBsBorderRadiusSm]: "0.25rem",
		[varBsBorderRadiusLg]: "0.5rem",
		[varBsBorderRadiusXl]: "1rem",
		[varBsBorderRadiusXxl]: "2rem",
		[varBsBorderRadiusPill]: "50rem",
		[varBsBoxShadow]: "0 0.5rem 1rem rgba(0, 0, 0, 0.15)",
		[varBsBoxShadowSm]: "0 0.125rem 0.25rem rgba(0, 0, 0, 0.075)",
		[varBsBoxShadowLg]: "0 1rem 3rem rgba(0, 0, 0, 0.175)",
		[varBsBoxShadowInset]: "inset 0 1px 2px rgba(0, 0, 0, 0.075)",
		[varBsFocusRingWidth]: "0.25rem",
		[varBsFocusRingOpacity]: 0.25,
		[varBsFocusRingColor]: "rgba(55, 90, 127, 0.25)",
		[varBsFormValidColor]: "#00bc8c",
		[varBsFormValidBorderColor]: "#00bc8c",
		[varBsFormInvalidColor]: "#e74c3c",
		[varBsFormInvalidBorderColor]: "#e74c3c",
		[varBsNavbarColor]: "rgba(255, 255, 255, 0.6)",
		[varBsNavbarHoverColor]: "#fff",
		[varBsNavbarDisabledColor]: "rgba(255, 255, 255, 0.25)",
		[varBsNavbarActiveColor]: "#fff",
		[varBsNavbarBrandColor]: "#fff",
		[varBsNavbarBrandHoverColor]: "#fff",
		[varBsNavbarTogglerBorderColor]: "rgba(255, 255, 255, 0.1)",
		[varBsNavbarTogglerIconBg]: "url(\"data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 30 30'%3e%3cpath stroke='rgba%28255, 255, 255, 0.6%29' stroke-linecap='round' stroke-miterlimit='10' stroke-width='2' d='M4 7h22M4 15h22M4 23h22'/%3e%3c/svg%3e\")",
		[varBsAccordionBtnIcon]: "url(\"data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16' fill='%23879cb2'%3e%3cpath fill-rule='evenodd' d='M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708'/%3e%3c/svg%3e\")",
		[varBsAccordionBtnActiveIcon]: "url(\"data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16' fill='%23879cb2'%3e%3cpath fill-rule='evenodd' d='M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708'/%3e%3c/svg%3e\")",
		[varBsCarouselIndicatorActiveBg]: "#fff",
		[varBsCarouselCaptionColor]: "#fff",
		[varBsCarouselControlIconFilter]: "",
	},
})

// ── Root / body styles ────────────────────────────────────────────────────────
// bodyText = typography; bodyFrame = page canvas (Ve2Shell). Do not add padding
// here — baseline screenshots have no padded wrapper around bd-example.

globalStyle(`${darklyScope}${bodyText}`, {
	fontFamily: varBsBodyFontFamily,
	fontSize: varBsBodyFontSize,
	fontWeight: varBsBodyFontWeight,
	lineHeight: varBsBodyLineHeight,
	color: varBsBodyColor,
})

globalStyle(`${darklyScope}${bodyFrame}`, {
	backgroundColor: varBsBodyBg,
	margin: 0,
	minHeight: '100vh',
})

// Bootstrap Modal JS adds modalOpenHook to <body> without theme scope.
globalStyle(`${modalOpenHook}`, {
	fontFamily: varBsBodyFontFamily,
	fontSize: varBsBodyFontSize,
	fontWeight: varBsBodyFontWeight,
	lineHeight: varBsBodyLineHeight,
	color: varBsBodyColor,
	backgroundColor: varBsBodyBg,
	margin: 0,
})
