// GERADO por scripts/gen-public-vars.mjs — NÃO editar à mão.
import { globalStyle } from '@vanilla-extract/css'
import { journalScope } from './scope.css'
import { varBsBlackRgb, varBsBodyBgRgb, varBsBodyColorRgb, varBsBorderColor, varBsBorderRadius, varBsBorderRadiusLg, varBsBorderRadiusPill, varBsBorderRadiusSm, varBsBorderRadiusXl, varBsBorderRadiusXxl, varBsBorderStyle, varBsBorderWidth, varBsBoxShadow, varBsBoxShadowLg, varBsBoxShadowSm, varBsDangerBgSubtle, varBsDangerBorderSubtle, varBsDangerRgb, varBsDangerTextEmphasis, varBsDarkBgSubtle, varBsDarkBorderSubtle, varBsDarkRgb, varBsDarkTextEmphasis, varBsEmphasisColor, varBsEmphasisColorRgb, varBsFocusRingColor, varBsFocusRingOpacity, varBsFontMonospace, varBsGradient, varBsInfoBgSubtle, varBsInfoBorderSubtle, varBsInfoRgb, varBsInfoTextEmphasis, varBsLightBgSubtle, varBsLightBorderSubtle, varBsLightRgb, varBsLightTextEmphasis, varBsLinkColorRgb, varBsPrimaryBgSubtle, varBsPrimaryBorderSubtle, varBsPrimaryRgb, varBsPrimaryTextEmphasis, varBsSecondaryBgRgb, varBsSecondaryBgSubtle, varBsSecondaryBorderSubtle, varBsSecondaryColor, varBsSecondaryRgb, varBsSecondaryTextEmphasis, varBsSuccessBgSubtle, varBsSuccessBorderSubtle, varBsSuccessRgb, varBsSuccessTextEmphasis, varBsTertiaryBgRgb, varBsTertiaryColor, varBsWarningBgSubtle, varBsWarningBorderSubtle, varBsWarningRgb, varBsWarningTextEmphasis, varBsWhiteRgb } from '../../theme-contract/_public-vars.css'

globalStyle(journalScope, {
	vars: {
		[varBsBlackRgb]: "0, 0, 0",
		[varBsBodyBgRgb]: "255, 255, 255",
		[varBsBodyColorRgb]: "34, 34, 34",
		[varBsBorderColor]: "#dee2e6",
		[varBsBorderRadius]: "0.375rem",
		[varBsBorderRadiusLg]: "0.5rem",
		[varBsBorderRadiusPill]: "50rem",
		[varBsBorderRadiusSm]: "0.25rem",
		[varBsBorderRadiusXl]: "1rem",
		[varBsBorderRadiusXxl]: "2rem",
		[varBsBorderStyle]: "solid",
		[varBsBorderWidth]: "1px",
		[varBsBoxShadow]: "0 0.5rem 1rem rgba(0, 0, 0, 0.15)",
		[varBsBoxShadowLg]: "0 1rem 3rem rgba(0, 0, 0, 0.175)",
		[varBsBoxShadowSm]: "0 0.125rem 0.25rem rgba(0, 0, 0, 0.075)",
		[varBsDangerBgSubtle]: "#fde4cc",
		[varBsDangerBorderSubtle]: "#fbca99",
		[varBsDangerRgb]: "245, 122, 0",
		[varBsDangerTextEmphasis]: "#623100",
		[varBsDarkBgSubtle]: "#ced4da",
		[varBsDarkBorderSubtle]: "#aaa",
		[varBsDarkRgb]: "34, 34, 34",
		[varBsDarkTextEmphasis]: "#495057",
		[varBsEmphasisColor]: "#000",
		[varBsEmphasisColorRgb]: "0, 0, 0",
		[varBsFocusRingColor]: "rgba(235, 104, 100, 0.25)",
		[varBsFocusRingOpacity]: "0.25",
		[varBsFontMonospace]: "SFMono-Regular, Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace",
		[varBsGradient]: "linear-gradient(180deg, rgba(255, 255, 255, 0.15), rgba(255, 255, 255, 0))",
		[varBsInfoBgSubtle]: "#d6e0eb",
		[varBsInfoBorderSubtle]: "#adc2d6",
		[varBsInfoRgb]: "51, 102, 153",
		[varBsInfoTextEmphasis]: "#14293d",
		[varBsLightBgSubtle]: "#fcfcfd",
		[varBsLightBorderSubtle]: "#eee",
		[varBsLightRgb]: "248, 249, 250",
		[varBsLightTextEmphasis]: "#495057",
		[varBsLinkColorRgb]: "235, 104, 100",
		[varBsPrimaryBgSubtle]: "#fbe1e0",
		[varBsPrimaryBorderSubtle]: "#f7c3c1",
		[varBsPrimaryRgb]: "235, 104, 100",
		[varBsPrimaryTextEmphasis]: "#5e2a28",
		[varBsSecondaryBgRgb]: "238, 238, 238",
		[varBsSecondaryBgSubtle]: "#eeeeee",
		[varBsSecondaryBorderSubtle]: "#dddddd",
		[varBsSecondaryColor]: "rgba(34, 34, 34, 0.75)",
		[varBsSecondaryRgb]: "170, 170, 170",
		[varBsSecondaryTextEmphasis]: "#444444",
		[varBsSuccessBgSubtle]: "#d3f0db",
		[varBsSuccessBorderSubtle]: "#a7e0b7",
		[varBsSuccessRgb]: "34, 178, 76",
		[varBsSuccessTextEmphasis]: "#0e471e",
		[varBsTertiaryBgRgb]: "248, 249, 250",
		[varBsTertiaryColor]: "rgba(34, 34, 34, 0.5)",
		[varBsWarningBgSubtle]: "#fdfad3",
		[varBsWarningBorderSubtle]: "#fbf5a8",
		[varBsWarningRgb]: "245, 230, 37",
		[varBsWarningTextEmphasis]: "#625c0f",
		[varBsWhiteRgb]: "255, 255, 255",
	},
})
