// GERADO por scripts/gen-public-vars.mjs — NÃO editar à mão.
import { globalStyle } from '@vanilla-extract/css'
import { sketchyScope } from './scope.css'
import { varBsBlackRgb, varBsBodyBgRgb, varBsBodyColorRgb, varBsBorderColor, varBsBorderRadius, varBsBorderRadiusLg, varBsBorderRadiusPill, varBsBorderRadiusSm, varBsBorderRadiusXl, varBsBorderRadiusXxl, varBsBorderStyle, varBsBorderWidth, varBsBoxShadow, varBsBoxShadowLg, varBsBoxShadowSm, varBsDangerBgSubtle, varBsDangerBorderSubtle, varBsDangerRgb, varBsDangerTextEmphasis, varBsDarkBgSubtle, varBsDarkBorderSubtle, varBsDarkRgb, varBsDarkTextEmphasis, varBsEmphasisColor, varBsEmphasisColorRgb, varBsFocusRingColor, varBsFocusRingOpacity, varBsFontMonospace, varBsGradient, varBsInfoBgSubtle, varBsInfoBorderSubtle, varBsInfoRgb, varBsInfoTextEmphasis, varBsLightBgSubtle, varBsLightBorderSubtle, varBsLightRgb, varBsLightTextEmphasis, varBsLinkColorRgb, varBsPrimaryBgSubtle, varBsPrimaryBorderSubtle, varBsPrimaryRgb, varBsPrimaryTextEmphasis, varBsSecondaryBgRgb, varBsSecondaryBgSubtle, varBsSecondaryBorderSubtle, varBsSecondaryColor, varBsSecondaryRgb, varBsSecondaryTextEmphasis, varBsSuccessBgSubtle, varBsSuccessBorderSubtle, varBsSuccessRgb, varBsSuccessTextEmphasis, varBsTertiaryBgRgb, varBsTertiaryColor, varBsWarningBgSubtle, varBsWarningBorderSubtle, varBsWarningRgb, varBsWarningTextEmphasis, varBsWhiteRgb } from '../../theme-contract/_public-vars.css'

globalStyle(sketchyScope, {
	vars: {
		[varBsBlackRgb]: "0, 0, 0",
		[varBsBodyBgRgb]: "255, 255, 255",
		[varBsBodyColorRgb]: "33, 37, 41",
		[varBsBorderColor]: "#dee2e6",
		[varBsBorderRadius]: "25px",
		[varBsBorderRadiusLg]: "35px",
		[varBsBorderRadiusPill]: "50rem",
		[varBsBorderRadiusSm]: "15px",
		[varBsBorderRadiusXl]: "1rem",
		[varBsBorderRadiusXxl]: "2rem",
		[varBsBorderStyle]: "solid",
		[varBsBorderWidth]: "2px",
		[varBsBoxShadow]: "0 0.5rem 1rem rgba(0, 0, 0, 0.15)",
		[varBsBoxShadowLg]: "0 1rem 3rem rgba(0, 0, 0, 0.175)",
		[varBsBoxShadowSm]: "0 0.125rem 0.25rem rgba(0, 0, 0, 0.075)",
		[varBsDangerBgSubtle]: "#f8d7da",
		[varBsDangerBorderSubtle]: "#f1aeb5",
		[varBsDangerRgb]: "220, 53, 69",
		[varBsDangerTextEmphasis]: "#58151c",
		[varBsDarkBgSubtle]: "#ccc",
		[varBsDarkBorderSubtle]: "#aaa",
		[varBsDarkRgb]: "85, 85, 85",
		[varBsDarkTextEmphasis]: "#555",
		[varBsEmphasisColor]: "#000",
		[varBsEmphasisColorRgb]: "0, 0, 0",
		[varBsFocusRingColor]: "rgba(51, 51, 51, 0.25)",
		[varBsFocusRingOpacity]: "0.25",
		[varBsFontMonospace]: "SFMono-Regular, Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace",
		[varBsGradient]: "linear-gradient(180deg, rgba(255, 255, 255, 0.15), rgba(255, 255, 255, 0))",
		[varBsInfoBgSubtle]: "#d1ecf1",
		[varBsInfoBorderSubtle]: "#a2dae3",
		[varBsInfoRgb]: "23, 162, 184",
		[varBsInfoTextEmphasis]: "#09414a",
		[varBsLightBgSubtle]: "#fcfcfd",
		[varBsLightBorderSubtle]: "#f7f7f9",
		[varBsLightRgb]: "255, 255, 255",
		[varBsLightTextEmphasis]: "#555",
		[varBsLinkColorRgb]: "51, 51, 51",
		[varBsPrimaryBgSubtle]: "#d6d6d6",
		[varBsPrimaryBorderSubtle]: "#adadad",
		[varBsPrimaryRgb]: "51, 51, 51",
		[varBsPrimaryTextEmphasis]: "#141414",
		[varBsSecondaryBgRgb]: "247, 247, 249",
		[varBsSecondaryBgSubtle]: "#dddddd",
		[varBsSecondaryBorderSubtle]: "#bbbbbb",
		[varBsSecondaryColor]: "rgba(33, 37, 41, 0.75)",
		[varBsSecondaryRgb]: "85, 85, 85",
		[varBsSecondaryTextEmphasis]: "#222222",
		[varBsSuccessBgSubtle]: "#d4edda",
		[varBsSuccessBorderSubtle]: "#a9dcb5",
		[varBsSuccessRgb]: "40, 167, 69",
		[varBsSuccessTextEmphasis]: "#10431c",
		[varBsTertiaryBgRgb]: "248, 249, 250",
		[varBsTertiaryColor]: "rgba(33, 37, 41, 0.5)",
		[varBsWarningBgSubtle]: "#fff3cd",
		[varBsWarningBorderSubtle]: "#ffe69c",
		[varBsWarningRgb]: "255, 193, 7",
		[varBsWarningTextEmphasis]: "#664d03",
		[varBsWhiteRgb]: "255, 255, 255",
	},
})
