import { globalStyle, style } from '@vanilla-extract/css'
import {
	varBsBlack,
	varBsBlackRgb,
	varBsBlue,
	varBsBodyBg,
	varBsBodyBgRgb,
	varBsBodyColor,
	varBsBodyColorRgb,
	varBsBodyFontFamily,
	varBsBodyFontSize,
	varBsBodyFontWeight,
	varBsBodyLineHeight,
	varBsBorderColor,
	varBsBorderColorTranslucent,
	varBsBorderRadius,
	varBsBorderRadiusLg,
	varBsBorderRadiusPill,
	varBsBorderRadiusSm,
	varBsBorderRadiusXl,
	varBsBorderRadiusXxl,
	varBsBorderStyle,
	varBsBorderWidth,
	varBsBoxShadow,
	varBsBoxShadowInset,
	varBsBoxShadowLg,
	varBsBoxShadowSm,
	varBsCarouselCaptionColor,
	varBsCarouselIndicatorActiveBg,
	varBsCodeColor,
	varBsCyan,
	varBsDanger,
	varBsDangerBgSubtle,
	varBsDangerBorderSubtle,
	varBsDangerRgb,
	varBsDangerTextEmphasis,
	varBsDark,
	varBsDarkBgSubtle,
	varBsDarkBorderSubtle,
	varBsDarkRgb,
	varBsDarkTextEmphasis,
	varBsEmphasisColor,
	varBsEmphasisColorRgb,
	varBsFocusRingColor,
	varBsFocusRingOpacity,
	varBsFocusRingWidth,
	varBsFontMonospace,
	varBsFontSansSerif,
	varBsGradient,
	varBsGray,
	varBsGrayDark,
	varBsGreen,
	varBsHeadingColor,
	varBsHighlightBg,
	varBsHighlightColor,
	varBsIndigo,
	varBsInfo,
	varBsInfoBgSubtle,
	varBsInfoBorderSubtle,
	varBsInfoRgb,
	varBsInfoTextEmphasis,
	varBsLight,
	varBsLightBgSubtle,
	varBsLightBorderSubtle,
	varBsLightRgb,
	varBsLightTextEmphasis,
	varBsLinkColor,
	varBsLinkColorRgb,
	varBsLinkDecoration,
	varBsLinkHoverColor,
	varBsLinkHoverColorRgb,
	varBsOrange,
	varBsPink,
	varBsPrimary,
	varBsPrimaryBgSubtle,
	varBsPrimaryBorderSubtle,
	varBsPrimaryRgb,
	varBsPrimaryTextEmphasis,
	varBsPurple,
	varBsRed,
	varBsSecondary,
	varBsSecondaryBg,
	varBsSecondaryBgSubtle,
	varBsSecondaryBorderSubtle,
	varBsSecondaryColor,
	varBsSecondaryRgb,
	varBsSecondaryTextEmphasis,
	varBsSuccess,
	varBsSuccessBgSubtle,
	varBsSuccessBorderSubtle,
	varBsSuccessRgb,
	varBsSuccessTextEmphasis,
	varBsTeal,
	varBsTertiaryBg,
	varBsTertiaryColor,
	varBsWarning,
	varBsWarningBgSubtle,
	varBsWarningBorderSubtle,
	varBsWarningRgb,
	varBsWarningTextEmphasis,
	varBsWhite,
	varBsWhiteRgb,
	varBsYellow,
} from '../../theme-contract/_vars.css'
import {
	varBsFormInvalidBorderColor,
	varBsFormInvalidColor,
	varBsFormValidBorderColor,
	varBsFormValidColor,
} from '../../theme-contract/forms/_vars.css'
import { body, bodyText, vars } from '../../theme-contract/theme-contract.css'

// Sketchy theme scope class.
// Zero-style identifier used as a stable selector prefix.
export const sketchyScope = style({})

// Global Bootstrap CSS custom properties (`--bs-*`) are assigned on the
// dedicated vars contract class to keep root var hosting separate from body
// layout/background styles.
globalStyle(`${sketchyScope}${vars}`, {
	vars: {
		[varBsBlue]: "#007bff",
		[varBsIndigo]: "#6610f2",
		[varBsPurple]: "#6f42c1",
		[varBsPink]: "#e83e8c",
		[varBsRed]: "#dc3545",
		[varBsOrange]: "#fd7e14",
		[varBsYellow]: "#ffc107",
		[varBsGreen]: "#28a745",
		[varBsTeal]: "#20c997",
		[varBsCyan]: "#17a2b8",
		[varBsBlack]: "#000",
		[varBsWhite]: "#fff",
		[varBsGray]: "#868e96",
		[varBsGrayDark]: "#333",
		[varBsPrimary]: "#333",
		[varBsSecondary]: "#555",
		[varBsSuccess]: "#28a745",
		[varBsInfo]: "#17a2b8",
		[varBsWarning]: "#ffc107",
		[varBsDanger]: "#dc3545",
		[varBsLight]: "#fff",
		[varBsDark]: "#555",
		[varBsPrimaryRgb]: "51, 51, 51",
		[varBsSecondaryRgb]: "85, 85, 85",
		[varBsSuccessRgb]: "40, 167, 69",
		[varBsInfoRgb]: "23, 162, 184",
		[varBsWarningRgb]: "255, 193, 7",
		[varBsDangerRgb]: "220, 53, 69",
		[varBsLightRgb]: "255, 255, 255",
		[varBsDarkRgb]: "85, 85, 85",
		[varBsPrimaryTextEmphasis]: "#141414",
		[varBsSecondaryTextEmphasis]: "#222222",
		[varBsSuccessTextEmphasis]: "#10431c",
		[varBsInfoTextEmphasis]: "#09414a",
		[varBsWarningTextEmphasis]: "#664d03",
		[varBsDangerTextEmphasis]: "#58151c",
		[varBsLightTextEmphasis]: "#555",
		[varBsDarkTextEmphasis]: "#555",
		[varBsPrimaryBgSubtle]: "#d6d6d6",
		[varBsSecondaryBgSubtle]: "#dddddd",
		[varBsSuccessBgSubtle]: "#d4edda",
		[varBsInfoBgSubtle]: "#d1ecf1",
		[varBsWarningBgSubtle]: "#fff3cd",
		[varBsDangerBgSubtle]: "#f8d7da",
		[varBsLightBgSubtle]: "#fcfcfd",
		[varBsDarkBgSubtle]: "#ccc",
		[varBsPrimaryBorderSubtle]: "#adadad",
		[varBsSecondaryBorderSubtle]: "#bbbbbb",
		[varBsSuccessBorderSubtle]: "#a9dcb5",
		[varBsInfoBorderSubtle]: "#a2dae3",
		[varBsWarningBorderSubtle]: "#ffe69c",
		[varBsDangerBorderSubtle]: "#f1aeb5",
		[varBsLightBorderSubtle]: "#f7f7f9",
		[varBsDarkBorderSubtle]: "#aaa",
		[varBsWhiteRgb]: "255, 255, 255",
		[varBsBlackRgb]: "0, 0, 0",
		[varBsFontSansSerif]: "Neucha, -apple-system, system-ui, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
		[varBsFontMonospace]: "SFMono-Regular, Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace",
		[varBsGradient]: "linear-gradient(180deg, rgba(255, 255, 255, 0.15), rgba(255, 255, 255, 0))",
		[varBsBodyFontFamily]: varBsFontSansSerif,
		[varBsBodyFontSize]: "1rem",
		[varBsBodyFontWeight]: 700,
		[varBsBodyLineHeight]: 1.5,
		[varBsBodyColor]: "#212529",
		[varBsBodyColorRgb]: "33, 37, 41",
		[varBsBodyBg]: "#fff",
		[varBsBodyBgRgb]: "255, 255, 255",
		[varBsEmphasisColor]: "#000",
		[varBsEmphasisColorRgb]: "0, 0, 0",
		[varBsSecondaryColor]: "rgba(33, 37, 41, 0.75)",
		[varBsSecondaryBg]: "#f7f7f9",
		[varBsTertiaryColor]: "rgba(33, 37, 41, 0.5)",
		[varBsTertiaryBg]: "#f8f9fa",
		[varBsHeadingColor]: "inherit",
		[varBsLinkColor]: "#333",
		[varBsLinkColorRgb]: "51, 51, 51",
		[varBsLinkDecoration]: "underline",
		[varBsLinkHoverColor]: "#292929",
		[varBsLinkHoverColorRgb]: "41, 41, 41",
		[varBsCodeColor]: "#e83e8c",
		[varBsHighlightColor]: "#212529",
		[varBsHighlightBg]: "#fff3cd",
		[varBsBorderWidth]: "2px",
		[varBsBorderStyle]: "solid",
		[varBsBorderColor]: "#dee2e6",
		[varBsBorderColorTranslucent]: "rgba(0, 0, 0, 0.175)",
		[varBsBorderRadius]: "25px",
		[varBsBorderRadiusSm]: "15px",
		[varBsBorderRadiusLg]: "35px",
		[varBsBorderRadiusXl]: "1rem",
		[varBsBorderRadiusXxl]: "2rem",
		[varBsBorderRadiusPill]: "50rem",
		[varBsBoxShadow]: "0 0.5rem 1rem rgba(0, 0, 0, 0.15)",
		[varBsBoxShadowSm]: "0 0.125rem 0.25rem rgba(0, 0, 0, 0.075)",
		[varBsBoxShadowLg]: "0 1rem 3rem rgba(0, 0, 0, 0.175)",
		[varBsBoxShadowInset]: "inset 0 1px 2px rgba(0, 0, 0, 0.075)",
		[varBsFocusRingWidth]: "0.25rem",
		[varBsFocusRingOpacity]: 0.25,
		[varBsFocusRingColor]: "rgba(51, 51, 51, 0.25)",
		[varBsCarouselIndicatorActiveBg]: "#fff",
		[varBsCarouselCaptionColor]: "#fff",
	},
})

// ── Root / body styles ────────────────────────────────────────────────────────

globalStyle(`${sketchyScope}${bodyText}`, {
	fontFamily: varBsBodyFontFamily,
	fontSize: varBsBodyFontSize,
	fontWeight: varBsBodyFontWeight,
	lineHeight: varBsBodyLineHeight,
	color: varBsBodyColor,
})

globalStyle(`${sketchyScope}${body}`, {
	backgroundColor: varBsBodyBg,
	padding: '1rem',
	display: 'block',
})
