// GERADO por scripts/gen-public-vars.mjs — NÃO editar à mão.
import { globalStyle } from '@vanilla-extract/css'
import { superheroScope } from './scope.css'
import { varBsBlackRgb, varBsBodyBgRgb, varBsBodyColorRgb, varBsBorderColor, varBsBorderRadius, varBsBorderRadiusLg, varBsBorderRadiusPill, varBsBorderRadiusSm, varBsBorderRadiusXl, varBsBorderRadiusXxl, varBsBorderStyle, varBsBorderWidth, varBsBoxShadow, varBsBoxShadowLg, varBsBoxShadowSm, varBsDangerBgSubtle, varBsDangerBorderSubtle, varBsDangerRgb, varBsDangerTextEmphasis, varBsDarkBgSubtle, varBsDarkBorderSubtle, varBsDarkRgb, varBsDarkTextEmphasis, varBsEmphasisColor, varBsEmphasisColorRgb, varBsFocusRingColor, varBsFocusRingOpacity, varBsFontMonospace, varBsGradient, varBsInfoBgSubtle, varBsInfoBorderSubtle, varBsInfoRgb, varBsInfoTextEmphasis, varBsLightBgSubtle, varBsLightBorderSubtle, varBsLightRgb, varBsLightTextEmphasis, varBsLinkColorRgb, varBsPrimaryBgSubtle, varBsPrimaryBorderSubtle, varBsPrimaryRgb, varBsPrimaryTextEmphasis, varBsSecondaryBgRgb, varBsSecondaryBgSubtle, varBsSecondaryBorderSubtle, varBsSecondaryColor, varBsSecondaryRgb, varBsSecondaryTextEmphasis, varBsSuccessBgSubtle, varBsSuccessBorderSubtle, varBsSuccessRgb, varBsSuccessTextEmphasis, varBsTertiaryBgRgb, varBsTertiaryColor, varBsWarningBgSubtle, varBsWarningBorderSubtle, varBsWarningRgb, varBsWarningTextEmphasis, varBsWhiteRgb } from '../../theme-contract/_public-vars.css'

globalStyle(superheroScope, {
	vars: {
		[varBsBlackRgb]: "0, 0, 0",
		[varBsBodyBgRgb]: "15, 37, 55",
		[varBsBodyColorRgb]: "235, 235, 235",
		[varBsBorderColor]: "#ced4da",
		[varBsBorderRadius]: "0",
		[varBsBorderRadiusLg]: "0",
		[varBsBorderRadiusPill]: "50rem",
		[varBsBorderRadiusSm]: "0",
		[varBsBorderRadiusXl]: "1rem",
		[varBsBorderRadiusXxl]: "2rem",
		[varBsBorderStyle]: "solid",
		[varBsBorderWidth]: "1px",
		[varBsBoxShadow]: "0 0.5rem 1rem rgba(0, 0, 0, 0.15)",
		[varBsBoxShadowLg]: "0 1rem 3rem rgba(0, 0, 0, 0.175)",
		[varBsBoxShadowSm]: "0 0.125rem 0.25rem rgba(0, 0, 0, 0.075)",
		[varBsDangerBgSubtle]: "#f7dddc",
		[varBsDangerBorderSubtle]: "#f0bab9",
		[varBsDangerRgb]: "217, 83, 79",
		[varBsDangerTextEmphasis]: "#572120",
		[varBsDarkBgSubtle]: "#adb5bd",
		[varBsDarkBorderSubtle]: "#868e96",
		[varBsDarkRgb]: "32, 55, 76",
		[varBsDarkTextEmphasis]: "#495057",
		[varBsEmphasisColor]: "#000",
		[varBsEmphasisColorRgb]: "0, 0, 0",
		[varBsFocusRingColor]: "rgba(223, 105, 25, 0.25)",
		[varBsFocusRingOpacity]: "0.25",
		[varBsFontMonospace]: "SFMono-Regular, Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace",
		[varBsGradient]: "linear-gradient(180deg, rgba(255, 255, 255, 0.15), rgba(255, 255, 255, 0))",
		[varBsInfoBgSubtle]: "#def2f8",
		[varBsInfoBorderSubtle]: "#bde6f2",
		[varBsInfoRgb]: "91, 192, 222",
		[varBsInfoTextEmphasis]: "#244d59",
		[varBsLightBgSubtle]: "whitesmoke",
		[varBsLightBorderSubtle]: "#dee2e6",
		[varBsLightRgb]: "171, 182, 194",
		[varBsLightTextEmphasis]: "#495057",
		[varBsLinkColorRgb]: "223, 105, 25",
		[varBsPrimaryBgSubtle]: "#f9e1d1",
		[varBsPrimaryBorderSubtle]: "#f2c3a3",
		[varBsPrimaryRgb]: "223, 105, 25",
		[varBsPrimaryTextEmphasis]: "#592a0a",
		[varBsSecondaryBgRgb]: "222, 226, 230",
		[varBsSecondaryBgSubtle]: "#dcdfe2",
		[varBsSecondaryBorderSubtle]: "#b8bec4",
		[varBsSecondaryColor]: "rgba(235, 235, 235, 0.75)",
		[varBsSecondaryRgb]: "78, 93, 108",
		[varBsSecondaryTextEmphasis]: "#1f252b",
		[varBsSuccessBgSubtle]: "#def1de",
		[varBsSuccessBorderSubtle]: "#bee3be",
		[varBsSuccessRgb]: "92, 184, 92",
		[varBsSuccessTextEmphasis]: "#254a25",
		[varBsTertiaryBgRgb]: "235, 235, 235",
		[varBsTertiaryColor]: "rgba(235, 235, 235, 0.5)",
		[varBsWarningBgSubtle]: "#fff3cd",
		[varBsWarningBorderSubtle]: "#ffe69c",
		[varBsWarningRgb]: "255, 193, 7",
		[varBsWarningTextEmphasis]: "#664d03",
		[varBsWhiteRgb]: "255, 255, 255",
	},
})
