import { globalStyle, style } from '@vanilla-extract/css'
import {
	varBsBlack,
	varBsBlackRgb,
	varBsBlue,
	varBsBodyBg,
	varBsBodyBgRgb,
	varBsBodyColor,
	varBsBodyColorRgb,
	varBsBodyFontFamily,
	varBsBodyFontSize,
	varBsBodyFontWeight,
	varBsBodyLineHeight,
	varBsBorderColor,
	varBsBorderColorTranslucent,
	varBsBorderRadius,
	varBsBorderRadiusLg,
	varBsBorderRadiusPill,
	varBsBorderRadiusSm,
	varBsBorderRadiusXl,
	varBsBorderRadiusXxl,
	varBsBorderStyle,
	varBsBorderWidth,
	varBsBoxShadow,
	varBsBoxShadowInset,
	varBsBoxShadowLg,
	varBsBoxShadowSm,
	varBsBtnCloseFilter,
	varBsCarouselCaptionColor,
	varBsCarouselControlIconFilter,
	varBsCarouselIndicatorActiveBg,
	varBsCodeColor,
	varBsCyan,
	varBsDanger,
	varBsDangerBgSubtle,
	varBsDangerBorderSubtle,
	varBsDangerRgb,
	varBsDangerTextEmphasis,
	varBsDark,
	varBsDarkBgSubtle,
	varBsDarkBorderSubtle,
	varBsDarkRgb,
	varBsDarkTextEmphasis,
	varBsEmphasisColor,
	varBsEmphasisColorRgb,
	varBsFocusRingColor,
	varBsFocusRingOpacity,
	varBsFocusRingWidth,
	varBsFontMonospace,
	varBsFontSansSerif,
	varBsGradient,
	varBsGray,
	varBsGrayDark,
	varBsGreen,
	varBsHeadingColor,
	varBsHighlightBg,
	varBsHighlightColor,
	varBsIndigo,
	varBsInfo,
	varBsInfoBgSubtle,
	varBsInfoBorderSubtle,
	varBsInfoRgb,
	varBsInfoTextEmphasis,
	varBsLight,
	varBsLightBgSubtle,
	varBsLightBorderSubtle,
	varBsLightRgb,
	varBsLightTextEmphasis,
	varBsLinkColor,
	varBsLinkColorRgb,
	varBsLinkDecoration,
	varBsLinkHoverColor,
	varBsLinkHoverColorRgb,
	varBsOrange,
	varBsPink,
	varBsPrimary,
	varBsPrimaryBgSubtle,
	varBsPrimaryBorderSubtle,
	varBsPrimaryRgb,
	varBsPrimaryTextEmphasis,
	varBsPurple,
	varBsRed,
	varBsSecondary,
	varBsSecondaryBg,
	varBsSecondaryBgSubtle,
	varBsSecondaryBorderSubtle,
	varBsSecondaryColor,
	varBsSecondaryRgb,
	varBsSecondaryTextEmphasis,
	varBsSuccess,
	varBsSuccessBgSubtle,
	varBsSuccessBorderSubtle,
	varBsSuccessRgb,
	varBsSuccessTextEmphasis,
	varBsTeal,
	varBsTertiaryBg,
	varBsTertiaryColor,
	varBsWarning,
	varBsWarningBgSubtle,
	varBsWarningBorderSubtle,
	varBsWarningRgb,
	varBsWarningTextEmphasis,
	varBsWhite,
	varBsWhiteRgb,
	varBsYellow,
} from '../../theme-contract/_vars.css'
import {
	varBsFormInvalidBorderColor,
	varBsFormInvalidColor,
	varBsFormValidBorderColor,
	varBsFormValidColor,
} from '../../theme-contract/forms/_vars.css'
import { bodyFrame, bodyText, vars } from '../../theme-contract/theme-contract.css'
import { modalOpenHook } from '../../theme-contract/ui/modal/contract.css'

// Superhero theme scope class.
// Zero-style identifier used as a stable selector prefix.
export const superheroScope = style({})

// Global Bootstrap CSS custom properties (`--bs-*`) are assigned on the
// dedicated vars contract class to keep root var hosting separate from body
// layout/background styles.
globalStyle(`${superheroScope}${vars}`, {
	vars: {
		[varBsBlue]: "#4c9be8",
		[varBsIndigo]: "#6610f2",
		[varBsPurple]: "#6f42c1",
		[varBsPink]: "#e83e8c",
		[varBsRed]: "#d9534f",
		[varBsOrange]: "#df6919",
		[varBsYellow]: "#ffc107",
		[varBsGreen]: "#5cb85c",
		[varBsTeal]: "#20c997",
		[varBsCyan]: "#5bc0de",
		[varBsBlack]: "#000",
		[varBsWhite]: "#fff",
		[varBsGray]: "#4e5d6c",
		[varBsGrayDark]: "#343a40",
		[varBsPrimary]: "#df6919",
		[varBsSecondary]: "#4e5d6c",
		[varBsSuccess]: "#5cb85c",
		[varBsInfo]: "#5bc0de",
		[varBsWarning]: "#ffc107",
		[varBsDanger]: "#d9534f",
		[varBsLight]: "#abb6c2",
		[varBsDark]: "#20374c",
		[varBsPrimaryRgb]: "223, 105, 25",
		[varBsSecondaryRgb]: "78, 93, 108",
		[varBsSuccessRgb]: "92, 184, 92",
		[varBsInfoRgb]: "91, 192, 222",
		[varBsWarningRgb]: "255, 193, 7",
		[varBsDangerRgb]: "217, 83, 79",
		[varBsLightRgb]: "171, 182, 194",
		[varBsDarkRgb]: "32, 55, 76",
		[varBsPrimaryTextEmphasis]: "#592a0a",
		[varBsSecondaryTextEmphasis]: "#1f252b",
		[varBsSuccessTextEmphasis]: "#254a25",
		[varBsInfoTextEmphasis]: "#244d59",
		[varBsWarningTextEmphasis]: "#664d03",
		[varBsDangerTextEmphasis]: "#572120",
		[varBsLightTextEmphasis]: "#495057",
		[varBsDarkTextEmphasis]: "#495057",
		[varBsPrimaryBgSubtle]: "#f9e1d1",
		[varBsSecondaryBgSubtle]: "#dcdfe2",
		[varBsSuccessBgSubtle]: "#def1de",
		[varBsInfoBgSubtle]: "#def2f8",
		[varBsWarningBgSubtle]: "#fff3cd",
		[varBsDangerBgSubtle]: "#f7dddc",
		[varBsLightBgSubtle]: "whitesmoke",
		[varBsDarkBgSubtle]: "#adb5bd",
		[varBsPrimaryBorderSubtle]: "#f2c3a3",
		[varBsSecondaryBorderSubtle]: "#b8bec4",
		[varBsSuccessBorderSubtle]: "#bee3be",
		[varBsInfoBorderSubtle]: "#bde6f2",
		[varBsWarningBorderSubtle]: "#ffe69c",
		[varBsDangerBorderSubtle]: "#f0bab9",
		[varBsLightBorderSubtle]: "#dee2e6",
		[varBsDarkBorderSubtle]: "#868e96",
		[varBsWhiteRgb]: "255, 255, 255",
		[varBsBlackRgb]: "0, 0, 0",
		[varBsFontSansSerif]: "Lato, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif, \"Apple Color Emoji\", \"Segoe UI Emoji\", \"Segoe UI Symbol\"",
		[varBsFontMonospace]: "SFMono-Regular, Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace",
		[varBsGradient]: "linear-gradient(180deg, rgba(255, 255, 255, 0.15), rgba(255, 255, 255, 0))",
		[varBsBodyFontFamily]: varBsFontSansSerif,
		[varBsBodyFontSize]: "1rem",
		[varBsBodyFontWeight]: 400,
		[varBsBodyLineHeight]: 1.5,
		[varBsBodyColor]: "#ebebeb",
		[varBsBodyColorRgb]: "235, 235, 235",
		[varBsBodyBg]: "#0f2537",
		[varBsBodyBgRgb]: "15, 37, 55",
		[varBsEmphasisColor]: "#000",
		[varBsEmphasisColorRgb]: "0, 0, 0",
		[varBsSecondaryColor]: "rgba(235, 235, 235, 0.75)",
		[varBsSecondaryBg]: "#dee2e6",
		[varBsTertiaryColor]: "rgba(235, 235, 235, 0.5)",
		[varBsTertiaryBg]: "#ebebeb",
		[varBsHeadingColor]: "inherit",
		[varBsLinkColor]: "#df6919",
		[varBsLinkColorRgb]: "223, 105, 25",
		[varBsLinkDecoration]: "underline",
		[varBsLinkHoverColor]: "#b25414",
		[varBsLinkHoverColorRgb]: "178, 84, 20",
		[varBsCodeColor]: "#e83e8c",
		[varBsHighlightColor]: "#ebebeb",
		[varBsHighlightBg]: "#fff3cd",
		[varBsBorderWidth]: "1px",
		[varBsBorderStyle]: "solid",
		[varBsBorderColor]: "#ced4da",
		[varBsBorderColorTranslucent]: "rgba(0, 0, 0, 0.175)",
		[varBsBorderRadius]: 0,
		[varBsBorderRadiusSm]: 0,
		[varBsBorderRadiusLg]: 0,
		[varBsBorderRadiusXl]: "1rem",
		[varBsBorderRadiusXxl]: "2rem",
		[varBsBorderRadiusPill]: "50rem",
		[varBsBoxShadow]: "0 0.5rem 1rem rgba(0, 0, 0, 0.15)",
		[varBsBoxShadowSm]: "0 0.125rem 0.25rem rgba(0, 0, 0, 0.075)",
		[varBsBoxShadowLg]: "0 1rem 3rem rgba(0, 0, 0, 0.175)",
		[varBsBoxShadowInset]: "inset 0 1px 2px rgba(0, 0, 0, 0.075)",
		[varBsFocusRingWidth]: "0.25rem",
		[varBsFocusRingOpacity]: 0.25,
		[varBsFocusRingColor]: "rgba(223, 105, 25, 0.25)",
		[varBsBtnCloseFilter]: "",
		[varBsCarouselIndicatorActiveBg]: "#fff",
		[varBsCarouselCaptionColor]: "#fff",
		[varBsCarouselControlIconFilter]: "",
		[varBsFormValidColor]: "#5cb85c",
		[varBsFormValidBorderColor]: "#5cb85c",
		[varBsFormInvalidColor]: "#d9534f",
		[varBsFormInvalidBorderColor]: "#d9534f",
	},
})

// ── Root / body styles ────────────────────────────────────────────────────────
// bodyText = typography; bodyFrame = page canvas (Ve2Shell). Do not add padding
// here — baseline screenshots have no padded wrapper around bd-example.

globalStyle(`${superheroScope}${bodyText}`, {
	fontFamily: varBsBodyFontFamily,
	fontSize: varBsBodyFontSize,
	fontWeight: varBsBodyFontWeight,
	lineHeight: varBsBodyLineHeight,
	color: varBsBodyColor,
})

globalStyle(`${superheroScope}${bodyFrame}`, {
	backgroundColor: varBsBodyBg,
	margin: 0,
	minHeight: '100vh',
})

// Bootstrap Modal JS adds modalOpenHook to <body> without theme scope.
globalStyle(`${modalOpenHook}`, {
	fontFamily: varBsBodyFontFamily,
	fontSize: varBsBodyFontSize,
	fontWeight: varBsBodyFontWeight,
	lineHeight: varBsBodyLineHeight,
	color: varBsBodyColor,
	backgroundColor: varBsBodyBg,
	margin: 0,
})
