import { visuallyHidden } from '../dropdowns/base.css'
import {
carousel,
carouselActive,
carouselCaption,
carouselCaptionResponsive,
carouselControlNext,
carouselControlNextIcon,
carouselControlPrev,
carouselControlPrevIcon,
carouselIndicators,
carouselIndicatorsTarget,
carouselInner,
carouselItem,
carouselItemEnd,
carouselItemNext,
carouselItemPrev,
carouselItemStart,
carouselSlide,
carouselSlideImage,
} from './base.css'

export const sketchyCarouselRuntimeClasses = {
carousel,
carouselActive,
carouselCaption,
carouselCaptionResponsive,
carouselControlNext,
carouselControlNextIcon,
carouselControlPrev,
carouselControlPrevIcon,
carouselIndicators,
carouselIndicatorsTarget,
carouselInner,
carouselItem,
carouselItemEnd,
carouselItemNext,
carouselItemPrev,
carouselItemStart,
carouselSlide,
carouselSlideImage,
visuallyHidden,
} as const
