import { inputGroup, inputGroupText } from './input-group/base.css'
import { formCheck, formCheckInput, formCheckLabel, formSwitch } from './overview/form-check.css'
import {
	fieldset,
	floatingLabel,
	form,
	formControl,
	formControlFloating,
	formControlLg,
	formControlSm,
	formFloating,
	formLabel,
	formRange,
	formSelect,
	formSelectLg,
	formSelectSm,
	formText,
	legend,
	legendClear,
	mb3,
} from './sizing/controls.css'
import {
	colMd3,
	colMd6,
	colSm6,
	g3,
	hasValidation,
	invalidFeedback,
	isInvalid,
	isValid,
	row,
	rowCol,
	validFeedback,
} from './validation/base.css'

export const bootstrapFormsRuntimeClasses = {
	colMd3,
	colMd6,
	colSm6,
	fieldset,
	floatingLabel,
	form,
	formCheck,
	formCheckInput,
	formCheckLabel,
	formControl,
	formControlFloating,
	formControlLg,
	formControlSm,
	formFloating,
	formLabel,
	formRange,
	formSelect,
	formSelectLg,
	formSelectSm,
	formSwitch,
	formText,
	g3,
	hasValidation,
	inputGroup,
	inputGroupText,
	invalidFeedback,
	isInvalid,
	isValid,
	legend,
	legendClear,
	mb3,
	row,
	rowCol,
	validFeedback,
} as const
