import { createVar } from '@vanilla-extract/css'

export const varBsNavbarPaddingX = createVar()
export const varBsNavbarPaddingY = createVar()
export const varBsNavbarColor = createVar()
export const varBsNavbarHoverColor = createVar()
export const varBsNavbarDisabledColor = createVar()
export const varBsNavbarActiveColor = createVar()
export const varBsNavbarBrandPaddingY = createVar()
export const varBsNavbarBrandMarginEnd = createVar()
export const varBsNavbarBrandFontSize = createVar()
export const varBsNavbarBrandColor = createVar()
export const varBsNavbarBrandHoverColor = createVar()
export const varBsNavbarNavLinkPaddingX = createVar()
export const varBsNavbarTogglerPaddingY = createVar()
export const varBsNavbarTogglerPaddingX = createVar()
export const varBsNavbarTogglerFontSize = createVar()
export const varBsNavbarTogglerIconBg = createVar()
export const varBsNavbarTogglerBorderColor = createVar()
export const varBsNavbarTogglerBorderRadius = createVar()
export const varBsNavbarTogglerFocusWidth = createVar()
export const varBsNavbarTogglerTransition = createVar()
