// GERADO por scripts/gen-public-vars.mjs — NÃO editar à mão.
import { globalStyle } from '@vanilla-extract/css'
import { zephyrScope } from './scope.css'
import { varBsBlackRgb, varBsBodyBgRgb, varBsBodyColorRgb, varBsBorderColor, varBsBorderRadius, varBsBorderRadiusLg, varBsBorderRadiusPill, varBsBorderRadiusSm, varBsBorderRadiusXl, varBsBorderRadiusXxl, varBsBorderStyle, varBsBorderWidth, varBsBoxShadow, varBsBoxShadowLg, varBsBoxShadowSm, varBsDangerBgSubtle, varBsDangerBorderSubtle, varBsDangerRgb, varBsDangerTextEmphasis, varBsDarkBgSubtle, varBsDarkBorderSubtle, varBsDarkRgb, varBsDarkTextEmphasis, varBsEmphasisColor, varBsEmphasisColorRgb, varBsFocusRingColor, varBsFocusRingOpacity, varBsFontMonospace, varBsGradient, varBsInfoBgSubtle, varBsInfoBorderSubtle, varBsInfoRgb, varBsInfoTextEmphasis, varBsLightBgSubtle, varBsLightBorderSubtle, varBsLightRgb, varBsLightTextEmphasis, varBsLinkColorRgb, varBsPrimaryBgSubtle, varBsPrimaryBorderSubtle, varBsPrimaryRgb, varBsPrimaryTextEmphasis, varBsSecondaryBgRgb, varBsSecondaryBgSubtle, varBsSecondaryBorderSubtle, varBsSecondaryColor, varBsSecondaryRgb, varBsSecondaryTextEmphasis, varBsSuccessBgSubtle, varBsSuccessBorderSubtle, varBsSuccessRgb, varBsSuccessTextEmphasis, varBsTertiaryBgRgb, varBsTertiaryColor, varBsWarningBgSubtle, varBsWarningBorderSubtle, varBsWarningRgb, varBsWarningTextEmphasis, varBsWhiteRgb } from '../../theme-contract/_public-vars.css'

globalStyle(zephyrScope, {
	vars: {
		[varBsBlackRgb]: "0, 0, 0",
		[varBsBodyBgRgb]: "255, 255, 255",
		[varBsBodyColorRgb]: "73, 80, 87",
		[varBsBorderColor]: "#dee2e6",
		[varBsBorderRadius]: "0.375rem",
		[varBsBorderRadiusLg]: "0.5rem",
		[varBsBorderRadiusPill]: "50rem",
		[varBsBorderRadiusSm]: "0.25rem",
		[varBsBorderRadiusXl]: "1rem",
		[varBsBorderRadiusXxl]: "2rem",
		[varBsBorderStyle]: "solid",
		[varBsBorderWidth]: "1px",
		[varBsBoxShadow]: "0 1px 2px rgba(0, 0, 0, 0.05)",
		[varBsBoxShadowLg]: "0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px 0 rgba(0, 0, 0, 0.06)",
		[varBsBoxShadowSm]: "0 0.125rem 0.25rem rgba(0, 0, 0, 0.075)",
		[varBsDangerBgSubtle]: "#f8d4d5",
		[varBsDangerBorderSubtle]: "#f0a9ab",
		[varBsDangerRgb]: "218, 41, 46",
		[varBsDangerTextEmphasis]: "#571012",
		[varBsDarkBgSubtle]: "#ced4da",
		[varBsDarkBorderSubtle]: "#adb5bd",
		[varBsDarkRgb]: "33, 37, 41",
		[varBsDarkTextEmphasis]: "#495057",
		[varBsEmphasisColor]: "#000",
		[varBsEmphasisColorRgb]: "0, 0, 0",
		[varBsFocusRingColor]: "rgba(52, 89, 230, 0.25)",
		[varBsFocusRingOpacity]: "0.25",
		[varBsFontMonospace]: "SFMono-Regular, Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace",
		[varBsGradient]: "linear-gradient(180deg, rgba(255, 255, 255, 0.15), rgba(255, 255, 255, 0))",
		[varBsInfoBgSubtle]: "#d4e5f0",
		[varBsInfoBorderSubtle]: "#a9cae1",
		[varBsInfoRgb]: "40, 123, 181",
		[varBsInfoTextEmphasis]: "#103148",
		[varBsLightBgSubtle]: "#fcfcfd",
		[varBsLightBorderSubtle]: "#e9ecef",
		[varBsLightRgb]: "248, 249, 250",
		[varBsLightTextEmphasis]: "#495057",
		[varBsLinkColorRgb]: "52, 89, 230",
		[varBsPrimaryBgSubtle]: "#d6defa",
		[varBsPrimaryBorderSubtle]: "#aebdf5",
		[varBsPrimaryRgb]: "52, 89, 230",
		[varBsPrimaryTextEmphasis]: "#15245c",
		[varBsSecondaryBgRgb]: "233, 236, 239",
		[varBsSecondaryBgSubtle]: "white",
		[varBsSecondaryBorderSubtle]: "white",
		[varBsSecondaryColor]: "rgba(73, 80, 87, 0.75)",
		[varBsSecondaryRgb]: "255, 255, 255",
		[varBsSecondaryTextEmphasis]: "#666666",
		[varBsSuccessBgSubtle]: "#d5f0e6",
		[varBsSuccessBorderSubtle]: "#ace1cc",
		[varBsSuccessRgb]: "47, 179, 128",
		[varBsSuccessTextEmphasis]: "#134833",
		[varBsTertiaryBgRgb]: "248, 249, 250",
		[varBsTertiaryColor]: "rgba(73, 80, 87, 0.5)",
		[varBsWarningBgSubtle]: "#fdf2df",
		[varBsWarningBorderSubtle]: "#fbe5c0",
		[varBsWarningRgb]: "244, 189, 97",
		[varBsWarningTextEmphasis]: "#624c27",
		[varBsWhiteRgb]: "255, 255, 255",
	},
})
