import {
listGroup,
listGroupFlush,
listGroupItem,
listGroupItemAction,
listGroupItemDanger,
listGroupItemDark,
listGroupItemDisabled,
listGroupItemInfo,
listGroupItemLight,
listGroupItemPrimary,
listGroupItemSecondary,
listGroupItemSuccess,
listGroupItemWarning,
} from './base.css'

export const sketchyListGroupRuntimeClasses = {
listGroup,
listGroupFlush,
listGroupItem,
listGroupItemAction,
listGroupItemDanger,
listGroupItemDark,
listGroupItemDisabled,
listGroupItemInfo,
listGroupItemLight,
listGroupItemPrimary,
listGroupItemSecondary,
listGroupItemSuccess,
listGroupItemWarning,
} as const
