import { Route, Router } from '@solidjs/router'
import { render } from '@solidjs/web'
import PocThemeScopeDemo from './components/poc/PocThemeScopeDemo'
import { Ve2Shell } from './components/shell/Ve2Shell'
import SolidBaseButton from './components/ui/buttons/solid/SolidBaseButton'
import SolidDisabledBaseButton from './components/ui/buttons/solid/disabled/SolidDisabledBaseButton'
import SolidCheckBaseButton from './components/ui/buttons/solid/check/SolidCheckBaseButton'
import SolidCheckDisabledBaseButton from './components/ui/buttons/solid/check/disabled/SolidCheckDisabledBaseButton'
import SolidCheckActiveBaseButton from './components/ui/buttons/solid/check-active/SolidCheckActiveBaseButton'
import SolidCheckActiveDisabledBaseButton from './components/ui/buttons/solid/check-active/disabled/SolidCheckActiveDisabledBaseButton'
import SolidToggleBaseButton from './components/ui/buttons/solid/toggle/SolidToggleBaseButton'
import SolidToggleDisabledBaseButton from './components/ui/buttons/solid/toggle/disabled/SolidToggleDisabledBaseButton'
import SolidToggleActiveBaseButton from './components/ui/buttons/solid/toggle-active/SolidToggleActiveBaseButton'
import SolidToggleActiveDisabledBaseButton from './components/ui/buttons/solid/toggle-active/disabled/SolidToggleActiveDisabledBaseButton'
import SolidPrimaryButton from './components/ui/buttons/solid/SolidPrimaryButton'
import SolidDisabledPrimaryButton from './components/ui/buttons/solid/disabled/SolidDisabledPrimaryButton'
import SolidCheckPrimaryButton from './components/ui/buttons/solid/check/SolidCheckPrimaryButton'
import SolidCheckDisabledPrimaryButton from './components/ui/buttons/solid/check/disabled/SolidCheckDisabledPrimaryButton'
import SolidCheckActivePrimaryButton from './components/ui/buttons/solid/check-active/SolidCheckActivePrimaryButton'
import SolidCheckActiveDisabledPrimaryButton from './components/ui/buttons/solid/check-active/disabled/SolidCheckActiveDisabledPrimaryButton'
import SolidTogglePrimaryButton from './components/ui/buttons/solid/toggle/SolidTogglePrimaryButton'
import SolidToggleDisabledPrimaryButton from './components/ui/buttons/solid/toggle/disabled/SolidToggleDisabledPrimaryButton'
import SolidToggleActivePrimaryButton from './components/ui/buttons/solid/toggle-active/SolidToggleActivePrimaryButton'
import SolidToggleActiveDisabledPrimaryButton from './components/ui/buttons/solid/toggle-active/disabled/SolidToggleActiveDisabledPrimaryButton'
import SolidSecondaryButton from './components/ui/buttons/solid/SolidSecondaryButton'
import SolidDisabledSecondaryButton from './components/ui/buttons/solid/disabled/SolidDisabledSecondaryButton'
import SolidCheckSecondaryButton from './components/ui/buttons/solid/check/SolidCheckSecondaryButton'
import SolidCheckDisabledSecondaryButton from './components/ui/buttons/solid/check/disabled/SolidCheckDisabledSecondaryButton'
import SolidCheckActiveSecondaryButton from './components/ui/buttons/solid/check-active/SolidCheckActiveSecondaryButton'
import SolidCheckActiveDisabledSecondaryButton from './components/ui/buttons/solid/check-active/disabled/SolidCheckActiveDisabledSecondaryButton'
import SolidToggleSecondaryButton from './components/ui/buttons/solid/toggle/SolidToggleSecondaryButton'
import SolidToggleDisabledSecondaryButton from './components/ui/buttons/solid/toggle/disabled/SolidToggleDisabledSecondaryButton'
import SolidToggleActiveSecondaryButton from './components/ui/buttons/solid/toggle-active/SolidToggleActiveSecondaryButton'
import SolidToggleActiveDisabledSecondaryButton from './components/ui/buttons/solid/toggle-active/disabled/SolidToggleActiveDisabledSecondaryButton'
import SolidSuccessButton from './components/ui/buttons/solid/SolidSuccessButton'
import SolidDisabledSuccessButton from './components/ui/buttons/solid/disabled/SolidDisabledSuccessButton'
import SolidCheckSuccessButton from './components/ui/buttons/solid/check/SolidCheckSuccessButton'
import SolidCheckDisabledSuccessButton from './components/ui/buttons/solid/check/disabled/SolidCheckDisabledSuccessButton'
import SolidCheckActiveSuccessButton from './components/ui/buttons/solid/check-active/SolidCheckActiveSuccessButton'
import SolidCheckActiveDisabledSuccessButton from './components/ui/buttons/solid/check-active/disabled/SolidCheckActiveDisabledSuccessButton'
import SolidToggleSuccessButton from './components/ui/buttons/solid/toggle/SolidToggleSuccessButton'
import SolidToggleDisabledSuccessButton from './components/ui/buttons/solid/toggle/disabled/SolidToggleDisabledSuccessButton'
import SolidToggleActiveSuccessButton from './components/ui/buttons/solid/toggle-active/SolidToggleActiveSuccessButton'
import SolidToggleActiveDisabledSuccessButton from './components/ui/buttons/solid/toggle-active/disabled/SolidToggleActiveDisabledSuccessButton'
import SolidDangerButton from './components/ui/buttons/solid/SolidDangerButton'
import SolidDisabledDangerButton from './components/ui/buttons/solid/disabled/SolidDisabledDangerButton'
import SolidCheckDangerButton from './components/ui/buttons/solid/check/SolidCheckDangerButton'
import SolidCheckDisabledDangerButton from './components/ui/buttons/solid/check/disabled/SolidCheckDisabledDangerButton'
import SolidCheckActiveDangerButton from './components/ui/buttons/solid/check-active/SolidCheckActiveDangerButton'
import SolidCheckActiveDisabledDangerButton from './components/ui/buttons/solid/check-active/disabled/SolidCheckActiveDisabledDangerButton'
import SolidToggleDangerButton from './components/ui/buttons/solid/toggle/SolidToggleDangerButton'
import SolidToggleDisabledDangerButton from './components/ui/buttons/solid/toggle/disabled/SolidToggleDisabledDangerButton'
import SolidToggleActiveDangerButton from './components/ui/buttons/solid/toggle-active/SolidToggleActiveDangerButton'
import SolidToggleActiveDisabledDangerButton from './components/ui/buttons/solid/toggle-active/disabled/SolidToggleActiveDisabledDangerButton'
import SolidWarningButton from './components/ui/buttons/solid/SolidWarningButton'
import SolidDisabledWarningButton from './components/ui/buttons/solid/disabled/SolidDisabledWarningButton'
import SolidCheckWarningButton from './components/ui/buttons/solid/check/SolidCheckWarningButton'
import SolidCheckDisabledWarningButton from './components/ui/buttons/solid/check/disabled/SolidCheckDisabledWarningButton'
import SolidCheckActiveWarningButton from './components/ui/buttons/solid/check-active/SolidCheckActiveWarningButton'
import SolidCheckActiveDisabledWarningButton from './components/ui/buttons/solid/check-active/disabled/SolidCheckActiveDisabledWarningButton'
import SolidToggleWarningButton from './components/ui/buttons/solid/toggle/SolidToggleWarningButton'
import SolidToggleDisabledWarningButton from './components/ui/buttons/solid/toggle/disabled/SolidToggleDisabledWarningButton'
import SolidToggleActiveWarningButton from './components/ui/buttons/solid/toggle-active/SolidToggleActiveWarningButton'
import SolidToggleActiveDisabledWarningButton from './components/ui/buttons/solid/toggle-active/disabled/SolidToggleActiveDisabledWarningButton'
import SolidInfoButton from './components/ui/buttons/solid/SolidInfoButton'
import SolidDisabledInfoButton from './components/ui/buttons/solid/disabled/SolidDisabledInfoButton'
import SolidCheckInfoButton from './components/ui/buttons/solid/check/SolidCheckInfoButton'
import SolidCheckDisabledInfoButton from './components/ui/buttons/solid/check/disabled/SolidCheckDisabledInfoButton'
import SolidCheckActiveInfoButton from './components/ui/buttons/solid/check-active/SolidCheckActiveInfoButton'
import SolidCheckActiveDisabledInfoButton from './components/ui/buttons/solid/check-active/disabled/SolidCheckActiveDisabledInfoButton'
import SolidToggleInfoButton from './components/ui/buttons/solid/toggle/SolidToggleInfoButton'
import SolidToggleDisabledInfoButton from './components/ui/buttons/solid/toggle/disabled/SolidToggleDisabledInfoButton'
import SolidToggleActiveInfoButton from './components/ui/buttons/solid/toggle-active/SolidToggleActiveInfoButton'
import SolidToggleActiveDisabledInfoButton from './components/ui/buttons/solid/toggle-active/disabled/SolidToggleActiveDisabledInfoButton'
import SolidLightButton from './components/ui/buttons/solid/SolidLightButton'
import SolidDisabledLightButton from './components/ui/buttons/solid/disabled/SolidDisabledLightButton'
import SolidCheckLightButton from './components/ui/buttons/solid/check/SolidCheckLightButton'
import SolidCheckDisabledLightButton from './components/ui/buttons/solid/check/disabled/SolidCheckDisabledLightButton'
import SolidCheckActiveLightButton from './components/ui/buttons/solid/check-active/SolidCheckActiveLightButton'
import SolidCheckActiveDisabledLightButton from './components/ui/buttons/solid/check-active/disabled/SolidCheckActiveDisabledLightButton'
import SolidToggleLightButton from './components/ui/buttons/solid/toggle/SolidToggleLightButton'
import SolidToggleDisabledLightButton from './components/ui/buttons/solid/toggle/disabled/SolidToggleDisabledLightButton'
import SolidToggleActiveLightButton from './components/ui/buttons/solid/toggle-active/SolidToggleActiveLightButton'
import SolidToggleActiveDisabledLightButton from './components/ui/buttons/solid/toggle-active/disabled/SolidToggleActiveDisabledLightButton'
import SolidDarkButton from './components/ui/buttons/solid/SolidDarkButton'
import SolidDisabledDarkButton from './components/ui/buttons/solid/disabled/SolidDisabledDarkButton'
import SolidCheckDarkButton from './components/ui/buttons/solid/check/SolidCheckDarkButton'
import SolidCheckDisabledDarkButton from './components/ui/buttons/solid/check/disabled/SolidCheckDisabledDarkButton'
import SolidCheckActiveDarkButton from './components/ui/buttons/solid/check-active/SolidCheckActiveDarkButton'
import SolidCheckActiveDisabledDarkButton from './components/ui/buttons/solid/check-active/disabled/SolidCheckActiveDisabledDarkButton'
import SolidToggleDarkButton from './components/ui/buttons/solid/toggle/SolidToggleDarkButton'
import SolidToggleDisabledDarkButton from './components/ui/buttons/solid/toggle/disabled/SolidToggleDisabledDarkButton'
import SolidToggleActiveDarkButton from './components/ui/buttons/solid/toggle-active/SolidToggleActiveDarkButton'
import SolidToggleActiveDisabledDarkButton from './components/ui/buttons/solid/toggle-active/disabled/SolidToggleActiveDisabledDarkButton'
import SolidLinkButton from './components/ui/buttons/solid/SolidLinkButton'
import SolidDisabledLinkButton from './components/ui/buttons/solid/disabled/SolidDisabledLinkButton'
import SolidCheckLinkButton from './components/ui/buttons/solid/check/SolidCheckLinkButton'
import SolidCheckDisabledLinkButton from './components/ui/buttons/solid/check/disabled/SolidCheckDisabledLinkButton'
import SolidCheckActiveLinkButton from './components/ui/buttons/solid/check-active/SolidCheckActiveLinkButton'
import SolidCheckActiveDisabledLinkButton from './components/ui/buttons/solid/check-active/disabled/SolidCheckActiveDisabledLinkButton'
import SolidToggleLinkButton from './components/ui/buttons/solid/toggle/SolidToggleLinkButton'
import SolidToggleDisabledLinkButton from './components/ui/buttons/solid/toggle/disabled/SolidToggleDisabledLinkButton'
import SolidToggleActiveLinkButton from './components/ui/buttons/solid/toggle-active/SolidToggleActiveLinkButton'
import SolidToggleActiveDisabledLinkButton from './components/ui/buttons/solid/toggle-active/disabled/SolidToggleActiveDisabledLinkButton'
import OutlinePrimaryButton from './components/ui/buttons/outline/OutlinePrimaryButton'
import OutlineDisabledPrimaryButton from './components/ui/buttons/outline/disabled/OutlineDisabledPrimaryButton'
import OutlineCheckPrimaryButton from './components/ui/buttons/outline/check/OutlineCheckPrimaryButton'
import OutlineCheckDisabledPrimaryButton from './components/ui/buttons/outline/check/disabled/OutlineCheckDisabledPrimaryButton'
import OutlineCheckActivePrimaryButton from './components/ui/buttons/outline/check-active/OutlineCheckActivePrimaryButton'
import OutlineCheckActiveDisabledPrimaryButton from './components/ui/buttons/outline/check-active/disabled/OutlineCheckActiveDisabledPrimaryButton'
import OutlineTogglePrimaryButton from './components/ui/buttons/outline/toggle/OutlineTogglePrimaryButton'
import OutlineToggleDisabledPrimaryButton from './components/ui/buttons/outline/toggle/disabled/OutlineToggleDisabledPrimaryButton'
import OutlineToggleActivePrimaryButton from './components/ui/buttons/outline/toggle-active/OutlineToggleActivePrimaryButton'
import OutlineToggleActiveDisabledPrimaryButton from './components/ui/buttons/outline/toggle-active/disabled/OutlineToggleActiveDisabledPrimaryButton'
import OutlineSecondaryButton from './components/ui/buttons/outline/OutlineSecondaryButton'
import OutlineDisabledSecondaryButton from './components/ui/buttons/outline/disabled/OutlineDisabledSecondaryButton'
import OutlineCheckSecondaryButton from './components/ui/buttons/outline/check/OutlineCheckSecondaryButton'
import OutlineCheckDisabledSecondaryButton from './components/ui/buttons/outline/check/disabled/OutlineCheckDisabledSecondaryButton'
import OutlineCheckActiveSecondaryButton from './components/ui/buttons/outline/check-active/OutlineCheckActiveSecondaryButton'
import OutlineCheckActiveDisabledSecondaryButton from './components/ui/buttons/outline/check-active/disabled/OutlineCheckActiveDisabledSecondaryButton'
import OutlineToggleSecondaryButton from './components/ui/buttons/outline/toggle/OutlineToggleSecondaryButton'
import OutlineToggleDisabledSecondaryButton from './components/ui/buttons/outline/toggle/disabled/OutlineToggleDisabledSecondaryButton'
import OutlineToggleActiveSecondaryButton from './components/ui/buttons/outline/toggle-active/OutlineToggleActiveSecondaryButton'
import OutlineToggleActiveDisabledSecondaryButton from './components/ui/buttons/outline/toggle-active/disabled/OutlineToggleActiveDisabledSecondaryButton'
import OutlineSuccessButton from './components/ui/buttons/outline/OutlineSuccessButton'
import OutlineDisabledSuccessButton from './components/ui/buttons/outline/disabled/OutlineDisabledSuccessButton'
import OutlineCheckSuccessButton from './components/ui/buttons/outline/check/OutlineCheckSuccessButton'
import OutlineCheckDisabledSuccessButton from './components/ui/buttons/outline/check/disabled/OutlineCheckDisabledSuccessButton'
import OutlineCheckActiveSuccessButton from './components/ui/buttons/outline/check-active/OutlineCheckActiveSuccessButton'
import OutlineCheckActiveDisabledSuccessButton from './components/ui/buttons/outline/check-active/disabled/OutlineCheckActiveDisabledSuccessButton'
import OutlineToggleSuccessButton from './components/ui/buttons/outline/toggle/OutlineToggleSuccessButton'
import OutlineToggleDisabledSuccessButton from './components/ui/buttons/outline/toggle/disabled/OutlineToggleDisabledSuccessButton'
import OutlineToggleActiveSuccessButton from './components/ui/buttons/outline/toggle-active/OutlineToggleActiveSuccessButton'
import OutlineToggleActiveDisabledSuccessButton from './components/ui/buttons/outline/toggle-active/disabled/OutlineToggleActiveDisabledSuccessButton'
import OutlineDangerButton from './components/ui/buttons/outline/OutlineDangerButton'
import OutlineDisabledDangerButton from './components/ui/buttons/outline/disabled/OutlineDisabledDangerButton'
import OutlineCheckDangerButton from './components/ui/buttons/outline/check/OutlineCheckDangerButton'
import OutlineCheckDisabledDangerButton from './components/ui/buttons/outline/check/disabled/OutlineCheckDisabledDangerButton'
import OutlineCheckActiveDangerButton from './components/ui/buttons/outline/check-active/OutlineCheckActiveDangerButton'
import OutlineCheckActiveDisabledDangerButton from './components/ui/buttons/outline/check-active/disabled/OutlineCheckActiveDisabledDangerButton'
import OutlineToggleDangerButton from './components/ui/buttons/outline/toggle/OutlineToggleDangerButton'
import OutlineToggleDisabledDangerButton from './components/ui/buttons/outline/toggle/disabled/OutlineToggleDisabledDangerButton'
import OutlineToggleActiveDangerButton from './components/ui/buttons/outline/toggle-active/OutlineToggleActiveDangerButton'
import OutlineToggleActiveDisabledDangerButton from './components/ui/buttons/outline/toggle-active/disabled/OutlineToggleActiveDisabledDangerButton'
import OutlineWarningButton from './components/ui/buttons/outline/OutlineWarningButton'
import OutlineDisabledWarningButton from './components/ui/buttons/outline/disabled/OutlineDisabledWarningButton'
import OutlineCheckWarningButton from './components/ui/buttons/outline/check/OutlineCheckWarningButton'
import OutlineCheckDisabledWarningButton from './components/ui/buttons/outline/check/disabled/OutlineCheckDisabledWarningButton'
import OutlineCheckActiveWarningButton from './components/ui/buttons/outline/check-active/OutlineCheckActiveWarningButton'
import OutlineCheckActiveDisabledWarningButton from './components/ui/buttons/outline/check-active/disabled/OutlineCheckActiveDisabledWarningButton'
import OutlineToggleWarningButton from './components/ui/buttons/outline/toggle/OutlineToggleWarningButton'
import OutlineToggleDisabledWarningButton from './components/ui/buttons/outline/toggle/disabled/OutlineToggleDisabledWarningButton'
import OutlineToggleActiveWarningButton from './components/ui/buttons/outline/toggle-active/OutlineToggleActiveWarningButton'
import OutlineToggleActiveDisabledWarningButton from './components/ui/buttons/outline/toggle-active/disabled/OutlineToggleActiveDisabledWarningButton'
import OutlineInfoButton from './components/ui/buttons/outline/OutlineInfoButton'
import OutlineDisabledInfoButton from './components/ui/buttons/outline/disabled/OutlineDisabledInfoButton'
import OutlineCheckInfoButton from './components/ui/buttons/outline/check/OutlineCheckInfoButton'
import OutlineCheckDisabledInfoButton from './components/ui/buttons/outline/check/disabled/OutlineCheckDisabledInfoButton'
import OutlineCheckActiveInfoButton from './components/ui/buttons/outline/check-active/OutlineCheckActiveInfoButton'
import OutlineCheckActiveDisabledInfoButton from './components/ui/buttons/outline/check-active/disabled/OutlineCheckActiveDisabledInfoButton'
import OutlineToggleInfoButton from './components/ui/buttons/outline/toggle/OutlineToggleInfoButton'
import OutlineToggleDisabledInfoButton from './components/ui/buttons/outline/toggle/disabled/OutlineToggleDisabledInfoButton'
import OutlineToggleActiveInfoButton from './components/ui/buttons/outline/toggle-active/OutlineToggleActiveInfoButton'
import OutlineToggleActiveDisabledInfoButton from './components/ui/buttons/outline/toggle-active/disabled/OutlineToggleActiveDisabledInfoButton'
import OutlineLightButton from './components/ui/buttons/outline/OutlineLightButton'
import OutlineDisabledLightButton from './components/ui/buttons/outline/disabled/OutlineDisabledLightButton'
import OutlineCheckLightButton from './components/ui/buttons/outline/check/OutlineCheckLightButton'
import OutlineCheckDisabledLightButton from './components/ui/buttons/outline/check/disabled/OutlineCheckDisabledLightButton'
import OutlineCheckActiveLightButton from './components/ui/buttons/outline/check-active/OutlineCheckActiveLightButton'
import OutlineCheckActiveDisabledLightButton from './components/ui/buttons/outline/check-active/disabled/OutlineCheckActiveDisabledLightButton'
import OutlineToggleLightButton from './components/ui/buttons/outline/toggle/OutlineToggleLightButton'
import OutlineToggleDisabledLightButton from './components/ui/buttons/outline/toggle/disabled/OutlineToggleDisabledLightButton'
import OutlineToggleActiveLightButton from './components/ui/buttons/outline/toggle-active/OutlineToggleActiveLightButton'
import OutlineToggleActiveDisabledLightButton from './components/ui/buttons/outline/toggle-active/disabled/OutlineToggleActiveDisabledLightButton'
import OutlineDarkButton from './components/ui/buttons/outline/OutlineDarkButton'
import OutlineDisabledDarkButton from './components/ui/buttons/outline/disabled/OutlineDisabledDarkButton'
import OutlineCheckDarkButton from './components/ui/buttons/outline/check/OutlineCheckDarkButton'
import OutlineCheckDisabledDarkButton from './components/ui/buttons/outline/check/disabled/OutlineCheckDisabledDarkButton'
import OutlineCheckActiveDarkButton from './components/ui/buttons/outline/check-active/OutlineCheckActiveDarkButton'
import OutlineCheckActiveDisabledDarkButton from './components/ui/buttons/outline/check-active/disabled/OutlineCheckActiveDisabledDarkButton'
import OutlineToggleDarkButton from './components/ui/buttons/outline/toggle/OutlineToggleDarkButton'
import OutlineToggleDisabledDarkButton from './components/ui/buttons/outline/toggle/disabled/OutlineToggleDisabledDarkButton'
import OutlineToggleActiveDarkButton from './components/ui/buttons/outline/toggle-active/OutlineToggleActiveDarkButton'
import OutlineToggleActiveDisabledDarkButton from './components/ui/buttons/outline/toggle-active/disabled/OutlineToggleActiveDisabledDarkButton'
import LargeButton from './components/ui/buttons/sizes/LargeButton'
import DisabledLargeButton from './components/ui/buttons/sizes/disabled/DisabledLargeButton'
import CheckLargeButton from './components/ui/buttons/sizes/check/CheckLargeButton'
import CheckDisabledLargeButton from './components/ui/buttons/sizes/check/disabled/CheckDisabledLargeButton'
import CheckActiveLargeButton from './components/ui/buttons/sizes/check-active/CheckActiveLargeButton'
import CheckActiveDisabledLargeButton from './components/ui/buttons/sizes/check-active/disabled/CheckActiveDisabledLargeButton'
import ToggleLargeButton from './components/ui/buttons/sizes/toggle/ToggleLargeButton'
import ToggleDisabledLargeButton from './components/ui/buttons/sizes/toggle/disabled/ToggleDisabledLargeButton'
import ToggleActiveLargeButton from './components/ui/buttons/sizes/toggle-active/ToggleActiveLargeButton'
import ToggleActiveDisabledLargeButton from './components/ui/buttons/sizes/toggle-active/disabled/ToggleActiveDisabledLargeButton'
import SmallButton from './components/ui/buttons/sizes/SmallButton'
import DisabledSmallButton from './components/ui/buttons/sizes/disabled/DisabledSmallButton'
import CheckSmallButton from './components/ui/buttons/sizes/check/CheckSmallButton'
import CheckDisabledSmallButton from './components/ui/buttons/sizes/check/disabled/CheckDisabledSmallButton'
import CheckActiveSmallButton from './components/ui/buttons/sizes/check-active/CheckActiveSmallButton'
import CheckActiveDisabledSmallButton from './components/ui/buttons/sizes/check-active/disabled/CheckActiveDisabledSmallButton'
import ToggleSmallButton from './components/ui/buttons/sizes/toggle/ToggleSmallButton'
import ToggleDisabledSmallButton from './components/ui/buttons/sizes/toggle/disabled/ToggleDisabledSmallButton'
import ToggleActiveSmallButton from './components/ui/buttons/sizes/toggle-active/ToggleActiveSmallButton'
import ToggleActiveDisabledSmallButton from './components/ui/buttons/sizes/toggle-active/disabled/ToggleActiveDisabledSmallButton'

render(
	() => (
		<Router>
			<Route path="/" component={PocThemeScopeDemo} />
			<Route component={Ve2Shell}>
			<Route path="/ui/buttons/solid/base-button" component={SolidBaseButton} />
			<Route path="/ui/buttons/solid/disabled/base-button" component={SolidDisabledBaseButton} />
			<Route path="/ui/buttons/solid/check/base-button" component={SolidCheckBaseButton} />
			<Route path="/ui/buttons/solid/check/disabled/base-button" component={SolidCheckDisabledBaseButton} />
			<Route path="/ui/buttons/solid/check-active/base-button" component={SolidCheckActiveBaseButton} />
			<Route path="/ui/buttons/solid/check-active/disabled/base-button" component={SolidCheckActiveDisabledBaseButton} />
			<Route path="/ui/buttons/solid/toggle/base-button" component={SolidToggleBaseButton} />
			<Route path="/ui/buttons/solid/toggle/disabled/base-button" component={SolidToggleDisabledBaseButton} />
			<Route path="/ui/buttons/solid/toggle-active/base-button" component={SolidToggleActiveBaseButton} />
			<Route path="/ui/buttons/solid/toggle-active/disabled/base-button" component={SolidToggleActiveDisabledBaseButton} />
			<Route path="/ui/buttons/solid/primary-button" component={SolidPrimaryButton} />
			<Route path="/ui/buttons/solid/disabled/primary-button" component={SolidDisabledPrimaryButton} />
			<Route path="/ui/buttons/solid/check/primary-button" component={SolidCheckPrimaryButton} />
			<Route path="/ui/buttons/solid/check/disabled/primary-button" component={SolidCheckDisabledPrimaryButton} />
			<Route path="/ui/buttons/solid/check-active/primary-button" component={SolidCheckActivePrimaryButton} />
			<Route path="/ui/buttons/solid/check-active/disabled/primary-button" component={SolidCheckActiveDisabledPrimaryButton} />
			<Route path="/ui/buttons/solid/toggle/primary-button" component={SolidTogglePrimaryButton} />
			<Route path="/ui/buttons/solid/toggle/disabled/primary-button" component={SolidToggleDisabledPrimaryButton} />
			<Route path="/ui/buttons/solid/toggle-active/primary-button" component={SolidToggleActivePrimaryButton} />
			<Route path="/ui/buttons/solid/toggle-active/disabled/primary-button" component={SolidToggleActiveDisabledPrimaryButton} />
			<Route path="/ui/buttons/solid/secondary-button" component={SolidSecondaryButton} />
			<Route path="/ui/buttons/solid/disabled/secondary-button" component={SolidDisabledSecondaryButton} />
			<Route path="/ui/buttons/solid/check/secondary-button" component={SolidCheckSecondaryButton} />
			<Route path="/ui/buttons/solid/check/disabled/secondary-button" component={SolidCheckDisabledSecondaryButton} />
			<Route path="/ui/buttons/solid/check-active/secondary-button" component={SolidCheckActiveSecondaryButton} />
			<Route path="/ui/buttons/solid/check-active/disabled/secondary-button" component={SolidCheckActiveDisabledSecondaryButton} />
			<Route path="/ui/buttons/solid/toggle/secondary-button" component={SolidToggleSecondaryButton} />
			<Route path="/ui/buttons/solid/toggle/disabled/secondary-button" component={SolidToggleDisabledSecondaryButton} />
			<Route path="/ui/buttons/solid/toggle-active/secondary-button" component={SolidToggleActiveSecondaryButton} />
			<Route path="/ui/buttons/solid/toggle-active/disabled/secondary-button" component={SolidToggleActiveDisabledSecondaryButton} />
			<Route path="/ui/buttons/solid/success-button" component={SolidSuccessButton} />
			<Route path="/ui/buttons/solid/disabled/success-button" component={SolidDisabledSuccessButton} />
			<Route path="/ui/buttons/solid/check/success-button" component={SolidCheckSuccessButton} />
			<Route path="/ui/buttons/solid/check/disabled/success-button" component={SolidCheckDisabledSuccessButton} />
			<Route path="/ui/buttons/solid/check-active/success-button" component={SolidCheckActiveSuccessButton} />
			<Route path="/ui/buttons/solid/check-active/disabled/success-button" component={SolidCheckActiveDisabledSuccessButton} />
			<Route path="/ui/buttons/solid/toggle/success-button" component={SolidToggleSuccessButton} />
			<Route path="/ui/buttons/solid/toggle/disabled/success-button" component={SolidToggleDisabledSuccessButton} />
			<Route path="/ui/buttons/solid/toggle-active/success-button" component={SolidToggleActiveSuccessButton} />
			<Route path="/ui/buttons/solid/toggle-active/disabled/success-button" component={SolidToggleActiveDisabledSuccessButton} />
			<Route path="/ui/buttons/solid/danger-button" component={SolidDangerButton} />
			<Route path="/ui/buttons/solid/disabled/danger-button" component={SolidDisabledDangerButton} />
			<Route path="/ui/buttons/solid/check/danger-button" component={SolidCheckDangerButton} />
			<Route path="/ui/buttons/solid/check/disabled/danger-button" component={SolidCheckDisabledDangerButton} />
			<Route path="/ui/buttons/solid/check-active/danger-button" component={SolidCheckActiveDangerButton} />
			<Route path="/ui/buttons/solid/check-active/disabled/danger-button" component={SolidCheckActiveDisabledDangerButton} />
			<Route path="/ui/buttons/solid/toggle/danger-button" component={SolidToggleDangerButton} />
			<Route path="/ui/buttons/solid/toggle/disabled/danger-button" component={SolidToggleDisabledDangerButton} />
			<Route path="/ui/buttons/solid/toggle-active/danger-button" component={SolidToggleActiveDangerButton} />
			<Route path="/ui/buttons/solid/toggle-active/disabled/danger-button" component={SolidToggleActiveDisabledDangerButton} />
			<Route path="/ui/buttons/solid/warning-button" component={SolidWarningButton} />
			<Route path="/ui/buttons/solid/disabled/warning-button" component={SolidDisabledWarningButton} />
			<Route path="/ui/buttons/solid/check/warning-button" component={SolidCheckWarningButton} />
			<Route path="/ui/buttons/solid/check/disabled/warning-button" component={SolidCheckDisabledWarningButton} />
			<Route path="/ui/buttons/solid/check-active/warning-button" component={SolidCheckActiveWarningButton} />
			<Route path="/ui/buttons/solid/check-active/disabled/warning-button" component={SolidCheckActiveDisabledWarningButton} />
			<Route path="/ui/buttons/solid/toggle/warning-button" component={SolidToggleWarningButton} />
			<Route path="/ui/buttons/solid/toggle/disabled/warning-button" component={SolidToggleDisabledWarningButton} />
			<Route path="/ui/buttons/solid/toggle-active/warning-button" component={SolidToggleActiveWarningButton} />
			<Route path="/ui/buttons/solid/toggle-active/disabled/warning-button" component={SolidToggleActiveDisabledWarningButton} />
			<Route path="/ui/buttons/solid/info-button" component={SolidInfoButton} />
			<Route path="/ui/buttons/solid/disabled/info-button" component={SolidDisabledInfoButton} />
			<Route path="/ui/buttons/solid/check/info-button" component={SolidCheckInfoButton} />
			<Route path="/ui/buttons/solid/check/disabled/info-button" component={SolidCheckDisabledInfoButton} />
			<Route path="/ui/buttons/solid/check-active/info-button" component={SolidCheckActiveInfoButton} />
			<Route path="/ui/buttons/solid/check-active/disabled/info-button" component={SolidCheckActiveDisabledInfoButton} />
			<Route path="/ui/buttons/solid/toggle/info-button" component={SolidToggleInfoButton} />
			<Route path="/ui/buttons/solid/toggle/disabled/info-button" component={SolidToggleDisabledInfoButton} />
			<Route path="/ui/buttons/solid/toggle-active/info-button" component={SolidToggleActiveInfoButton} />
			<Route path="/ui/buttons/solid/toggle-active/disabled/info-button" component={SolidToggleActiveDisabledInfoButton} />
			<Route path="/ui/buttons/solid/light-button" component={SolidLightButton} />
			<Route path="/ui/buttons/solid/disabled/light-button" component={SolidDisabledLightButton} />
			<Route path="/ui/buttons/solid/check/light-button" component={SolidCheckLightButton} />
			<Route path="/ui/buttons/solid/check/disabled/light-button" component={SolidCheckDisabledLightButton} />
			<Route path="/ui/buttons/solid/check-active/light-button" component={SolidCheckActiveLightButton} />
			<Route path="/ui/buttons/solid/check-active/disabled/light-button" component={SolidCheckActiveDisabledLightButton} />
			<Route path="/ui/buttons/solid/toggle/light-button" component={SolidToggleLightButton} />
			<Route path="/ui/buttons/solid/toggle/disabled/light-button" component={SolidToggleDisabledLightButton} />
			<Route path="/ui/buttons/solid/toggle-active/light-button" component={SolidToggleActiveLightButton} />
			<Route path="/ui/buttons/solid/toggle-active/disabled/light-button" component={SolidToggleActiveDisabledLightButton} />
			<Route path="/ui/buttons/solid/dark-button" component={SolidDarkButton} />
			<Route path="/ui/buttons/solid/disabled/dark-button" component={SolidDisabledDarkButton} />
			<Route path="/ui/buttons/solid/check/dark-button" component={SolidCheckDarkButton} />
			<Route path="/ui/buttons/solid/check/disabled/dark-button" component={SolidCheckDisabledDarkButton} />
			<Route path="/ui/buttons/solid/check-active/dark-button" component={SolidCheckActiveDarkButton} />
			<Route path="/ui/buttons/solid/check-active/disabled/dark-button" component={SolidCheckActiveDisabledDarkButton} />
			<Route path="/ui/buttons/solid/toggle/dark-button" component={SolidToggleDarkButton} />
			<Route path="/ui/buttons/solid/toggle/disabled/dark-button" component={SolidToggleDisabledDarkButton} />
			<Route path="/ui/buttons/solid/toggle-active/dark-button" component={SolidToggleActiveDarkButton} />
			<Route path="/ui/buttons/solid/toggle-active/disabled/dark-button" component={SolidToggleActiveDisabledDarkButton} />
			<Route path="/ui/buttons/solid/link-button" component={SolidLinkButton} />
			<Route path="/ui/buttons/solid/disabled/link-button" component={SolidDisabledLinkButton} />
			<Route path="/ui/buttons/solid/check/link-button" component={SolidCheckLinkButton} />
			<Route path="/ui/buttons/solid/check/disabled/link-button" component={SolidCheckDisabledLinkButton} />
			<Route path="/ui/buttons/solid/check-active/link-button" component={SolidCheckActiveLinkButton} />
			<Route path="/ui/buttons/solid/check-active/disabled/link-button" component={SolidCheckActiveDisabledLinkButton} />
			<Route path="/ui/buttons/solid/toggle/link-button" component={SolidToggleLinkButton} />
			<Route path="/ui/buttons/solid/toggle/disabled/link-button" component={SolidToggleDisabledLinkButton} />
			<Route path="/ui/buttons/solid/toggle-active/link-button" component={SolidToggleActiveLinkButton} />
			<Route path="/ui/buttons/solid/toggle-active/disabled/link-button" component={SolidToggleActiveDisabledLinkButton} />
			<Route path="/ui/buttons/outline/primary-button" component={OutlinePrimaryButton} />
			<Route path="/ui/buttons/outline/disabled/primary-button" component={OutlineDisabledPrimaryButton} />
			<Route path="/ui/buttons/outline/check/primary-button" component={OutlineCheckPrimaryButton} />
			<Route path="/ui/buttons/outline/check/disabled/primary-button" component={OutlineCheckDisabledPrimaryButton} />
			<Route path="/ui/buttons/outline/check-active/primary-button" component={OutlineCheckActivePrimaryButton} />
			<Route path="/ui/buttons/outline/check-active/disabled/primary-button" component={OutlineCheckActiveDisabledPrimaryButton} />
			<Route path="/ui/buttons/outline/toggle/primary-button" component={OutlineTogglePrimaryButton} />
			<Route path="/ui/buttons/outline/toggle/disabled/primary-button" component={OutlineToggleDisabledPrimaryButton} />
			<Route path="/ui/buttons/outline/toggle-active/primary-button" component={OutlineToggleActivePrimaryButton} />
			<Route path="/ui/buttons/outline/toggle-active/disabled/primary-button" component={OutlineToggleActiveDisabledPrimaryButton} />
			<Route path="/ui/buttons/outline/secondary-button" component={OutlineSecondaryButton} />
			<Route path="/ui/buttons/outline/disabled/secondary-button" component={OutlineDisabledSecondaryButton} />
			<Route path="/ui/buttons/outline/check/secondary-button" component={OutlineCheckSecondaryButton} />
			<Route path="/ui/buttons/outline/check/disabled/secondary-button" component={OutlineCheckDisabledSecondaryButton} />
			<Route path="/ui/buttons/outline/check-active/secondary-button" component={OutlineCheckActiveSecondaryButton} />
			<Route path="/ui/buttons/outline/check-active/disabled/secondary-button" component={OutlineCheckActiveDisabledSecondaryButton} />
			<Route path="/ui/buttons/outline/toggle/secondary-button" component={OutlineToggleSecondaryButton} />
			<Route path="/ui/buttons/outline/toggle/disabled/secondary-button" component={OutlineToggleDisabledSecondaryButton} />
			<Route path="/ui/buttons/outline/toggle-active/secondary-button" component={OutlineToggleActiveSecondaryButton} />
			<Route path="/ui/buttons/outline/toggle-active/disabled/secondary-button" component={OutlineToggleActiveDisabledSecondaryButton} />
			<Route path="/ui/buttons/outline/success-button" component={OutlineSuccessButton} />
			<Route path="/ui/buttons/outline/disabled/success-button" component={OutlineDisabledSuccessButton} />
			<Route path="/ui/buttons/outline/check/success-button" component={OutlineCheckSuccessButton} />
			<Route path="/ui/buttons/outline/check/disabled/success-button" component={OutlineCheckDisabledSuccessButton} />
			<Route path="/ui/buttons/outline/check-active/success-button" component={OutlineCheckActiveSuccessButton} />
			<Route path="/ui/buttons/outline/check-active/disabled/success-button" component={OutlineCheckActiveDisabledSuccessButton} />
			<Route path="/ui/buttons/outline/toggle/success-button" component={OutlineToggleSuccessButton} />
			<Route path="/ui/buttons/outline/toggle/disabled/success-button" component={OutlineToggleDisabledSuccessButton} />
			<Route path="/ui/buttons/outline/toggle-active/success-button" component={OutlineToggleActiveSuccessButton} />
			<Route path="/ui/buttons/outline/toggle-active/disabled/success-button" component={OutlineToggleActiveDisabledSuccessButton} />
			<Route path="/ui/buttons/outline/danger-button" component={OutlineDangerButton} />
			<Route path="/ui/buttons/outline/disabled/danger-button" component={OutlineDisabledDangerButton} />
			<Route path="/ui/buttons/outline/check/danger-button" component={OutlineCheckDangerButton} />
			<Route path="/ui/buttons/outline/check/disabled/danger-button" component={OutlineCheckDisabledDangerButton} />
			<Route path="/ui/buttons/outline/check-active/danger-button" component={OutlineCheckActiveDangerButton} />
			<Route path="/ui/buttons/outline/check-active/disabled/danger-button" component={OutlineCheckActiveDisabledDangerButton} />
			<Route path="/ui/buttons/outline/toggle/danger-button" component={OutlineToggleDangerButton} />
			<Route path="/ui/buttons/outline/toggle/disabled/danger-button" component={OutlineToggleDisabledDangerButton} />
			<Route path="/ui/buttons/outline/toggle-active/danger-button" component={OutlineToggleActiveDangerButton} />
			<Route path="/ui/buttons/outline/toggle-active/disabled/danger-button" component={OutlineToggleActiveDisabledDangerButton} />
			<Route path="/ui/buttons/outline/warning-button" component={OutlineWarningButton} />
			<Route path="/ui/buttons/outline/disabled/warning-button" component={OutlineDisabledWarningButton} />
			<Route path="/ui/buttons/outline/check/warning-button" component={OutlineCheckWarningButton} />
			<Route path="/ui/buttons/outline/check/disabled/warning-button" component={OutlineCheckDisabledWarningButton} />
			<Route path="/ui/buttons/outline/check-active/warning-button" component={OutlineCheckActiveWarningButton} />
			<Route path="/ui/buttons/outline/check-active/disabled/warning-button" component={OutlineCheckActiveDisabledWarningButton} />
			<Route path="/ui/buttons/outline/toggle/warning-button" component={OutlineToggleWarningButton} />
			<Route path="/ui/buttons/outline/toggle/disabled/warning-button" component={OutlineToggleDisabledWarningButton} />
			<Route path="/ui/buttons/outline/toggle-active/warning-button" component={OutlineToggleActiveWarningButton} />
			<Route path="/ui/buttons/outline/toggle-active/disabled/warning-button" component={OutlineToggleActiveDisabledWarningButton} />
			<Route path="/ui/buttons/outline/info-button" component={OutlineInfoButton} />
			<Route path="/ui/buttons/outline/disabled/info-button" component={OutlineDisabledInfoButton} />
			<Route path="/ui/buttons/outline/check/info-button" component={OutlineCheckInfoButton} />
			<Route path="/ui/buttons/outline/check/disabled/info-button" component={OutlineCheckDisabledInfoButton} />
			<Route path="/ui/buttons/outline/check-active/info-button" component={OutlineCheckActiveInfoButton} />
			<Route path="/ui/buttons/outline/check-active/disabled/info-button" component={OutlineCheckActiveDisabledInfoButton} />
			<Route path="/ui/buttons/outline/toggle/info-button" component={OutlineToggleInfoButton} />
			<Route path="/ui/buttons/outline/toggle/disabled/info-button" component={OutlineToggleDisabledInfoButton} />
			<Route path="/ui/buttons/outline/toggle-active/info-button" component={OutlineToggleActiveInfoButton} />
			<Route path="/ui/buttons/outline/toggle-active/disabled/info-button" component={OutlineToggleActiveDisabledInfoButton} />
			<Route path="/ui/buttons/outline/light-button" component={OutlineLightButton} />
			<Route path="/ui/buttons/outline/disabled/light-button" component={OutlineDisabledLightButton} />
			<Route path="/ui/buttons/outline/check/light-button" component={OutlineCheckLightButton} />
			<Route path="/ui/buttons/outline/check/disabled/light-button" component={OutlineCheckDisabledLightButton} />
			<Route path="/ui/buttons/outline/check-active/light-button" component={OutlineCheckActiveLightButton} />
			<Route path="/ui/buttons/outline/check-active/disabled/light-button" component={OutlineCheckActiveDisabledLightButton} />
			<Route path="/ui/buttons/outline/toggle/light-button" component={OutlineToggleLightButton} />
			<Route path="/ui/buttons/outline/toggle/disabled/light-button" component={OutlineToggleDisabledLightButton} />
			<Route path="/ui/buttons/outline/toggle-active/light-button" component={OutlineToggleActiveLightButton} />
			<Route path="/ui/buttons/outline/toggle-active/disabled/light-button" component={OutlineToggleActiveDisabledLightButton} />
			<Route path="/ui/buttons/outline/dark-button" component={OutlineDarkButton} />
			<Route path="/ui/buttons/outline/disabled/dark-button" component={OutlineDisabledDarkButton} />
			<Route path="/ui/buttons/outline/check/dark-button" component={OutlineCheckDarkButton} />
			<Route path="/ui/buttons/outline/check/disabled/dark-button" component={OutlineCheckDisabledDarkButton} />
			<Route path="/ui/buttons/outline/check-active/dark-button" component={OutlineCheckActiveDarkButton} />
			<Route path="/ui/buttons/outline/check-active/disabled/dark-button" component={OutlineCheckActiveDisabledDarkButton} />
			<Route path="/ui/buttons/outline/toggle/dark-button" component={OutlineToggleDarkButton} />
			<Route path="/ui/buttons/outline/toggle/disabled/dark-button" component={OutlineToggleDisabledDarkButton} />
			<Route path="/ui/buttons/outline/toggle-active/dark-button" component={OutlineToggleActiveDarkButton} />
			<Route path="/ui/buttons/outline/toggle-active/disabled/dark-button" component={OutlineToggleActiveDisabledDarkButton} />
			<Route path="/ui/buttons/sizes/large-button" component={LargeButton} />
			<Route path="/ui/buttons/sizes/disabled/large-button" component={DisabledLargeButton} />
			<Route path="/ui/buttons/sizes/check/large-button" component={CheckLargeButton} />
			<Route path="/ui/buttons/sizes/check/disabled/large-button" component={CheckDisabledLargeButton} />
			<Route path="/ui/buttons/sizes/check-active/large-button" component={CheckActiveLargeButton} />
			<Route path="/ui/buttons/sizes/check-active/disabled/large-button" component={CheckActiveDisabledLargeButton} />
			<Route path="/ui/buttons/sizes/toggle/large-button" component={ToggleLargeButton} />
			<Route path="/ui/buttons/sizes/toggle/disabled/large-button" component={ToggleDisabledLargeButton} />
			<Route path="/ui/buttons/sizes/toggle-active/large-button" component={ToggleActiveLargeButton} />
			<Route path="/ui/buttons/sizes/toggle-active/disabled/large-button" component={ToggleActiveDisabledLargeButton} />
			<Route path="/ui/buttons/sizes/small-button" component={SmallButton} />
			<Route path="/ui/buttons/sizes/disabled/small-button" component={DisabledSmallButton} />
			<Route path="/ui/buttons/sizes/check/small-button" component={CheckSmallButton} />
			<Route path="/ui/buttons/sizes/check/disabled/small-button" component={CheckDisabledSmallButton} />
			<Route path="/ui/buttons/sizes/check-active/small-button" component={CheckActiveSmallButton} />
			<Route path="/ui/buttons/sizes/check-active/disabled/small-button" component={CheckActiveDisabledSmallButton} />
			<Route path="/ui/buttons/sizes/toggle/small-button" component={ToggleSmallButton} />
			<Route path="/ui/buttons/sizes/toggle/disabled/small-button" component={ToggleDisabledSmallButton} />
			<Route path="/ui/buttons/sizes/toggle-active/small-button" component={ToggleActiveSmallButton} />
			<Route path="/ui/buttons/sizes/toggle-active/disabled/small-button" component={ToggleActiveDisabledSmallButton} />
			</Route>
		</Router>
	),
	document.getElementById('root') as HTMLElement,
)
