// GERADO por scripts/gen-public-vars.mjs — NÃO editar à mão.
import { globalStyle } from '@vanilla-extract/css'
import { lumenScope } from './scope.css'
import { varBsBlackRgb, varBsBodyBgRgb, varBsBodyColorRgb, varBsBorderColor, varBsBorderRadius, varBsBorderRadiusLg, varBsBorderRadiusPill, varBsBorderRadiusSm, varBsBorderRadiusXl, varBsBorderRadiusXxl, varBsBorderStyle, varBsBorderWidth, varBsBoxShadow, varBsBoxShadowLg, varBsBoxShadowSm, varBsDangerBgSubtle, varBsDangerBorderSubtle, varBsDangerRgb, varBsDangerTextEmphasis, varBsDarkBgSubtle, varBsDarkBorderSubtle, varBsDarkRgb, varBsDarkTextEmphasis, varBsEmphasisColor, varBsEmphasisColorRgb, varBsFocusRingColor, varBsFocusRingOpacity, varBsFontMonospace, varBsGradient, varBsInfoBgSubtle, varBsInfoBorderSubtle, varBsInfoRgb, varBsInfoTextEmphasis, varBsLightBgSubtle, varBsLightBorderSubtle, varBsLightRgb, varBsLightTextEmphasis, varBsLinkColorRgb, varBsPrimaryBgSubtle, varBsPrimaryBorderSubtle, varBsPrimaryRgb, varBsPrimaryTextEmphasis, varBsSecondaryBgRgb, varBsSecondaryBgSubtle, varBsSecondaryBorderSubtle, varBsSecondaryColor, varBsSecondaryRgb, varBsSecondaryTextEmphasis, varBsSuccessBgSubtle, varBsSuccessBorderSubtle, varBsSuccessRgb, varBsSuccessTextEmphasis, varBsTertiaryBgRgb, varBsTertiaryColor, varBsWarningBgSubtle, varBsWarningBorderSubtle, varBsWarningRgb, varBsWarningTextEmphasis, varBsWhiteRgb } from '../../theme-contract/_public-vars.css'

globalStyle(lumenScope, {
	vars: {
		[varBsBlackRgb]: "0, 0, 0",
		[varBsBodyBgRgb]: "255, 255, 255",
		[varBsBodyColorRgb]: "34, 34, 34",
		[varBsBorderColor]: "#dee2e6",
		[varBsBorderRadius]: "0.375rem",
		[varBsBorderRadiusLg]: "0.5rem",
		[varBsBorderRadiusPill]: "50rem",
		[varBsBorderRadiusSm]: "0.25rem",
		[varBsBorderRadiusXl]: "1rem",
		[varBsBorderRadiusXxl]: "2rem",
		[varBsBorderStyle]: "solid",
		[varBsBorderWidth]: "1px",
		[varBsBoxShadow]: "0 0.5rem 1rem rgba(0, 0, 0, 0.15)",
		[varBsBoxShadowLg]: "0 1rem 3rem rgba(0, 0, 0, 0.175)",
		[varBsBoxShadowSm]: "0 0.125rem 0.25rem rgba(0, 0, 0, 0.075)",
		[varBsDangerBgSubtle]: "#ffd9d7",
		[varBsDangerBorderSubtle]: "#ffb3af",
		[varBsDangerRgb]: "255, 65, 54",
		[varBsDangerTextEmphasis]: "#661a16",
		[varBsDarkBgSubtle]: "#ced4da",
		[varBsDarkBorderSubtle]: "#adb5bd",
		[varBsDarkRgb]: "85, 85, 85",
		[varBsDarkTextEmphasis]: "#555",
		[varBsEmphasisColor]: "#000",
		[varBsEmphasisColorRgb]: "0, 0, 0",
		[varBsFocusRingColor]: "rgba(21, 140, 186, 0.25)",
		[varBsFocusRingOpacity]: "0.25",
		[varBsFontMonospace]: "SFMono-Regular, Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace",
		[varBsGradient]: "linear-gradient(180deg, rgba(255, 255, 255, 0.15), rgba(255, 255, 255, 0))",
		[varBsInfoBgSubtle]: "#e3f4fb",
		[varBsInfoBorderSubtle]: "#c8eaf7",
		[varBsInfoRgb]: "117, 202, 235",
		[varBsInfoTextEmphasis]: "#2f515e",
		[varBsLightBgSubtle]: "#fbfbfb",
		[varBsLightBorderSubtle]: "#f0f0f0",
		[varBsLightRgb]: "246, 246, 246",
		[varBsLightTextEmphasis]: "#555",
		[varBsLinkColorRgb]: "21, 140, 186",
		[varBsPrimaryBgSubtle]: "#d0e8f1",
		[varBsPrimaryBorderSubtle]: "#a1d1e3",
		[varBsPrimaryRgb]: "21, 140, 186",
		[varBsPrimaryTextEmphasis]: "#08384a",
		[varBsSecondaryBgRgb]: "240, 240, 240",
		[varBsSecondaryBgSubtle]: "#fcfcfc",
		[varBsSecondaryBorderSubtle]: "#f9f9f9",
		[varBsSecondaryColor]: "rgba(34, 34, 34, 0.75)",
		[varBsSecondaryRgb]: "240, 240, 240",
		[varBsSecondaryTextEmphasis]: "#606060",
		[varBsSuccessBgSubtle]: "#d4f0d5",
		[varBsSuccessBorderSubtle]: "#a9e2ab",
		[varBsSuccessRgb]: "40, 182, 44",
		[varBsSuccessTextEmphasis]: "#104912",
		[varBsTertiaryBgRgb]: "246, 246, 246",
		[varBsTertiaryColor]: "rgba(34, 34, 34, 0.5)",
		[varBsWarningBgSubtle]: "#ffe7d1",
		[varBsWarningBorderSubtle]: "#ffcea4",
		[varBsWarningRgb]: "255, 133, 27",
		[varBsWarningTextEmphasis]: "#66350b",
		[varBsWhiteRgb]: "255, 255, 255",
	},
})
