import { globalStyle, style } from '@vanilla-extract/css'
import {
	varBsBlack,
	varBsBlackRgb,
	varBsBlue,
	varBsBodyBg,
	varBsBodyBgRgb,
	varBsBodyColor,
	varBsBodyColorRgb,
	varBsBodyFontFamily,
	varBsBodyFontSize,
	varBsBodyFontWeight,
	varBsBodyLineHeight,
	varBsBorderColor,
	varBsBorderColorTranslucent,
	varBsBorderRadius,
	varBsBorderRadiusLg,
	varBsBorderRadiusPill,
	varBsBorderRadiusSm,
	varBsBorderRadiusXl,
	varBsBorderRadiusXxl,
	varBsBorderStyle,
	varBsBorderWidth,
	varBsBoxShadow,
	varBsBoxShadowInset,
	varBsBoxShadowLg,
	varBsBoxShadowSm,
	varBsBtnCloseFilter,
	varBsCarouselCaptionColor,
	varBsCarouselControlIconFilter,
	varBsCarouselIndicatorActiveBg,
	varBsCodeColor,
	varBsCyan,
	varBsDanger,
	varBsDangerBgSubtle,
	varBsDangerBorderSubtle,
	varBsDangerRgb,
	varBsDangerTextEmphasis,
	varBsDark,
	varBsDarkBgSubtle,
	varBsDarkBorderSubtle,
	varBsDarkRgb,
	varBsDarkTextEmphasis,
	varBsEmphasisColor,
	varBsEmphasisColorRgb,
	varBsFocusRingColor,
	varBsFocusRingOpacity,
	varBsFocusRingWidth,
	varBsFontMonospace,
	varBsFontSansSerif,
	varBsGradient,
	varBsGray,
	varBsGrayDark,
	varBsGreen,
	varBsHeadingColor,
	varBsHighlightBg,
	varBsHighlightColor,
	varBsIndigo,
	varBsInfo,
	varBsInfoBgSubtle,
	varBsInfoBorderSubtle,
	varBsInfoRgb,
	varBsInfoTextEmphasis,
	varBsLight,
	varBsLightBgSubtle,
	varBsLightBorderSubtle,
	varBsLightRgb,
	varBsLightTextEmphasis,
	varBsLinkColor,
	varBsLinkColorRgb,
	varBsLinkDecoration,
	varBsLinkHoverColor,
	varBsLinkHoverColorRgb,
	varBsOrange,
	varBsPink,
	varBsPrimary,
	varBsPrimaryBgSubtle,
	varBsPrimaryBorderSubtle,
	varBsPrimaryRgb,
	varBsPrimaryTextEmphasis,
	varBsPurple,
	varBsRed,
	varBsSecondary,
	varBsSecondaryBg,
	varBsSecondaryBgSubtle,
	varBsSecondaryBorderSubtle,
	varBsSecondaryColor,
	varBsSecondaryRgb,
	varBsSecondaryTextEmphasis,
	varBsSuccess,
	varBsSuccessBgSubtle,
	varBsSuccessBorderSubtle,
	varBsSuccessRgb,
	varBsSuccessTextEmphasis,
	varBsTeal,
	varBsTertiaryBg,
	varBsTertiaryColor,
	varBsWarning,
	varBsWarningBgSubtle,
	varBsWarningBorderSubtle,
	varBsWarningRgb,
	varBsWarningTextEmphasis,
	varBsWhite,
	varBsWhiteRgb,
	varBsYellow,
} from '../../theme-contract/_vars.css'
import {
	varBsFormInvalidBorderColor,
	varBsFormInvalidColor,
	varBsFormValidBorderColor,
	varBsFormValidColor,
} from '../../theme-contract/forms/_vars.css'
import { bodyFrame, bodyText, vars } from '../../theme-contract/theme-contract.css'
import { modalOpenHook } from '../../theme-contract/ui/modal/contract.css'

// Lumen theme scope class.
// Zero-style identifier used as a stable selector prefix.
export const lumenScope = style({})

// Global Bootstrap CSS custom properties (`--bs-*`) are assigned on the
// dedicated vars contract class to keep root var hosting separate from body
// layout/background styles.
globalStyle(`${lumenScope}${vars}`, {
	vars: {
		[varBsBlue]: "#158cba",
		[varBsIndigo]: "#6610f2",
		[varBsPurple]: "#6f42c1",
		[varBsPink]: "#e83e8c",
		[varBsRed]: "#ff4136",
		[varBsOrange]: "#fd7e14",
		[varBsYellow]: "#ff851b",
		[varBsGreen]: "#28b62c",
		[varBsTeal]: "#20c997",
		[varBsCyan]: "#75caeb",
		[varBsBlack]: "#000",
		[varBsWhite]: "#fff",
		[varBsGray]: "#999",
		[varBsGrayDark]: "#333",
		[varBsPrimary]: "#158cba",
		[varBsSecondary]: "#f0f0f0",
		[varBsSuccess]: "#28b62c",
		[varBsInfo]: "#75caeb",
		[varBsWarning]: "#ff851b",
		[varBsDanger]: "#ff4136",
		[varBsLight]: "#f6f6f6",
		[varBsDark]: "#555",
		[varBsPrimaryRgb]: "21, 140, 186",
		[varBsSecondaryRgb]: "240, 240, 240",
		[varBsSuccessRgb]: "40, 182, 44",
		[varBsInfoRgb]: "117, 202, 235",
		[varBsWarningRgb]: "255, 133, 27",
		[varBsDangerRgb]: "255, 65, 54",
		[varBsLightRgb]: "246, 246, 246",
		[varBsDarkRgb]: "85, 85, 85",
		[varBsPrimaryTextEmphasis]: "#08384a",
		[varBsSecondaryTextEmphasis]: "#606060",
		[varBsSuccessTextEmphasis]: "#104912",
		[varBsInfoTextEmphasis]: "#2f515e",
		[varBsWarningTextEmphasis]: "#66350b",
		[varBsDangerTextEmphasis]: "#661a16",
		[varBsLightTextEmphasis]: "#555",
		[varBsDarkTextEmphasis]: "#555",
		[varBsPrimaryBgSubtle]: "#d0e8f1",
		[varBsSecondaryBgSubtle]: "#fcfcfc",
		[varBsSuccessBgSubtle]: "#d4f0d5",
		[varBsInfoBgSubtle]: "#e3f4fb",
		[varBsWarningBgSubtle]: "#ffe7d1",
		[varBsDangerBgSubtle]: "#ffd9d7",
		[varBsLightBgSubtle]: "#fbfbfb",
		[varBsDarkBgSubtle]: "#ced4da",
		[varBsPrimaryBorderSubtle]: "#a1d1e3",
		[varBsSecondaryBorderSubtle]: "#f9f9f9",
		[varBsSuccessBorderSubtle]: "#a9e2ab",
		[varBsInfoBorderSubtle]: "#c8eaf7",
		[varBsWarningBorderSubtle]: "#ffcea4",
		[varBsDangerBorderSubtle]: "#ffb3af",
		[varBsLightBorderSubtle]: "#f0f0f0",
		[varBsDarkBorderSubtle]: "#adb5bd",
		[varBsWhiteRgb]: "255, 255, 255",
		[varBsBlackRgb]: "0, 0, 0",
		[varBsFontSansSerif]: "\"Source Sans Pro\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif, \"Apple Color Emoji\", \"Segoe UI Emoji\", \"Segoe UI Symbol\"",
		[varBsFontMonospace]: "SFMono-Regular, Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace",
		[varBsGradient]: "linear-gradient(180deg, rgba(255, 255, 255, 0.15), rgba(255, 255, 255, 0))",
		[varBsBodyFontFamily]: varBsFontSansSerif,
		[varBsBodyFontSize]: "1rem",
		[varBsBodyFontWeight]: 400,
		[varBsBodyLineHeight]: 1.5,
		[varBsBodyColor]: "#222",
		[varBsBodyColorRgb]: "34, 34, 34",
		[varBsBodyBg]: "#fff",
		[varBsBodyBgRgb]: "255, 255, 255",
		[varBsEmphasisColor]: "#000",
		[varBsEmphasisColorRgb]: "0, 0, 0",
		[varBsSecondaryColor]: "rgba(34, 34, 34, 0.75)",
		[varBsSecondaryBg]: "#f0f0f0",
		[varBsTertiaryColor]: "rgba(34, 34, 34, 0.5)",
		[varBsTertiaryBg]: "#f6f6f6",
		[varBsHeadingColor]: "inherit",
		[varBsLinkColor]: "#158cba",
		[varBsLinkColorRgb]: "21, 140, 186",
		[varBsLinkDecoration]: "underline",
		[varBsLinkHoverColor]: "#117095",
		[varBsLinkHoverColorRgb]: "17, 112, 149",
		[varBsCodeColor]: "#e83e8c",
		[varBsHighlightColor]: "#222",
		[varBsHighlightBg]: "#ffe7d1",
		[varBsBorderWidth]: "1px",
		[varBsBorderStyle]: "solid",
		[varBsBorderColor]: "#dee2e6",
		[varBsBorderColorTranslucent]: "rgba(0, 0, 0, 0.175)",
		[varBsBorderRadius]: "0.375rem",
		[varBsBorderRadiusSm]: "0.25rem",
		[varBsBorderRadiusLg]: "0.5rem",
		[varBsBorderRadiusXl]: "1rem",
		[varBsBorderRadiusXxl]: "2rem",
		[varBsBorderRadiusPill]: "50rem",
		[varBsBoxShadow]: "0 0.5rem 1rem rgba(0, 0, 0, 0.15)",
		[varBsBoxShadowSm]: "0 0.125rem 0.25rem rgba(0, 0, 0, 0.075)",
		[varBsBoxShadowLg]: "0 1rem 3rem rgba(0, 0, 0, 0.175)",
		[varBsBoxShadowInset]: "inset 0 1px 2px rgba(0, 0, 0, 0.075)",
		[varBsFocusRingWidth]: "0.25rem",
		[varBsFocusRingOpacity]: 0.25,
		[varBsFocusRingColor]: "rgba(21, 140, 186, 0.25)",
		[varBsBtnCloseFilter]: "",
		[varBsCarouselIndicatorActiveBg]: "#fff",
		[varBsCarouselCaptionColor]: "#fff",
		[varBsCarouselControlIconFilter]: "",
		[varBsFormValidColor]: "#28b62c",
		[varBsFormValidBorderColor]: "#28b62c",
		[varBsFormInvalidColor]: "#ff4136",
		[varBsFormInvalidBorderColor]: "#ff4136",
	},
})

// ── Root / body styles ────────────────────────────────────────────────────────
// bodyText = typography; bodyFrame = page canvas (Ve2Shell). Do not add padding
// here — baseline screenshots have no padded wrapper around bd-example.

globalStyle(`${lumenScope}${bodyText}`, {
	fontFamily: varBsBodyFontFamily,
	fontSize: varBsBodyFontSize,
	fontWeight: varBsBodyFontWeight,
	lineHeight: varBsBodyLineHeight,
	color: varBsBodyColor,
})

globalStyle(`${lumenScope}${bodyFrame}`, {
	backgroundColor: varBsBodyBg,
	margin: 0,
	minHeight: '100vh',
})

// Bootstrap Modal JS adds modalOpenHook to <body> without theme scope.
globalStyle(`${modalOpenHook}`, {
	fontFamily: varBsBodyFontFamily,
	fontSize: varBsBodyFontSize,
	fontWeight: varBsBodyFontWeight,
	lineHeight: varBsBodyLineHeight,
	color: varBsBodyColor,
	backgroundColor: varBsBodyBg,
	margin: 0,
})
