import { globalStyle, style } from '@vanilla-extract/css'
import {
	varBsBlack,
	varBsBlackRgb,
	varBsBlue,
	varBsBodyBg,
	varBsBodyBgRgb,
	varBsBodyColor,
	varBsBodyColorRgb,
	varBsBodyFontFamily,
	varBsBodyFontSize,
	varBsBodyFontWeight,
	varBsBodyLineHeight,
	varBsBorderColor,
	varBsBorderColorTranslucent,
	varBsBorderRadius,
	varBsBorderRadiusLg,
	varBsBorderRadiusPill,
	varBsBorderRadiusSm,
	varBsBorderRadiusXl,
	varBsBorderRadiusXxl,
	varBsBorderStyle,
	varBsBorderWidth,
	varBsBoxShadow,
	varBsBoxShadowInset,
	varBsBoxShadowLg,
	varBsBoxShadowSm,
	varBsCodeColor,
	varBsCyan,
	varBsDanger,
	varBsDangerBgSubtle,
	varBsDangerBorderSubtle,
	varBsDangerRgb,
	varBsDangerTextEmphasis,
	varBsDark,
	varBsDarkBgSubtle,
	varBsDarkBorderSubtle,
	varBsDarkRgb,
	varBsDarkTextEmphasis,
	varBsEmphasisColor,
	varBsEmphasisColorRgb,
	varBsFocusRingColor,
	varBsFocusRingOpacity,
	varBsFocusRingWidth,
	varBsFontMonospace,
	varBsFontSansSerif,
	varBsGradient,
	varBsGray,
	varBsGrayDark,
	varBsGreen,
	varBsHeadingColor,
	varBsHighlightBg,
	varBsHighlightColor,
	varBsIndigo,
	varBsInfo,
	varBsInfoBgSubtle,
	varBsInfoBorderSubtle,
	varBsInfoRgb,
	varBsInfoTextEmphasis,
	varBsLight,
	varBsLightBgSubtle,
	varBsLightBorderSubtle,
	varBsLightRgb,
	varBsLightTextEmphasis,
	varBsLinkColor,
	varBsLinkColorRgb,
	varBsLinkDecoration,
	varBsLinkHoverColor,
	varBsLinkHoverColorRgb,
	varBsOrange,
	varBsPink,
	varBsPrimary,
	varBsPrimaryBgSubtle,
	varBsPrimaryBorderSubtle,
	varBsPrimaryRgb,
	varBsPrimaryTextEmphasis,
	varBsPurple,
	varBsRed,
	varBsSecondary,
	varBsSecondaryBg,
	varBsSecondaryBgSubtle,
	varBsSecondaryBorderSubtle,
	varBsSecondaryColor,
	varBsSecondaryRgb,
	varBsSecondaryTextEmphasis,
	varBsSuccess,
	varBsSuccessBgSubtle,
	varBsSuccessBorderSubtle,
	varBsSuccessRgb,
	varBsSuccessTextEmphasis,
	varBsTeal,
	varBsTertiaryBg,
	varBsTertiaryColor,
	varBsWarning,
	varBsWarningBgSubtle,
	varBsWarningBorderSubtle,
	varBsWarningRgb,
	varBsWarningTextEmphasis,
	varBsWhite,
	varBsWhiteRgb,
	varBsYellow,
} from '../../theme-contract/_vars.css'
import {
	varBsFormInvalidBorderColor,
	varBsFormInvalidColor,
	varBsFormValidBorderColor,
	varBsFormValidColor,
} from '../../theme-contract/forms/_vars.css'
import { varBsCarouselCaptionColor, varBsCarouselIndicatorActiveBg } from '../../theme-contract/ui/carousel/_vars.css'
import { bodyFrame, bodyText, vars } from '../../theme-contract/theme-contract.css'
import { varBsLinkOpacity } from '../../theme-contract/utilities/generated/_vars.css'
import { modalOpenHook } from '../../theme-contract/ui/modal/contract.css'

// Bootstrap theme scope class.
// Zero-style identifier used as a stable selector prefix.
export const bootstrapScope = style({})

// Global Bootstrap CSS custom properties (`--bs-*`) are assigned on the
// dedicated vars contract class to keep root var hosting separate from body
// layout/background styles.
globalStyle(`${bootstrapScope}${vars}`, {
	vars: {
		[varBsBlue]: "#0d6efd",
		[varBsIndigo]: "#6610f2",
		[varBsPurple]: "#6f42c1",
		[varBsPink]: "#d63384",
		[varBsRed]: "#dc3545",
		[varBsOrange]: "#fd7e14",
		[varBsYellow]: "#ffc107",
		[varBsGreen]: "#198754",
		[varBsTeal]: "#20c997",
		[varBsCyan]: "#0dcaf0",
		[varBsBlack]: "#000",
		[varBsWhite]: "#fff",
		[varBsGray]: "#6c757d",
		[varBsGrayDark]: "#343a40",
		[varBsPrimary]: "#0d6efd",
		[varBsSecondary]: "#6c757d",
		[varBsSuccess]: "#198754",
		[varBsInfo]: "#0dcaf0",
		[varBsWarning]: "#ffc107",
		[varBsDanger]: "#dc3545",
		[varBsLight]: "#f8f9fa",
		[varBsDark]: "#212529",
		[varBsPrimaryRgb]: "13, 110, 253",
		[varBsSecondaryRgb]: "108, 117, 125",
		[varBsSuccessRgb]: "25, 135, 84",
		[varBsInfoRgb]: "13, 202, 240",
		[varBsWarningRgb]: "255, 193, 7",
		[varBsDangerRgb]: "220, 53, 69",
		[varBsLightRgb]: "248, 249, 250",
		[varBsDarkRgb]: "33, 37, 41",
		[varBsPrimaryTextEmphasis]: "#052c65",
		[varBsSecondaryTextEmphasis]: "#2b2f32",
		[varBsSuccessTextEmphasis]: "#0a3622",
		[varBsInfoTextEmphasis]: "#055160",
		[varBsWarningTextEmphasis]: "#664d03",
		[varBsDangerTextEmphasis]: "#58151c",
		[varBsLightTextEmphasis]: "#495057",
		[varBsDarkTextEmphasis]: "#495057",
		[varBsPrimaryBgSubtle]: "#cfe2ff",
		[varBsSecondaryBgSubtle]: "#e2e3e5",
		[varBsSuccessBgSubtle]: "#d1e7dd",
		[varBsInfoBgSubtle]: "#cff4fc",
		[varBsWarningBgSubtle]: "#fff3cd",
		[varBsDangerBgSubtle]: "#f8d7da",
		[varBsLightBgSubtle]: "#fcfcfd",
		[varBsDarkBgSubtle]: "#ced4da",
		[varBsPrimaryBorderSubtle]: "#9ec5fe",
		[varBsSecondaryBorderSubtle]: "#c4c8cb",
		[varBsSuccessBorderSubtle]: "#a3cfbb",
		[varBsInfoBorderSubtle]: "#9eeaf9",
		[varBsWarningBorderSubtle]: "#ffe69c",
		[varBsDangerBorderSubtle]: "#f1aeb5",
		[varBsLightBorderSubtle]: "#e9ecef",
		[varBsDarkBorderSubtle]: "#adb5bd",
		[varBsWhiteRgb]: "255, 255, 255",
		[varBsBlackRgb]: "0, 0, 0",
		[varBsFontSansSerif]: "system-ui, -apple-system, \"Segoe UI\", Roboto, \"Helvetica Neue\", \"Noto Sans\", \"Liberation Sans\", Arial, sans-serif, \"Apple Color Emoji\", \"Segoe UI Emoji\", \"Segoe UI Symbol\", \"Noto Color Emoji\"",
		[varBsFontMonospace]: "SFMono-Regular, Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace",
		[varBsGradient]: "linear-gradient(180deg, rgba(255, 255, 255, 0.15), rgba(255, 255, 255, 0))",
		[varBsBodyFontFamily]: varBsFontSansSerif,
		[varBsBodyFontSize]: "1rem",
		[varBsBodyFontWeight]: 400,
		[varBsBodyLineHeight]: 1.5,
		[varBsBodyColor]: "#212529",
		[varBsBodyColorRgb]: "33, 37, 41",
		[varBsBodyBg]: "#fff",
		[varBsBodyBgRgb]: "255, 255, 255",
		[varBsEmphasisColor]: "#000",
		[varBsEmphasisColorRgb]: "0, 0, 0",
		[varBsSecondaryColor]: "rgba(33, 37, 41, 0.75)",
		[varBsSecondaryBg]: "#e9ecef",
		[varBsTertiaryColor]: "rgba(33, 37, 41, 0.5)",
		[varBsTertiaryBg]: "#f8f9fa",
		[varBsHeadingColor]: "inherit",
		[varBsLinkColor]: "#0d6efd",
		[varBsLinkColorRgb]: "13, 110, 253",
		[varBsLinkDecoration]: "underline",
		[varBsLinkHoverColor]: "#0a58ca",
		[varBsLinkHoverColorRgb]: "10, 88, 202",
		[varBsLinkOpacity]: '1',
		[varBsCodeColor]: "#d63384",
		[varBsHighlightColor]: "#212529",
		[varBsHighlightBg]: "#fff3cd",
		[varBsBorderWidth]: "1px",
		[varBsBorderStyle]: "solid",
		[varBsBorderColor]: "#dee2e6",
		[varBsBorderColorTranslucent]: "rgba(0, 0, 0, 0.175)",
		[varBsBorderRadius]: "0.375rem",
		[varBsBorderRadiusSm]: "0.25rem",
		[varBsBorderRadiusLg]: "0.5rem",
		[varBsBorderRadiusXl]: "1rem",
		[varBsBorderRadiusXxl]: "2rem",
		[varBsBorderRadiusPill]: "50rem",
		[varBsBoxShadow]: "0 0.5rem 1rem rgba(0, 0, 0, 0.15)",
		[varBsBoxShadowSm]: "0 0.125rem 0.25rem rgba(0, 0, 0, 0.075)",
		[varBsBoxShadowLg]: "0 1rem 3rem rgba(0, 0, 0, 0.175)",
		[varBsBoxShadowInset]: "inset 0 1px 2px rgba(0, 0, 0, 0.075)",
		[varBsFocusRingWidth]: "0.25rem",
		[varBsFocusRingOpacity]: 0.25,
		[varBsFocusRingColor]: "rgba(13, 110, 253, 0.25)",
		[varBsCarouselIndicatorActiveBg]: "#fff",
		[varBsCarouselCaptionColor]: "#fff",
		[varBsFormValidColor]: '#198754',
		[varBsFormValidBorderColor]: '#198754',
		[varBsFormInvalidColor]: '#dc3545',
		[varBsFormInvalidBorderColor]: '#dc3545',
	},
})

// ── Root / body styles ────────────────────────────────────────────────────────
// bodyText = typography; bodyFrame = page canvas (Ve2Shell). Do not add padding
// here — baseline screenshots have no padded wrapper around bd-example.

globalStyle(`${bootstrapScope}${bodyText}`, {
	fontFamily: varBsBodyFontFamily,
	fontSize: varBsBodyFontSize,
	fontWeight: varBsBodyFontWeight,
	lineHeight: varBsBodyLineHeight,
	color: varBsBodyColor,
})

globalStyle(`${bootstrapScope}${bodyFrame}`, {
	backgroundColor: varBsBodyBg,
	margin: 0,
})

globalStyle(`${modalOpenHook}`, {
	fontFamily: varBsBodyFontFamily,
	fontSize: varBsBodyFontSize,
	fontWeight: varBsBodyFontWeight,
	lineHeight: varBsBodyLineHeight,
	color: varBsBodyColor,
	backgroundColor: varBsBodyBg,
	margin: 0,
})
