import { createVar } from '@vanilla-extract/css'

export const varBsPaginationPaddingX = createVar()
export const varBsPaginationPaddingY = createVar()
export const varBsPaginationFontSize = createVar()
export const varBsPaginationColor = createVar()
export const varBsPaginationBg = createVar()
export const varBsPaginationBorderWidth = createVar()
export const varBsPaginationBorderColor = createVar()
export const varBsPaginationBorderRadius = createVar()
export const varBsPaginationHoverColor = createVar()
export const varBsPaginationHoverBg = createVar()
export const varBsPaginationHoverBorderColor = createVar()
export const varBsPaginationFocusColor = createVar()
export const varBsPaginationFocusBg = createVar()
export const varBsPaginationFocusBoxShadow = createVar()
export const varBsPaginationActiveColor = createVar()
export const varBsPaginationActiveBg = createVar()
export const varBsPaginationActiveBorderColor = createVar()
export const varBsPaginationDisabledColor = createVar()
export const varBsPaginationDisabledBg = createVar()
export const varBsPaginationDisabledBorderColor = createVar()
