// GERADO por scripts/gen-public-vars.mjs — NÃO editar à mão.
import { globalStyle } from '@vanilla-extract/css'
import { materiaScope } from './scope.css'
import { varBsBlackRgb, varBsBodyBgRgb, varBsBodyColorRgb, varBsBorderColor, varBsBorderRadius, varBsBorderRadiusLg, varBsBorderRadiusPill, varBsBorderRadiusSm, varBsBorderRadiusXl, varBsBorderRadiusXxl, varBsBorderStyle, varBsBorderWidth, varBsBoxShadow, varBsBoxShadowLg, varBsBoxShadowSm, varBsDangerBgSubtle, varBsDangerBorderSubtle, varBsDangerRgb, varBsDangerTextEmphasis, varBsDarkBgSubtle, varBsDarkBorderSubtle, varBsDarkRgb, varBsDarkTextEmphasis, varBsEmphasisColor, varBsEmphasisColorRgb, varBsFocusRingColor, varBsFocusRingOpacity, varBsFontMonospace, varBsGradient, varBsInfoBgSubtle, varBsInfoBorderSubtle, varBsInfoRgb, varBsInfoTextEmphasis, varBsLightBgSubtle, varBsLightBorderSubtle, varBsLightRgb, varBsLightTextEmphasis, varBsLinkColorRgb, varBsPrimaryBgSubtle, varBsPrimaryBorderSubtle, varBsPrimaryRgb, varBsPrimaryTextEmphasis, varBsSecondaryBgRgb, varBsSecondaryBgSubtle, varBsSecondaryBorderSubtle, varBsSecondaryColor, varBsSecondaryRgb, varBsSecondaryTextEmphasis, varBsSuccessBgSubtle, varBsSuccessBorderSubtle, varBsSuccessRgb, varBsSuccessTextEmphasis, varBsTertiaryBgRgb, varBsTertiaryColor, varBsWarningBgSubtle, varBsWarningBorderSubtle, varBsWarningRgb, varBsWarningTextEmphasis, varBsWhiteRgb } from '../../theme-contract/_public-vars.css'

globalStyle(materiaScope, {
	vars: {
		[varBsBlackRgb]: "0, 0, 0",
		[varBsBodyBgRgb]: "255, 255, 255",
		[varBsBodyColorRgb]: "68, 68, 68",
		[varBsBorderColor]: "#dee2e6",
		[varBsBorderRadius]: "0.375rem",
		[varBsBorderRadiusLg]: "0.5rem",
		[varBsBorderRadiusPill]: "50rem",
		[varBsBorderRadiusSm]: "0.25rem",
		[varBsBorderRadiusXl]: "1rem",
		[varBsBorderRadiusXxl]: "2rem",
		[varBsBorderStyle]: "solid",
		[varBsBorderWidth]: "1px",
		[varBsBoxShadow]: "0 0.5rem 1rem rgba(0, 0, 0, 0.15)",
		[varBsBoxShadowLg]: "0 1rem 3rem rgba(0, 0, 0, 0.175)",
		[varBsBoxShadowSm]: "0 0.125rem 0.25rem rgba(0, 0, 0, 0.075)",
		[varBsDangerBgSubtle]: "#fad2d3",
		[varBsDangerBorderSubtle]: "#f5a4a7",
		[varBsDangerRgb]: "229, 28, 35",
		[varBsDangerTextEmphasis]: "#5c0b0e",
		[varBsDarkBgSubtle]: "#ced4da",
		[varBsDarkBorderSubtle]: "#bbb",
		[varBsDarkRgb]: "34, 34, 34",
		[varBsDarkTextEmphasis]: "#444",
		[varBsEmphasisColor]: "#000",
		[varBsEmphasisColorRgb]: "0, 0, 0",
		[varBsFocusRingColor]: "rgba(33, 150, 243, 0.25)",
		[varBsFocusRingOpacity]: "0.25",
		[varBsFontMonospace]: "SFMono-Regular, Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace",
		[varBsGradient]: "linear-gradient(180deg, rgba(255, 255, 255, 0.15), rgba(255, 255, 255, 0))",
		[varBsInfoBgSubtle]: "#ebd4ef",
		[varBsInfoBorderSubtle]: "#d7a9df",
		[varBsInfoRgb]: "156, 39, 176",
		[varBsInfoTextEmphasis]: "#3e1046",
		[varBsLightBgSubtle]: "#fcfcfd",
		[varBsLightBorderSubtle]: "#eee",
		[varBsLightRgb]: "248, 249, 250",
		[varBsLightTextEmphasis]: "#444",
		[varBsLinkColorRgb]: "33, 150, 243",
		[varBsPrimaryBgSubtle]: "#d3eafd",
		[varBsPrimaryBorderSubtle]: "#a6d5fa",
		[varBsPrimaryRgb]: "33, 150, 243",
		[varBsPrimaryTextEmphasis]: "#0d3c61",
		[varBsSecondaryBgRgb]: "238, 238, 238",
		[varBsSecondaryBgSubtle]: "white",
		[varBsSecondaryBorderSubtle]: "white",
		[varBsSecondaryColor]: "rgba(68, 68, 68, 0.75)",
		[varBsSecondaryRgb]: "255, 255, 255",
		[varBsSecondaryTextEmphasis]: "#666666",
		[varBsSuccessBgSubtle]: "#dbefdc",
		[varBsSuccessBorderSubtle]: "#b7dfb9",
		[varBsSuccessRgb]: "76, 175, 80",
		[varBsSuccessTextEmphasis]: "#1e4620",
		[varBsTertiaryBgRgb]: "248, 249, 250",
		[varBsTertiaryColor]: "rgba(68, 68, 68, 0.5)",
		[varBsWarningBgSubtle]: "#ffeacc",
		[varBsWarningBorderSubtle]: "#ffd699",
		[varBsWarningRgb]: "255, 152, 0",
		[varBsWarningTextEmphasis]: "#663d00",
		[varBsWhiteRgb]: "255, 255, 255",
	},
})
