import { globalStyle, style } from '@vanilla-extract/css'
import {
varBsBodyBg,
varBsBodyBgRgb,
varBsBodyColor,
varBsBodyColorRgb,
varBsBodyFontFamily,
varBsFontSansSerif,
varBsBorderColor,
varBsBorderColorTranslucent,
varBsBorderRadius,
varBsBorderRadius2xl,
varBsBorderRadiusLg,
varBsBorderRadiusPill,
varBsBorderRadiusSm,
varBsBorderRadiusXl,
varBsBorderRadiusXxl,
varBsBorderStyle,
varBsBorderWidth,
varBsBoxShadow,
varBsBoxShadowInset,
varBsBoxShadowLg,
varBsBoxShadowSm,
varBsDanger,
varBsDangerBgSubtle,
varBsDangerBorderSubtle,
varBsDangerRgb,
varBsDangerTextEmphasis,
varBsDark,
varBsDarkBgSubtle,
varBsDarkBorderSubtle,
varBsDarkRgb,
varBsDarkTextEmphasis,
varBsFocusRingColor,
varBsFocusRingOpacity,
varBsFocusRingWidth,
varBsInfo,
varBsInfoBgSubtle,
varBsInfoBorderSubtle,
varBsInfoRgb,
varBsInfoTextEmphasis,
varBsLight,
varBsLightBgSubtle,
varBsLightBorderSubtle,
varBsLightRgb,
varBsLightTextEmphasis,
varBsPrimary,
varBsPrimaryBgSubtle,
varBsPrimaryBorderSubtle,
varBsPrimaryRgb,
varBsPrimaryTextEmphasis,
varBsSecondary,
varBsSecondaryBgSubtle,
varBsSecondaryBorderSubtle,
varBsSecondaryRgb,
varBsSecondaryTextEmphasis,
varBsSuccess,
varBsSuccessBgSubtle,
varBsSuccessBorderSubtle,
varBsSuccessRgb,
varBsSuccessTextEmphasis,
varBsWarning,
varBsWarningBgSubtle,
varBsWarningBorderSubtle,
varBsWarningRgb,
varBsWarningTextEmphasis,
varBsEmphasisColor,
varBsEmphasisColorRgb,
varBsSecondaryColor,
varBsSecondaryBg,
varBsTertiaryColor,
varBsTertiaryBg,
varBsHighlightColor,
varBsHighlightBg,
varBsLinkColor,
varBsLinkHoverColor,
varBsCodeColor,
varBsFontMonospace,
varBsGradient,
} from '../../theme-contract/_vars.css'
import {
varBsFormValidColor,
varBsFormValidBorderColor,
varBsFormInvalidColor,
varBsFormInvalidBorderColor,
} from '../../theme-contract/forms/_vars.css'
import { body, bodyText, bodyFrame, vars } from '../../theme-contract/theme-contract.css'

export const materiaScope = style({ letterSpacing: '0.1px' })

globalStyle(`${materiaScope}${vars}`, {
vars: {
[varBsPrimary]: '#2196f3',
[varBsSecondary]: '#fff',
[varBsSuccess]: '#4caf50',
[varBsInfo]: '#9c27b0',
[varBsWarning]: '#ff9800',
[varBsDanger]: '#e51c23',
[varBsLight]: '#f8f9fa',
[varBsDark]: '#222',
[varBsPrimaryRgb]: '33, 150, 243',
[varBsSecondaryRgb]: '255, 255, 255',
[varBsSuccessRgb]: '76, 175, 80',
[varBsInfoRgb]: '156, 39, 176',
[varBsWarningRgb]: '255, 152, 0',
[varBsDangerRgb]: '229, 28, 35',
[varBsLightRgb]: '248, 249, 250',
[varBsDarkRgb]: '34, 34, 34',
[varBsPrimaryTextEmphasis]: '#0d3c61',
[varBsSecondaryTextEmphasis]: '#666666',
[varBsSuccessTextEmphasis]: '#1e4620',
[varBsInfoTextEmphasis]: '#3e1046',
[varBsWarningTextEmphasis]: '#663d00',
[varBsDangerTextEmphasis]: '#5c0b0e',
[varBsLightTextEmphasis]: '#444',
[varBsDarkTextEmphasis]: '#444',
[varBsPrimaryBgSubtle]: '#d3eafd',
[varBsSecondaryBgSubtle]: '#ffffff',
[varBsSuccessBgSubtle]: '#dbefdc',
[varBsInfoBgSubtle]: '#ebd4ef',
[varBsWarningBgSubtle]: '#ffeacc',
[varBsDangerBgSubtle]: '#fad2d3',
[varBsLightBgSubtle]: '#fcfcfd',
[varBsDarkBgSubtle]: '#ced4da',
[varBsPrimaryBorderSubtle]: '#a6d5fa',
[varBsSecondaryBorderSubtle]: '#ffffff',
[varBsSuccessBorderSubtle]: '#b7dfb9',
[varBsInfoBorderSubtle]: '#d7a9df',
[varBsWarningBorderSubtle]: '#ffd699',
[varBsDangerBorderSubtle]: '#f5a4a7',
[varBsLightBorderSubtle]: '#eee',
[varBsDarkBorderSubtle]: '#bbb',
[varBsFontSansSerif]: 'Roboto, -apple-system, BlinkMacSystemFont, "Segoe UI", "Helvetica Neue", Arial, sans-serif',
[varBsBodyFontFamily]: varBsFontSansSerif,
[varBsBodyColor]: '#444',
[varBsBodyColorRgb]: '68, 68, 68',
[varBsBodyBg]: '#fff',
[varBsBodyBgRgb]: '255, 255, 255',
[varBsBorderWidth]: '1px',
[varBsBorderStyle]: 'solid',
[varBsBorderColor]: '#dee2e6',
[varBsBorderColorTranslucent]: 'rgba(0, 0, 0, 0.175)',
[varBsBorderRadius]: '0.375rem',
[varBsBorderRadiusSm]: '0.25rem',
[varBsBorderRadiusLg]: '0.5rem',
[varBsBorderRadiusXl]: '1rem',
[varBsBorderRadiusXxl]: '2rem',
[varBsBorderRadius2xl]: varBsBorderRadiusXxl,
[varBsBorderRadiusPill]: '50rem',
[varBsBoxShadow]: '0 0.5rem 1rem rgba(0, 0, 0, 0.15)',
[varBsBoxShadowSm]: '0 0.125rem 0.25rem rgba(0, 0, 0, 0.075)',
[varBsBoxShadowLg]: '0 1rem 3rem rgba(0, 0, 0, 0.175)',
[varBsBoxShadowInset]: 'inset 0 1px 2px rgba(0, 0, 0, 0.075)',
[varBsFocusRingWidth]: '0.25rem',
[varBsFocusRingOpacity]: '0.25',
[varBsFocusRingColor]: 'rgba(33, 150, 243, 0.25)',
[varBsEmphasisColor]: '#000',
[varBsEmphasisColorRgb]: '0, 0, 0',
[varBsSecondaryColor]: 'rgba(68, 68, 68, 0.75)',
[varBsSecondaryBg]: '#eee',
[varBsTertiaryColor]: 'rgba(68, 68, 68, 0.5)',
[varBsTertiaryBg]: '#f8f9fa',
[varBsHighlightColor]: '#444',
[varBsHighlightBg]: '#ffeacc',
[varBsLinkColor]: '#2196f3',
[varBsLinkHoverColor]: '#1a78c2',
[varBsCodeColor]: '#e83e8c',
[varBsFontMonospace]: 'SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
[varBsGradient]: 'linear-gradient(180deg, rgba(255, 255, 255, 0.15), rgba(255, 255, 255, 0))',
[varBsFormValidColor]: '#4caf50',
[varBsFormValidBorderColor]: '#4caf50',
[varBsFormInvalidColor]: '#e51c23',
[varBsFormInvalidBorderColor]: '#e51c23',
},
})

globalStyle(`${materiaScope}${bodyText}`, {
fontFamily: 'Roboto, -apple-system, BlinkMacSystemFont, "Segoe UI", "Helvetica Neue", Arial, sans-serif',
fontSize: '1rem',
fontWeight: 400,
lineHeight: 1.5,
color: '#444',
letterSpacing: '0.1px',
})

globalStyle(`${materiaScope}${body}`, {
backgroundColor: '#fff',
padding: '1rem',
display: 'block',
})

globalStyle(`${materiaScope}${bodyFrame}`, {
minHeight: '100vh',
display: 'flow-root',
backgroundColor: '#fff',
})
