import { globalStyle, style } from '@vanilla-extract/css'
import {
	varBsBlack,
	varBsBlackRgb,
	varBsBlue,
	varBsBodyBg,
	varBsBodyBgRgb,
	varBsBodyColor,
	varBsBodyColorRgb,
	varBsBodyFontFamily,
	varBsBodyFontSize,
	varBsBodyFontWeight,
	varBsBodyLineHeight,
	varBsBorderColor,
	varBsBorderColorTranslucent,
	varBsBorderRadius,
	varBsBorderRadiusLg,
	varBsBorderRadiusPill,
	varBsBorderRadiusSm,
	varBsBorderRadiusXl,
	varBsBorderRadiusXxl,
	varBsBorderStyle,
	varBsBorderWidth,
	varBsBoxShadow,
	varBsBoxShadowInset,
	varBsBoxShadowLg,
	varBsBoxShadowSm,
	varBsCarouselCaptionColor,
	varBsCarouselIndicatorActiveBg,
	varBsCodeColor,
	varBsCyan,
	varBsDanger,
	varBsDangerBgSubtle,
	varBsDangerBorderSubtle,
	varBsDangerRgb,
	varBsDangerTextEmphasis,
	varBsDark,
	varBsDarkBgSubtle,
	varBsDarkBorderSubtle,
	varBsDarkRgb,
	varBsDarkTextEmphasis,
	varBsEmphasisColor,
	varBsEmphasisColorRgb,
	varBsFocusRingColor,
	varBsFocusRingOpacity,
	varBsFocusRingWidth,
	varBsFontMonospace,
	varBsFontSansSerif,
	varBsGradient,
	varBsGray,
	varBsGrayDark,
	varBsGreen,
	varBsHeadingColor,
	varBsHighlightBg,
	varBsHighlightColor,
	varBsIndigo,
	varBsInfo,
	varBsInfoBgSubtle,
	varBsInfoBorderSubtle,
	varBsInfoRgb,
	varBsInfoTextEmphasis,
	varBsLight,
	varBsLightBgSubtle,
	varBsLightBorderSubtle,
	varBsLightRgb,
	varBsLightTextEmphasis,
	varBsLinkColor,
	varBsLinkColorRgb,
	varBsLinkDecoration,
	varBsLinkHoverColor,
	varBsLinkHoverColorRgb,
	varBsOrange,
	varBsPink,
	varBsPrimary,
	varBsPrimaryBgSubtle,
	varBsPrimaryBorderSubtle,
	varBsPrimaryRgb,
	varBsPrimaryTextEmphasis,
	varBsPurple,
	varBsRed,
	varBsSecondary,
	varBsSecondaryBg,
	varBsSecondaryBgSubtle,
	varBsSecondaryBorderSubtle,
	varBsSecondaryColor,
	varBsSecondaryRgb,
	varBsSecondaryTextEmphasis,
	varBsSuccess,
	varBsSuccessBgSubtle,
	varBsSuccessBorderSubtle,
	varBsSuccessRgb,
	varBsSuccessTextEmphasis,
	varBsTeal,
	varBsTertiaryBg,
	varBsTertiaryColor,
	varBsWarning,
	varBsWarningBgSubtle,
	varBsWarningBorderSubtle,
	varBsWarningRgb,
	varBsWarningTextEmphasis,
	varBsWhite,
	varBsWhiteRgb,
	varBsYellow,
} from '../../theme-contract/_vars.css'
import {
	varBsFormInvalidBorderColor,
	varBsFormInvalidColor,
	varBsFormValidBorderColor,
	varBsFormValidColor,
} from '../../theme-contract/forms/_vars.css'
import { body, bodyText, vars } from '../../theme-contract/theme-contract.css'

// Materia theme scope class.
// Zero-style identifier used as a stable selector prefix.
export const materiaScope = style({})

// Global Bootstrap CSS custom properties (`--bs-*`) are assigned on the
// dedicated vars contract class to keep root var hosting separate from body
// layout/background styles.
globalStyle(`${materiaScope}${vars}`, {
	vars: {
		[varBsBlue]: "#2196f3",
		[varBsIndigo]: "#6610f2",
		[varBsPurple]: "#6f42c1",
		[varBsPink]: "#e83e8c",
		[varBsRed]: "#e51c23",
		[varBsOrange]: "#fd7e14",
		[varBsYellow]: "#ff9800",
		[varBsGreen]: "#4caf50",
		[varBsTeal]: "#20c997",
		[varBsCyan]: "#9c27b0",
		[varBsBlack]: "#000",
		[varBsWhite]: "#fff",
		[varBsGray]: "#666",
		[varBsGrayDark]: "#222",
		[varBsPrimary]: "#2196f3",
		[varBsSecondary]: "#fff",
		[varBsSuccess]: "#4caf50",
		[varBsInfo]: "#9c27b0",
		[varBsWarning]: "#ff9800",
		[varBsDanger]: "#e51c23",
		[varBsLight]: "#f8f9fa",
		[varBsDark]: "#222",
		[varBsPrimaryRgb]: "33, 150, 243",
		[varBsSecondaryRgb]: "255, 255, 255",
		[varBsSuccessRgb]: "76, 175, 80",
		[varBsInfoRgb]: "156, 39, 176",
		[varBsWarningRgb]: "255, 152, 0",
		[varBsDangerRgb]: "229, 28, 35",
		[varBsLightRgb]: "248, 249, 250",
		[varBsDarkRgb]: "34, 34, 34",
		[varBsPrimaryTextEmphasis]: "#0d3c61",
		[varBsSecondaryTextEmphasis]: "#666666",
		[varBsSuccessTextEmphasis]: "#1e4620",
		[varBsInfoTextEmphasis]: "#3e1046",
		[varBsWarningTextEmphasis]: "#663d00",
		[varBsDangerTextEmphasis]: "#5c0b0e",
		[varBsLightTextEmphasis]: "#444",
		[varBsDarkTextEmphasis]: "#444",
		[varBsPrimaryBgSubtle]: "#d3eafd",
		[varBsSecondaryBgSubtle]: "white",
		[varBsSuccessBgSubtle]: "#dbefdc",
		[varBsInfoBgSubtle]: "#ebd4ef",
		[varBsWarningBgSubtle]: "#ffeacc",
		[varBsDangerBgSubtle]: "#fad2d3",
		[varBsLightBgSubtle]: "#fcfcfd",
		[varBsDarkBgSubtle]: "#ced4da",
		[varBsPrimaryBorderSubtle]: "#a6d5fa",
		[varBsSecondaryBorderSubtle]: "white",
		[varBsSuccessBorderSubtle]: "#b7dfb9",
		[varBsInfoBorderSubtle]: "#d7a9df",
		[varBsWarningBorderSubtle]: "#ffd699",
		[varBsDangerBorderSubtle]: "#f5a4a7",
		[varBsLightBorderSubtle]: "#eee",
		[varBsDarkBorderSubtle]: "#bbb",
		[varBsWhiteRgb]: "255, 255, 255",
		[varBsBlackRgb]: "0, 0, 0",
		[varBsFontSansSerif]: "Roboto, -apple-system, BlinkMacSystemFont, \"Segoe UI\", \"Helvetica Neue\", Arial, sans-serif",
		[varBsFontMonospace]: "SFMono-Regular, Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace",
		[varBsGradient]: "linear-gradient(180deg, rgba(255, 255, 255, 0.15), rgba(255, 255, 255, 0))",
		[varBsBodyFontFamily]: varBsFontSansSerif,
		[varBsBodyFontSize]: "1rem",
		[varBsBodyFontWeight]: 400,
		[varBsBodyLineHeight]: 1.5,
		[varBsBodyColor]: "#444",
		[varBsBodyColorRgb]: "68, 68, 68",
		[varBsBodyBg]: "#fff",
		[varBsBodyBgRgb]: "255, 255, 255",
		[varBsEmphasisColor]: "#000",
		[varBsEmphasisColorRgb]: "0, 0, 0",
		[varBsSecondaryColor]: "rgba(68, 68, 68, 0.75)",
		[varBsSecondaryBg]: "#eee",
		[varBsTertiaryColor]: "rgba(68, 68, 68, 0.5)",
		[varBsTertiaryBg]: "#f8f9fa",
		[varBsHeadingColor]: "inherit",
		[varBsLinkColor]: "#2196f3",
		[varBsLinkColorRgb]: "33, 150, 243",
		[varBsLinkDecoration]: "underline",
		[varBsLinkHoverColor]: "#1a78c2",
		[varBsLinkHoverColorRgb]: "26, 120, 194",
		[varBsCodeColor]: "#e83e8c",
		[varBsHighlightColor]: "#444",
		[varBsHighlightBg]: "#ffeacc",
		[varBsBorderWidth]: "1px",
		[varBsBorderStyle]: "solid",
		[varBsBorderColor]: "#dee2e6",
		[varBsBorderColorTranslucent]: "rgba(0, 0, 0, 0.175)",
		[varBsBorderRadius]: "0.375rem",
		[varBsBorderRadiusSm]: "0.25rem",
		[varBsBorderRadiusLg]: "0.5rem",
		[varBsBorderRadiusXl]: "1rem",
		[varBsBorderRadiusXxl]: "2rem",
		[varBsBorderRadiusPill]: "50rem",
		[varBsBoxShadow]: "0 0.5rem 1rem rgba(0, 0, 0, 0.15)",
		[varBsBoxShadowSm]: "0 0.125rem 0.25rem rgba(0, 0, 0, 0.075)",
		[varBsBoxShadowLg]: "0 1rem 3rem rgba(0, 0, 0, 0.175)",
		[varBsBoxShadowInset]: "inset 0 1px 2px rgba(0, 0, 0, 0.075)",
		[varBsFocusRingWidth]: "0.25rem",
		[varBsFocusRingOpacity]: 0.25,
		[varBsFocusRingColor]: "rgba(33, 150, 243, 0.25)",
		[varBsCarouselIndicatorActiveBg]: "#fff",
		[varBsCarouselCaptionColor]: "#fff",
	},
})

// ── Root / body styles ────────────────────────────────────────────────────────

globalStyle(`${materiaScope}${bodyText}`, {
	fontFamily: varBsBodyFontFamily,
	fontSize: varBsBodyFontSize,
	fontWeight: varBsBodyFontWeight,
	lineHeight: varBsBodyLineHeight,
	color: varBsBodyColor,
})

globalStyle(`${materiaScope}${body}`, {
	backgroundColor: varBsBodyBg,
	padding: '1rem',
	display: 'block',
})
