// GERADO por scripts/gen-public-vars.mjs — NÃO editar à mão.
import { globalStyle } from '@vanilla-extract/css'
import { spacelabScope } from './scope.css'
import { varBsBlackRgb, varBsBodyBgRgb, varBsBodyColorRgb, varBsBorderColor, varBsBorderRadius, varBsBorderRadiusLg, varBsBorderRadiusPill, varBsBorderRadiusSm, varBsBorderRadiusXl, varBsBorderRadiusXxl, varBsBorderStyle, varBsBorderWidth, varBsBoxShadow, varBsBoxShadowLg, varBsBoxShadowSm, varBsDangerBgSubtle, varBsDangerBorderSubtle, varBsDangerRgb, varBsDangerTextEmphasis, varBsDarkBgSubtle, varBsDarkBorderSubtle, varBsDarkRgb, varBsDarkTextEmphasis, varBsEmphasisColor, varBsEmphasisColorRgb, varBsFocusRingColor, varBsFocusRingOpacity, varBsFontMonospace, varBsGradient, varBsInfoBgSubtle, varBsInfoBorderSubtle, varBsInfoRgb, varBsInfoTextEmphasis, varBsLightBgSubtle, varBsLightBorderSubtle, varBsLightRgb, varBsLightTextEmphasis, varBsLinkColorRgb, varBsPrimaryBgSubtle, varBsPrimaryBorderSubtle, varBsPrimaryRgb, varBsPrimaryTextEmphasis, varBsSecondaryBgRgb, varBsSecondaryBgSubtle, varBsSecondaryBorderSubtle, varBsSecondaryColor, varBsSecondaryRgb, varBsSecondaryTextEmphasis, varBsSuccessBgSubtle, varBsSuccessBorderSubtle, varBsSuccessRgb, varBsSuccessTextEmphasis, varBsTertiaryBgRgb, varBsTertiaryColor, varBsWarningBgSubtle, varBsWarningBorderSubtle, varBsWarningRgb, varBsWarningTextEmphasis, varBsWhiteRgb } from '../../theme-contract/_public-vars.css'

globalStyle(spacelabScope, {
	vars: {
		[varBsBlackRgb]: "0, 0, 0",
		[varBsBodyBgRgb]: "255, 255, 255",
		[varBsBodyColorRgb]: "119, 119, 119",
		[varBsBorderColor]: "#dee2e6",
		[varBsBorderRadius]: "0.375rem",
		[varBsBorderRadiusLg]: "0.5rem",
		[varBsBorderRadiusPill]: "50rem",
		[varBsBorderRadiusSm]: "0.25rem",
		[varBsBorderRadiusXl]: "1rem",
		[varBsBorderRadiusXxl]: "2rem",
		[varBsBorderStyle]: "solid",
		[varBsBorderWidth]: "1px",
		[varBsBoxShadow]: "0 0.5rem 1rem rgba(0, 0, 0, 0.15)",
		[varBsBoxShadowLg]: "0 1rem 3rem rgba(0, 0, 0, 0.175)",
		[varBsBoxShadowSm]: "0 0.125rem 0.25rem rgba(0, 0, 0, 0.075)",
		[varBsDangerBgSubtle]: "#f5cccc",
		[varBsDangerBorderSubtle]: "#eb9a99",
		[varBsDangerRgb]: "205, 2, 0",
		[varBsDangerTextEmphasis]: "#520100",
		[varBsDarkBgSubtle]: "#ced4da",
		[varBsDarkBorderSubtle]: "#999",
		[varBsDarkRgb]: "51, 51, 51",
		[varBsDarkTextEmphasis]: "#495057",
		[varBsEmphasisColor]: "#000",
		[varBsEmphasisColorRgb]: "0, 0, 0",
		[varBsFocusRingColor]: "rgba(68, 110, 155, 0.25)",
		[varBsFocusRingOpacity]: "0.25",
		[varBsFontMonospace]: "SFMono-Regular, Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace",
		[varBsGradient]: "linear-gradient(180deg, rgba(255, 255, 255, 0.15), rgba(255, 255, 255, 0))",
		[varBsInfoBgSubtle]: "#d6ebfd",
		[varBsInfoBorderSubtle]: "#add6fa",
		[varBsInfoRgb]: "51, 153, 243",
		[varBsInfoTextEmphasis]: "#143d61",
		[varBsLightBgSubtle]: "#fcfcfd",
		[varBsLightBorderSubtle]: "#eee",
		[varBsLightRgb]: "238, 238, 238",
		[varBsLightTextEmphasis]: "#495057",
		[varBsLinkColorRgb]: "51, 153, 243",
		[varBsPrimaryBgSubtle]: "#dae2eb",
		[varBsPrimaryBorderSubtle]: "#b4c5d7",
		[varBsPrimaryRgb]: "68, 110, 155",
		[varBsPrimaryTextEmphasis]: "#1b2c3e",
		[varBsSecondaryBgRgb]: "238, 238, 238",
		[varBsSecondaryBgSubtle]: "#ebebeb",
		[varBsSecondaryBorderSubtle]: "#d6d6d6",
		[varBsSecondaryColor]: "rgba(119, 119, 119, 0.75)",
		[varBsSecondaryRgb]: "153, 153, 153",
		[varBsSecondaryTextEmphasis]: "#3d3d3d",
		[varBsSuccessBgSubtle]: "#d8f0d3",
		[varBsSuccessBorderSubtle]: "#b1e1a6",
		[varBsSuccessRgb]: "60, 181, 33",
		[varBsSuccessTextEmphasis]: "#18480d",
		[varBsTertiaryBgRgb]: "248, 249, 250",
		[varBsTertiaryColor]: "rgba(119, 119, 119, 0.5)",
		[varBsWarningBgSubtle]: "#f6e3cc",
		[varBsWarningBorderSubtle]: "#eec899",
		[varBsWarningRgb]: "212, 117, 0",
		[varBsWarningTextEmphasis]: "#552f00",
		[varBsWhiteRgb]: "255, 255, 255",
	},
})
