import { globalStyle, style } from '@vanilla-extract/css'
import {
	varBsBlack,
	varBsBlackRgb,
	varBsBlue,
	varBsBodyBg,
	varBsBodyBgRgb,
	varBsBodyColor,
	varBsBodyColorRgb,
	varBsBodyFontFamily,
	varBsBodyFontSize,
	varBsBodyFontWeight,
	varBsBodyLineHeight,
	varBsBorderColor,
	varBsBorderColorTranslucent,
	varBsBorderRadius,
	varBsBorderRadiusLg,
	varBsBorderRadiusPill,
	varBsBorderRadiusSm,
	varBsBorderRadiusXl,
	varBsBorderRadiusXxl,
	varBsBorderStyle,
	varBsBorderWidth,
	varBsBoxShadow,
	varBsBoxShadowInset,
	varBsBoxShadowLg,
	varBsBoxShadowSm,
	varBsBtnCloseFilter,
	varBsCarouselCaptionColor,
	varBsCarouselControlIconFilter,
	varBsCarouselIndicatorActiveBg,
	varBsCodeColor,
	varBsCyan,
	varBsDanger,
	varBsDangerBgSubtle,
	varBsDangerBorderSubtle,
	varBsDangerRgb,
	varBsDangerTextEmphasis,
	varBsDark,
	varBsDarkBgSubtle,
	varBsDarkBorderSubtle,
	varBsDarkRgb,
	varBsDarkTextEmphasis,
	varBsEmphasisColor,
	varBsEmphasisColorRgb,
	varBsFocusRingColor,
	varBsFocusRingOpacity,
	varBsFocusRingWidth,
	varBsFontMonospace,
	varBsFontSansSerif,
	varBsGradient,
	varBsGray,
	varBsGrayDark,
	varBsGreen,
	varBsHeadingColor,
	varBsHighlightBg,
	varBsHighlightColor,
	varBsIndigo,
	varBsInfo,
	varBsInfoBgSubtle,
	varBsInfoBorderSubtle,
	varBsInfoRgb,
	varBsInfoTextEmphasis,
	varBsLight,
	varBsLightBgSubtle,
	varBsLightBorderSubtle,
	varBsLightRgb,
	varBsLightTextEmphasis,
	varBsLinkColor,
	varBsLinkColorRgb,
	varBsLinkDecoration,
	varBsLinkHoverColor,
	varBsLinkHoverColorRgb,
	varBsOrange,
	varBsPink,
	varBsPrimary,
	varBsPrimaryBgSubtle,
	varBsPrimaryBorderSubtle,
	varBsPrimaryRgb,
	varBsPrimaryTextEmphasis,
	varBsPurple,
	varBsRed,
	varBsSecondary,
	varBsSecondaryBg,
	varBsSecondaryBgSubtle,
	varBsSecondaryBorderSubtle,
	varBsSecondaryColor,
	varBsSecondaryRgb,
	varBsSecondaryTextEmphasis,
	varBsSuccess,
	varBsSuccessBgSubtle,
	varBsSuccessBorderSubtle,
	varBsSuccessRgb,
	varBsSuccessTextEmphasis,
	varBsTeal,
	varBsTertiaryBg,
	varBsTertiaryColor,
	varBsWarning,
	varBsWarningBgSubtle,
	varBsWarningBorderSubtle,
	varBsWarningRgb,
	varBsWarningTextEmphasis,
	varBsWhite,
	varBsWhiteRgb,
	varBsYellow,
} from '../../theme-contract/_vars.css'
import {
	varBsFormInvalidBorderColor,
	varBsFormInvalidColor,
	varBsFormValidBorderColor,
	varBsFormValidColor,
} from '../../theme-contract/forms/_vars.css'
import { bodyFrame, bodyText, vars } from '../../theme-contract/theme-contract.css'
import { modalOpenHook } from '../../theme-contract/ui/modal/contract.css'

// Spacelab theme scope class.
// Zero-style identifier used as a stable selector prefix.
export const spacelabScope = style({})

// Global Bootstrap CSS custom properties (`--bs-*`) are assigned on the
// dedicated vars contract class to keep root var hosting separate from body
// layout/background styles.
globalStyle(`${spacelabScope}${vars}`, {
	vars: {
		[varBsBlue]: "#446e9b",
		[varBsIndigo]: "#6610f2",
		[varBsPurple]: "#6f42c1",
		[varBsPink]: "#e83e8c",
		[varBsRed]: "#cd0200",
		[varBsOrange]: "#fd7e14",
		[varBsYellow]: "#d47500",
		[varBsGreen]: "#3cb521",
		[varBsTeal]: "#20c997",
		[varBsCyan]: "#3399f3",
		[varBsBlack]: "#000",
		[varBsWhite]: "#fff",
		[varBsGray]: "#777",
		[varBsGrayDark]: "#333",
		[varBsPrimary]: "#446e9b",
		[varBsSecondary]: "#999",
		[varBsSuccess]: "#3cb521",
		[varBsInfo]: "#3399f3",
		[varBsWarning]: "#d47500",
		[varBsDanger]: "#cd0200",
		[varBsLight]: "#eee",
		[varBsDark]: "#333",
		[varBsPrimaryRgb]: "68, 110, 155",
		[varBsSecondaryRgb]: "153, 153, 153",
		[varBsSuccessRgb]: "60, 181, 33",
		[varBsInfoRgb]: "51, 153, 243",
		[varBsWarningRgb]: "212, 117, 0",
		[varBsDangerRgb]: "205, 2, 0",
		[varBsLightRgb]: "238, 238, 238",
		[varBsDarkRgb]: "51, 51, 51",
		[varBsPrimaryTextEmphasis]: "#1b2c3e",
		[varBsSecondaryTextEmphasis]: "#3d3d3d",
		[varBsSuccessTextEmphasis]: "#18480d",
		[varBsInfoTextEmphasis]: "#143d61",
		[varBsWarningTextEmphasis]: "#552f00",
		[varBsDangerTextEmphasis]: "#520100",
		[varBsLightTextEmphasis]: "#495057",
		[varBsDarkTextEmphasis]: "#495057",
		[varBsPrimaryBgSubtle]: "#dae2eb",
		[varBsSecondaryBgSubtle]: "#ebebeb",
		[varBsSuccessBgSubtle]: "#d8f0d3",
		[varBsInfoBgSubtle]: "#d6ebfd",
		[varBsWarningBgSubtle]: "#f6e3cc",
		[varBsDangerBgSubtle]: "#f5cccc",
		[varBsLightBgSubtle]: "#fcfcfd",
		[varBsDarkBgSubtle]: "#ced4da",
		[varBsPrimaryBorderSubtle]: "#b4c5d7",
		[varBsSecondaryBorderSubtle]: "#d6d6d6",
		[varBsSuccessBorderSubtle]: "#b1e1a6",
		[varBsInfoBorderSubtle]: "#add6fa",
		[varBsWarningBorderSubtle]: "#eec899",
		[varBsDangerBorderSubtle]: "#eb9a99",
		[varBsLightBorderSubtle]: "#eee",
		[varBsDarkBorderSubtle]: "#999",
		[varBsWhiteRgb]: "255, 255, 255",
		[varBsBlackRgb]: "0, 0, 0",
		[varBsFontSansSerif]: "\"Open Sans\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif, \"Apple Color Emoji\", \"Segoe UI Emoji\", \"Segoe UI Symbol\"",
		[varBsFontMonospace]: "SFMono-Regular, Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace",
		[varBsGradient]: "linear-gradient(180deg, rgba(255, 255, 255, 0.15), rgba(255, 255, 255, 0))",
		[varBsBodyFontFamily]: varBsFontSansSerif,
		[varBsBodyFontSize]: "1rem",
		[varBsBodyFontWeight]: 400,
		[varBsBodyLineHeight]: 1.5,
		[varBsBodyColor]: "#777",
		[varBsBodyColorRgb]: "119, 119, 119",
		[varBsBodyBg]: "#fff",
		[varBsBodyBgRgb]: "255, 255, 255",
		[varBsEmphasisColor]: "#000",
		[varBsEmphasisColorRgb]: "0, 0, 0",
		[varBsSecondaryColor]: "rgba(119, 119, 119, 0.75)",
		[varBsSecondaryBg]: "#eee",
		[varBsTertiaryColor]: "rgba(119, 119, 119, 0.5)",
		[varBsTertiaryBg]: "#f8f9fa",
		[varBsHeadingColor]: "#2d2d2d",
		[varBsLinkColor]: "#3399f3",
		[varBsLinkColorRgb]: "51, 153, 243",
		[varBsLinkDecoration]: "underline",
		[varBsLinkHoverColor]: "#297ac2",
		[varBsLinkHoverColorRgb]: "41, 122, 194",
		[varBsCodeColor]: "#e83e8c",
		[varBsHighlightColor]: "#777",
		[varBsHighlightBg]: "#f6e3cc",
		[varBsBorderWidth]: "1px",
		[varBsBorderStyle]: "solid",
		[varBsBorderColor]: "#dee2e6",
		[varBsBorderColorTranslucent]: "rgba(0, 0, 0, 0.175)",
		[varBsBorderRadius]: "0.375rem",
		[varBsBorderRadiusSm]: "0.25rem",
		[varBsBorderRadiusLg]: "0.5rem",
		[varBsBorderRadiusXl]: "1rem",
		[varBsBorderRadiusXxl]: "2rem",
		[varBsBorderRadiusPill]: "50rem",
		[varBsBoxShadow]: "0 0.5rem 1rem rgba(0, 0, 0, 0.15)",
		[varBsBoxShadowSm]: "0 0.125rem 0.25rem rgba(0, 0, 0, 0.075)",
		[varBsBoxShadowLg]: "0 1rem 3rem rgba(0, 0, 0, 0.175)",
		[varBsBoxShadowInset]: "inset 0 1px 2px rgba(0, 0, 0, 0.075)",
		[varBsFocusRingWidth]: "0.25rem",
		[varBsFocusRingOpacity]: 0.25,
		[varBsFocusRingColor]: "rgba(68, 110, 155, 0.25)",
		[varBsBtnCloseFilter]: "",
		[varBsCarouselIndicatorActiveBg]: "#fff",
		[varBsCarouselCaptionColor]: "#fff",
		[varBsCarouselControlIconFilter]: "",
		[varBsFormValidColor]: "#3cb521",
		[varBsFormValidBorderColor]: "#3cb521",
		[varBsFormInvalidColor]: "#cd0200",
		[varBsFormInvalidBorderColor]: "#cd0200",
	},
})

// ── Root / body styles ────────────────────────────────────────────────────────
// bodyText = typography; bodyFrame = page canvas (Ve2Shell). Do not add padding
// here — baseline screenshots have no padded wrapper around bd-example.

globalStyle(`${spacelabScope}${bodyText}`, {
	fontFamily: varBsBodyFontFamily,
	fontSize: varBsBodyFontSize,
	fontWeight: varBsBodyFontWeight,
	lineHeight: varBsBodyLineHeight,
	color: varBsBodyColor,
})

globalStyle(`${spacelabScope}${bodyFrame}`, {
	backgroundColor: varBsBodyBg,
	margin: 0,
	minHeight: '100vh',
})

// Bootstrap Modal JS adds modalOpenHook to <body> without theme scope.
globalStyle(`${modalOpenHook}`, {
	fontFamily: varBsBodyFontFamily,
	fontSize: varBsBodyFontSize,
	fontWeight: varBsBodyFontWeight,
	lineHeight: varBsBodyLineHeight,
	color: varBsBodyColor,
	backgroundColor: varBsBodyBg,
	margin: 0,
})
