// GERADO por scripts/gen-public-vars.mjs — NÃO editar à mão.
import { globalStyle } from '@vanilla-extract/css'
import { yetiScope } from './scope.css'
import { varBsBlackRgb, varBsBodyBgRgb, varBsBodyColorRgb, varBsBorderColor, varBsBorderRadius, varBsBorderRadiusLg, varBsBorderRadiusPill, varBsBorderRadiusSm, varBsBorderRadiusXl, varBsBorderRadiusXxl, varBsBorderStyle, varBsBorderWidth, varBsBoxShadow, varBsBoxShadowLg, varBsBoxShadowSm, varBsDangerBgSubtle, varBsDangerBorderSubtle, varBsDangerRgb, varBsDangerTextEmphasis, varBsDarkBgSubtle, varBsDarkBorderSubtle, varBsDarkRgb, varBsDarkTextEmphasis, varBsEmphasisColor, varBsEmphasisColorRgb, varBsFocusRingColor, varBsFocusRingOpacity, varBsFontMonospace, varBsGradient, varBsInfoBgSubtle, varBsInfoBorderSubtle, varBsInfoRgb, varBsInfoTextEmphasis, varBsLightBgSubtle, varBsLightBorderSubtle, varBsLightRgb, varBsLightTextEmphasis, varBsLinkColorRgb, varBsPrimaryBgSubtle, varBsPrimaryBorderSubtle, varBsPrimaryRgb, varBsPrimaryTextEmphasis, varBsSecondaryBgRgb, varBsSecondaryBgSubtle, varBsSecondaryBorderSubtle, varBsSecondaryColor, varBsSecondaryRgb, varBsSecondaryTextEmphasis, varBsSuccessBgSubtle, varBsSuccessBorderSubtle, varBsSuccessRgb, varBsSuccessTextEmphasis, varBsTertiaryBgRgb, varBsTertiaryColor, varBsWarningBgSubtle, varBsWarningBorderSubtle, varBsWarningRgb, varBsWarningTextEmphasis, varBsWhiteRgb } from '../../theme-contract/_public-vars.css'

globalStyle(yetiScope, {
	vars: {
		[varBsBlackRgb]: "0, 0, 0",
		[varBsBodyBgRgb]: "255, 255, 255",
		[varBsBodyColorRgb]: "34, 34, 34",
		[varBsBorderColor]: "#dee2e6",
		[varBsBorderRadius]: "0",
		[varBsBorderRadiusLg]: "0",
		[varBsBorderRadiusPill]: "50rem",
		[varBsBorderRadiusSm]: "0",
		[varBsBorderRadiusXl]: "1rem",
		[varBsBorderRadiusXxl]: "2rem",
		[varBsBorderStyle]: "solid",
		[varBsBorderWidth]: "1px",
		[varBsBoxShadow]: "0 0.5rem 1rem rgba(0, 0, 0, 0.15)",
		[varBsBoxShadowLg]: "0 1rem 3rem rgba(0, 0, 0, 0.175)",
		[varBsBoxShadowSm]: "0 0.125rem 0.25rem rgba(0, 0, 0, 0.075)",
		[varBsDangerBgSubtle]: "#fcd9d3",
		[varBsDangerBorderSubtle]: "#f9b3a7",
		[varBsDangerRgb]: "240, 65, 36",
		[varBsDangerTextEmphasis]: "#601a0e",
		[varBsDarkBgSubtle]: "#ccc",
		[varBsDarkBorderSubtle]: "#adb5bd",
		[varBsDarkRgb]: "51, 51, 51",
		[varBsDarkTextEmphasis]: "#495057",
		[varBsEmphasisColor]: "#000",
		[varBsEmphasisColorRgb]: "0, 0, 0",
		[varBsFocusRingColor]: "rgba(0, 140, 186, 0.25)",
		[varBsFocusRingOpacity]: "0.25",
		[varBsFontMonospace]: "SFMono-Regular, Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace",
		[varBsGradient]: "linear-gradient(180deg, rgba(255, 255, 255, 0.15), rgba(255, 255, 255, 0))",
		[varBsInfoBgSubtle]: "#def2f8",
		[varBsInfoBorderSubtle]: "#bde6f2",
		[varBsInfoRgb]: "91, 192, 222",
		[varBsInfoTextEmphasis]: "#244d59",
		[varBsLightBgSubtle]: "#fcfcfd",
		[varBsLightBorderSubtle]: "#eee",
		[varBsLightRgb]: "238, 238, 238",
		[varBsLightTextEmphasis]: "#495057",
		[varBsLinkColorRgb]: "0, 140, 186",
		[varBsPrimaryBgSubtle]: "#cce8f1",
		[varBsPrimaryBorderSubtle]: "#99d1e3",
		[varBsPrimaryRgb]: "0, 140, 186",
		[varBsPrimaryTextEmphasis]: "#00384a",
		[varBsSecondaryBgRgb]: "238, 238, 238",
		[varBsSecondaryBgSubtle]: "#fcfcfc",
		[varBsSecondaryBorderSubtle]: "#f8f8f8",
		[varBsSecondaryColor]: "rgba(34, 34, 34, 0.75)",
		[varBsSecondaryRgb]: "238, 238, 238",
		[varBsSecondaryTextEmphasis]: "#5f5f5f",
		[varBsSuccessBgSubtle]: "#d9eee1",
		[varBsSuccessBorderSubtle]: "#b4dec3",
		[varBsSuccessRgb]: "67, 172, 106",
		[varBsSuccessTextEmphasis]: "#1b452a",
		[varBsTertiaryBgRgb]: "248, 249, 250",
		[varBsTertiaryColor]: "rgba(34, 34, 34, 0.5)",
		[varBsWarningBgSubtle]: "#fbe9cc",
		[varBsWarningBorderSubtle]: "#f6d39a",
		[varBsWarningRgb]: "233, 144, 2",
		[varBsWarningTextEmphasis]: "#5d3a01",
		[varBsWhiteRgb]: "255, 255, 255",
	},
})
