import { globalStyle, style } from '@vanilla-extract/css'
import {
	varBsAccordionBtnActiveIcon,
	varBsAccordionBtnIcon,
	varBsBlack,
	varBsBlackRgb,
	varBsBlue,
	varBsBodyBg,
	varBsBodyBgRgb,
	varBsBodyColor,
	varBsBodyColorRgb,
	varBsBodyFontFamily,
	varBsBodyFontSize,
	varBsBodyFontWeight,
	varBsBodyLineHeight,
	varBsBorderColor,
	varBsBorderColorTranslucent,
	varBsBorderRadius,
	varBsBorderRadiusLg,
	varBsBorderRadiusPill,
	varBsBorderRadiusSm,
	varBsBorderRadiusXl,
	varBsBorderRadiusXxl,
	varBsBorderStyle,
	varBsBorderWidth,
	varBsBoxShadow,
	varBsBoxShadowInset,
	varBsBoxShadowLg,
	varBsBoxShadowSm,
	varBsCarouselCaptionColor,
	varBsCarouselControlIconFilter,
	varBsCarouselIndicatorActiveBg,
	varBsCodeColor,
	varBsCyan,
	varBsDanger,
	varBsDangerBgSubtle,
	varBsDangerBorderSubtle,
	varBsDangerRgb,
	varBsDangerTextEmphasis,
	varBsDark,
	varBsDarkBgSubtle,
	varBsDarkBorderSubtle,
	varBsDarkRgb,
	varBsDarkTextEmphasis,
	varBsEmphasisColor,
	varBsEmphasisColorRgb,
	varBsFocusRingColor,
	varBsFocusRingOpacity,
	varBsFocusRingWidth,
	varBsFontMonospace,
	varBsFontSansSerif,
	varBsGradient,
	varBsGray,
	varBsGrayDark,
	varBsGreen,
	varBsHeadingColor,
	varBsHighlightBg,
	varBsHighlightColor,
	varBsIndigo,
	varBsInfo,
	varBsInfoBgSubtle,
	varBsInfoBorderSubtle,
	varBsInfoRgb,
	varBsInfoTextEmphasis,
	varBsLight,
	varBsLightBgSubtle,
	varBsLightBorderSubtle,
	varBsLightRgb,
	varBsLightTextEmphasis,
	varBsLinkColor,
	varBsLinkColorRgb,
	varBsLinkDecoration,
	varBsLinkHoverColor,
	varBsLinkHoverColorRgb,
	varBsNavbarActiveColor,
	varBsNavbarBrandColor,
	varBsNavbarBrandHoverColor,
	varBsNavbarColor,
	varBsNavbarDisabledColor,
	varBsNavbarHoverColor,
	varBsNavbarTogglerBorderColor,
	varBsNavbarTogglerIconBg,
	varBsOrange,
	varBsPaginationDisabledColor,
	varBsPink,
	varBsPrimary,
	varBsPrimaryBgSubtle,
	varBsPrimaryBorderSubtle,
	varBsPrimaryRgb,
	varBsPrimaryTextEmphasis,
	varBsPurple,
	varBsRed,
	varBsSecondary,
	varBsSecondaryBg,
	varBsSecondaryBgSubtle,
	varBsSecondaryBorderSubtle,
	varBsSecondaryColor,
	varBsSecondaryRgb,
	varBsSecondaryTextEmphasis,
	varBsSuccess,
	varBsSuccessBgSubtle,
	varBsSuccessBorderSubtle,
	varBsSuccessRgb,
	varBsSuccessTextEmphasis,
	varBsTeal,
	varBsTertiaryBg,
	varBsTertiaryColor,
	varBsWarning,
	varBsWarningBgSubtle,
	varBsWarningBorderSubtle,
	varBsWarningRgb,
	varBsWarningTextEmphasis,
	varBsWhite,
	varBsWhiteRgb,
	varBsYellow,
} from '../../theme-contract/_vars.css'
import {
	varBsFormInvalidBorderColor,
	varBsFormInvalidColor,
	varBsFormSelectBgImg,
	varBsFormSwitchBg,
	varBsFormValidBorderColor,
	varBsFormValidColor,
} from '../../theme-contract/forms/_vars.css'
import { body, bodyText, vars } from '../../theme-contract/theme-contract.css'

// Yeti theme scope class.
// Zero-style identifier used as a stable selector prefix.
export const yetiScope = style({})

// Global Bootstrap CSS custom properties (`--bs-*`) are assigned on the
// dedicated vars contract class to keep root var hosting separate from body
// layout/background styles.
globalStyle(`${yetiScope}${vars}`, {
	vars: {
		[varBsBlue]: "#008cba",
		[varBsIndigo]: "#6610f2",
		[varBsPurple]: "#6f42c1",
		[varBsPink]: "#e83e8c",
		[varBsRed]: "#f04124",
		[varBsOrange]: "#fd7e14",
		[varBsYellow]: "#e99002",
		[varBsGreen]: "#43ac6a",
		[varBsTeal]: "#20c997",
		[varBsCyan]: "#5bc0de",
		[varBsBlack]: "#000",
		[varBsWhite]: "#fff",
		[varBsGray]: "#888",
		[varBsGrayDark]: "#333",
		[varBsPrimary]: "#008cba",
		[varBsSecondary]: "#eee",
		[varBsSuccess]: "#43ac6a",
		[varBsInfo]: "#5bc0de",
		[varBsWarning]: "#e99002",
		[varBsDanger]: "#f04124",
		[varBsLight]: "#eee",
		[varBsDark]: "#333",
		[varBsPrimaryRgb]: "0, 140, 186",
		[varBsSecondaryRgb]: "238, 238, 238",
		[varBsSuccessRgb]: "67, 172, 106",
		[varBsInfoRgb]: "91, 192, 222",
		[varBsWarningRgb]: "233, 144, 2",
		[varBsDangerRgb]: "240, 65, 36",
		[varBsLightRgb]: "238, 238, 238",
		[varBsDarkRgb]: "51, 51, 51",
		[varBsPrimaryTextEmphasis]: "#66bad6",
		[varBsSecondaryTextEmphasis]: "whitesmoke",
		[varBsSuccessTextEmphasis]: "#8ecda6",
		[varBsInfoTextEmphasis]: "#9dd9eb",
		[varBsWarningTextEmphasis]: "#f2bc67",
		[varBsDangerTextEmphasis]: "#f68d7c",
		[varBsLightTextEmphasis]: "#f8f9fa",
		[varBsDarkTextEmphasis]: "#dee2e6",
		[varBsPrimaryBgSubtle]: "#001c25",
		[varBsSecondaryBgSubtle]: "#303030",
		[varBsSuccessBgSubtle]: "#0d2215",
		[varBsInfoBgSubtle]: "#12262c",
		[varBsWarningBgSubtle]: "#2f1d00",
		[varBsDangerBgSubtle]: "#300d07",
		[varBsLightBgSubtle]: "#333",
		[varBsDarkBgSubtle]: "#1a1a1a",
		[varBsPrimaryBorderSubtle]: "#005470",
		[varBsSecondaryBorderSubtle]: "#8f8f8f",
		[varBsSuccessBorderSubtle]: "#286740",
		[varBsInfoBorderSubtle]: "#377385",
		[varBsWarningBorderSubtle]: "#8c5601",
		[varBsDangerBorderSubtle]: "#902716",
		[varBsLightBorderSubtle]: "#495057",
		[varBsDarkBorderSubtle]: "#333",
		[varBsWhiteRgb]: "255, 255, 255",
		[varBsBlackRgb]: "0, 0, 0",
		[varBsFontSansSerif]: "\"Open Sans\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif, \"Apple Color Emoji\", \"Segoe UI Emoji\", \"Segoe UI Symbol\"",
		[varBsFontMonospace]: "SFMono-Regular, Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace",
		[varBsGradient]: "linear-gradient(180deg, rgba(255, 255, 255, 0.15), rgba(255, 255, 255, 0))",
		[varBsBodyFontFamily]: varBsFontSansSerif,
		[varBsBodyFontSize]: "1rem",
		[varBsBodyFontWeight]: 400,
		[varBsBodyLineHeight]: 1.5,
		[varBsBodyColor]: "#dee2e6",
		[varBsBodyColorRgb]: "222, 226, 230",
		[varBsBodyBg]: "#222",
		[varBsBodyBgRgb]: "34, 34, 34",
		[varBsEmphasisColor]: "#fff",
		[varBsEmphasisColorRgb]: "255, 255, 255",
		[varBsSecondaryColor]: "rgba(222, 226, 230, 0.75)",
		[varBsSecondaryBg]: "#333",
		[varBsTertiaryColor]: "rgba(222, 226, 230, 0.5)",
		[varBsTertiaryBg]: "#2b2b2b",
		[varBsHeadingColor]: "inherit",
		[varBsLinkColor]: "#66bad6",
		[varBsLinkColorRgb]: "102, 186, 214",
		[varBsLinkDecoration]: "underline",
		[varBsLinkHoverColor]: "#85c8de",
		[varBsLinkHoverColorRgb]: "133, 200, 222",
		[varBsCodeColor]: "#f18bba",
		[varBsHighlightColor]: "#dee2e6",
		[varBsHighlightBg]: "#5d3a01",
		[varBsBorderWidth]: "1px",
		[varBsBorderStyle]: "solid",
		[varBsBorderColor]: "#495057",
		[varBsBorderColorTranslucent]: "rgba(255, 255, 255, 0.15)",
		[varBsBorderRadius]: 0,
		[varBsBorderRadiusSm]: 0,
		[varBsBorderRadiusLg]: 0,
		[varBsBorderRadiusXl]: "1rem",
		[varBsBorderRadiusXxl]: "2rem",
		[varBsBorderRadiusPill]: "50rem",
		[varBsBoxShadow]: "0 0.5rem 1rem rgba(0, 0, 0, 0.15)",
		[varBsBoxShadowSm]: "0 0.125rem 0.25rem rgba(0, 0, 0, 0.075)",
		[varBsBoxShadowLg]: "0 1rem 3rem rgba(0, 0, 0, 0.175)",
		[varBsBoxShadowInset]: "inset 0 1px 2px rgba(0, 0, 0, 0.075)",
		[varBsFocusRingWidth]: "0.25rem",
		[varBsFocusRingOpacity]: 0.25,
		[varBsFocusRingColor]: "rgba(0, 140, 186, 0.25)",
		[varBsNavbarColor]: "rgba(255, 255, 255, 0.7)",
		[varBsNavbarHoverColor]: "#fff",
		[varBsNavbarDisabledColor]: "rgba(255, 255, 255, 0.25)",
		[varBsNavbarActiveColor]: "#fff",
		[varBsNavbarBrandColor]: "#fff",
		[varBsNavbarBrandHoverColor]: "#fff",
		[varBsNavbarTogglerBorderColor]: "rgba(255, 255, 255, 0.1)",
		[varBsNavbarTogglerIconBg]: "url(\"data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 30 30'%3e%3cpath stroke='rgba%28255, 255, 255, 0.7%29' stroke-linecap='round' stroke-miterlimit='10' stroke-width='2' d='M4 7h22M4 15h22M4 23h22'/%3e%3c/svg%3e\")",
		[varBsAccordionBtnIcon]: "url(\"data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16' fill='%2366bad6'%3e%3cpath fill-rule='evenodd' d='M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708'/%3e%3c/svg%3e\")",
		[varBsAccordionBtnActiveIcon]: "url(\"data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16' fill='%2366bad6'%3e%3cpath fill-rule='evenodd' d='M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708'/%3e%3c/svg%3e\")",
		[varBsCarouselIndicatorActiveBg]: "#000",
		[varBsCarouselCaptionColor]: "#000",
		[varBsCarouselControlIconFilter]: "invert(1) grayscale(100)",
		[varBsPaginationDisabledColor]: "#495057",
	},
})

// ── Root / body styles ────────────────────────────────────────────────────────

globalStyle(`${yetiScope}${bodyText}`, {
	fontFamily: varBsBodyFontFamily,
	fontSize: varBsBodyFontSize,
	fontWeight: varBsBodyFontWeight,
	lineHeight: varBsBodyLineHeight,
	color: varBsBodyColor,
})

globalStyle(`${yetiScope}${body}`, {
	backgroundColor: varBsBodyBg,
	padding: '1rem',
	display: 'block',
})
