import { bootstrapScope } from '../themes/bootstrap/scope.css'
import { materiaScope } from '../themes/materia/scope.css'
import { quartzScope } from '../themes/quartz/scope.css'
import { sandstoneScope } from '../themes/sandstone/scope.css'
import { sketchyScope } from '../themes/sketchy/scope.css'
import { slateScope } from '../themes/slate/scope.css'
import { solarScope } from '../themes/solar/scope.css'
import { vaporScope } from '../themes/vapor/scope.css'
import type { Ve2StyleFamily } from './style-families'

export const VE2_THEME_KEYS = [
	'bootstrap',
	'quartz',
	'solar',
	'slate',
	'sketchy',
	'vapor',
	'sandstone',
	'materia',
] as const

export type Ve2ThemeKey = (typeof VE2_THEME_KEYS)[number]

export type Ve2StyleFamilyLoaderMap = Partial<Record<Ve2StyleFamily, () => Promise<unknown>>>

const themeScopes: Record<Ve2ThemeKey, string> = {
	bootstrap: bootstrapScope,
	quartz: quartzScope,
	solar: solarScope,
	slate: slateScope,
	sketchy: sketchyScope,
	vapor: vaporScope,
	sandstone: sandstoneScope,
	materia: materiaScope,
}

export const ve2ThemeLoaders: Record<Ve2ThemeKey, () => Promise<unknown>> = {
	bootstrap: () => import('../themes/bootstrap/theme.js'),
	quartz: () => import('../themes/quartz/theme.js'),
	solar: () => import('../themes/solar/theme.js'),
	slate: () => import('../themes/slate/theme.js'),
	sketchy: () => import('../themes/sketchy/theme.js'),
	vapor: () => import('../themes/vapor/theme.js'),
	sandstone: () => import('../themes/sandstone/theme.js'),
	materia: () => import('../themes/materia/theme.js'),
}

export const ve2ThemeFamilyLoaders: Record<Ve2ThemeKey, Ve2StyleFamilyLoaderMap> = {
	bootstrap: {
		contents: () => import('../themes/bootstrap/contents/styles.css'),
		'contents/basic': () => import('../themes/bootstrap/contents/basic/styles.css'),
		'contents/heading': () => import('../themes/bootstrap/contents/heading/styles.css'),
		'contents/display': () => import('../themes/bootstrap/contents/display/styles.css'),
		'contents/lists': () => import('../themes/bootstrap/contents/lists/styles.css'),
		'contents/tables': () => import('../themes/bootstrap/contents/tables/styles.css'),
		'contents/images': () => import('../themes/bootstrap/contents/images/styles.css'),
		forms: () => import('../themes/bootstrap/forms/styles.css'),
		utilities: () => import('../themes/bootstrap/utilities/styles.css'),
		'ui/accordion': () => import('../themes/bootstrap/ui/accordion/styles.css'),
		'ui/alerts': () => import('../themes/bootstrap/ui/alerts/styles.css'),
		'ui/badge': () => import('../themes/bootstrap/ui/badge/styles.css'),
		'ui/breadcrumb': () => import('../themes/bootstrap/ui/breadcrumb/styles.css'),
		'ui/button-group': () => import('../themes/bootstrap/ui/button-group/styles.css'),
		'ui/buttons': () => import('../themes/bootstrap/ui/buttons/styles.css'),
		'ui/card': () => import('../themes/bootstrap/ui/card/styles.css'),
		'ui/card-tabs': () => import('../themes/bootstrap/ui/card-tabs/styles.css'),
		'ui/carousel': () => import('../themes/bootstrap/ui/carousel/styles.css'),
		'ui/dropdowns': () => import('../themes/bootstrap/ui/dropdowns/styles.css'),
		'ui/list-group': () => import('../themes/bootstrap/ui/list-group/styles.css'),
		'ui/modal': () => import('../themes/bootstrap/ui/modal/styles.css'),
		'ui/navbar': () => import('../themes/bootstrap/ui/navbar/styles.css'),
		'ui/navs': () => import('../themes/bootstrap/ui/navs/styles.css'),
		'ui/pagination': () => import('../themes/bootstrap/ui/pagination/styles.css'),
		'ui/popovers': () => import('../themes/bootstrap/ui/popovers/styles.css'),
		'ui/progress': () => import('../themes/bootstrap/ui/progress/styles.css'),
		'ui/scrollspy': () => import('../themes/bootstrap/ui/scrollspy/styles.css'),
		'ui/spinners': () => import('../themes/bootstrap/ui/spinners/styles.css'),
		'ui/toasts': () => import('../themes/bootstrap/ui/toasts/styles.css'),
		'ui/tooltips': () => import('../themes/bootstrap/ui/tooltips/styles.css'),
	},
	quartz: {
		contents: () => import('../themes/quartz/contents/styles.css'),
		'contents/basic': () => import('../themes/quartz/contents/basic/styles.css'),
		'contents/heading': () => import('../themes/quartz/contents/heading/styles.css'),
		'contents/display': () => import('../themes/quartz/contents/display/styles.css'),
		'contents/lists': () => import('../themes/quartz/contents/lists/styles.css'),
		'contents/tables': () => import('../themes/quartz/contents/tables/styles.css'),
		'contents/images': () => import('../themes/quartz/contents/images/styles.css'),
		forms: () => import('../themes/quartz/forms/styles.css'),
		utilities: () => import('../themes/quartz/utilities/styles.css'),
		'ui/accordion': () => import('../themes/quartz/ui/accordion/styles.css'),
		'ui/alerts': () => import('../themes/quartz/ui/alerts/styles.css'),
		'ui/badge': () => import('../themes/quartz/ui/badge/styles.css'),
		'ui/breadcrumb': () => import('../themes/quartz/ui/breadcrumb/styles.css'),
		'ui/button-group': () => import('../themes/quartz/ui/button-group/styles.css'),
		'ui/buttons': () => import('../themes/quartz/ui/buttons/styles.css'),
		'ui/card': () => import('../themes/quartz/ui/card/styles.css'),
		'ui/card-tabs': () => import('../themes/quartz/ui/card-tabs/styles.css'),
		'ui/carousel': () => import('../themes/quartz/ui/carousel/styles.css'),
		'ui/dropdowns': () => import('../themes/quartz/ui/dropdowns/styles.css'),
		'ui/list-group': () => import('../themes/quartz/ui/list-group/styles.css'),
		'ui/modal': () => import('../themes/quartz/ui/modal/styles.css'),
		'ui/navbar': () => import('../themes/quartz/ui/navbar/styles.css'),
		'ui/navs': () => import('../themes/quartz/ui/navs/styles.css'),
		'ui/pagination': () => import('../themes/quartz/ui/pagination/styles.css'),
		'ui/popovers': () => import('../themes/quartz/ui/popovers/styles.css'),
		'ui/progress': () => import('../themes/quartz/ui/progress/styles.css'),
		'ui/scrollspy': () => import('../themes/quartz/ui/scrollspy/styles.css'),
		'ui/spinners': () => import('../themes/quartz/ui/spinners/styles.css'),
		'ui/toasts': () => import('../themes/quartz/ui/toasts/styles.css'),
		'ui/tooltips': () => import('../themes/quartz/ui/tooltips/styles.css'),
	},
	solar: {
		contents: () => import('../themes/solar/contents/styles.css'),
		'contents/basic': () => import('../themes/solar/contents/basic/styles.css'),
		'contents/heading': () => import('../themes/solar/contents/heading/styles.css'),
		'contents/display': () => import('../themes/solar/contents/display/styles.css'),
		'contents/lists': () => import('../themes/solar/contents/lists/styles.css'),
		'contents/tables': () => import('../themes/solar/contents/tables/styles.css'),
		'contents/images': () => import('../themes/solar/contents/images/styles.css'),
		forms: () => import('../themes/solar/forms/styles.css'),
		utilities: () => import('../themes/solar/utilities/styles.css'),
		'ui/accordion': () => import('../themes/solar/ui/accordion/styles.css'),
		'ui/alerts': () => import('../themes/solar/ui/alerts/styles.css'),
		'ui/badge': () => import('../themes/solar/ui/badge/styles.css'),
		'ui/breadcrumb': () => import('../themes/solar/ui/breadcrumb/styles.css'),
		'ui/button-group': () => import('../themes/solar/ui/button-group/styles.css'),
		'ui/buttons': () => import('../themes/solar/ui/buttons/styles.css'),
		'ui/card': () => import('../themes/solar/ui/card/styles.css'),
		'ui/card-tabs': () => import('../themes/solar/ui/card-tabs/styles.css'),
		'ui/carousel': () => import('../themes/solar/ui/carousel/styles.css'),
		'ui/dropdowns': () => import('../themes/solar/ui/dropdowns/styles.css'),
		'ui/list-group': () => import('../themes/solar/ui/list-group/styles.css'),
		'ui/modal': () => import('../themes/solar/ui/modal/styles.css'),
		'ui/navbar': () => import('../themes/solar/ui/navbar/styles.css'),
		'ui/navs': () => import('../themes/solar/ui/navs/styles.css'),
		'ui/pagination': () => import('../themes/solar/ui/pagination/styles.css'),
		'ui/popovers': () => import('../themes/solar/ui/popovers/styles.css'),
		'ui/progress': () => import('../themes/solar/ui/progress/styles.css'),
		'ui/scrollspy': () => import('../themes/solar/ui/scrollspy/styles.css'),
		'ui/spinners': () => import('../themes/solar/ui/spinners/styles.css'),
		'ui/toasts': () => import('../themes/solar/ui/toasts/styles.css'),
		'ui/tooltips': () => import('../themes/solar/ui/tooltips/styles.css'),
	},
	slate: {
		contents: () => import('../themes/slate/contents/styles.css'),
		'contents/basic': () => import('../themes/slate/contents/basic/styles.css'),
		'contents/heading': () => import('../themes/slate/contents/heading/styles.css'),
		'contents/display': () => import('../themes/slate/contents/display/styles.css'),
		'contents/lists': () => import('../themes/slate/contents/lists/styles.css'),
		'contents/tables': () => import('../themes/slate/contents/tables/styles.css'),
		'contents/images': () => import('../themes/slate/contents/images/styles.css'),
		forms: () => import('../themes/slate/forms/styles.css'),
		utilities: () => import('../themes/slate/utilities/styles.css'),
		'ui/accordion': () => import('../themes/slate/ui/accordion/styles.css'),
		'ui/alerts': () => import('../themes/slate/ui/alerts/styles.css'),
		'ui/badge': () => import('../themes/slate/ui/badge/styles.css'),
		'ui/breadcrumb': () => import('../themes/slate/ui/breadcrumb/styles.css'),
		'ui/button-group': () => import('../themes/slate/ui/button-group/styles.css'),
		'ui/buttons': () => import('../themes/slate/ui/buttons/styles.css'),
		'ui/card': () => import('../themes/slate/ui/card/styles.css'),
		'ui/card-tabs': () => import('../themes/slate/ui/card-tabs/styles.css'),
		'ui/carousel': () => import('../themes/slate/ui/carousel/styles.css'),
		'ui/dropdowns': () => import('../themes/slate/ui/dropdowns/styles.css'),
		'ui/list-group': () => import('../themes/slate/ui/list-group/styles.css'),
		'ui/modal': () => import('../themes/slate/ui/modal/styles.css'),
		'ui/navbar': () => import('../themes/slate/ui/navbar/styles.css'),
		'ui/navs': () => import('../themes/slate/ui/navs/styles.css'),
		'ui/pagination': () => import('../themes/slate/ui/pagination/styles.css'),
		'ui/popovers': () => import('../themes/slate/ui/popovers/styles.css'),
		'ui/progress': () => import('../themes/slate/ui/progress/styles.css'),
		'ui/scrollspy': () => import('../themes/slate/ui/scrollspy/styles.css'),
		'ui/spinners': () => import('../themes/slate/ui/spinners/styles.css'),
		'ui/toasts': () => import('../themes/slate/ui/toasts/styles.css'),
		'ui/tooltips': () => import('../themes/slate/ui/tooltips/styles.css'),
	},
	sketchy: {
		contents: () => import('../themes/sketchy/contents/styles.css'),
		'contents/basic': () => import('../themes/sketchy/contents/basic/styles.css'),
		'contents/heading': () => import('../themes/sketchy/contents/heading/styles.css'),
		'contents/display': () => import('../themes/sketchy/contents/display/styles.css'),
		'contents/lists': () => import('../themes/sketchy/contents/lists/styles.css'),
		'contents/tables': () => import('../themes/sketchy/contents/tables/styles.css'),
		'contents/images': () => import('../themes/sketchy/contents/images/styles.css'),
		forms: () => import('../themes/sketchy/forms/styles.css'),
		utilities: () => import('../themes/sketchy/utilities/styles.css'),
		'ui/accordion': () => import('../themes/sketchy/ui/accordion/styles.css'),
		'ui/alerts': () => import('../themes/sketchy/ui/alerts/styles.css'),
		'ui/badge': () => import('../themes/sketchy/ui/badge/styles.css'),
		'ui/breadcrumb': () => import('../themes/sketchy/ui/breadcrumb/styles.css'),
		'ui/button-group': () => import('../themes/sketchy/ui/button-group/styles.css'),
		'ui/buttons': () => import('../themes/sketchy/ui/buttons/styles.css'),
		'ui/card': () => import('../themes/sketchy/ui/card/styles.css'),
		'ui/card-tabs': () => import('../themes/sketchy/ui/card-tabs/styles.css'),
		'ui/carousel': () => import('../themes/sketchy/ui/carousel/styles.css'),
		'ui/dropdowns': () => import('../themes/sketchy/ui/dropdowns/styles.css'),
		'ui/list-group': () => import('../themes/sketchy/ui/list-group/styles.css'),
		'ui/modal': () => import('../themes/sketchy/ui/modal/styles.css'),
		'ui/navbar': () => import('../themes/sketchy/ui/navbar/styles.css'),
		'ui/navs': () => import('../themes/sketchy/ui/navs/styles.css'),
		'ui/pagination': () => import('../themes/sketchy/ui/pagination/styles.css'),
		'ui/popovers': () => import('../themes/sketchy/ui/popovers/styles.css'),
		'ui/progress': () => import('../themes/sketchy/ui/progress/styles.css'),
		'ui/scrollspy': () => import('../themes/sketchy/ui/scrollspy/styles.css'),
		'ui/spinners': () => import('../themes/sketchy/ui/spinners/styles.css'),
		'ui/toasts': () => import('../themes/sketchy/ui/toasts/styles.css'),
		'ui/tooltips': () => import('../themes/sketchy/ui/tooltips/styles.css'),
	},
	vapor: {
		contents: () => import('../themes/vapor/contents/styles.css'),
		'contents/basic': () => import('../themes/vapor/contents/basic/styles.css'),
		'contents/heading': () => import('../themes/vapor/contents/heading/styles.css'),
		'contents/display': () => import('../themes/vapor/contents/display/styles.css'),
		'contents/lists': () => import('../themes/vapor/contents/lists/styles.css'),
		'contents/tables': () => import('../themes/vapor/contents/tables/styles.css'),
		'contents/images': () => import('../themes/vapor/contents/images/styles.css'),
		forms: () => import('../themes/vapor/forms/styles.css'),
		utilities: () => import('../themes/vapor/utilities/styles.css'),
		'ui/accordion': () => import('../themes/vapor/ui/accordion/styles.css'),
		'ui/alerts': () => import('../themes/vapor/ui/alerts/styles.css'),
		'ui/badge': () => import('../themes/vapor/ui/badge/styles.css'),
		'ui/breadcrumb': () => import('../themes/vapor/ui/breadcrumb/styles.css'),
		'ui/button-group': () => import('../themes/vapor/ui/button-group/styles.css'),
		'ui/buttons': () => import('../themes/vapor/ui/buttons/styles.css'),
		'ui/card': () => import('../themes/vapor/ui/card/styles.css'),
		'ui/card-tabs': () => import('../themes/vapor/ui/card-tabs/styles.css'),
		'ui/carousel': () => import('../themes/vapor/ui/carousel/styles.css'),
		'ui/dropdowns': () => import('../themes/vapor/ui/dropdowns/styles.css'),
		'ui/list-group': () => import('../themes/vapor/ui/list-group/styles.css'),
		'ui/modal': () => import('../themes/vapor/ui/modal/styles.css'),
		'ui/navbar': () => import('../themes/vapor/ui/navbar/styles.css'),
		'ui/navs': () => import('../themes/vapor/ui/navs/styles.css'),
		'ui/pagination': () => import('../themes/vapor/ui/pagination/styles.css'),
		'ui/popovers': () => import('../themes/vapor/ui/popovers/styles.css'),
		'ui/progress': () => import('../themes/vapor/ui/progress/styles.css'),
		'ui/scrollspy': () => import('../themes/vapor/ui/scrollspy/styles.css'),
		'ui/spinners': () => import('../themes/vapor/ui/spinners/styles.css'),
		'ui/toasts': () => import('../themes/vapor/ui/toasts/styles.css'),
		'ui/tooltips': () => import('../themes/vapor/ui/tooltips/styles.css'),
	},
	sandstone: {
		contents: () => import('../themes/sandstone/contents/styles.css'),
		'contents/basic': () => import('../themes/sandstone/contents/basic/styles.css'),
		'contents/heading': () => import('../themes/sandstone/contents/heading/styles.css'),
		'contents/display': () => import('../themes/sandstone/contents/display/styles.css'),
		'contents/lists': () => import('../themes/sandstone/contents/lists/styles.css'),
		'contents/tables': () => import('../themes/sandstone/contents/tables/styles.css'),
		'contents/images': () => import('../themes/sandstone/contents/images/styles.css'),
		forms: () => import('../themes/sandstone/forms/styles.css'),
		utilities: () => import('../themes/sandstone/utilities/styles.css'),
		'ui/accordion': () => import('../themes/sandstone/ui/accordion/styles.css'),
		'ui/alerts': () => import('../themes/sandstone/ui/alerts/styles.css'),
		'ui/badge': () => import('../themes/sandstone/ui/badge/styles.css'),
		'ui/breadcrumb': () => import('../themes/sandstone/ui/breadcrumb/styles.css'),
		'ui/button-group': () => import('../themes/sandstone/ui/button-group/styles.css'),
		'ui/buttons': () => import('../themes/sandstone/ui/buttons/styles.css'),
		'ui/card': () => import('../themes/sandstone/ui/card/styles.css'),
		'ui/card-tabs': () => import('../themes/sandstone/ui/card-tabs/styles.css'),
		'ui/carousel': () => import('../themes/sandstone/ui/carousel/styles.css'),
		'ui/dropdowns': () => import('../themes/sandstone/ui/dropdowns/styles.css'),
		'ui/list-group': () => import('../themes/sandstone/ui/list-group/styles.css'),
		'ui/modal': () => import('../themes/sandstone/ui/modal/styles.css'),
		'ui/navbar': () => import('../themes/sandstone/ui/navbar/styles.css'),
		'ui/navs': () => import('../themes/sandstone/ui/navs/styles.css'),
		'ui/pagination': () => import('../themes/sandstone/ui/pagination/styles.css'),
		'ui/popovers': () => import('../themes/sandstone/ui/popovers/styles.css'),
		'ui/progress': () => import('../themes/sandstone/ui/progress/styles.css'),
		'ui/scrollspy': () => import('../themes/sandstone/ui/scrollspy/styles.css'),
		'ui/spinners': () => import('../themes/sandstone/ui/spinners/styles.css'),
		'ui/toasts': () => import('../themes/sandstone/ui/toasts/styles.css'),
		'ui/tooltips': () => import('../themes/sandstone/ui/tooltips/styles.css'),
	},
	materia: {
		contents: () => import('../themes/materia/contents/styles.css'),
		'contents/basic': () => import('../themes/materia/contents/basic/styles.css'),
		'contents/heading': () => import('../themes/materia/contents/heading/styles.css'),
		'contents/display': () => import('../themes/materia/contents/display/styles.css'),
		'contents/lists': () => import('../themes/materia/contents/lists/styles.css'),
		'contents/tables': () => import('../themes/materia/contents/tables/styles.css'),
		'contents/images': () => import('../themes/materia/contents/images/styles.css'),
		forms: () => import('../themes/materia/forms/styles.css'),
		utilities: () => import('../themes/materia/utilities/styles.css'),
		'ui/accordion': () => import('../themes/materia/ui/accordion/styles.css'),
		'ui/alerts': () => import('../themes/materia/ui/alerts/styles.css'),
		'ui/badge': () => import('../themes/materia/ui/badge/styles.css'),
		'ui/breadcrumb': () => import('../themes/materia/ui/breadcrumb/styles.css'),
		'ui/button-group': () => import('../themes/materia/ui/button-group/styles.css'),
		'ui/buttons': () => import('../themes/materia/ui/buttons/styles.css'),
		'ui/card': () => import('../themes/materia/ui/card/styles.css'),
		'ui/card-tabs': () => import('../themes/materia/ui/card-tabs/styles.css'),
		'ui/carousel': () => import('../themes/materia/ui/carousel/styles.css'),
		'ui/dropdowns': () => import('../themes/materia/ui/dropdowns/styles.css'),
		'ui/list-group': () => import('../themes/materia/ui/list-group/styles.css'),
		'ui/modal': () => import('../themes/materia/ui/modal/styles.css'),
		'ui/navbar': () => import('../themes/materia/ui/navbar/styles.css'),
		'ui/navs': () => import('../themes/materia/ui/navs/styles.css'),
		'ui/pagination': () => import('../themes/materia/ui/pagination/styles.css'),
		'ui/popovers': () => import('../themes/materia/ui/popovers/styles.css'),
		'ui/progress': () => import('../themes/materia/ui/progress/styles.css'),
		'ui/scrollspy': () => import('../themes/materia/ui/scrollspy/styles.css'),
		'ui/spinners': () => import('../themes/materia/ui/spinners/styles.css'),
		'ui/toasts': () => import('../themes/materia/ui/toasts/styles.css'),
		'ui/tooltips': () => import('../themes/materia/ui/tooltips/styles.css'),
	},
}

export function resolveVe2ThemeKey(rawTheme: string | null | undefined): Ve2ThemeKey {
	switch (rawTheme) {
		case 'quartz':
		case 'solar':
		case 'slate':
		case 'sketchy':
		case 'vapor':
		case 'sandstone':
		case 'materia':
			return rawTheme
		default:
			return 'bootstrap'
	}
}

export function resolveVe2ThemeClass(rawTheme: string | null | undefined): string {
	return themeScopes[resolveVe2ThemeKey(rawTheme)]
}
