// GERADO por scripts/gen-public-vars.mjs — NÃO editar à mão.
import { globalStyle } from '@vanilla-extract/css'
import { quartzScope } from './scope.css'
import { varBsBlackRgb, varBsBodyBgRgb, varBsBodyColorRgb, varBsBorderColor, varBsBorderRadius, varBsBorderRadiusLg, varBsBorderRadiusPill, varBsBorderRadiusSm, varBsBorderRadiusXl, varBsBorderRadiusXxl, varBsBorderStyle, varBsBorderWidth, varBsBoxShadow, varBsBoxShadowLg, varBsBoxShadowSm, varBsDangerBgSubtle, varBsDangerBorderSubtle, varBsDangerRgb, varBsDangerTextEmphasis, varBsDarkBgSubtle, varBsDarkBorderSubtle, varBsDarkRgb, varBsDarkTextEmphasis, varBsEmphasisColor, varBsEmphasisColorRgb, varBsFocusRingColor, varBsFocusRingOpacity, varBsFontMonospace, varBsGradient, varBsInfoBgSubtle, varBsInfoBorderSubtle, varBsInfoRgb, varBsInfoTextEmphasis, varBsLightBgSubtle, varBsLightBorderSubtle, varBsLightRgb, varBsLightTextEmphasis, varBsLinkColorRgb, varBsPrimaryBgSubtle, varBsPrimaryBorderSubtle, varBsPrimaryRgb, varBsPrimaryTextEmphasis, varBsSecondaryBgRgb, varBsSecondaryBgSubtle, varBsSecondaryBorderSubtle, varBsSecondaryColor, varBsSecondaryRgb, varBsSecondaryTextEmphasis, varBsSuccessBgSubtle, varBsSuccessBorderSubtle, varBsSuccessRgb, varBsSuccessTextEmphasis, varBsTertiaryBgRgb, varBsTertiaryColor, varBsWarningBgSubtle, varBsWarningBorderSubtle, varBsWarningRgb, varBsWarningTextEmphasis, varBsWhiteRgb } from '../../theme-contract/_public-vars.css'

globalStyle(quartzScope, {
	vars: {
		[varBsBlackRgb]: "0, 0, 0",
		[varBsBodyBgRgb]: "104, 109, 195",
		[varBsBodyColorRgb]: "255, 255, 255",
		[varBsBorderColor]: "rgba(255, 255, 255, 0.2)",
		[varBsBorderRadius]: "0.5rem",
		[varBsBorderRadiusLg]: "0.7rem",
		[varBsBorderRadiusPill]: "50rem",
		[varBsBorderRadiusSm]: "0.6rem",
		[varBsBorderRadiusXl]: "1rem",
		[varBsBorderRadiusXxl]: "2rem",
		[varBsBorderStyle]: "solid",
		[varBsBorderWidth]: "1px",
		[varBsBoxShadow]: "1px 3px 24px -1px rgba(0, 0, 0, 0.15)",
		[varBsBoxShadowLg]: "0 1rem 3rem rgba(0, 0, 0, 0.175)",
		[varBsBoxShadowSm]: "0 1px 1px rgba(0, 0, 0, 0.1)",
		[varBsDangerBgSubtle]: "#ffe5d0",
		[varBsDangerBorderSubtle]: "#fecba1",
		[varBsDangerRgb]: "253, 126, 20",
		[varBsDangerTextEmphasis]: "#653208",
		[varBsDarkBgSubtle]: "#ced4da",
		[varBsDarkBorderSubtle]: "#adb5bd",
		[varBsDarkRgb]: "33, 37, 41",
		[varBsDarkTextEmphasis]: "#495057",
		[varBsEmphasisColor]: "#000",
		[varBsEmphasisColorRgb]: "0, 0, 0",
		[varBsFocusRingColor]: "rgba(232, 50, 131, 0.25)",
		[varBsFocusRingOpacity]: "0.25",
		[varBsFontMonospace]: "SFMono-Regular, Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace",
		[varBsGradient]: "linear-gradient(180deg, rgba(255, 255, 255, 0.15), rgba(255, 255, 255, 0))",
		[varBsInfoBgSubtle]: "#d7f5fe",
		[varBsInfoBorderSubtle]: "#b0eafd",
		[varBsInfoRgb]: "57, 203, 251",
		[varBsInfoTextEmphasis]: "#175164",
		[varBsLightBgSubtle]: "#fcfcfd",
		[varBsLightBorderSubtle]: "#e9e9e8",
		[varBsLightRgb]: "233, 233, 232",
		[varBsLightTextEmphasis]: "#495057",
		[varBsLinkColorRgb]: "255, 255, 255",
		[varBsPrimaryBgSubtle]: "#fad6e6",
		[varBsPrimaryBorderSubtle]: "#f6adcd",
		[varBsPrimaryRgb]: "232, 50, 131",
		[varBsPrimaryTextEmphasis]: "#5d1434",
		[varBsSecondaryBgRgb]: "233, 233, 232",
		[varBsSecondaryBgSubtle]: "rgba(255, 255, 255, 0.88)",
		[varBsSecondaryBorderSubtle]: "rgba(255, 255, 255, 0.76)",
		[varBsSecondaryColor]: "rgba(255, 255, 255, 0.75)",
		[varBsSecondaryRgb]: "255, 255, 255",
		[varBsSecondaryTextEmphasis]: "rgba(36, 36, 36, 0.76)",
		[varBsSuccessBgSubtle]: "#d9f7ed",
		[varBsSuccessBorderSubtle]: "#b3efdc",
		[varBsSuccessRgb]: "65, 215, 167",
		[varBsSuccessTextEmphasis]: "#1a5643",
		[varBsTertiaryBgRgb]: "248, 249, 250",
		[varBsTertiaryColor]: "rgba(255, 255, 255, 0.5)",
		[varBsWarningBgSubtle]: "#fff3cd",
		[varBsWarningBorderSubtle]: "#ffe69c",
		[varBsWarningRgb]: "255, 193, 7",
		[varBsWarningTextEmphasis]: "#664d03",
		[varBsWhiteRgb]: "255, 255, 255",
	},
})
