import { globalStyle, style } from '@vanilla-extract/css'
import {
	varBsBlack,
	varBsBlackRgb,
	varBsBlue,
	varBsBodyBg,
	varBsBodyBgRgb,
	varBsBodyColor,
	varBsBodyColorRgb,
	varBsBodyFontFamily,
	varBsBodyFontSize,
	varBsBodyFontWeight,
	varBsBodyLineHeight,
	varBsBorderColor,
	varBsBorderColorTranslucent,
	varBsBorderRadius,
	varBsBorderRadiusLg,
	varBsBorderRadiusPill,
	varBsBorderRadiusSm,
	varBsBorderRadiusXl,
	varBsBorderRadiusXxl,
	varBsBorderStyle,
	varBsBorderWidth,
	varBsBoxShadow,
	varBsBoxShadowInset,
	varBsBoxShadowLg,
	varBsBoxShadowSm,
	varBsCarouselCaptionColor,
	varBsCarouselIndicatorActiveBg,
	varBsCodeColor,
	varBsCyan,
	varBsDanger,
	varBsDangerBgSubtle,
	varBsDangerBorderSubtle,
	varBsDangerRgb,
	varBsDangerTextEmphasis,
	varBsDark,
	varBsDarkBgSubtle,
	varBsDarkBorderSubtle,
	varBsDarkRgb,
	varBsDarkTextEmphasis,
	varBsEmphasisColor,
	varBsEmphasisColorRgb,
	varBsFocusRingColor,
	varBsFocusRingOpacity,
	varBsFocusRingWidth,
	varBsFontMonospace,
	varBsFontSansSerif,
	varBsGradient,
	varBsGray,
	varBsGrayDark,
	varBsGreen,
	varBsHeadingColor,
	varBsHighlightBg,
	varBsHighlightColor,
	varBsIndigo,
	varBsInfo,
	varBsInfoBgSubtle,
	varBsInfoBorderSubtle,
	varBsInfoRgb,
	varBsInfoTextEmphasis,
	varBsLight,
	varBsLightBgSubtle,
	varBsLightBorderSubtle,
	varBsLightRgb,
	varBsLightTextEmphasis,
	varBsLinkColor,
	varBsLinkColorRgb,
	varBsLinkDecoration,
	varBsLinkHoverColor,
	varBsLinkHoverColorRgb,
	varBsOrange,
	varBsPink,
	varBsPrimary,
	varBsPrimaryBgSubtle,
	varBsPrimaryBorderSubtle,
	varBsPrimaryRgb,
	varBsPrimaryTextEmphasis,
	varBsPurple,
	varBsRed,
	varBsSecondary,
	varBsSecondaryBg,
	varBsSecondaryBgSubtle,
	varBsSecondaryBorderSubtle,
	varBsSecondaryColor,
	varBsSecondaryRgb,
	varBsSecondaryTextEmphasis,
	varBsSuccess,
	varBsSuccessBgSubtle,
	varBsSuccessBorderSubtle,
	varBsSuccessRgb,
	varBsSuccessTextEmphasis,
	varBsTeal,
	varBsTertiaryBg,
	varBsTertiaryColor,
	varBsWarning,
	varBsWarningBgSubtle,
	varBsWarningBorderSubtle,
	varBsWarningRgb,
	varBsWarningTextEmphasis,
	varBsWhite,
	varBsWhiteRgb,
	varBsYellow,
} from '../../theme-contract/_vars.css'
import {
	varBsFormInvalidBorderColor,
	varBsFormInvalidColor,
	varBsFormValidBorderColor,
	varBsFormValidColor,
} from '../../theme-contract/forms/_vars.css'
import { bodyFrame, bodyText, vars } from '../../theme-contract/theme-contract.css'
import { modalOpenHook } from '../../theme-contract/ui/modal/contract.css'

// Quartz theme scope class.
// Zero-style identifier used as a stable selector prefix.
export const quartzScope = style({})

// Global Bootstrap CSS custom properties (`--bs-*`) are assigned on the
// dedicated vars contract class to keep root var hosting separate from body
// layout/background styles.
globalStyle(`${quartzScope}${vars}`, {
	vars: {
		[varBsBlue]: "#3a8fd9",
		[varBsIndigo]: "#6610f2",
		[varBsPurple]: "#686dc3",
		[varBsPink]: "#e83283",
		[varBsRed]: "#fc346f",
		[varBsOrange]: "#fd7e14",
		[varBsYellow]: "#ffc107",
		[varBsGreen]: "#41d7a7",
		[varBsTeal]: "#528fb3",
		[varBsCyan]: "#39cbfb",
		[varBsBlack]: "#000",
		[varBsWhite]: "#fff",
		[varBsGray]: "#6c757d",
		[varBsGrayDark]: "#343a40",
		[varBsPrimary]: "#e83283",
		[varBsSecondary]: "rgba(255, 255, 255, 0.4)",
		[varBsSuccess]: "#41d7a7",
		[varBsInfo]: "#39cbfb",
		[varBsWarning]: "#ffc107",
		[varBsDanger]: "#fd7e14",
		[varBsLight]: "#e9e9e8",
		[varBsDark]: "#212529",
		[varBsPrimaryRgb]: "232, 50, 131",
		[varBsSecondaryRgb]: "255, 255, 255",
		[varBsSuccessRgb]: "65, 215, 167",
		[varBsInfoRgb]: "57, 203, 251",
		[varBsWarningRgb]: "255, 193, 7",
		[varBsDangerRgb]: "253, 126, 20",
		[varBsLightRgb]: "233, 233, 232",
		[varBsDarkRgb]: "33, 37, 41",
		[varBsPrimaryTextEmphasis]: "#5d1434",
		[varBsSecondaryTextEmphasis]: "rgba(36, 36, 36, 0.76)",
		[varBsSuccessTextEmphasis]: "#1a5643",
		[varBsInfoTextEmphasis]: "#175164",
		[varBsWarningTextEmphasis]: "#664d03",
		[varBsDangerTextEmphasis]: "#653208",
		[varBsLightTextEmphasis]: "#495057",
		[varBsDarkTextEmphasis]: "#495057",
		[varBsPrimaryBgSubtle]: "#fad6e6",
		[varBsSecondaryBgSubtle]: "rgba(255, 255, 255, 0.88)",
		[varBsSuccessBgSubtle]: "#d9f7ed",
		[varBsInfoBgSubtle]: "#d7f5fe",
		[varBsWarningBgSubtle]: "#fff3cd",
		[varBsDangerBgSubtle]: "#ffe5d0",
		[varBsLightBgSubtle]: "#fcfcfd",
		[varBsDarkBgSubtle]: "#ced4da",
		[varBsPrimaryBorderSubtle]: "#f6adcd",
		[varBsSecondaryBorderSubtle]: "rgba(255, 255, 255, 0.76)",
		[varBsSuccessBorderSubtle]: "#b3efdc",
		[varBsInfoBorderSubtle]: "#b0eafd",
		[varBsWarningBorderSubtle]: "#ffe69c",
		[varBsDangerBorderSubtle]: "#fecba1",
		[varBsLightBorderSubtle]: "#e9e9e8",
		[varBsDarkBorderSubtle]: "#adb5bd",
		[varBsWhiteRgb]: "255, 255, 255",
		[varBsBlackRgb]: "0, 0, 0",
		[varBsFontSansSerif]: "system-ui, -apple-system, \"Segoe UI\", Roboto, \"Helvetica Neue\", \"Noto Sans\", \"Liberation Sans\", Arial, sans-serif, \"Apple Color Emoji\", \"Segoe UI Emoji\", \"Segoe UI Symbol\", \"Noto Color Emoji\"",
		[varBsFontMonospace]: "SFMono-Regular, Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace",
		[varBsGradient]: "linear-gradient(180deg, rgba(255, 255, 255, 0.15), rgba(255, 255, 255, 0))",
		[varBsBodyFontFamily]: varBsFontSansSerif,
		[varBsBodyFontSize]: "1rem",
		[varBsBodyFontWeight]: 400,
		[varBsBodyLineHeight]: 1.5,
		[varBsBodyColor]: "#fff",
		[varBsBodyColorRgb]: "255, 255, 255",
		[varBsBodyBg]: "#686dc3",
		[varBsBodyBgRgb]: "104, 109, 195",
		[varBsEmphasisColor]: "#000",
		[varBsEmphasisColorRgb]: "0, 0, 0",
		[varBsSecondaryColor]: "rgba(255, 255, 255, 0.75)",
		[varBsSecondaryBg]: "#e9e9e8",
		[varBsTertiaryColor]: "rgba(255, 255, 255, 0.5)",
		[varBsTertiaryBg]: "#f8f9fa",
		[varBsHeadingColor]: "inherit",
		[varBsLinkColor]: "#fff",
		[varBsLinkColorRgb]: "255, 255, 255",
		[varBsLinkDecoration]: "underline",
		[varBsLinkHoverColor]: "#cccccc",
		[varBsLinkHoverColorRgb]: "204, 204, 204",
		[varBsCodeColor]: "#e83283",
		[varBsHighlightColor]: "#fff",
		[varBsHighlightBg]: "#fff3cd",
		[varBsBorderWidth]: "1px",
		[varBsBorderStyle]: "solid",
		[varBsBorderColor]: "rgba(255, 255, 255, 0.2)",
		[varBsBorderColorTranslucent]: "rgba(0, 0, 0, 0.175)",
		[varBsBorderRadius]: "0.5rem",
		[varBsBorderRadiusSm]: "0.6rem",
		[varBsBorderRadiusLg]: "0.7rem",
		[varBsBorderRadiusXl]: "1rem",
		[varBsBorderRadiusXxl]: "2rem",
		[varBsBorderRadiusPill]: "50rem",
		[varBsBoxShadow]: "1px 3px 24px -1px rgba(0, 0, 0, 0.15)",
		[varBsBoxShadowSm]: "0 1px 1px rgba(0, 0, 0, 0.1)",
		[varBsBoxShadowLg]: "0 1rem 3rem rgba(0, 0, 0, 0.175)",
		[varBsBoxShadowInset]: "inset 0 1px 2px rgba(0, 0, 0, 0.075)",
		[varBsFocusRingWidth]: "0.25rem",
		[varBsFocusRingOpacity]: 0.25,
		[varBsFocusRingColor]: "rgba(232, 50, 131, 0.25)",
		[varBsCarouselIndicatorActiveBg]: "#fff",
		[varBsCarouselCaptionColor]: "#fff",
		[varBsFormValidColor]: "#41d7a7",
		[varBsFormValidBorderColor]: "#41d7a7",
		[varBsFormInvalidColor]: "#fd7e14",
		[varBsFormInvalidBorderColor]: "#fd7e14",
	},
})

// ── Root / body styles ────────────────────────────────────────────────────────
// bodyText = typography; bodyFrame = page canvas (Ve2Shell). Do not add padding
// here — baseline screenshots have no padded wrapper around bd-example.

globalStyle(`${quartzScope}${bodyText}`, {
	fontFamily: varBsBodyFontFamily,
	fontSize: varBsBodyFontSize,
	fontWeight: varBsBodyFontWeight,
	lineHeight: varBsBodyLineHeight,
	color: varBsBodyColor,
})

globalStyle(`${quartzScope}${bodyFrame}`, {
	backgroundColor: varBsBodyBg,
	margin: 0,
	minHeight: '100vh',
})

// Bootstrap Modal JS adds modalOpenHook to <body> without theme scope.
globalStyle(`${modalOpenHook}`, {
	fontFamily: varBsBodyFontFamily,
	fontSize: varBsBodyFontSize,
	fontWeight: varBsBodyFontWeight,
	lineHeight: varBsBodyLineHeight,
	color: varBsBodyColor,
	backgroundColor: varBsBodyBg,
	margin: 0,
})
