// GERADO por scripts/gen-public-vars.mjs — NÃO editar à mão.
import { globalStyle } from '@vanilla-extract/css'
import { cyborgScope } from './scope.css'
import { varBsBlackRgb, varBsBodyBgRgb, varBsBodyColorRgb, varBsBorderColor, varBsBorderRadius, varBsBorderRadiusLg, varBsBorderRadiusPill, varBsBorderRadiusSm, varBsBorderRadiusXl, varBsBorderRadiusXxl, varBsBorderStyle, varBsBorderWidth, varBsBoxShadow, varBsBoxShadowLg, varBsBoxShadowSm, varBsDangerBgSubtle, varBsDangerBorderSubtle, varBsDangerRgb, varBsDangerTextEmphasis, varBsDarkBgSubtle, varBsDarkBorderSubtle, varBsDarkRgb, varBsDarkTextEmphasis, varBsEmphasisColor, varBsEmphasisColorRgb, varBsFocusRingColor, varBsFocusRingOpacity, varBsFontMonospace, varBsGradient, varBsInfoBgSubtle, varBsInfoBorderSubtle, varBsInfoRgb, varBsInfoTextEmphasis, varBsLightBgSubtle, varBsLightBorderSubtle, varBsLightRgb, varBsLightTextEmphasis, varBsLinkColorRgb, varBsPrimaryBgSubtle, varBsPrimaryBorderSubtle, varBsPrimaryRgb, varBsPrimaryTextEmphasis, varBsSecondaryBgRgb, varBsSecondaryBgSubtle, varBsSecondaryBorderSubtle, varBsSecondaryColor, varBsSecondaryRgb, varBsSecondaryTextEmphasis, varBsSuccessBgSubtle, varBsSuccessBorderSubtle, varBsSuccessRgb, varBsSuccessTextEmphasis, varBsTertiaryBgRgb, varBsTertiaryColor, varBsWarningBgSubtle, varBsWarningBorderSubtle, varBsWarningRgb, varBsWarningTextEmphasis, varBsWhiteRgb } from '../../theme-contract/_public-vars.css'

globalStyle(cyborgScope, {
	vars: {
		[varBsBlackRgb]: "0, 0, 0",
		[varBsBodyBgRgb]: "6, 6, 6",
		[varBsBodyColorRgb]: "173, 175, 174",
		[varBsBorderColor]: "#dee2e6",
		[varBsBorderRadius]: "0.375rem",
		[varBsBorderRadiusLg]: "0.5rem",
		[varBsBorderRadiusPill]: "50rem",
		[varBsBorderRadiusSm]: "0.25rem",
		[varBsBorderRadiusXl]: "1rem",
		[varBsBorderRadiusXxl]: "2rem",
		[varBsBorderStyle]: "solid",
		[varBsBorderWidth]: "1px",
		[varBsBoxShadow]: "0 0.5rem 1rem rgba(0, 0, 0, 0.15)",
		[varBsBoxShadowLg]: "0 1rem 3rem rgba(0, 0, 0, 0.175)",
		[varBsBoxShadowSm]: "0 0.125rem 0.25rem rgba(0, 0, 0, 0.075)",
		[varBsDangerBgSubtle]: "#f5cccc",
		[varBsDangerBorderSubtle]: "#eb9999",
		[varBsDangerRgb]: "204, 0, 0",
		[varBsDangerTextEmphasis]: "#520000",
		[varBsDarkBgSubtle]: "#adafae",
		[varBsDarkBorderSubtle]: "#888",
		[varBsDarkRgb]: "173, 175, 174",
		[varBsDarkTextEmphasis]: "#282828",
		[varBsEmphasisColor]: "#000",
		[varBsEmphasisColorRgb]: "0, 0, 0",
		[varBsFocusRingColor]: "rgba(42, 159, 214, 0.25)",
		[varBsFocusRingOpacity]: "0.25",
		[varBsFontMonospace]: "SFMono-Regular, Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace",
		[varBsGradient]: "linear-gradient(180deg, rgba(255, 255, 255, 0.15), rgba(255, 255, 255, 0))",
		[varBsInfoBgSubtle]: "#ebd6f5",
		[varBsInfoBorderSubtle]: "#d6adeb",
		[varBsInfoRgb]: "153, 51, 204",
		[varBsInfoTextEmphasis]: "#3d1452",
		[varBsLightBgSubtle]: "#fcfcfd",
		[varBsLightBorderSubtle]: "#e9ecef",
		[varBsLightRgb]: "34, 34, 34",
		[varBsLightTextEmphasis]: "#282828",
		[varBsLinkColorRgb]: "42, 159, 214",
		[varBsPrimaryBgSubtle]: "#d4ecf7",
		[varBsPrimaryBorderSubtle]: "#aad9ef",
		[varBsPrimaryRgb]: "42, 159, 214",
		[varBsPrimaryTextEmphasis]: "#114056",
		[varBsSecondaryBgRgb]: "233, 236, 239",
		[varBsSecondaryBgSubtle]: "#dddddd",
		[varBsSecondaryBorderSubtle]: "#bbbbbb",
		[varBsSecondaryColor]: "rgba(173, 175, 174, 0.75)",
		[varBsSecondaryRgb]: "85, 85, 85",
		[varBsSecondaryTextEmphasis]: "#222222",
		[varBsSuccessBgSubtle]: "#e4f0cc",
		[varBsSuccessBorderSubtle]: "#c9e199",
		[varBsSuccessRgb]: "119, 179, 0",
		[varBsSuccessTextEmphasis]: "#304800",
		[varBsTertiaryBgRgb]: "248, 249, 250",
		[varBsTertiaryColor]: "rgba(173, 175, 174, 0.5)",
		[varBsWarningBgSubtle]: "#ffe7cc",
		[varBsWarningBorderSubtle]: "#ffcf99",
		[varBsWarningRgb]: "255, 136, 0",
		[varBsWarningTextEmphasis]: "#663600",
		[varBsWhiteRgb]: "255, 255, 255",
	},
})
