import { globalStyle, style } from '@vanilla-extract/css'
import {
	varBsBlack,
	varBsBlackRgb,
	varBsBlue,
	varBsBodyBg,
	varBsBodyBgRgb,
	varBsBodyColor,
	varBsBodyColorRgb,
	varBsBodyFontFamily,
	varBsBodyFontSize,
	varBsBodyFontWeight,
	varBsBodyLineHeight,
	varBsBorderColor,
	varBsBorderColorTranslucent,
	varBsBorderRadius,
	varBsBorderRadiusLg,
	varBsBorderRadiusPill,
	varBsBorderRadiusSm,
	varBsBorderRadiusXl,
	varBsBorderRadiusXxl,
	varBsBorderStyle,
	varBsBorderWidth,
	varBsBoxShadow,
	varBsBoxShadowInset,
	varBsBoxShadowLg,
	varBsBoxShadowSm,
	varBsCarouselCaptionColor,
	varBsCarouselControlIconFilter,
	varBsCarouselIndicatorActiveBg,
	varBsCodeColor,
	varBsCyan,
	varBsDanger,
	varBsDangerBgSubtle,
	varBsDangerBorderSubtle,
	varBsDangerRgb,
	varBsDangerTextEmphasis,
	varBsDark,
	varBsDarkBgSubtle,
	varBsDarkBorderSubtle,
	varBsDarkRgb,
	varBsDarkTextEmphasis,
	varBsEmphasisColor,
	varBsEmphasisColorRgb,
	varBsFocusRingColor,
	varBsFocusRingOpacity,
	varBsFocusRingWidth,
	varBsFontMonospace,
	varBsFontSansSerif,
	varBsGradient,
	varBsGray,
	varBsGrayDark,
	varBsGreen,
	varBsHeadingColor,
	varBsHighlightBg,
	varBsHighlightColor,
	varBsIndigo,
	varBsInfo,
	varBsInfoBgSubtle,
	varBsInfoBorderSubtle,
	varBsInfoRgb,
	varBsInfoTextEmphasis,
	varBsLight,
	varBsLightBgSubtle,
	varBsLightBorderSubtle,
	varBsLightRgb,
	varBsLightTextEmphasis,
	varBsLinkColor,
	varBsLinkColorRgb,
	varBsLinkDecoration,
	varBsLinkHoverColor,
	varBsLinkHoverColorRgb,
	varBsOrange,
	varBsPink,
	varBsPrimary,
	varBsPrimaryBgSubtle,
	varBsPrimaryBorderSubtle,
	varBsPrimaryRgb,
	varBsPrimaryTextEmphasis,
	varBsPurple,
	varBsRed,
	varBsSecondary,
	varBsSecondaryBg,
	varBsSecondaryBgSubtle,
	varBsSecondaryBorderSubtle,
	varBsSecondaryColor,
	varBsSecondaryRgb,
	varBsSecondaryTextEmphasis,
	varBsSuccess,
	varBsSuccessBgSubtle,
	varBsSuccessBorderSubtle,
	varBsSuccessRgb,
	varBsSuccessTextEmphasis,
	varBsTeal,
	varBsTertiaryBg,
	varBsTertiaryColor,
	varBsWarning,
	varBsWarningBgSubtle,
	varBsWarningBorderSubtle,
	varBsWarningRgb,
	varBsWarningTextEmphasis,
	varBsWhite,
	varBsWhiteRgb,
	varBsYellow,
} from '../../theme-contract/_vars.css'
import {
	varBsFormInvalidBorderColor,
	varBsFormInvalidColor,
	varBsFormValidBorderColor,
	varBsFormValidColor,
} from '../../theme-contract/forms/_vars.css'
import { bodyFrame, bodyText, vars } from '../../theme-contract/theme-contract.css'
import { modalOpenHook } from '../../theme-contract/ui/modal/contract.css'

// Cyborg theme scope class.
// Zero-style identifier used as a stable selector prefix.
export const cyborgScope = style({})

// Global Bootstrap CSS custom properties (`--bs-*`) are assigned on the
// dedicated vars contract class to keep root var hosting separate from body
// layout/background styles.
globalStyle(`${cyborgScope}${vars}`, {
	vars: {
		[varBsBlue]: "#2a9fd6",
		[varBsIndigo]: "#6610f2",
		[varBsPurple]: "#6f42c1",
		[varBsPink]: "#e83e8c",
		[varBsRed]: "#c00",
		[varBsOrange]: "#fd7e14",
		[varBsYellow]: "#f80",
		[varBsGreen]: "#77b300",
		[varBsTeal]: "#20c997",
		[varBsCyan]: "#93c",
		[varBsBlack]: "#000",
		[varBsWhite]: "#fff",
		[varBsGray]: "#555",
		[varBsGrayDark]: "#222",
		[varBsPrimary]: "#2a9fd6",
		[varBsSecondary]: "#555",
		[varBsSuccess]: "#77b300",
		[varBsInfo]: "#93c",
		[varBsWarning]: "#f80",
		[varBsDanger]: "#c00",
		[varBsLight]: "#222",
		[varBsDark]: "#adafae",
		[varBsPrimaryRgb]: "42, 159, 214",
		[varBsSecondaryRgb]: "85, 85, 85",
		[varBsSuccessRgb]: "119, 179, 0",
		[varBsInfoRgb]: "153, 51, 204",
		[varBsWarningRgb]: "255, 136, 0",
		[varBsDangerRgb]: "204, 0, 0",
		[varBsLightRgb]: "34, 34, 34",
		[varBsDarkRgb]: "173, 175, 174",
		[varBsPrimaryTextEmphasis]: "#114056",
		[varBsSecondaryTextEmphasis]: "#222222",
		[varBsSuccessTextEmphasis]: "#304800",
		[varBsInfoTextEmphasis]: "#3d1452",
		[varBsWarningTextEmphasis]: "#663600",
		[varBsDangerTextEmphasis]: "#520000",
		[varBsLightTextEmphasis]: "#282828",
		[varBsDarkTextEmphasis]: "#282828",
		[varBsPrimaryBgSubtle]: "#d4ecf7",
		[varBsSecondaryBgSubtle]: "#dddddd",
		[varBsSuccessBgSubtle]: "#e4f0cc",
		[varBsInfoBgSubtle]: "#ebd6f5",
		[varBsWarningBgSubtle]: "#ffe7cc",
		[varBsDangerBgSubtle]: "#f5cccc",
		[varBsLightBgSubtle]: "#fcfcfd",
		[varBsDarkBgSubtle]: "#adafae",
		[varBsPrimaryBorderSubtle]: "#aad9ef",
		[varBsSecondaryBorderSubtle]: "#bbbbbb",
		[varBsSuccessBorderSubtle]: "#c9e199",
		[varBsInfoBorderSubtle]: "#d6adeb",
		[varBsWarningBorderSubtle]: "#ffcf99",
		[varBsDangerBorderSubtle]: "#eb9999",
		[varBsLightBorderSubtle]: "#e9ecef",
		[varBsDarkBorderSubtle]: "#888",
		[varBsWhiteRgb]: "255, 255, 255",
		[varBsBlackRgb]: "0, 0, 0",
		[varBsFontSansSerif]: "Roboto, -apple-system, BlinkMacSystemFont, \"Segoe UI\", \"Helvetica Neue\", Arial, sans-serif",
		[varBsFontMonospace]: "SFMono-Regular, Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace",
		[varBsGradient]: "linear-gradient(180deg, rgba(255, 255, 255, 0.15), rgba(255, 255, 255, 0))",
		[varBsBodyFontFamily]: varBsFontSansSerif,
		[varBsBodyFontSize]: "1rem",
		[varBsBodyFontWeight]: 400,
		[varBsBodyLineHeight]: 1.5,
		[varBsBodyColor]: "#adafae",
		[varBsBodyColorRgb]: "173, 175, 174",
		[varBsBodyBg]: "#060606",
		[varBsBodyBgRgb]: "6, 6, 6",
		[varBsEmphasisColor]: "#000",
		[varBsEmphasisColorRgb]: "0, 0, 0",
		[varBsSecondaryColor]: "rgba(173, 175, 174, 0.75)",
		[varBsSecondaryBg]: "#e9ecef",
		[varBsTertiaryColor]: "rgba(173, 175, 174, 0.5)",
		[varBsTertiaryBg]: "#f8f9fa",
		[varBsHeadingColor]: "#fff",
		[varBsLinkColor]: "#2a9fd6",
		[varBsLinkColorRgb]: "42, 159, 214",
		[varBsLinkDecoration]: "underline",
		[varBsLinkHoverColor]: "#227fab",
		[varBsLinkHoverColorRgb]: "34, 127, 171",
		[varBsCodeColor]: "#e83e8c",
		[varBsHighlightColor]: "#adafae",
		[varBsHighlightBg]: "#ffe7cc",
		[varBsBorderWidth]: "1px",
		[varBsBorderStyle]: "solid",
		[varBsBorderColor]: "#dee2e6",
		[varBsBorderColorTranslucent]: "rgba(0, 0, 0, 0.175)",
		[varBsBorderRadius]: "0.375rem",
		[varBsBorderRadiusSm]: "0.25rem",
		[varBsBorderRadiusLg]: "0.5rem",
		[varBsBorderRadiusXl]: "1rem",
		[varBsBorderRadiusXxl]: "2rem",
		[varBsBorderRadiusPill]: "50rem",
		[varBsBoxShadow]: "0 0.5rem 1rem rgba(0, 0, 0, 0.15)",
		[varBsBoxShadowSm]: "0 0.125rem 0.25rem rgba(0, 0, 0, 0.075)",
		[varBsBoxShadowLg]: "0 1rem 3rem rgba(0, 0, 0, 0.175)",
		[varBsBoxShadowInset]: "inset 0 1px 2px rgba(0, 0, 0, 0.075)",
		[varBsFocusRingWidth]: "0.25rem",
		[varBsFocusRingOpacity]: 0.25,
		[varBsFocusRingColor]: "rgba(42, 159, 214, 0.25)",
		[varBsCarouselIndicatorActiveBg]: "#fff",
		[varBsCarouselCaptionColor]: "#fff",
		[varBsCarouselControlIconFilter]: "",
		[varBsFormValidColor]: "#77b300",
		[varBsFormValidBorderColor]: "#77b300",
		[varBsFormInvalidColor]: "#c00",
		[varBsFormInvalidBorderColor]: "#c00",
	},
})

// ── Root / body styles ────────────────────────────────────────────────────────
// bodyText = typography; bodyFrame = page canvas (Ve2Shell). Do not add padding
// here — baseline screenshots have no padded wrapper around bd-example.

globalStyle(`${cyborgScope}${bodyText}`, {
	fontFamily: varBsBodyFontFamily,
	fontSize: varBsBodyFontSize,
	fontWeight: varBsBodyFontWeight,
	lineHeight: varBsBodyLineHeight,
	color: varBsBodyColor,
})

globalStyle(`${cyborgScope}${bodyFrame}`, {
	backgroundColor: varBsBodyBg,
	margin: 0,
	minHeight: '100vh',
})

// Bootstrap Modal JS adds modalOpenHook to <body> without theme scope.
globalStyle(`${modalOpenHook}`, {
	fontFamily: varBsBodyFontFamily,
	fontSize: varBsBodyFontSize,
	fontWeight: varBsBodyFontWeight,
	lineHeight: varBsBodyLineHeight,
	color: varBsBodyColor,
	backgroundColor: varBsBodyBg,
	margin: 0,
})
