import { createVar } from '@vanilla-extract/css'

export const varBsPopoverZindex = createVar()
export const varBsPopoverMaxWidth = createVar()
export const varBsPopoverFontSize = createVar()
export const varBsPopoverBg = createVar()
export const varBsPopoverBorderWidth = createVar()
export const varBsPopoverBorderColor = createVar()
export const varBsPopoverBorderRadius = createVar()
export const varBsPopoverInnerBorderRadius = createVar()
export const varBsPopoverBoxShadow = createVar()
export const varBsPopoverHeaderPaddingX = createVar()
export const varBsPopoverHeaderPaddingY = createVar()
export const varBsPopoverHeaderFontSize = createVar()
export const varBsPopoverHeaderColor = createVar()
export const varBsPopoverHeaderBg = createVar()
export const varBsPopoverBodyPaddingX = createVar()
export const varBsPopoverBodyPaddingY = createVar()
export const varBsPopoverBodyColor = createVar()
export const varBsPopoverArrowWidth = createVar()
export const varBsPopoverArrowHeight = createVar()
export const varBsPopoverArrowBorder = createVar()
