import { style } from '@vanilla-extract/css'
import {
varBsBorderColor,
varBsBorderColorTranslucent,
varBsBorderRadius,
varBsBorderRadius2xl,
varBsBorderRadiusLg,
varBsBorderRadiusPill,
varBsBorderRadiusSm,
varBsBorderRadiusXl,
varBsBorderRadiusXxl,
varBsBorderStyle,
varBsBorderWidth,
varBsBodyBg,
varBsBodyColor,
varBsBodyColorRgb,
varBsBodyFontWeight,
varBsBoxShadow,
varBsBoxShadowInset,
varBsBoxShadowLg,
varBsBoxShadowSm,
varBsCodeColor,
varBsDanger,
varBsDangerBgSubtle,
varBsDangerBorderSubtle,
varBsDangerRgb,
varBsDangerTextEmphasis,
varBsDark,
varBsDarkBgSubtle,
varBsDarkBorderSubtle,
varBsDarkRgb,
varBsDarkTextEmphasis,
varBsEmphasisColor,
varBsFocusRingColor,
varBsFocusRingOpacity,
varBsFocusRingWidth,
varBsFontSansSerif,
varBsInfo,
varBsInfoBgSubtle,
varBsInfoBorderSubtle,
varBsInfoRgb,
varBsInfoTextEmphasis,
varBsLight,
varBsLightBgSubtle,
varBsLightBorderSubtle,
varBsLightRgb,
varBsLightTextEmphasis,
varBsLinkColor,
varBsLinkColorRgb,
varBsLinkHoverColor,
varBsLinkHoverColorRgb,
varBsPrimary,
varBsPrimaryBgSubtle,
varBsPrimaryBorderSubtle,
varBsPrimaryRgb,
varBsPrimaryTextEmphasis,
varBsSecondary,
varBsSecondaryBg,
varBsSecondaryBgSubtle,
varBsSecondaryBorderSubtle,
varBsSecondaryColor,
varBsSecondaryRgb,
varBsSecondaryTextEmphasis,
varBsSuccess,
varBsSuccessBgSubtle,
varBsSuccessBorderSubtle,
varBsSuccessRgb,
varBsSuccessTextEmphasis,
varBsTertiaryBg,
varBsTertiaryColor,
varBsWarning,
varBsWarningBgSubtle,
varBsWarningBorderSubtle,
varBsWarningRgb,
varBsWarningTextEmphasis,
} from '../../theme-contract/_vars.css'
import { bsTheme as bootstrapBsTheme } from '../bootstrap/_vars.css'

export const bsTheme = style([bootstrapBsTheme, {
vars: {
[varBsPrimary]: '#333',
[varBsSecondary]: '#555',
[varBsSuccess]: '#28a745',
[varBsInfo]: '#17a2b8',
[varBsWarning]: '#ffc107',
[varBsDanger]: '#dc3545',
[varBsLight]: '#fff',
[varBsDark]: '#555',
[varBsPrimaryRgb]: '51, 51, 51',
[varBsSecondaryRgb]: '85, 85, 85',
[varBsSuccessRgb]: '40, 167, 69',
[varBsInfoRgb]: '23, 162, 184',
[varBsWarningRgb]: '255, 193, 7',
[varBsDangerRgb]: '220, 53, 69',
[varBsLightRgb]: '255, 255, 255',
[varBsDarkRgb]: '85, 85, 85',
[varBsPrimaryTextEmphasis]: '#141414',
[varBsSecondaryTextEmphasis]: '#222222',
[varBsSuccessTextEmphasis]: '#10431c',
[varBsInfoTextEmphasis]: '#09414a',
[varBsWarningTextEmphasis]: '#664d03',
[varBsDangerTextEmphasis]: '#58151c',
[varBsLightTextEmphasis]: '#555',
[varBsDarkTextEmphasis]: '#555',
[varBsPrimaryBgSubtle]: '#d6d6d6',
[varBsSecondaryBgSubtle]: '#dddddd',
[varBsSuccessBgSubtle]: '#d4edda',
[varBsInfoBgSubtle]: '#d1ecf1',
[varBsWarningBgSubtle]: '#fff3cd',
[varBsDangerBgSubtle]: '#f8d7da',
[varBsLightBgSubtle]: '#fcfcfd',
[varBsDarkBgSubtle]: '#ccc',
[varBsPrimaryBorderSubtle]: '#adadad',
[varBsSecondaryBorderSubtle]: '#bbbbbb',
[varBsSuccessBorderSubtle]: '#a9dcb5',
[varBsInfoBorderSubtle]: '#a2dae3',
[varBsWarningBorderSubtle]: '#ffe69c',
[varBsDangerBorderSubtle]: '#f1aeb5',
[varBsLightBorderSubtle]: '#f7f7f9',
[varBsDarkBorderSubtle]: '#aaa',
[varBsBodyColor]: '#212529',
[varBsBodyColorRgb]: '33, 37, 41',
[varBsBodyBg]: '#fff',
[varBsBorderWidth]: '2px',
[varBsBorderStyle]: 'solid',
[varBsBorderColor]: '#dee2e6',
[varBsBorderColorTranslucent]: 'rgba(0, 0, 0, 0.175)',
[varBsBorderRadius]: '25px',
[varBsBorderRadiusSm]: '15px',
[varBsBorderRadiusLg]: '35px',
[varBsBorderRadiusXl]: '1rem',
[varBsBorderRadiusXxl]: '2rem',
[varBsBorderRadius2xl]: '2rem',
[varBsBorderRadiusPill]: '50rem',
[varBsBoxShadow]: '0 0.5rem 1rem rgba(0, 0, 0, 0.15)',
[varBsBoxShadowSm]: '0 0.125rem 0.25rem rgba(0, 0, 0, 0.075)',
[varBsBoxShadowLg]: '0 1rem 3rem rgba(0, 0, 0, 0.175)',
[varBsBoxShadowInset]: 'inset 0 1px 2px rgba(0, 0, 0, 0.075)',
[varBsFocusRingWidth]: '0.25rem',
[varBsFocusRingOpacity]: '0.25',
[varBsFocusRingColor]: 'rgba(51, 51, 51, 0.25)',
[varBsEmphasisColor]: '#000',
[varBsSecondaryColor]: 'rgba(33, 37, 41, 0.75)',
[varBsSecondaryBg]: '#f7f7f9',
[varBsTertiaryColor]: 'rgba(33, 37, 41, 0.5)',
[varBsTertiaryBg]: '#f8f9fa',
[varBsLinkColor]: '#333',
[varBsLinkColorRgb]: '51, 51, 51',
[varBsLinkHoverColor]: '#292929',
[varBsLinkHoverColorRgb]: '41, 41, 41',
[varBsFontSansSerif]: 'Neucha, -apple-system, system-ui, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif',
[varBsBodyFontWeight]: '700',
[varBsCodeColor]: '#e83e8c',
},
}])
