// GERADO por scripts/gen-public-vars.mjs — NÃO editar à mão.
import { globalStyle } from '@vanilla-extract/css'
import { ceruleanScope } from './scope.css'
import { varBsBlackRgb, varBsBodyBgRgb, varBsBodyColorRgb, varBsBorderColor, varBsBorderRadius, varBsBorderRadiusLg, varBsBorderRadiusPill, varBsBorderRadiusSm, varBsBorderRadiusXl, varBsBorderRadiusXxl, varBsBorderStyle, varBsBorderWidth, varBsBoxShadow, varBsBoxShadowLg, varBsBoxShadowSm, varBsDangerBgSubtle, varBsDangerBorderSubtle, varBsDangerRgb, varBsDangerTextEmphasis, varBsDarkBgSubtle, varBsDarkBorderSubtle, varBsDarkRgb, varBsDarkTextEmphasis, varBsEmphasisColor, varBsEmphasisColorRgb, varBsFocusRingColor, varBsFocusRingOpacity, varBsFontMonospace, varBsGradient, varBsInfoBgSubtle, varBsInfoBorderSubtle, varBsInfoRgb, varBsInfoTextEmphasis, varBsLightBgSubtle, varBsLightBorderSubtle, varBsLightRgb, varBsLightTextEmphasis, varBsLinkColorRgb, varBsPrimaryBgSubtle, varBsPrimaryBorderSubtle, varBsPrimaryRgb, varBsPrimaryTextEmphasis, varBsSecondaryBgRgb, varBsSecondaryBgSubtle, varBsSecondaryBorderSubtle, varBsSecondaryColor, varBsSecondaryRgb, varBsSecondaryTextEmphasis, varBsSuccessBgSubtle, varBsSuccessBorderSubtle, varBsSuccessRgb, varBsSuccessTextEmphasis, varBsTertiaryBgRgb, varBsTertiaryColor, varBsWarningBgSubtle, varBsWarningBorderSubtle, varBsWarningRgb, varBsWarningTextEmphasis, varBsWhiteRgb } from '../../theme-contract/_public-vars.css'

globalStyle(ceruleanScope, {
	vars: {
		[varBsBlackRgb]: "0, 0, 0",
		[varBsBodyBgRgb]: "255, 255, 255",
		[varBsBodyColorRgb]: "73, 80, 87",
		[varBsBorderColor]: "#dee2e6",
		[varBsBorderRadius]: "0.375rem",
		[varBsBorderRadiusLg]: "0.5rem",
		[varBsBorderRadiusPill]: "50rem",
		[varBsBorderRadiusSm]: "0.25rem",
		[varBsBorderRadiusXl]: "1rem",
		[varBsBorderRadiusXxl]: "2rem",
		[varBsBorderStyle]: "solid",
		[varBsBorderWidth]: "1px",
		[varBsBoxShadow]: "0 0.5rem 1rem rgba(0, 0, 0, 0.15)",
		[varBsBoxShadowLg]: "0 1rem 3rem rgba(0, 0, 0, 0.175)",
		[varBsBoxShadowSm]: "0 0.125rem 0.25rem rgba(0, 0, 0, 0.075)",
		[varBsDangerBgSubtle]: "#f4d2d3",
		[varBsDangerBorderSubtle]: "#e9a4a7",
		[varBsDangerRgb]: "199, 28, 34",
		[varBsDangerTextEmphasis]: "#500b0e",
		[varBsDarkBgSubtle]: "#ced4da",
		[varBsDarkBorderSubtle]: "#adb5bd",
		[varBsDarkRgb]: "52, 58, 64",
		[varBsDarkTextEmphasis]: "#495057",
		[varBsEmphasisColor]: "#000",
		[varBsEmphasisColorRgb]: "0, 0, 0",
		[varBsFocusRingColor]: "rgba(47, 164, 231, 0.25)",
		[varBsFocusRingOpacity]: "0.25",
		[varBsFontMonospace]: "SFMono-Regular, Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace",
		[varBsGradient]: "linear-gradient(180deg, rgba(255, 255, 255, 0.15), rgba(255, 255, 255, 0))",
		[varBsInfoBgSubtle]: "#cdd8e3",
		[varBsInfoBorderSubtle]: "#9ab1c7",
		[varBsInfoRgb]: "3, 60, 115",
		[varBsInfoTextEmphasis]: "#01182e",
		[varBsLightBgSubtle]: "#fcfcfd",
		[varBsLightBorderSubtle]: "#e9ecef",
		[varBsLightRgb]: "248, 249, 250",
		[varBsLightTextEmphasis]: "#495057",
		[varBsLinkColorRgb]: "47, 164, 231",
		[varBsPrimaryBgSubtle]: "#d5edfa",
		[varBsPrimaryBorderSubtle]: "#acdbf5",
		[varBsPrimaryRgb]: "47, 164, 231",
		[varBsPrimaryTextEmphasis]: "#13425c",
		[varBsSecondaryBgRgb]: "233, 236, 239",
		[varBsSecondaryBgSubtle]: "#fbfbfc",
		[varBsSecondaryBorderSubtle]: "#f6f7f9",
		[varBsSecondaryColor]: "rgba(73, 80, 87, 0.75)",
		[varBsSecondaryRgb]: "233, 236, 239",
		[varBsSecondaryTextEmphasis]: "#5d5e60",
		[varBsSuccessBgSubtle]: "#e3eed7",
		[varBsSuccessBorderSubtle]: "#c7dcb0",
		[varBsSuccessRgb]: "115, 168, 57",
		[varBsSuccessTextEmphasis]: "#2e4317",
		[varBsTertiaryBgRgb]: "248, 249, 250",
		[varBsTertiaryColor]: "rgba(73, 80, 87, 0.5)",
		[varBsWarningBgSubtle]: "#f8ddcc",
		[varBsWarningBorderSubtle]: "#f1bb99",
		[varBsWarningRgb]: "221, 86, 0",
		[varBsWarningTextEmphasis]: "#582200",
		[varBsWhiteRgb]: "255, 255, 255",
	},
})
