// GERADO por scripts/gen-public-vars.mjs — NÃO editar à mão.
import { globalStyle } from '@vanilla-extract/css'
import { cosmoScope } from './scope.css'
import { varBsBlackRgb, varBsBodyBgRgb, varBsBodyColorRgb, varBsBorderColor, varBsBorderRadius, varBsBorderRadiusLg, varBsBorderRadiusPill, varBsBorderRadiusSm, varBsBorderRadiusXl, varBsBorderRadiusXxl, varBsBorderStyle, varBsBorderWidth, varBsBoxShadow, varBsBoxShadowLg, varBsBoxShadowSm, varBsDangerBgSubtle, varBsDangerBorderSubtle, varBsDangerRgb, varBsDangerTextEmphasis, varBsDarkBgSubtle, varBsDarkBorderSubtle, varBsDarkRgb, varBsDarkTextEmphasis, varBsEmphasisColor, varBsEmphasisColorRgb, varBsFocusRingColor, varBsFocusRingOpacity, varBsFontMonospace, varBsGradient, varBsInfoBgSubtle, varBsInfoBorderSubtle, varBsInfoRgb, varBsInfoTextEmphasis, varBsLightBgSubtle, varBsLightBorderSubtle, varBsLightRgb, varBsLightTextEmphasis, varBsLinkColorRgb, varBsPrimaryBgSubtle, varBsPrimaryBorderSubtle, varBsPrimaryRgb, varBsPrimaryTextEmphasis, varBsSecondaryBgRgb, varBsSecondaryBgSubtle, varBsSecondaryBorderSubtle, varBsSecondaryColor, varBsSecondaryRgb, varBsSecondaryTextEmphasis, varBsSuccessBgSubtle, varBsSuccessBorderSubtle, varBsSuccessRgb, varBsSuccessTextEmphasis, varBsTertiaryBgRgb, varBsTertiaryColor, varBsWarningBgSubtle, varBsWarningBorderSubtle, varBsWarningRgb, varBsWarningTextEmphasis, varBsWhiteRgb } from '../../theme-contract/_public-vars.css'

globalStyle(cosmoScope, {
	vars: {
		[varBsBlackRgb]: "0, 0, 0",
		[varBsBodyBgRgb]: "255, 255, 255",
		[varBsBodyColorRgb]: "55, 58, 60",
		[varBsBorderColor]: "#dee2e6",
		[varBsBorderRadius]: "0.375rem",
		[varBsBorderRadiusLg]: "0.5rem",
		[varBsBorderRadiusPill]: "50rem",
		[varBsBorderRadiusSm]: "0.25rem",
		[varBsBorderRadiusXl]: "1rem",
		[varBsBorderRadiusXxl]: "2rem",
		[varBsBorderStyle]: "solid",
		[varBsBorderWidth]: "1px",
		[varBsBoxShadow]: "0 0.5rem 1rem rgba(0, 0, 0, 0.15)",
		[varBsBoxShadowLg]: "0 1rem 3rem rgba(0, 0, 0, 0.175)",
		[varBsBoxShadowSm]: "0 0.125rem 0.25rem rgba(0, 0, 0, 0.075)",
		[varBsDangerBgSubtle]: "#ffccd7",
		[varBsDangerBorderSubtle]: "#ff99b0",
		[varBsDangerRgb]: "255, 0, 57",
		[varBsDangerTextEmphasis]: "#660017",
		[varBsDarkBgSubtle]: "#ced4da",
		[varBsDarkBorderSubtle]: "#adb5bd",
		[varBsDarkRgb]: "55, 58, 60",
		[varBsDarkTextEmphasis]: "#495057",
		[varBsEmphasisColor]: "#000",
		[varBsEmphasisColorRgb]: "0, 0, 0",
		[varBsFocusRingColor]: "rgba(39, 128, 227, 0.25)",
		[varBsFocusRingOpacity]: "0.25",
		[varBsFontMonospace]: "SFMono-Regular, Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace",
		[varBsGradient]: "linear-gradient(180deg, rgba(255, 255, 255, 0.15), rgba(255, 255, 255, 0))",
		[varBsInfoBgSubtle]: "#ebddf1",
		[varBsInfoBorderSubtle]: "#d6bbe4",
		[varBsInfoRgb]: "153, 84, 187",
		[varBsInfoTextEmphasis]: "#3d224b",
		[varBsLightBgSubtle]: "#fcfcfd",
		[varBsLightBorderSubtle]: "#e9ecef",
		[varBsLightRgb]: "248, 249, 250",
		[varBsLightTextEmphasis]: "#495057",
		[varBsLinkColorRgb]: "39, 128, 227",
		[varBsPrimaryBgSubtle]: "#d4e6f9",
		[varBsPrimaryBorderSubtle]: "#a9ccf4",
		[varBsPrimaryRgb]: "39, 128, 227",
		[varBsPrimaryTextEmphasis]: "#10335b",
		[varBsSecondaryBgRgb]: "233, 236, 239",
		[varBsSecondaryBgSubtle]: "#d7d8d8",
		[varBsSecondaryBorderSubtle]: "#afb0b1",
		[varBsSecondaryColor]: "rgba(55, 58, 60, 0.75)",
		[varBsSecondaryRgb]: "55, 58, 60",
		[varBsSecondaryTextEmphasis]: "#161718",
		[varBsSuccessBgSubtle]: "#d9f0d1",
		[varBsSuccessBorderSubtle]: "#b2e2a3",
		[varBsSuccessRgb]: "63, 182, 24",
		[varBsSuccessTextEmphasis]: "#19490a",
		[varBsTertiaryBgRgb]: "248, 249, 250",
		[varBsTertiaryColor]: "rgba(55, 58, 60, 0.5)",
		[varBsWarningBgSubtle]: "#ffe3d1",
		[varBsWarningBorderSubtle]: "#ffc8a3",
		[varBsWarningRgb]: "255, 117, 24",
		[varBsWarningTextEmphasis]: "#662f0a",
		[varBsWhiteRgb]: "255, 255, 255",
	},
})
