import { h6 } from '../../contents/generated.css'
import { btn, btnShowHook } from '../buttons/base.css'
import { btnDanger, btnDark, btnInfo, btnLg, btnLight, btnPrimary, btnSecondary, btnSm, btnSuccess, btnWarning } from '../buttons/generated.css'
import {
	btnGroup,
	dropdown,
	dropdownDivider,
	dropdownHeader,
	dropdownItem,
	dropdownMenu,
	dropdownMenuEnd,
	dropdownMenuShow,
	dropdownToggle,
	dropdownToggleSplit,
	dropend,
	dropendMenu,
	dropendToggle,
	dropstart,
	dropstartMenu,
	dropstartToggle,
	dropup,
	dropupMenu,
	dropupToggle,
	visuallyHidden,
} from './base.css'

export const bootstrapDropdownRuntimeClasses = {
	h6,
	btn,
	btnShowHook,
	btnLg,
	btnSm,
	btnPrimary,
	btnSecondary,
	btnSuccess,
	btnInfo,
	btnWarning,
	btnDanger,
	btnLight,
	btnDark,
	btnGroup,
	dropdown,
	dropdownDivider,
	dropdownHeader,
	dropdownItem,
	dropdownMenu,
	dropdownMenuShow,
	dropdownMenuEnd,
	dropdownToggle,
	dropdownToggleSplit,
	dropup,
	dropupMenu,
	dropupToggle,
	dropend,
	dropendMenu,
	dropendToggle,
	dropstart,
	dropstartMenu,
	dropstartToggle,
	visuallyHidden,
} as const
