import { createVar } from '@vanilla-extract/css'

export const varBsModalZindex = createVar()
export const varBsModalWidth = createVar()
export const varBsModalPadding = createVar()
export const varBsModalMargin = createVar()
export const varBsModalColor = createVar()
export const varBsModalBg = createVar()
export const varBsModalBorderColor = createVar()
export const varBsModalBorderWidth = createVar()
export const varBsModalBorderRadius = createVar()
export const varBsModalBoxShadow = createVar()
export const varBsModalInnerBorderRadius = createVar()
export const varBsModalHeaderPaddingX = createVar()
export const varBsModalHeaderPaddingY = createVar()
export const varBsModalHeaderPadding = createVar()
export const varBsModalHeaderBorderColor = createVar()
export const varBsModalHeaderBorderWidth = createVar()
export const varBsModalTitleLineHeight = createVar()
export const varBsModalFooterGap = createVar()
export const varBsModalFooterBg = createVar()
export const varBsModalFooterBorderColor = createVar()
export const varBsModalFooterBorderWidth = createVar()

export const varBsBackdropZindex = createVar()
export const varBsBackdropBg = createVar()
export const varBsBackdropOpacity = createVar()
