export {
popoverClass,
bsPopoverTop,
bsPopoverEnd,
bsPopoverBottom,
bsPopoverStart,
bsPopoverAuto,
popoverArrow,
popoverHeader,
popoverBody,
frame,
frameColumn,
frameRow,
justifyEnd,
justifyStart,
} from '../../../bootstrap/ui/popovers/base.css'
