import { createVar } from '@vanilla-extract/css'

export const varBsAccordionColor = createVar()
export const varBsAccordionBg = createVar()
export const varBsAccordionTransition = createVar()
export const varBsAccordionBorderColor = createVar()
export const varBsAccordionBorderWidth = createVar()
export const varBsAccordionBorderRadius = createVar()
export const varBsAccordionInnerBorderRadius = createVar()
export const varBsAccordionBtnPaddingX = createVar()
export const varBsAccordionBtnPaddingY = createVar()
export const varBsAccordionBtnColor = createVar()
export const varBsAccordionBtnBg = createVar()
export const varBsAccordionBtnIcon = createVar()
export const varBsAccordionBtnIconWidth = createVar()
export const varBsAccordionBtnIconTransform = createVar()
export const varBsAccordionBtnIconTransition = createVar()
export const varBsAccordionBtnActiveIcon = createVar()
export const varBsAccordionBtnFocusBoxShadow = createVar()
export const varBsAccordionBodyPaddingX = createVar()
export const varBsAccordionBodyPaddingY = createVar()
export const varBsAccordionActiveColor = createVar()
export const varBsAccordionActiveBg = createVar()
