import { bootstrapScope } from '../bootstrap/scope.css'
import { materiaScope } from '../materia/scope.css'
import { quartzScope } from '../quartz/scope.css'
import { sandstoneScope } from '../sandstone/scope.css'
import { sketchyScope } from '../sketchy/scope.css'
import { slateScope } from '../slate/scope.css'
import { solarScope } from '../solar/scope.css'
import { vaporScope } from '../vapor/scope.css'
import type { Ve2StyleFamily } from './style-families'

export const VE2_THEME_KEYS = [
	'bootstrap',
	'quartz',
	'solar',
	'slate',
	'sketchy',
	'vapor',
	'sandstone',
	'materia',
] as const

export type Ve2ThemeKey = (typeof VE2_THEME_KEYS)[number]

export type Ve2StyleFamilyLoaderMap = Partial<Record<Ve2StyleFamily, () => Promise<unknown>>>

const themeScopes: Record<Ve2ThemeKey, string> = {
	bootstrap: bootstrapScope,
	quartz: quartzScope,
	solar: solarScope,
	slate: slateScope,
	sketchy: sketchyScope,
	vapor: vaporScope,
	sandstone: sandstoneScope,
	materia: materiaScope,
}

export const ve2ThemeLoaders: Record<Ve2ThemeKey, () => Promise<unknown>> = {
	bootstrap: () => import('../bootstrap/theme.js'),
	quartz: () => import('../quartz/theme.js'),
	solar: () => import('../solar/theme.js'),
	slate: () => import('../slate/theme.js'),
	sketchy: () => import('../sketchy/theme.js'),
	vapor: () => import('../vapor/theme.js'),
	sandstone: () => import('../sandstone/theme.js'),
	materia: () => import('../materia/theme.js'),
}

export const ve2ThemeFamilyLoaders: Record<Ve2ThemeKey, Ve2StyleFamilyLoaderMap> = {
	bootstrap: {
		contents: () => import('../bootstrap/contents/styles.css'),
		forms: () => import('../bootstrap/forms/styles.css'),
		utilities: () => import('../bootstrap/utilities/styles.css'),
		'ui/accordion': () => import('../bootstrap/ui/accordion/styles.css'),
		'ui/alerts': () => import('../bootstrap/ui/alerts/styles.css'),
		'ui/badge': () => import('../bootstrap/ui/badge/styles.css'),
		'ui/breadcrumb': () => import('../bootstrap/ui/breadcrumb/styles.css'),
		'ui/button-group': () => import('../bootstrap/ui/button-group/styles.css'),
		'ui/buttons': () => import('../bootstrap/ui/buttons/styles.css'),
		'ui/card': () => import('../bootstrap/ui/card/styles.css'),
		'ui/card-tabs': () => import('../bootstrap/ui/card-tabs/styles.css'),
		'ui/carousel': () => import('../bootstrap/ui/carousel/styles.css'),
		'ui/dropdowns': () => import('../bootstrap/ui/dropdowns/styles.css'),
		'ui/list-group': () => import('../bootstrap/ui/list-group/styles.css'),
		'ui/modal': () => import('../bootstrap/ui/modal/styles.css'),
		'ui/navbar': () => import('../bootstrap/ui/navbar/styles.css'),
		'ui/navs': () => import('../bootstrap/ui/navs/styles.css'),
		'ui/pagination': () => import('../bootstrap/ui/pagination/styles.css'),
		'ui/popovers': () => import('../bootstrap/ui/popovers/styles.css'),
		'ui/progress': () => import('../bootstrap/ui/progress/styles.css'),
		'ui/scrollspy': () => import('../bootstrap/ui/scrollspy/styles.css'),
		'ui/spinners': () => import('../bootstrap/ui/spinners/styles.css'),
		'ui/toasts': () => import('../bootstrap/ui/toasts/styles.css'),
		'ui/tooltips': () => import('../bootstrap/ui/tooltips/styles.css'),
	},
	quartz: {
		contents: () => import('../quartz/contents/styles.css'),
		forms: () => import('../quartz/forms/styles.css'),
		utilities: () => import('../quartz/utilities/styles.css'),
		'ui/accordion': () => import('../quartz/ui/accordion/styles.css'),
		'ui/alerts': () => import('../quartz/ui/alerts/styles.css'),
		'ui/badge': () => import('../quartz/ui/badge/styles.css'),
		'ui/breadcrumb': () => import('../quartz/ui/breadcrumb/styles.css'),
		'ui/button-group': () => import('../quartz/ui/button-group/styles.css'),
		'ui/buttons': () => import('../quartz/ui/buttons/styles.css'),
		'ui/card': () => import('../quartz/ui/card/styles.css'),
		'ui/card-tabs': () => import('../quartz/ui/card-tabs/styles.css'),
		'ui/carousel': () => import('../quartz/ui/carousel/styles.css'),
		'ui/dropdowns': () => import('../quartz/ui/dropdowns/styles.css'),
		'ui/list-group': () => import('../quartz/ui/list-group/styles.css'),
		'ui/modal': () => import('../quartz/ui/modal/styles.css'),
		'ui/navbar': () => import('../quartz/ui/navbar/styles.css'),
		'ui/navs': () => import('../quartz/ui/navs/styles.css'),
		'ui/pagination': () => import('../quartz/ui/pagination/styles.css'),
		'ui/popovers': () => import('../quartz/ui/popovers/styles.css'),
		'ui/progress': () => import('../quartz/ui/progress/styles.css'),
		'ui/scrollspy': () => import('../quartz/ui/scrollspy/styles.css'),
		'ui/spinners': () => import('../quartz/ui/spinners/styles.css'),
		'ui/toasts': () => import('../quartz/ui/toasts/styles.css'),
		'ui/tooltips': () => import('../quartz/ui/tooltips/styles.css'),
	},
	solar: {
		contents: () => import('../solar/contents/styles.css'),
		forms: () => import('../solar/forms/styles.css'),
		utilities: () => import('../solar/utilities/styles.css'),
		'ui/accordion': () => import('../solar/ui/accordion/styles.css'),
		'ui/alerts': () => import('../solar/ui/alerts/styles.css'),
		'ui/badge': () => import('../solar/ui/badge/styles.css'),
		'ui/breadcrumb': () => import('../solar/ui/breadcrumb/styles.css'),
		'ui/button-group': () => import('../solar/ui/button-group/styles.css'),
		'ui/buttons': () => import('../solar/ui/buttons/styles.css'),
		'ui/card': () => import('../solar/ui/card/styles.css'),
		'ui/card-tabs': () => import('../solar/ui/card-tabs/styles.css'),
		'ui/carousel': () => import('../solar/ui/carousel/styles.css'),
		'ui/dropdowns': () => import('../solar/ui/dropdowns/styles.css'),
		'ui/list-group': () => import('../solar/ui/list-group/styles.css'),
		'ui/modal': () => import('../solar/ui/modal/styles.css'),
		'ui/navbar': () => import('../solar/ui/navbar/styles.css'),
		'ui/navs': () => import('../solar/ui/navs/styles.css'),
		'ui/pagination': () => import('../solar/ui/pagination/styles.css'),
		'ui/popovers': () => import('../solar/ui/popovers/styles.css'),
		'ui/progress': () => import('../solar/ui/progress/styles.css'),
		'ui/scrollspy': () => import('../solar/ui/scrollspy/styles.css'),
		'ui/spinners': () => import('../solar/ui/spinners/styles.css'),
		'ui/toasts': () => import('../solar/ui/toasts/styles.css'),
		'ui/tooltips': () => import('../solar/ui/tooltips/styles.css'),
	},
	slate: {
		contents: () => import('../slate/contents/styles.css'),
		forms: () => import('../slate/forms/styles.css'),
		utilities: () => import('../slate/utilities/styles.css'),
		'ui/accordion': () => import('../slate/ui/accordion/styles.css'),
		'ui/alerts': () => import('../slate/ui/alerts/styles.css'),
		'ui/badge': () => import('../slate/ui/badge/styles.css'),
		'ui/breadcrumb': () => import('../slate/ui/breadcrumb/styles.css'),
		'ui/button-group': () => import('../slate/ui/button-group/styles.css'),
		'ui/buttons': () => import('../slate/ui/buttons/styles.css'),
		'ui/card': () => import('../slate/ui/card/styles.css'),
		'ui/card-tabs': () => import('../slate/ui/card-tabs/styles.css'),
		'ui/carousel': () => import('../slate/ui/carousel/styles.css'),
		'ui/dropdowns': () => import('../slate/ui/dropdowns/styles.css'),
		'ui/list-group': () => import('../slate/ui/list-group/styles.css'),
		'ui/modal': () => import('../slate/ui/modal/styles.css'),
		'ui/navbar': () => import('../slate/ui/navbar/styles.css'),
		'ui/navs': () => import('../slate/ui/navs/styles.css'),
		'ui/pagination': () => import('../slate/ui/pagination/styles.css'),
		'ui/popovers': () => import('../slate/ui/popovers/styles.css'),
		'ui/progress': () => import('../slate/ui/progress/styles.css'),
		'ui/scrollspy': () => import('../slate/ui/scrollspy/styles.css'),
		'ui/spinners': () => import('../slate/ui/spinners/styles.css'),
		'ui/toasts': () => import('../slate/ui/toasts/styles.css'),
		'ui/tooltips': () => import('../slate/ui/tooltips/styles.css'),
	},
	sketchy: {
		contents: () => import('../sketchy/contents/styles.css'),
		forms: () => import('../sketchy/forms/styles.css'),
		utilities: () => import('../sketchy/utilities/styles.css'),
		'ui/accordion': () => import('../sketchy/ui/accordion/styles.css'),
		'ui/alerts': () => import('../sketchy/ui/alerts/styles.css'),
		'ui/badge': () => import('../sketchy/ui/badge/styles.css'),
		'ui/breadcrumb': () => import('../sketchy/ui/breadcrumb/styles.css'),
		'ui/button-group': () => import('../sketchy/ui/button-group/styles.css'),
		'ui/buttons': () => import('../sketchy/ui/buttons/styles.css'),
		'ui/card': () => import('../sketchy/ui/card/styles.css'),
		'ui/card-tabs': () => import('../sketchy/ui/card-tabs/styles.css'),
		'ui/carousel': () => import('../sketchy/ui/carousel/styles.css'),
		'ui/dropdowns': () => import('../sketchy/ui/dropdowns/styles.css'),
		'ui/list-group': () => import('../sketchy/ui/list-group/styles.css'),
		'ui/modal': () => import('../sketchy/ui/modal/styles.css'),
		'ui/navbar': () => import('../sketchy/ui/navbar/styles.css'),
		'ui/navs': () => import('../sketchy/ui/navs/styles.css'),
		'ui/pagination': () => import('../sketchy/ui/pagination/styles.css'),
		'ui/popovers': () => import('../sketchy/ui/popovers/styles.css'),
		'ui/progress': () => import('../sketchy/ui/progress/styles.css'),
		'ui/scrollspy': () => import('../sketchy/ui/scrollspy/styles.css'),
		'ui/spinners': () => import('../sketchy/ui/spinners/styles.css'),
		'ui/toasts': () => import('../sketchy/ui/toasts/styles.css'),
		'ui/tooltips': () => import('../sketchy/ui/tooltips/styles.css'),
	},
	vapor: {
		contents: () => import('../vapor/contents/styles.css'),
		forms: () => import('../vapor/forms/styles.css'),
		utilities: () => import('../vapor/utilities/styles.css'),
		'ui/accordion': () => import('../vapor/ui/accordion/styles.css'),
		'ui/alerts': () => import('../vapor/ui/alerts/styles.css'),
		'ui/badge': () => import('../vapor/ui/badge/styles.css'),
		'ui/breadcrumb': () => import('../vapor/ui/breadcrumb/styles.css'),
		'ui/button-group': () => import('../vapor/ui/button-group/styles.css'),
		'ui/buttons': () => import('../vapor/ui/buttons/styles.css'),
		'ui/card': () => import('../vapor/ui/card/styles.css'),
		'ui/card-tabs': () => import('../vapor/ui/card-tabs/styles.css'),
		'ui/carousel': () => import('../vapor/ui/carousel/styles.css'),
		'ui/dropdowns': () => import('../vapor/ui/dropdowns/styles.css'),
		'ui/list-group': () => import('../vapor/ui/list-group/styles.css'),
		'ui/modal': () => import('../vapor/ui/modal/styles.css'),
		'ui/navbar': () => import('../vapor/ui/navbar/styles.css'),
		'ui/navs': () => import('../vapor/ui/navs/styles.css'),
		'ui/pagination': () => import('../vapor/ui/pagination/styles.css'),
		'ui/popovers': () => import('../vapor/ui/popovers/styles.css'),
		'ui/progress': () => import('../vapor/ui/progress/styles.css'),
		'ui/scrollspy': () => import('../vapor/ui/scrollspy/styles.css'),
		'ui/spinners': () => import('../vapor/ui/spinners/styles.css'),
		'ui/toasts': () => import('../vapor/ui/toasts/styles.css'),
		'ui/tooltips': () => import('../vapor/ui/tooltips/styles.css'),
	},
	sandstone: {
		contents: () => import('../sandstone/contents/styles.css'),
		forms: () => import('../sandstone/forms/styles.css'),
		utilities: () => import('../sandstone/utilities/styles.css'),
		'ui/accordion': () => import('../sandstone/ui/accordion/styles.css'),
		'ui/alerts': () => import('../sandstone/ui/alerts/styles.css'),
		'ui/badge': () => import('../sandstone/ui/badge/styles.css'),
		'ui/breadcrumb': () => import('../sandstone/ui/breadcrumb/styles.css'),
		'ui/button-group': () => import('../sandstone/ui/button-group/styles.css'),
		'ui/buttons': () => import('../sandstone/ui/buttons/styles.css'),
		'ui/card': () => import('../sandstone/ui/card/styles.css'),
		'ui/card-tabs': () => import('../sandstone/ui/card-tabs/styles.css'),
		'ui/carousel': () => import('../sandstone/ui/carousel/styles.css'),
		'ui/dropdowns': () => import('../sandstone/ui/dropdowns/styles.css'),
		'ui/list-group': () => import('../sandstone/ui/list-group/styles.css'),
		'ui/modal': () => import('../sandstone/ui/modal/styles.css'),
		'ui/navbar': () => import('../sandstone/ui/navbar/styles.css'),
		'ui/navs': () => import('../sandstone/ui/navs/styles.css'),
		'ui/pagination': () => import('../sandstone/ui/pagination/styles.css'),
		'ui/popovers': () => import('../sandstone/ui/popovers/styles.css'),
		'ui/progress': () => import('../sandstone/ui/progress/styles.css'),
		'ui/scrollspy': () => import('../sandstone/ui/scrollspy/styles.css'),
		'ui/spinners': () => import('../sandstone/ui/spinners/styles.css'),
		'ui/toasts': () => import('../sandstone/ui/toasts/styles.css'),
		'ui/tooltips': () => import('../sandstone/ui/tooltips/styles.css'),
	},
	materia: {
		contents: () => import('../materia/contents/styles.css'),
		forms: () => import('../materia/forms/styles.css'),
		utilities: () => import('../materia/utilities/styles.css'),
		'ui/accordion': () => import('../materia/ui/accordion/styles.css'),
		'ui/alerts': () => import('../materia/ui/alerts/styles.css'),
		'ui/badge': () => import('../materia/ui/badge/styles.css'),
		'ui/breadcrumb': () => import('../materia/ui/breadcrumb/styles.css'),
		'ui/button-group': () => import('../materia/ui/button-group/styles.css'),
		'ui/buttons': () => import('../materia/ui/buttons/styles.css'),
		'ui/card': () => import('../materia/ui/card/styles.css'),
		'ui/card-tabs': () => import('../materia/ui/card-tabs/styles.css'),
		'ui/carousel': () => import('../materia/ui/carousel/styles.css'),
		'ui/dropdowns': () => import('../materia/ui/dropdowns/styles.css'),
		'ui/list-group': () => import('../materia/ui/list-group/styles.css'),
		'ui/modal': () => import('../materia/ui/modal/styles.css'),
		'ui/navbar': () => import('../materia/ui/navbar/styles.css'),
		'ui/navs': () => import('../materia/ui/navs/styles.css'),
		'ui/pagination': () => import('../materia/ui/pagination/styles.css'),
		'ui/popovers': () => import('../materia/ui/popovers/styles.css'),
		'ui/progress': () => import('../materia/ui/progress/styles.css'),
		'ui/scrollspy': () => import('../materia/ui/scrollspy/styles.css'),
		'ui/spinners': () => import('../materia/ui/spinners/styles.css'),
		'ui/toasts': () => import('../materia/ui/toasts/styles.css'),
		'ui/tooltips': () => import('../materia/ui/tooltips/styles.css'),
	},
}

export function resolveVe2ThemeKey(rawTheme: string | null | undefined): Ve2ThemeKey {
	switch (rawTheme) {
		case 'quartz':
		case 'solar':
		case 'slate':
		case 'sketchy':
		case 'vapor':
		case 'sandstone':
		case 'materia':
			return rawTheme
		default:
			return 'bootstrap'
	}
}

export function resolveVe2ThemeClass(rawTheme: string | null | undefined): string {
	return themeScopes[resolveVe2ThemeKey(rawTheme)]
}
