export {
btnCheck,
btnDanger,
btnDark,
btnInfo,
btnLg,
btnLight,
btnLink,
btnOutlineDanger,
btnOutlineDark,
btnOutlineInfo,
btnOutlineLight,
btnOutlinePrimary,
btnOutlineSecondary,
btnOutlineSuccess,
btnOutlineWarning,
btnPrimary,
btnSecondary,
btnSm,
btnSuccess,
btnWarning,
} from '../../bootstrap/ui/buttons/generated.css'
