import { btn, btnActiveHook, btnCheckHook, btnShowHook, btnDisabledHook } from './base.css'
import {
btnCheck,
btnDanger,
btnDark,
btnInfo,
btnLg,
btnLight,
btnLink,
btnOutlineDanger,
btnOutlineDark,
btnOutlineInfo,
btnOutlineLight,
btnOutlinePrimary,
btnOutlineSecondary,
btnOutlineSuccess,
btnOutlineWarning,
btnPrimary,
btnSecondary,
btnSm,
btnSuccess,
btnWarning,
} from './generated.css'

export const sketchyButtonRuntimeClasses = {
btn,
btnActiveHook,
btnCheck,
btnDanger,
btnDark,
btnInfo,
btnLg,
btnLight,
btnLink,
btnOutlineDanger,
btnOutlineDark,
btnOutlineInfo,
btnOutlineLight,
btnOutlinePrimary,
btnOutlineSecondary,
btnOutlineSuccess,
btnOutlineWarning,
btnPrimary,
btnSecondary,
btnSm,
btnSuccess,
btnWarning,
} as const
