// GERADO por scripts/gen-public-vars.mjs — NÃO editar à mão.
import { globalStyle } from '@vanilla-extract/css'
import { mintyScope } from './scope.css'
import { varBsBlackRgb, varBsBodyBgRgb, varBsBodyColorRgb, varBsBorderColor, varBsBorderRadius, varBsBorderRadiusLg, varBsBorderRadiusPill, varBsBorderRadiusSm, varBsBorderRadiusXl, varBsBorderRadiusXxl, varBsBorderStyle, varBsBorderWidth, varBsBoxShadow, varBsBoxShadowLg, varBsBoxShadowSm, varBsDangerBgSubtle, varBsDangerBorderSubtle, varBsDangerRgb, varBsDangerTextEmphasis, varBsDarkBgSubtle, varBsDarkBorderSubtle, varBsDarkRgb, varBsDarkTextEmphasis, varBsEmphasisColor, varBsEmphasisColorRgb, varBsFocusRingColor, varBsFocusRingOpacity, varBsFontMonospace, varBsGradient, varBsInfoBgSubtle, varBsInfoBorderSubtle, varBsInfoRgb, varBsInfoTextEmphasis, varBsLightBgSubtle, varBsLightBorderSubtle, varBsLightRgb, varBsLightTextEmphasis, varBsLinkColorRgb, varBsPrimaryBgSubtle, varBsPrimaryBorderSubtle, varBsPrimaryRgb, varBsPrimaryTextEmphasis, varBsSecondaryBgRgb, varBsSecondaryBgSubtle, varBsSecondaryBorderSubtle, varBsSecondaryColor, varBsSecondaryRgb, varBsSecondaryTextEmphasis, varBsSuccessBgSubtle, varBsSuccessBorderSubtle, varBsSuccessRgb, varBsSuccessTextEmphasis, varBsTertiaryBgRgb, varBsTertiaryColor, varBsWarningBgSubtle, varBsWarningBorderSubtle, varBsWarningRgb, varBsWarningTextEmphasis, varBsWhiteRgb } from '../../theme-contract/_public-vars.css'

globalStyle(mintyScope, {
	vars: {
		[varBsBlackRgb]: "0, 0, 0",
		[varBsBodyBgRgb]: "255, 255, 255",
		[varBsBodyColorRgb]: "136, 136, 136",
		[varBsBorderColor]: "#eceeef",
		[varBsBorderRadius]: "0.4rem",
		[varBsBorderRadiusLg]: "0.6rem",
		[varBsBorderRadiusPill]: "50rem",
		[varBsBorderRadiusSm]: "0.3rem",
		[varBsBorderRadiusXl]: "1rem",
		[varBsBorderRadiusXxl]: "2rem",
		[varBsBorderStyle]: "solid",
		[varBsBorderWidth]: "1px",
		[varBsBoxShadow]: "0 0.5rem 1rem rgba(0, 0, 0, 0.15)",
		[varBsBoxShadowLg]: "0 1rem 3rem rgba(0, 0, 0, 0.175)",
		[varBsBoxShadowSm]: "0 0.125rem 0.25rem rgba(0, 0, 0, 0.075)",
		[varBsDangerBgSubtle]: "#ffe4dc",
		[varBsDangerBorderSubtle]: "#ffc9b9",
		[varBsDangerRgb]: "255, 120, 81",
		[varBsDangerTextEmphasis]: "#663020",
		[varBsDarkBgSubtle]: "#ced4da",
		[varBsDarkBorderSubtle]: "#aaa",
		[varBsDarkRgb]: "52, 58, 64",
		[varBsDarkTextEmphasis]: "#5a5a5a",
		[varBsEmphasisColor]: "#000",
		[varBsEmphasisColorRgb]: "0, 0, 0",
		[varBsFocusRingColor]: "rgba(120, 194, 173, 0.25)",
		[varBsFocusRingOpacity]: "0.25",
		[varBsFontMonospace]: "SFMono-Regular, Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace",
		[varBsGradient]: "linear-gradient(180deg, rgba(255, 255, 255, 0.15), rgba(255, 255, 255, 0))",
		[varBsInfoBgSubtle]: "#e2f3f7",
		[varBsInfoBorderSubtle]: "#c4e7ee",
		[varBsInfoRgb]: "108, 195, 213",
		[varBsInfoTextEmphasis]: "#2b4e55",
		[varBsLightBgSubtle]: "#fcfcfd",
		[varBsLightBorderSubtle]: "#f7f7f9",
		[varBsLightRgb]: "248, 249, 250",
		[varBsLightTextEmphasis]: "#5a5a5a",
		[varBsLinkColorRgb]: "120, 194, 173",
		[varBsPrimaryBgSubtle]: "#e4f3ef",
		[varBsPrimaryBorderSubtle]: "#c9e7de",
		[varBsPrimaryRgb]: "120, 194, 173",
		[varBsPrimaryTextEmphasis]: "#304e45",
		[varBsSecondaryBgRgb]: "247, 247, 249",
		[varBsSecondaryBgSubtle]: "#fdeaeb",
		[varBsSecondaryBorderSubtle]: "#fad5d7",
		[varBsSecondaryColor]: "rgba(136, 136, 136, 0.75)",
		[varBsSecondaryRgb]: "243, 150, 154",
		[varBsSecondaryTextEmphasis]: "#613c3e",
		[varBsSuccessBgSubtle]: "#ddf5eb",
		[varBsSuccessBorderSubtle]: "#bbebd8",
		[varBsSuccessRgb]: "86, 204, 157",
		[varBsSuccessTextEmphasis]: "#22523f",
		[varBsTertiaryBgRgb]: "248, 249, 250",
		[varBsTertiaryColor]: "rgba(136, 136, 136, 0.5)",
		[varBsWarningBgSubtle]: "#fff5e1",
		[varBsWarningBorderSubtle]: "#ffebc2",
		[varBsWarningRgb]: "255, 206, 103",
		[varBsWarningTextEmphasis]: "#665229",
		[varBsWhiteRgb]: "255, 255, 255",
	},
})
