import { globalStyle, style } from '@vanilla-extract/css'
import {
	varBsAccordionBtnActiveIcon,
	varBsAccordionBtnIcon,
	varBsBlack,
	varBsBlackRgb,
	varBsBlue,
	varBsBodyBg,
	varBsBodyBgRgb,
	varBsBodyColor,
	varBsBodyColorRgb,
	varBsBodyFontFamily,
	varBsBodyFontSize,
	varBsBodyFontWeight,
	varBsBodyLineHeight,
	varBsBorderColor,
	varBsBorderColorTranslucent,
	varBsBorderRadius,
	varBsBorderRadiusLg,
	varBsBorderRadiusPill,
	varBsBorderRadiusSm,
	varBsBorderRadiusXl,
	varBsBorderRadiusXxl,
	varBsBorderStyle,
	varBsBorderWidth,
	varBsBoxShadow,
	varBsBoxShadowInset,
	varBsBoxShadowLg,
	varBsBoxShadowSm,
	varBsCarouselCaptionColor,
	varBsCarouselControlIconFilter,
	varBsCarouselIndicatorActiveBg,
	varBsCodeColor,
	varBsCyan,
	varBsDanger,
	varBsDangerBgSubtle,
	varBsDangerBorderSubtle,
	varBsDangerRgb,
	varBsDangerTextEmphasis,
	varBsDark,
	varBsDarkBgSubtle,
	varBsDarkBorderSubtle,
	varBsDarkRgb,
	varBsDarkTextEmphasis,
	varBsEmphasisColor,
	varBsEmphasisColorRgb,
	varBsFocusRingColor,
	varBsFocusRingOpacity,
	varBsFocusRingWidth,
	varBsFontMonospace,
	varBsFontSansSerif,
	varBsGradient,
	varBsGray,
	varBsGrayDark,
	varBsGreen,
	varBsHeadingColor,
	varBsHighlightBg,
	varBsHighlightColor,
	varBsIndigo,
	varBsInfo,
	varBsInfoBgSubtle,
	varBsInfoBorderSubtle,
	varBsInfoRgb,
	varBsInfoTextEmphasis,
	varBsLight,
	varBsLightBgSubtle,
	varBsLightBorderSubtle,
	varBsLightRgb,
	varBsLightTextEmphasis,
	varBsLinkColor,
	varBsLinkColorRgb,
	varBsLinkDecoration,
	varBsLinkHoverColor,
	varBsLinkHoverColorRgb,
	varBsNavbarActiveColor,
	varBsNavbarBrandColor,
	varBsNavbarBrandHoverColor,
	varBsNavbarColor,
	varBsNavbarDisabledColor,
	varBsNavbarHoverColor,
	varBsNavbarTogglerBorderColor,
	varBsNavbarTogglerIconBg,
	varBsOrange,
	varBsPink,
	varBsPrimary,
	varBsPrimaryBgSubtle,
	varBsPrimaryBorderSubtle,
	varBsPrimaryRgb,
	varBsPrimaryTextEmphasis,
	varBsPurple,
	varBsRed,
	varBsSecondary,
	varBsSecondaryBg,
	varBsSecondaryBgSubtle,
	varBsSecondaryBorderSubtle,
	varBsSecondaryColor,
	varBsSecondaryRgb,
	varBsSecondaryTextEmphasis,
	varBsSuccess,
	varBsSuccessBgSubtle,
	varBsSuccessBorderSubtle,
	varBsSuccessRgb,
	varBsSuccessTextEmphasis,
	varBsTeal,
	varBsTertiaryBg,
	varBsTertiaryColor,
	varBsWarning,
	varBsWarningBgSubtle,
	varBsWarningBorderSubtle,
	varBsWarningRgb,
	varBsWarningTextEmphasis,
	varBsWhite,
	varBsWhiteRgb,
	varBsYellow,
} from '../../theme-contract/_vars.css'
import {
	varBsFormInvalidBorderColor,
	varBsFormInvalidColor,
	varBsFormSelectBgImg,
	varBsFormSwitchBg,
	varBsFormValidBorderColor,
	varBsFormValidColor,
} from '../../theme-contract/forms/_vars.css'
import { body, bodyText, vars } from '../../theme-contract/theme-contract.css'

// Minty theme scope class.
// Zero-style identifier used as a stable selector prefix.
export const mintyScope = style({})

// Global Bootstrap CSS custom properties (`--bs-*`) are assigned on the
// dedicated vars contract class to keep root var hosting separate from body
// layout/background styles.
globalStyle(`${mintyScope}${vars}`, {
	vars: {
		[varBsBlue]: "#007bff",
		[varBsIndigo]: "#6610f2",
		[varBsPurple]: "#6f42c1",
		[varBsPink]: "#e83e8c",
		[varBsRed]: "#ff7851",
		[varBsOrange]: "#fd7e14",
		[varBsYellow]: "#ffce67",
		[varBsGreen]: "#56cc9d",
		[varBsTeal]: "#20c997",
		[varBsCyan]: "#6cc3d5",
		[varBsBlack]: "#000",
		[varBsWhite]: "#fff",
		[varBsGray]: "#888",
		[varBsGrayDark]: "#343a40",
		[varBsPrimary]: "#78c2ad",
		[varBsSecondary]: "#f3969a",
		[varBsSuccess]: "#56cc9d",
		[varBsInfo]: "#6cc3d5",
		[varBsWarning]: "#ffce67",
		[varBsDanger]: "#ff7851",
		[varBsLight]: "#f8f9fa",
		[varBsDark]: "#343a40",
		[varBsPrimaryRgb]: "120, 194, 173",
		[varBsSecondaryRgb]: "243, 150, 154",
		[varBsSuccessRgb]: "86, 204, 157",
		[varBsInfoRgb]: "108, 195, 213",
		[varBsWarningRgb]: "255, 206, 103",
		[varBsDangerRgb]: "255, 120, 81",
		[varBsLightRgb]: "248, 249, 250",
		[varBsDarkRgb]: "52, 58, 64",
		[varBsPrimaryTextEmphasis]: "#aedace",
		[varBsSecondaryTextEmphasis]: "#f8c0c2",
		[varBsSuccessTextEmphasis]: "#9ae0c4",
		[varBsInfoTextEmphasis]: "#a7dbe6",
		[varBsWarningTextEmphasis]: "#ffe2a4",
		[varBsDangerTextEmphasis]: "#ffae97",
		[varBsLightTextEmphasis]: "#f8f9fa",
		[varBsDarkTextEmphasis]: "#eceeef",
		[varBsPrimaryBgSubtle]: "#182723",
		[varBsSecondaryBgSubtle]: "#311e1f",
		[varBsSuccessBgSubtle]: "#11291f",
		[varBsInfoBgSubtle]: "#16272b",
		[varBsWarningBgSubtle]: "#332915",
		[varBsDangerBgSubtle]: "#331810",
		[varBsLightBgSubtle]: "#343a40",
		[varBsDarkBgSubtle]: "#1a1d20",
		[varBsPrimaryBorderSubtle]: "#487468",
		[varBsSecondaryBorderSubtle]: "#925a5c",
		[varBsSuccessBorderSubtle]: "#347a5e",
		[varBsInfoBorderSubtle]: "#417580",
		[varBsWarningBorderSubtle]: "#997c3e",
		[varBsDangerBorderSubtle]: "#994831",
		[varBsLightBorderSubtle]: "#5a5a5a",
		[varBsDarkBorderSubtle]: "#343a40",
		[varBsWhiteRgb]: "255, 255, 255",
		[varBsBlackRgb]: "0, 0, 0",
		[varBsFontSansSerif]: "system-ui, -apple-system, \"Segoe UI\", Roboto, \"Helvetica Neue\", \"Noto Sans\", \"Liberation Sans\", Arial, sans-serif, \"Apple Color Emoji\", \"Segoe UI Emoji\", \"Segoe UI Symbol\", \"Noto Color Emoji\"",
		[varBsFontMonospace]: "SFMono-Regular, Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace",
		[varBsGradient]: "linear-gradient(180deg, rgba(255, 255, 255, 0.15), rgba(255, 255, 255, 0))",
		[varBsBodyFontFamily]: varBsFontSansSerif,
		[varBsBodyFontSize]: "1rem",
		[varBsBodyFontWeight]: 400,
		[varBsBodyLineHeight]: 1.5,
		[varBsBodyColor]: "#eceeef",
		[varBsBodyColorRgb]: "236, 238, 239",
		[varBsBodyBg]: "#212529",
		[varBsBodyBgRgb]: "33, 37, 41",
		[varBsEmphasisColor]: "#fff",
		[varBsEmphasisColorRgb]: "255, 255, 255",
		[varBsSecondaryColor]: "rgba(236, 238, 239, 0.75)",
		[varBsSecondaryBg]: "#343a40",
		[varBsTertiaryColor]: "rgba(236, 238, 239, 0.5)",
		[varBsTertiaryBg]: "#2b3035",
		[varBsHeadingColor]: "inherit",
		[varBsLinkColor]: "#aedace",
		[varBsLinkColorRgb]: "174, 218, 206",
		[varBsLinkDecoration]: "underline",
		[varBsLinkHoverColor]: "#bee1d8",
		[varBsLinkHoverColorRgb]: "190, 225, 216",
		[varBsCodeColor]: "#f18bba",
		[varBsHighlightColor]: "#eceeef",
		[varBsHighlightBg]: "#665229",
		[varBsBorderWidth]: "1px",
		[varBsBorderStyle]: "solid",
		[varBsBorderColor]: "#5a5a5a",
		[varBsBorderColorTranslucent]: "rgba(255, 255, 255, 0.15)",
		[varBsBorderRadius]: "0.4rem",
		[varBsBorderRadiusSm]: "0.3rem",
		[varBsBorderRadiusLg]: "0.6rem",
		[varBsBorderRadiusXl]: "1rem",
		[varBsBorderRadiusXxl]: "2rem",
		[varBsBorderRadiusPill]: "50rem",
		[varBsBoxShadow]: "0 0.5rem 1rem rgba(0, 0, 0, 0.15)",
		[varBsBoxShadowSm]: "0 0.125rem 0.25rem rgba(0, 0, 0, 0.075)",
		[varBsBoxShadowLg]: "0 1rem 3rem rgba(0, 0, 0, 0.175)",
		[varBsBoxShadowInset]: "inset 0 1px 2px rgba(0, 0, 0, 0.075)",
		[varBsFocusRingWidth]: "0.25rem",
		[varBsFocusRingOpacity]: 0.25,
		[varBsFocusRingColor]: "rgba(120, 194, 173, 0.25)",
		[varBsNavbarColor]: "rgba(255, 255, 255, 0.55)",
		[varBsNavbarHoverColor]: "rgba(255, 255, 255, 0.75)",
		[varBsNavbarDisabledColor]: "rgba(255, 255, 255, 0.25)",
		[varBsNavbarActiveColor]: "#fff",
		[varBsNavbarBrandColor]: "#fff",
		[varBsNavbarBrandHoverColor]: "#fff",
		[varBsNavbarTogglerBorderColor]: "rgba(255, 255, 255, 0.1)",
		[varBsNavbarTogglerIconBg]: "url(\"data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 30 30'%3e%3cpath stroke='rgba%28255, 255, 255, 0.55%29' stroke-linecap='round' stroke-miterlimit='10' stroke-width='2' d='M4 7h22M4 15h22M4 23h22'/%3e%3c/svg%3e\")",
		[varBsAccordionBtnIcon]: "url(\"data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16' fill='%23aedace'%3e%3cpath fill-rule='evenodd' d='M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708'/%3e%3c/svg%3e\")",
		[varBsAccordionBtnActiveIcon]: "url(\"data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16' fill='%23aedace'%3e%3cpath fill-rule='evenodd' d='M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708'/%3e%3c/svg%3e\")",
		[varBsCarouselIndicatorActiveBg]: "#000",
		[varBsCarouselCaptionColor]: "#000",
		[varBsCarouselControlIconFilter]: "invert(1) grayscale(100)",
	},
})

// ── Root / body styles ────────────────────────────────────────────────────────

globalStyle(`${mintyScope}${bodyText}`, {
	fontFamily: varBsBodyFontFamily,
	fontSize: varBsBodyFontSize,
	fontWeight: varBsBodyFontWeight,
	lineHeight: varBsBodyLineHeight,
	color: varBsBodyColor,
})

globalStyle(`${mintyScope}${body}`, {
	backgroundColor: varBsBodyBg,
	padding: '1rem',
	display: 'block',
})
