import { globalStyle, style } from '@vanilla-extract/css'
import {
	varBsBlack,
	varBsBlackRgb,
	varBsBlue,
	varBsBodyBg,
	varBsBodyBgRgb,
	varBsBodyColor,
	varBsBodyColorRgb,
	varBsBodyFontFamily,
	varBsBodyFontSize,
	varBsBodyFontWeight,
	varBsBodyLineHeight,
	varBsBorderColor,
	varBsBorderColorTranslucent,
	varBsBorderRadius,
	varBsBorderRadiusLg,
	varBsBorderRadiusPill,
	varBsBorderRadiusSm,
	varBsBorderRadiusXl,
	varBsBorderRadiusXxl,
	varBsBorderStyle,
	varBsBorderWidth,
	varBsBoxShadow,
	varBsBoxShadowInset,
	varBsBoxShadowLg,
	varBsBoxShadowSm,
	varBsBtnCloseFilter,
	varBsCarouselCaptionColor,
	varBsCarouselControlIconFilter,
	varBsCarouselIndicatorActiveBg,
	varBsCodeColor,
	varBsCyan,
	varBsDanger,
	varBsDangerBgSubtle,
	varBsDangerBorderSubtle,
	varBsDangerRgb,
	varBsDangerTextEmphasis,
	varBsDark,
	varBsDarkBgSubtle,
	varBsDarkBorderSubtle,
	varBsDarkRgb,
	varBsDarkTextEmphasis,
	varBsEmphasisColor,
	varBsEmphasisColorRgb,
	varBsFocusRingColor,
	varBsFocusRingOpacity,
	varBsFocusRingWidth,
	varBsFontMonospace,
	varBsFontSansSerif,
	varBsGradient,
	varBsGray,
	varBsGrayDark,
	varBsGreen,
	varBsHeadingColor,
	varBsHighlightBg,
	varBsHighlightColor,
	varBsIndigo,
	varBsInfo,
	varBsInfoBgSubtle,
	varBsInfoBorderSubtle,
	varBsInfoRgb,
	varBsInfoTextEmphasis,
	varBsLight,
	varBsLightBgSubtle,
	varBsLightBorderSubtle,
	varBsLightRgb,
	varBsLightTextEmphasis,
	varBsLinkColor,
	varBsLinkColorRgb,
	varBsLinkDecoration,
	varBsLinkHoverColor,
	varBsLinkHoverColorRgb,
	varBsOrange,
	varBsPink,
	varBsPrimary,
	varBsPrimaryBgSubtle,
	varBsPrimaryBorderSubtle,
	varBsPrimaryRgb,
	varBsPrimaryTextEmphasis,
	varBsPurple,
	varBsRed,
	varBsSecondary,
	varBsSecondaryBg,
	varBsSecondaryBgSubtle,
	varBsSecondaryBorderSubtle,
	varBsSecondaryColor,
	varBsSecondaryRgb,
	varBsSecondaryTextEmphasis,
	varBsSuccess,
	varBsSuccessBgSubtle,
	varBsSuccessBorderSubtle,
	varBsSuccessRgb,
	varBsSuccessTextEmphasis,
	varBsTeal,
	varBsTertiaryBg,
	varBsTertiaryColor,
	varBsWarning,
	varBsWarningBgSubtle,
	varBsWarningBorderSubtle,
	varBsWarningRgb,
	varBsWarningTextEmphasis,
	varBsWhite,
	varBsWhiteRgb,
	varBsYellow,
} from '../../theme-contract/_vars.css'
import {
	varBsFormInvalidBorderColor,
	varBsFormInvalidColor,
	varBsFormValidBorderColor,
	varBsFormValidColor,
} from '../../theme-contract/forms/_vars.css'
import { bodyFrame, bodyText, vars } from '../../theme-contract/theme-contract.css'
import { modalOpenHook } from '../../theme-contract/ui/modal/contract.css'

// Minty theme scope class.
// Zero-style identifier used as a stable selector prefix.
export const mintyScope = style({})

// Global Bootstrap CSS custom properties (`--bs-*`) are assigned on the
// dedicated vars contract class to keep root var hosting separate from body
// layout/background styles.
globalStyle(`${mintyScope}${vars}`, {
	vars: {
		[varBsBlue]: "#007bff",
		[varBsIndigo]: "#6610f2",
		[varBsPurple]: "#6f42c1",
		[varBsPink]: "#e83e8c",
		[varBsRed]: "#ff7851",
		[varBsOrange]: "#fd7e14",
		[varBsYellow]: "#ffce67",
		[varBsGreen]: "#56cc9d",
		[varBsTeal]: "#20c997",
		[varBsCyan]: "#6cc3d5",
		[varBsBlack]: "#000",
		[varBsWhite]: "#fff",
		[varBsGray]: "#888",
		[varBsGrayDark]: "#343a40",
		[varBsPrimary]: "#78c2ad",
		[varBsSecondary]: "#f3969a",
		[varBsSuccess]: "#56cc9d",
		[varBsInfo]: "#6cc3d5",
		[varBsWarning]: "#ffce67",
		[varBsDanger]: "#ff7851",
		[varBsLight]: "#f8f9fa",
		[varBsDark]: "#343a40",
		[varBsPrimaryRgb]: "120, 194, 173",
		[varBsSecondaryRgb]: "243, 150, 154",
		[varBsSuccessRgb]: "86, 204, 157",
		[varBsInfoRgb]: "108, 195, 213",
		[varBsWarningRgb]: "255, 206, 103",
		[varBsDangerRgb]: "255, 120, 81",
		[varBsLightRgb]: "248, 249, 250",
		[varBsDarkRgb]: "52, 58, 64",
		[varBsPrimaryTextEmphasis]: "#304e45",
		[varBsSecondaryTextEmphasis]: "#613c3e",
		[varBsSuccessTextEmphasis]: "#22523f",
		[varBsInfoTextEmphasis]: "#2b4e55",
		[varBsWarningTextEmphasis]: "#665229",
		[varBsDangerTextEmphasis]: "#663020",
		[varBsLightTextEmphasis]: "#5a5a5a",
		[varBsDarkTextEmphasis]: "#5a5a5a",
		[varBsPrimaryBgSubtle]: "#e4f3ef",
		[varBsSecondaryBgSubtle]: "#fdeaeb",
		[varBsSuccessBgSubtle]: "#ddf5eb",
		[varBsInfoBgSubtle]: "#e2f3f7",
		[varBsWarningBgSubtle]: "#fff5e1",
		[varBsDangerBgSubtle]: "#ffe4dc",
		[varBsLightBgSubtle]: "#fcfcfd",
		[varBsDarkBgSubtle]: "#ced4da",
		[varBsPrimaryBorderSubtle]: "#c9e7de",
		[varBsSecondaryBorderSubtle]: "#fad5d7",
		[varBsSuccessBorderSubtle]: "#bbebd8",
		[varBsInfoBorderSubtle]: "#c4e7ee",
		[varBsWarningBorderSubtle]: "#ffebc2",
		[varBsDangerBorderSubtle]: "#ffc9b9",
		[varBsLightBorderSubtle]: "#f7f7f9",
		[varBsDarkBorderSubtle]: "#aaa",
		[varBsWhiteRgb]: "255, 255, 255",
		[varBsBlackRgb]: "0, 0, 0",
		[varBsFontSansSerif]: "system-ui, -apple-system, \"Segoe UI\", Roboto, \"Helvetica Neue\", \"Noto Sans\", \"Liberation Sans\", Arial, sans-serif, \"Apple Color Emoji\", \"Segoe UI Emoji\", \"Segoe UI Symbol\", \"Noto Color Emoji\"",
		[varBsFontMonospace]: "SFMono-Regular, Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace",
		[varBsGradient]: "linear-gradient(180deg, rgba(255, 255, 255, 0.15), rgba(255, 255, 255, 0))",
		[varBsBodyFontFamily]: varBsFontSansSerif,
		[varBsBodyFontSize]: "1rem",
		[varBsBodyFontWeight]: 400,
		[varBsBodyLineHeight]: 1.5,
		[varBsBodyColor]: "#888",
		[varBsBodyColorRgb]: "136, 136, 136",
		[varBsBodyBg]: "#fff",
		[varBsBodyBgRgb]: "255, 255, 255",
		[varBsEmphasisColor]: "#000",
		[varBsEmphasisColorRgb]: "0, 0, 0",
		[varBsSecondaryColor]: "rgba(136, 136, 136, 0.75)",
		[varBsSecondaryBg]: "#f7f7f9",
		[varBsTertiaryColor]: "rgba(136, 136, 136, 0.5)",
		[varBsTertiaryBg]: "#f8f9fa",
		[varBsHeadingColor]: "#5a5a5a",
		[varBsLinkColor]: "#78c2ad",
		[varBsLinkColorRgb]: "120, 194, 173",
		[varBsLinkDecoration]: "underline",
		[varBsLinkHoverColor]: "#609b8a",
		[varBsLinkHoverColorRgb]: "96, 155, 138",
		[varBsCodeColor]: "#e83e8c",
		[varBsHighlightColor]: "#888",
		[varBsHighlightBg]: "#fff5e1",
		[varBsBorderWidth]: "1px",
		[varBsBorderStyle]: "solid",
		[varBsBorderColor]: "#eceeef",
		[varBsBorderColorTranslucent]: "rgba(0, 0, 0, 0.175)",
		[varBsBorderRadius]: "0.4rem",
		[varBsBorderRadiusSm]: "0.3rem",
		[varBsBorderRadiusLg]: "0.6rem",
		[varBsBorderRadiusXl]: "1rem",
		[varBsBorderRadiusXxl]: "2rem",
		[varBsBorderRadiusPill]: "50rem",
		[varBsBoxShadow]: "0 0.5rem 1rem rgba(0, 0, 0, 0.15)",
		[varBsBoxShadowSm]: "0 0.125rem 0.25rem rgba(0, 0, 0, 0.075)",
		[varBsBoxShadowLg]: "0 1rem 3rem rgba(0, 0, 0, 0.175)",
		[varBsBoxShadowInset]: "inset 0 1px 2px rgba(0, 0, 0, 0.075)",
		[varBsFocusRingWidth]: "0.25rem",
		[varBsFocusRingOpacity]: 0.25,
		[varBsFocusRingColor]: "rgba(120, 194, 173, 0.25)",
		[varBsBtnCloseFilter]: "",
		[varBsCarouselIndicatorActiveBg]: "#fff",
		[varBsCarouselCaptionColor]: "#fff",
		[varBsCarouselControlIconFilter]: "",
		[varBsFormValidColor]: "#56cc9d",
		[varBsFormValidBorderColor]: "#56cc9d",
		[varBsFormInvalidColor]: "#ff7851",
		[varBsFormInvalidBorderColor]: "#ff7851",
	},
})

// ── Root / body styles ────────────────────────────────────────────────────────
// bodyText = typography; bodyFrame = page canvas (Ve2Shell). Do not add padding
// here — baseline screenshots have no padded wrapper around bd-example.

globalStyle(`${mintyScope}${bodyText}`, {
	fontFamily: varBsBodyFontFamily,
	fontSize: varBsBodyFontSize,
	fontWeight: varBsBodyFontWeight,
	lineHeight: varBsBodyLineHeight,
	color: varBsBodyColor,
})

globalStyle(`${mintyScope}${bodyFrame}`, {
	backgroundColor: varBsBodyBg,
	margin: 0,
	minHeight: '100vh',
})

// Bootstrap Modal JS adds modalOpenHook to <body> without theme scope.
globalStyle(`${modalOpenHook}`, {
	fontFamily: varBsBodyFontFamily,
	fontSize: varBsBodyFontSize,
	fontWeight: varBsBodyFontWeight,
	lineHeight: varBsBodyLineHeight,
	color: varBsBodyColor,
	backgroundColor: varBsBodyBg,
	margin: 0,
})
