import { createVar } from '@vanilla-extract/css'

export const varBsNavLinkPaddingX = createVar()
export const varBsNavLinkPaddingY = createVar()
export const varBsNavLinkFontSize = createVar()
export const varBsNavLinkFontWeight = createVar()
export const varBsNavLinkColor = createVar()
export const varBsNavLinkHoverColor = createVar()
export const varBsNavLinkDisabledColor = createVar()
export const varBsNavTabsBorderWidth = createVar()
export const varBsNavTabsBorderColor = createVar()
export const varBsNavTabsBorderRadius = createVar()
export const varBsNavTabsLinkHoverBorderColor = createVar()
export const varBsNavTabsLinkActiveColor = createVar()
export const varBsNavTabsLinkActiveBg = createVar()
export const varBsNavTabsLinkActiveBorderColor = createVar()
export const varBsNavPillsBorderRadius = createVar()
export const varBsNavPillsLinkActiveColor = createVar()
export const varBsNavPillsLinkActiveBg = createVar()
