// GERADO por scripts/gen-public-vars.mjs — NÃO editar à mão.
import { globalStyle } from '@vanilla-extract/css'
import { sandstoneScope } from './scope.css'
import { varBsBlackRgb, varBsBodyBgRgb, varBsBodyColorRgb, varBsBorderColor, varBsBorderRadius, varBsBorderRadiusLg, varBsBorderRadiusPill, varBsBorderRadiusSm, varBsBorderRadiusXl, varBsBorderRadiusXxl, varBsBorderStyle, varBsBorderWidth, varBsBoxShadow, varBsBoxShadowLg, varBsBoxShadowSm, varBsDangerBgSubtle, varBsDangerBorderSubtle, varBsDangerRgb, varBsDangerTextEmphasis, varBsDarkBgSubtle, varBsDarkBorderSubtle, varBsDarkRgb, varBsDarkTextEmphasis, varBsEmphasisColor, varBsEmphasisColorRgb, varBsFocusRingColor, varBsFocusRingOpacity, varBsFontMonospace, varBsGradient, varBsInfoBgSubtle, varBsInfoBorderSubtle, varBsInfoRgb, varBsInfoTextEmphasis, varBsLightBgSubtle, varBsLightBorderSubtle, varBsLightRgb, varBsLightTextEmphasis, varBsLinkColorRgb, varBsPrimaryBgSubtle, varBsPrimaryBorderSubtle, varBsPrimaryRgb, varBsPrimaryTextEmphasis, varBsSecondaryBgRgb, varBsSecondaryBgSubtle, varBsSecondaryBorderSubtle, varBsSecondaryColor, varBsSecondaryRgb, varBsSecondaryTextEmphasis, varBsSuccessBgSubtle, varBsSuccessBorderSubtle, varBsSuccessRgb, varBsSuccessTextEmphasis, varBsTertiaryBgRgb, varBsTertiaryColor, varBsWarningBgSubtle, varBsWarningBorderSubtle, varBsWarningRgb, varBsWarningTextEmphasis, varBsWhiteRgb } from '../../theme-contract/_public-vars.css'

globalStyle(sandstoneScope, {
	vars: {
		[varBsBlackRgb]: "0, 0, 0",
		[varBsBodyBgRgb]: "255, 255, 255",
		[varBsBodyColorRgb]: "62, 63, 58",
		[varBsBorderColor]: "#dfd7ca",
		[varBsBorderRadius]: "0.375rem",
		[varBsBorderRadiusLg]: "0.5rem",
		[varBsBorderRadiusPill]: "50rem",
		[varBsBorderRadiusSm]: "0.25rem",
		[varBsBorderRadiusXl]: "1rem",
		[varBsBorderRadiusXxl]: "2rem",
		[varBsBorderStyle]: "solid",
		[varBsBorderWidth]: "1px",
		[varBsBoxShadow]: "0 0.5rem 1rem rgba(0, 0, 0, 0.15)",
		[varBsBoxShadowLg]: "0 1rem 3rem rgba(0, 0, 0, 0.175)",
		[varBsBoxShadowSm]: "0 0.125rem 0.25rem rgba(0, 0, 0, 0.075)",
		[varBsDangerBgSubtle]: "#f7dddc",
		[varBsDangerBorderSubtle]: "#f0bab9",
		[varBsDangerRgb]: "217, 83, 79",
		[varBsDangerTextEmphasis]: "#572120",
		[varBsDarkBgSubtle]: "#ced4da",
		[varBsDarkBorderSubtle]: "#98978b",
		[varBsDarkRgb]: "62, 63, 58",
		[varBsDarkTextEmphasis]: "#495057",
		[varBsEmphasisColor]: "#000",
		[varBsEmphasisColorRgb]: "0, 0, 0",
		[varBsFocusRingColor]: "rgba(50, 93, 136, 0.25)",
		[varBsFocusRingOpacity]: "0.25",
		[varBsFontMonospace]: "SFMono-Regular, Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace",
		[varBsGradient]: "linear-gradient(180deg, rgba(255, 255, 255, 0.15), rgba(255, 255, 255, 0))",
		[varBsInfoBgSubtle]: "#d4eef9",
		[varBsInfoBorderSubtle]: "#a9ddf3",
		[varBsInfoRgb]: "41, 171, 224",
		[varBsInfoTextEmphasis]: "#10445a",
		[varBsLightBgSubtle]: "#fcfcfd",
		[varBsLightBorderSubtle]: "#f8f5f0",
		[varBsLightRgb]: "248, 245, 240",
		[varBsLightTextEmphasis]: "#495057",
		[varBsLinkColorRgb]: "147, 197, 75",
		[varBsPrimaryBgSubtle]: "#d6dfe7",
		[varBsPrimaryBorderSubtle]: "#adbecf",
		[varBsPrimaryRgb]: "50, 93, 136",
		[varBsPrimaryTextEmphasis]: "#142536",
		[varBsSecondaryBgRgb]: "248, 245, 240",
		[varBsSecondaryBgSubtle]: "#e8e8e6",
		[varBsSecondaryBorderSubtle]: "#d2d1ce",
		[varBsSecondaryColor]: "rgba(62, 63, 58, 0.75)",
		[varBsSecondaryRgb]: "142, 140, 132",
		[varBsSecondaryTextEmphasis]: "#393835",
		[varBsSuccessBgSubtle]: "#e9f3db",
		[varBsSuccessBorderSubtle]: "#d4e8b7",
		[varBsSuccessRgb]: "147, 197, 75",
		[varBsSuccessTextEmphasis]: "#3b4f1e",
		[varBsTertiaryBgRgb]: "248, 249, 250",
		[varBsTertiaryColor]: "rgba(62, 63, 58, 0.5)",
		[varBsWarningBgSubtle]: "#fde5d8",
		[varBsWarningBorderSubtle]: "#fbcbb1",
		[varBsWarningRgb]: "244, 124, 60",
		[varBsWarningTextEmphasis]: "#623218",
		[varBsWhiteRgb]: "255, 255, 255",
	},
})
