import { globalStyle, style } from '@vanilla-extract/css'
import {
varBsBodyBg,
varBsBodyBgRgb,
varBsBodyColor,
varBsBodyColorRgb,
varBsBodyFontFamily,
varBsFontSansSerif,
varBsBorderColor,
varBsBorderColorTranslucent,
varBsBorderRadius,
varBsBorderRadius2xl,
varBsBorderRadiusLg,
varBsBorderRadiusPill,
varBsBorderRadiusSm,
varBsBorderRadiusXl,
varBsBorderRadiusXxl,
varBsBorderStyle,
varBsBorderWidth,
varBsBoxShadow,
varBsBoxShadowInset,
varBsBoxShadowLg,
varBsBoxShadowSm,
varBsDanger,
varBsDangerBgSubtle,
varBsDangerBorderSubtle,
varBsDangerRgb,
varBsDangerTextEmphasis,
varBsDark,
varBsDarkBgSubtle,
varBsDarkBorderSubtle,
varBsDarkRgb,
varBsDarkTextEmphasis,
varBsFocusRingColor,
varBsFocusRingOpacity,
varBsFocusRingWidth,
varBsInfo,
varBsInfoBgSubtle,
varBsInfoBorderSubtle,
varBsInfoRgb,
varBsInfoTextEmphasis,
varBsLight,
varBsLightBgSubtle,
varBsLightBorderSubtle,
varBsLightRgb,
varBsLightTextEmphasis,
varBsPrimary,
varBsPrimaryBgSubtle,
varBsPrimaryBorderSubtle,
varBsPrimaryRgb,
varBsPrimaryTextEmphasis,
varBsSecondary,
varBsSecondaryBgSubtle,
varBsSecondaryBorderSubtle,
varBsSecondaryRgb,
varBsSecondaryTextEmphasis,
varBsSuccess,
varBsSuccessBgSubtle,
varBsSuccessBorderSubtle,
varBsSuccessRgb,
varBsSuccessTextEmphasis,
varBsWarning,
varBsWarningBgSubtle,
varBsWarningBorderSubtle,
varBsWarningRgb,
varBsWarningTextEmphasis,
varBsEmphasisColor,
varBsEmphasisColorRgb,
varBsSecondaryColor,
varBsSecondaryBg,
varBsTertiaryColor,
varBsTertiaryBg,
varBsHighlightColor,
varBsHighlightBg,
varBsLinkColor,
varBsLinkHoverColor,
varBsCodeColor,
varBsFontMonospace,
} from '../../theme-contract/_vars.css'
import {
varBsFormValidColor,
varBsFormValidBorderColor,
varBsFormInvalidColor,
varBsFormInvalidBorderColor,
} from '../../theme-contract/forms/_vars.css'
import { body, bodyText, bodyFrame, vars } from '../../theme-contract/theme-contract.css'

export const sandstoneScope = style({})

globalStyle(`${sandstoneScope}${vars}`, {
vars: {
[varBsPrimary]: '#325d88',
[varBsSecondary]: '#8e8c84',
[varBsSuccess]: '#93c54b',
[varBsInfo]: '#29abe0',
[varBsWarning]: '#f47c3c',
[varBsDanger]: '#d9534f',
[varBsLight]: '#f8f5f0',
[varBsDark]: '#3e3f3a',
[varBsPrimaryRgb]: '50, 93, 136',
[varBsSecondaryRgb]: '142, 140, 132',
[varBsSuccessRgb]: '147, 197, 75',
[varBsInfoRgb]: '41, 171, 224',
[varBsWarningRgb]: '244, 124, 60',
[varBsDangerRgb]: '217, 83, 79',
[varBsLightRgb]: '248, 245, 240',
[varBsDarkRgb]: '62, 63, 58',
[varBsPrimaryTextEmphasis]: '#142536',
[varBsSecondaryTextEmphasis]: '#393835',
[varBsSuccessTextEmphasis]: '#3b4f1e',
[varBsInfoTextEmphasis]: '#10445a',
[varBsWarningTextEmphasis]: '#623218',
[varBsDangerTextEmphasis]: '#572120',
[varBsLightTextEmphasis]: '#495057',
[varBsDarkTextEmphasis]: '#495057',
[varBsPrimaryBgSubtle]: '#d6dfe7',
[varBsSecondaryBgSubtle]: '#e8e8e6',
[varBsSuccessBgSubtle]: '#e9f3db',
[varBsInfoBgSubtle]: '#d4eef9',
[varBsWarningBgSubtle]: '#fde5d8',
[varBsDangerBgSubtle]: '#f7dddc',
[varBsLightBgSubtle]: '#fcfcfd',
[varBsDarkBgSubtle]: '#ced4da',
[varBsPrimaryBorderSubtle]: '#adbecf',
[varBsSecondaryBorderSubtle]: '#d2d1ce',
[varBsSuccessBorderSubtle]: '#d4e8b7',
[varBsInfoBorderSubtle]: '#a9ddf3',
[varBsWarningBorderSubtle]: '#fbcbb1',
[varBsDangerBorderSubtle]: '#f0bab9',
[varBsLightBorderSubtle]: '#f8f5f0',
[varBsDarkBorderSubtle]: '#98978b',
[varBsFontSansSerif]: 'Roboto, -apple-system, BlinkMacSystemFont, "Segoe UI", "Helvetica Neue", Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"',
[varBsBodyFontFamily]: varBsFontSansSerif,
[varBsBodyColor]: '#3e3f3a',
[varBsBodyColorRgb]: '62, 63, 58',
[varBsBodyBg]: '#fff',
[varBsBodyBgRgb]: '255, 255, 255',
[varBsBorderWidth]: '1px',
[varBsBorderStyle]: 'solid',
[varBsBorderColor]: '#dfd7ca',
[varBsBorderColorTranslucent]: 'rgba(0, 0, 0, 0.175)',
[varBsBorderRadius]: '0.375rem',
[varBsBorderRadiusSm]: '0.25rem',
[varBsBorderRadiusLg]: '0.5rem',
[varBsBorderRadiusXl]: '1rem',
[varBsBorderRadiusXxl]: '2rem',
[varBsBorderRadius2xl]: '2rem',
[varBsBorderRadiusPill]: '50rem',
[varBsBoxShadow]: '0 0.5rem 1rem rgba(0, 0, 0, 0.15)',
[varBsBoxShadowSm]: '0 0.125rem 0.25rem rgba(0, 0, 0, 0.075)',
[varBsBoxShadowLg]: '0 1rem 3rem rgba(0, 0, 0, 0.175)',
[varBsBoxShadowInset]: 'inset 0 1px 2px rgba(0, 0, 0, 0.075)',
[varBsFocusRingWidth]: '0.25rem',
[varBsFocusRingOpacity]: '0.25',
[varBsFocusRingColor]: 'rgba(50, 93, 136, 0.25)',
[varBsEmphasisColor]: '#000',
[varBsEmphasisColorRgb]: '0, 0, 0',
[varBsSecondaryColor]: 'rgba(62, 63, 58, 0.75)',
[varBsSecondaryBg]: '#f8f5f0',
[varBsTertiaryColor]: 'rgba(62, 63, 58, 0.5)',
[varBsTertiaryBg]: '#f8f9fa',
[varBsHighlightColor]: '#3e3f3a',
[varBsHighlightBg]: '#fff3cd',
[varBsLinkColor]: '#93c54b',
[varBsLinkHoverColor]: '#769e3c',
[varBsCodeColor]: '#e83e8c',
[varBsFontMonospace]: 'SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
[varBsFormValidColor]: '#93c54b',
[varBsFormValidBorderColor]: '#93c54b',
[varBsFormInvalidColor]: '#d9534f',
[varBsFormInvalidBorderColor]: '#d9534f',
},
})

globalStyle(`${sandstoneScope}${bodyText}`, {
fontFamily:
'Roboto, -apple-system, BlinkMacSystemFont, "Segoe UI", "Helvetica Neue", Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"',
fontSize: '1rem',
fontWeight: 400,
lineHeight: 1.5,
color: '#3e3f3a',
})

globalStyle(`${sandstoneScope}${body}`, {
backgroundColor: '#fff',
padding: '1rem',
display: 'block',
})

globalStyle(`${sandstoneScope}${bodyFrame}`, {
minHeight: '100vh',
display: 'flow-root',
backgroundColor: '#fff',
})
