import { globalStyle, style } from '@vanilla-extract/css'
import {
	varBsBlack,
	varBsBlackRgb,
	varBsBlue,
	varBsBodyBg,
	varBsBodyBgRgb,
	varBsBodyColor,
	varBsBodyColorRgb,
	varBsBodyFontFamily,
	varBsBodyFontSize,
	varBsBodyFontWeight,
	varBsBodyLineHeight,
	varBsBorderColor,
	varBsBorderColorTranslucent,
	varBsBorderRadius,
	varBsBorderRadiusLg,
	varBsBorderRadiusPill,
	varBsBorderRadiusSm,
	varBsBorderRadiusXl,
	varBsBorderRadiusXxl,
	varBsBorderStyle,
	varBsBorderWidth,
	varBsBoxShadow,
	varBsBoxShadowInset,
	varBsBoxShadowLg,
	varBsBoxShadowSm,
	varBsCarouselCaptionColor,
	varBsCarouselIndicatorActiveBg,
	varBsCodeColor,
	varBsCyan,
	varBsDanger,
	varBsDangerBgSubtle,
	varBsDangerBorderSubtle,
	varBsDangerRgb,
	varBsDangerTextEmphasis,
	varBsDark,
	varBsDarkBgSubtle,
	varBsDarkBorderSubtle,
	varBsDarkRgb,
	varBsDarkTextEmphasis,
	varBsEmphasisColor,
	varBsEmphasisColorRgb,
	varBsFocusRingColor,
	varBsFocusRingOpacity,
	varBsFocusRingWidth,
	varBsFontMonospace,
	varBsFontSansSerif,
	varBsGradient,
	varBsGray,
	varBsGrayDark,
	varBsGreen,
	varBsHeadingColor,
	varBsHighlightBg,
	varBsHighlightColor,
	varBsIndigo,
	varBsInfo,
	varBsInfoBgSubtle,
	varBsInfoBorderSubtle,
	varBsInfoRgb,
	varBsInfoTextEmphasis,
	varBsLight,
	varBsLightBgSubtle,
	varBsLightBorderSubtle,
	varBsLightRgb,
	varBsLightTextEmphasis,
	varBsLinkColor,
	varBsLinkColorRgb,
	varBsLinkDecoration,
	varBsLinkHoverColor,
	varBsLinkHoverColorRgb,
	varBsOrange,
	varBsPink,
	varBsPrimary,
	varBsPrimaryBgSubtle,
	varBsPrimaryBorderSubtle,
	varBsPrimaryRgb,
	varBsPrimaryTextEmphasis,
	varBsPurple,
	varBsRed,
	varBsSecondary,
	varBsSecondaryBg,
	varBsSecondaryBgSubtle,
	varBsSecondaryBorderSubtle,
	varBsSecondaryColor,
	varBsSecondaryRgb,
	varBsSecondaryTextEmphasis,
	varBsSuccess,
	varBsSuccessBgSubtle,
	varBsSuccessBorderSubtle,
	varBsSuccessRgb,
	varBsSuccessTextEmphasis,
	varBsTeal,
	varBsTertiaryBg,
	varBsTertiaryColor,
	varBsWarning,
	varBsWarningBgSubtle,
	varBsWarningBorderSubtle,
	varBsWarningRgb,
	varBsWarningTextEmphasis,
	varBsWhite,
	varBsWhiteRgb,
	varBsYellow,
} from '../../theme-contract/_vars.css'
import {
	varBsFormInvalidBorderColor,
	varBsFormInvalidColor,
	varBsFormValidBorderColor,
	varBsFormValidColor,
} from '../../theme-contract/forms/_vars.css'
import { body, bodyText, vars } from '../../theme-contract/theme-contract.css'

// Sandstone theme scope class.
// Zero-style identifier used as a stable selector prefix.
export const sandstoneScope = style({})

// Global Bootstrap CSS custom properties (`--bs-*`) are assigned on the
// dedicated vars contract class to keep root var hosting separate from body
// layout/background styles.
globalStyle(`${sandstoneScope}${vars}`, {
	vars: {
		[varBsBlue]: "#325d88",
		[varBsIndigo]: "#6610f2",
		[varBsPurple]: "#6f42c1",
		[varBsPink]: "#e83e8c",
		[varBsRed]: "#d9534f",
		[varBsOrange]: "#f47c3c",
		[varBsYellow]: "#ffc107",
		[varBsGreen]: "#93c54b",
		[varBsTeal]: "#20c997",
		[varBsCyan]: "#29abe0",
		[varBsBlack]: "#000",
		[varBsWhite]: "#fff",
		[varBsGray]: "#8e8c84",
		[varBsGrayDark]: "#3e3f3a",
		[varBsPrimary]: "#325d88",
		[varBsSecondary]: "#8e8c84",
		[varBsSuccess]: "#93c54b",
		[varBsInfo]: "#29abe0",
		[varBsWarning]: "#f47c3c",
		[varBsDanger]: "#d9534f",
		[varBsLight]: "#f8f5f0",
		[varBsDark]: "#3e3f3a",
		[varBsPrimaryRgb]: "50, 93, 136",
		[varBsSecondaryRgb]: "142, 140, 132",
		[varBsSuccessRgb]: "147, 197, 75",
		[varBsInfoRgb]: "41, 171, 224",
		[varBsWarningRgb]: "244, 124, 60",
		[varBsDangerRgb]: "217, 83, 79",
		[varBsLightRgb]: "248, 245, 240",
		[varBsDarkRgb]: "62, 63, 58",
		[varBsPrimaryTextEmphasis]: "#142536",
		[varBsSecondaryTextEmphasis]: "#393835",
		[varBsSuccessTextEmphasis]: "#3b4f1e",
		[varBsInfoTextEmphasis]: "#10445a",
		[varBsWarningTextEmphasis]: "#623218",
		[varBsDangerTextEmphasis]: "#572120",
		[varBsLightTextEmphasis]: "#495057",
		[varBsDarkTextEmphasis]: "#495057",
		[varBsPrimaryBgSubtle]: "#d6dfe7",
		[varBsSecondaryBgSubtle]: "#e8e8e6",
		[varBsSuccessBgSubtle]: "#e9f3db",
		[varBsInfoBgSubtle]: "#d4eef9",
		[varBsWarningBgSubtle]: "#fde5d8",
		[varBsDangerBgSubtle]: "#f7dddc",
		[varBsLightBgSubtle]: "#fcfcfd",
		[varBsDarkBgSubtle]: "#ced4da",
		[varBsPrimaryBorderSubtle]: "#adbecf",
		[varBsSecondaryBorderSubtle]: "#d2d1ce",
		[varBsSuccessBorderSubtle]: "#d4e8b7",
		[varBsInfoBorderSubtle]: "#a9ddf3",
		[varBsWarningBorderSubtle]: "#fbcbb1",
		[varBsDangerBorderSubtle]: "#f0bab9",
		[varBsLightBorderSubtle]: "#f8f5f0",
		[varBsDarkBorderSubtle]: "#98978b",
		[varBsWhiteRgb]: "255, 255, 255",
		[varBsBlackRgb]: "0, 0, 0",
		[varBsFontSansSerif]: "Roboto, -apple-system, BlinkMacSystemFont, \"Segoe UI\", \"Helvetica Neue\", Arial, sans-serif, \"Apple Color Emoji\", \"Segoe UI Emoji\", \"Segoe UI Symbol\"",
		[varBsFontMonospace]: "SFMono-Regular, Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace",
		[varBsGradient]: "linear-gradient(180deg, rgba(255, 255, 255, 0.15), rgba(255, 255, 255, 0))",
		[varBsBodyFontFamily]: varBsFontSansSerif,
		[varBsBodyFontSize]: "1rem",
		[varBsBodyFontWeight]: 400,
		[varBsBodyLineHeight]: 1.5,
		[varBsBodyColor]: "#3e3f3a",
		[varBsBodyColorRgb]: "62, 63, 58",
		[varBsBodyBg]: "#fff",
		[varBsBodyBgRgb]: "255, 255, 255",
		[varBsEmphasisColor]: "#000",
		[varBsEmphasisColorRgb]: "0, 0, 0",
		[varBsSecondaryColor]: "rgba(62, 63, 58, 0.75)",
		[varBsSecondaryBg]: "#f8f5f0",
		[varBsTertiaryColor]: "rgba(62, 63, 58, 0.5)",
		[varBsTertiaryBg]: "#f8f9fa",
		[varBsHeadingColor]: "inherit",
		[varBsLinkColor]: "#93c54b",
		[varBsLinkColorRgb]: "147, 197, 75",
		[varBsLinkDecoration]: "underline",
		[varBsLinkHoverColor]: "#769e3c",
		[varBsLinkHoverColorRgb]: "118, 158, 60",
		[varBsCodeColor]: "#e83e8c",
		[varBsHighlightColor]: "#3e3f3a",
		[varBsHighlightBg]: "#fff3cd",
		[varBsBorderWidth]: "1px",
		[varBsBorderStyle]: "solid",
		[varBsBorderColor]: "#dfd7ca",
		[varBsBorderColorTranslucent]: "rgba(0, 0, 0, 0.175)",
		[varBsBorderRadius]: "0.375rem",
		[varBsBorderRadiusSm]: "0.25rem",
		[varBsBorderRadiusLg]: "0.5rem",
		[varBsBorderRadiusXl]: "1rem",
		[varBsBorderRadiusXxl]: "2rem",
		[varBsBorderRadiusPill]: "50rem",
		[varBsBoxShadow]: "0 0.5rem 1rem rgba(0, 0, 0, 0.15)",
		[varBsBoxShadowSm]: "0 0.125rem 0.25rem rgba(0, 0, 0, 0.075)",
		[varBsBoxShadowLg]: "0 1rem 3rem rgba(0, 0, 0, 0.175)",
		[varBsBoxShadowInset]: "inset 0 1px 2px rgba(0, 0, 0, 0.075)",
		[varBsFocusRingWidth]: "0.25rem",
		[varBsFocusRingOpacity]: 0.25,
		[varBsFocusRingColor]: "rgba(50, 93, 136, 0.25)",
		[varBsCarouselIndicatorActiveBg]: "#fff",
		[varBsCarouselCaptionColor]: "#fff",
	},
})

// ── Root / body styles ────────────────────────────────────────────────────────

globalStyle(`${sandstoneScope}${bodyText}`, {
	fontFamily: varBsBodyFontFamily,
	fontSize: varBsBodyFontSize,
	fontWeight: varBsBodyFontWeight,
	lineHeight: varBsBodyLineHeight,
	color: varBsBodyColor,
})

globalStyle(`${sandstoneScope}${body}`, {
	backgroundColor: varBsBodyBg,
	padding: '1rem',
	display: 'block',
})
