// GERADO por scripts/gen-public-vars.mjs — NÃO editar à mão.
import { globalStyle } from '@vanilla-extract/css'
import { morphScope } from './scope.css'
import { varBsBlackRgb, varBsBodyBgRgb, varBsBodyColorRgb, varBsBorderColor, varBsBorderRadius, varBsBorderRadiusLg, varBsBorderRadiusPill, varBsBorderRadiusSm, varBsBorderRadiusXl, varBsBorderRadiusXxl, varBsBorderStyle, varBsBorderWidth, varBsBoxShadow, varBsBoxShadowLg, varBsBoxShadowSm, varBsDangerBgSubtle, varBsDangerBorderSubtle, varBsDangerRgb, varBsDangerTextEmphasis, varBsDarkBgSubtle, varBsDarkBorderSubtle, varBsDarkRgb, varBsDarkTextEmphasis, varBsEmphasisColor, varBsEmphasisColorRgb, varBsFocusRingColor, varBsFocusRingOpacity, varBsFontMonospace, varBsGradient, varBsInfoBgSubtle, varBsInfoBorderSubtle, varBsInfoRgb, varBsInfoTextEmphasis, varBsLightBgSubtle, varBsLightBorderSubtle, varBsLightRgb, varBsLightTextEmphasis, varBsLinkColorRgb, varBsPrimaryBgSubtle, varBsPrimaryBorderSubtle, varBsPrimaryRgb, varBsPrimaryTextEmphasis, varBsSecondaryBgRgb, varBsSecondaryBgSubtle, varBsSecondaryBorderSubtle, varBsSecondaryColor, varBsSecondaryRgb, varBsSecondaryTextEmphasis, varBsSuccessBgSubtle, varBsSuccessBorderSubtle, varBsSuccessRgb, varBsSuccessTextEmphasis, varBsTertiaryBgRgb, varBsTertiaryColor, varBsWarningBgSubtle, varBsWarningBorderSubtle, varBsWarningRgb, varBsWarningTextEmphasis, varBsWhiteRgb } from '../../theme-contract/_public-vars.css'

globalStyle(morphScope, {
	vars: {
		[varBsBlackRgb]: "0, 0, 0",
		[varBsBodyBgRgb]: "217, 227, 241",
		[varBsBodyColorRgb]: "123, 138, 184",
		[varBsBorderColor]: "rgba(55, 94, 148, 0.1)",
		[varBsBorderRadius]: "0.375rem",
		[varBsBorderRadiusLg]: "0.5rem",
		[varBsBorderRadiusPill]: "50rem",
		[varBsBorderRadiusSm]: "0.25rem",
		[varBsBorderRadiusXl]: "1rem",
		[varBsBorderRadiusXxl]: "2rem",
		[varBsBorderStyle]: "solid",
		[varBsBorderWidth]: "0",
		[varBsBoxShadow]: "5px 5px 10px rgba(55, 94, 148, 0.2), -5px -5px 10px rgba(255, 255, 255, 0.4)",
		[varBsBoxShadowLg]: "8px 8px 40px rgba(0, 0, 0, 0.15)",
		[varBsBoxShadowSm]: "0 0.125rem 0.25rem rgba(55, 94, 148, 0.2)",
		[varBsDangerBgSubtle]: "#fad3d4",
		[varBsDangerBorderSubtle]: "#f5a8a9",
		[varBsDangerRgb]: "229, 37, 39",
		[varBsDangerTextEmphasis]: "#5c0f10",
		[varBsDarkBgSubtle]: "#bed1e6",
		[varBsDarkBorderSubtle]: "#adb5bd",
		[varBsDarkRgb]: "33, 37, 41",
		[varBsDarkTextEmphasis]: "#7b8ab8",
		[varBsEmphasisColor]: "#000",
		[varBsEmphasisColorRgb]: "0, 0, 0",
		[varBsFocusRingColor]: "rgba(55, 141, 252, 0.25)",
		[varBsFocusRingOpacity]: "0.25",
		[varBsFontMonospace]: "SFMono-Regular, Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace",
		[varBsGradient]: "linear-gradient(180deg, rgba(255, 255, 255, 0.15), rgba(255, 255, 255, 0))",
		[varBsInfoBgSubtle]: "#dee0fd",
		[varBsInfoBorderSubtle]: "#bdc0fb",
		[varBsInfoRgb]: "91, 98, 244",
		[varBsInfoTextEmphasis]: "#242762",
		[varBsLightBgSubtle]: "#f8fafd",
		[varBsLightBorderSubtle]: "#d9e3f1",
		[varBsLightRgb]: "240, 245, 250",
		[varBsLightTextEmphasis]: "#7b8ab8",
		[varBsLinkColorRgb]: "72, 87, 133",
		[varBsPrimaryBgSubtle]: "#d7e8fe",
		[varBsPrimaryBorderSubtle]: "#afd1fe",
		[varBsPrimaryRgb]: "55, 141, 252",
		[varBsPrimaryTextEmphasis]: "#163865",
		[varBsSecondaryBgRgb]: "217, 227, 241",
		[varBsSecondaryBgSubtle]: "#f7f9fc",
		[varBsSecondaryBorderSubtle]: "#f0f4f9",
		[varBsSecondaryColor]: "rgba(123, 138, 184, 0.75)",
		[varBsSecondaryRgb]: "217, 227, 241",
		[varBsSecondaryTextEmphasis]: "#575b60",
		[varBsSuccessBgSubtle]: "#d9f5d4",
		[varBsSuccessBorderSubtle]: "#b4eba9",
		[varBsSuccessRgb]: "67, 204, 41",
		[varBsSuccessTextEmphasis]: "#1b5210",
		[varBsTertiaryBgRgb]: "240, 245, 250",
		[varBsTertiaryColor]: "rgba(123, 138, 184, 0.5)",
		[varBsWarningBgSubtle]: "#fff3cd",
		[varBsWarningBorderSubtle]: "#ffe69c",
		[varBsWarningRgb]: "255, 193, 7",
		[varBsWarningTextEmphasis]: "#664d03",
		[varBsWhiteRgb]: "255, 255, 255",
	},
})
