import { globalStyle, style } from '@vanilla-extract/css'
import {
	varBsBlack,
	varBsBlackRgb,
	varBsBlue,
	varBsBodyBg,
	varBsBodyBgRgb,
	varBsBodyColor,
	varBsBodyColorRgb,
	varBsBodyFontFamily,
	varBsBodyFontSize,
	varBsBodyFontWeight,
	varBsBodyLineHeight,
	varBsBorderColor,
	varBsBorderColorTranslucent,
	varBsBorderRadius,
	varBsBorderRadiusLg,
	varBsBorderRadiusPill,
	varBsBorderRadiusSm,
	varBsBorderRadiusXl,
	varBsBorderRadiusXxl,
	varBsBorderStyle,
	varBsBorderWidth,
	varBsBoxShadow,
	varBsBoxShadowInset,
	varBsBoxShadowLg,
	varBsBoxShadowSm,
	varBsBtnCloseFilter,
	varBsCarouselCaptionColor,
	varBsCarouselControlIconFilter,
	varBsCarouselIndicatorActiveBg,
	varBsCodeColor,
	varBsCyan,
	varBsDanger,
	varBsDangerBgSubtle,
	varBsDangerBorderSubtle,
	varBsDangerRgb,
	varBsDangerTextEmphasis,
	varBsDark,
	varBsDarkBgSubtle,
	varBsDarkBorderSubtle,
	varBsDarkRgb,
	varBsDarkTextEmphasis,
	varBsEmphasisColor,
	varBsEmphasisColorRgb,
	varBsFocusRingColor,
	varBsFocusRingOpacity,
	varBsFocusRingWidth,
	varBsFontMonospace,
	varBsFontSansSerif,
	varBsGradient,
	varBsGray,
	varBsGrayDark,
	varBsGreen,
	varBsHeadingColor,
	varBsHighlightBg,
	varBsHighlightColor,
	varBsIndigo,
	varBsInfo,
	varBsInfoBgSubtle,
	varBsInfoBorderSubtle,
	varBsInfoRgb,
	varBsInfoTextEmphasis,
	varBsLight,
	varBsLightBgSubtle,
	varBsLightBorderSubtle,
	varBsLightRgb,
	varBsLightTextEmphasis,
	varBsLinkColor,
	varBsLinkColorRgb,
	varBsLinkDecoration,
	varBsLinkHoverColor,
	varBsLinkHoverColorRgb,
	varBsOrange,
	varBsPink,
	varBsPrimary,
	varBsPrimaryBgSubtle,
	varBsPrimaryBorderSubtle,
	varBsPrimaryRgb,
	varBsPrimaryTextEmphasis,
	varBsPurple,
	varBsRed,
	varBsSecondary,
	varBsSecondaryBg,
	varBsSecondaryBgSubtle,
	varBsSecondaryBorderSubtle,
	varBsSecondaryColor,
	varBsSecondaryRgb,
	varBsSecondaryTextEmphasis,
	varBsSuccess,
	varBsSuccessBgSubtle,
	varBsSuccessBorderSubtle,
	varBsSuccessRgb,
	varBsSuccessTextEmphasis,
	varBsTeal,
	varBsTertiaryBg,
	varBsTertiaryColor,
	varBsWarning,
	varBsWarningBgSubtle,
	varBsWarningBorderSubtle,
	varBsWarningRgb,
	varBsWarningTextEmphasis,
	varBsWhite,
	varBsWhiteRgb,
	varBsYellow,
} from '../../theme-contract/_vars.css'
import {
	varBsFormInvalidBorderColor,
	varBsFormInvalidColor,
	varBsFormValidBorderColor,
	varBsFormValidColor,
} from '../../theme-contract/forms/_vars.css'
import { bodyFrame, bodyText, vars } from '../../theme-contract/theme-contract.css'
import { modalOpenHook } from '../../theme-contract/ui/modal/contract.css'

// Morph theme scope class.
// Zero-style identifier used as a stable selector prefix.
export const morphScope = style({})

// Global Bootstrap CSS custom properties (`--bs-*`) are assigned on the
// dedicated vars contract class to keep root var hosting separate from body
// layout/background styles.
globalStyle(`${morphScope}${vars}`, {
	vars: {
		[varBsBlue]: "#378dfc",
		[varBsIndigo]: "#6610f2",
		[varBsPurple]: "#5b62f4",
		[varBsPink]: "#d63384",
		[varBsRed]: "#e52527",
		[varBsOrange]: "#fd7e14",
		[varBsYellow]: "#ffc107",
		[varBsGreen]: "#43cc29",
		[varBsTeal]: "#20c997",
		[varBsCyan]: "#0dcaf0",
		[varBsBlack]: "#000",
		[varBsWhite]: "#fff",
		[varBsGray]: "#7f8a99",
		[varBsGrayDark]: "#444b40",
		[varBsPrimary]: "#378dfc",
		[varBsSecondary]: "#d9e3f1",
		[varBsSuccess]: "#43cc29",
		[varBsInfo]: "#5b62f4",
		[varBsWarning]: "#ffc107",
		[varBsDanger]: "#e52527",
		[varBsLight]: "#f0f5fa",
		[varBsDark]: "#212529",
		[varBsPrimaryRgb]: "55, 141, 252",
		[varBsSecondaryRgb]: "217, 227, 241",
		[varBsSuccessRgb]: "67, 204, 41",
		[varBsInfoRgb]: "91, 98, 244",
		[varBsWarningRgb]: "255, 193, 7",
		[varBsDangerRgb]: "229, 37, 39",
		[varBsLightRgb]: "240, 245, 250",
		[varBsDarkRgb]: "33, 37, 41",
		[varBsPrimaryTextEmphasis]: "#163865",
		[varBsSecondaryTextEmphasis]: "#575b60",
		[varBsSuccessTextEmphasis]: "#1b5210",
		[varBsInfoTextEmphasis]: "#242762",
		[varBsWarningTextEmphasis]: "#664d03",
		[varBsDangerTextEmphasis]: "#5c0f10",
		[varBsLightTextEmphasis]: "#7b8ab8",
		[varBsDarkTextEmphasis]: "#7b8ab8",
		[varBsPrimaryBgSubtle]: "#d7e8fe",
		[varBsSecondaryBgSubtle]: "#f7f9fc",
		[varBsSuccessBgSubtle]: "#d9f5d4",
		[varBsInfoBgSubtle]: "#dee0fd",
		[varBsWarningBgSubtle]: "#fff3cd",
		[varBsDangerBgSubtle]: "#fad3d4",
		[varBsLightBgSubtle]: "#f8fafd",
		[varBsDarkBgSubtle]: "#bed1e6",
		[varBsPrimaryBorderSubtle]: "#afd1fe",
		[varBsSecondaryBorderSubtle]: "#f0f4f9",
		[varBsSuccessBorderSubtle]: "#b4eba9",
		[varBsInfoBorderSubtle]: "#bdc0fb",
		[varBsWarningBorderSubtle]: "#ffe69c",
		[varBsDangerBorderSubtle]: "#f5a8a9",
		[varBsLightBorderSubtle]: "#d9e3f1",
		[varBsDarkBorderSubtle]: "#adb5bd",
		[varBsWhiteRgb]: "255, 255, 255",
		[varBsBlackRgb]: "0, 0, 0",
		[varBsFontSansSerif]: "Nunito, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif, \"Apple Color Emoji\", \"Segoe UI Emoji\", \"Segoe UI Symbol\"",
		[varBsFontMonospace]: "SFMono-Regular, Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace",
		[varBsGradient]: "linear-gradient(180deg, rgba(255, 255, 255, 0.15), rgba(255, 255, 255, 0))",
		[varBsBodyFontFamily]: varBsFontSansSerif,
		[varBsBodyFontSize]: "1rem",
		[varBsBodyFontWeight]: 400,
		[varBsBodyLineHeight]: 1.5,
		[varBsBodyColor]: "#7b8ab8",
		[varBsBodyColorRgb]: "123, 138, 184",
		[varBsBodyBg]: "#d9e3f1",
		[varBsBodyBgRgb]: "217, 227, 241",
		[varBsEmphasisColor]: "#000",
		[varBsEmphasisColorRgb]: "0, 0, 0",
		[varBsSecondaryColor]: "rgba(123, 138, 184, 0.75)",
		[varBsSecondaryBg]: "#d9e3f1",
		[varBsTertiaryColor]: "rgba(123, 138, 184, 0.5)",
		[varBsTertiaryBg]: "#f0f5fa",
		[varBsHeadingColor]: "#485785",
		[varBsLinkColor]: "#485785",
		[varBsLinkColorRgb]: "72, 87, 133",
		[varBsLinkDecoration]: "underline",
		[varBsLinkHoverColor]: "#3a466a",
		[varBsLinkHoverColorRgb]: "58, 70, 106",
		[varBsCodeColor]: "#d63384",
		[varBsHighlightColor]: "#7b8ab8",
		[varBsHighlightBg]: "#fff3cd",
		[varBsBorderWidth]: 0,
		[varBsBorderStyle]: "solid",
		[varBsBorderColor]: "rgba(55, 94, 148, 0.1)",
		[varBsBorderColorTranslucent]: "rgba(0, 0, 0, 0.175)",
		[varBsBorderRadius]: "0.375rem",
		[varBsBorderRadiusSm]: "0.25rem",
		[varBsBorderRadiusLg]: "0.5rem",
		[varBsBorderRadiusXl]: "1rem",
		[varBsBorderRadiusXxl]: "2rem",
		[varBsBorderRadiusPill]: "50rem",
		[varBsBoxShadow]: "5px 5px 10px rgba(55, 94, 148, 0.2), -5px -5px 10px rgba(255, 255, 255, 0.4)",
		[varBsBoxShadowSm]: "0 0.125rem 0.25rem rgba(55, 94, 148, 0.2)",
		[varBsBoxShadowLg]: "8px 8px 40px rgba(0, 0, 0, 0.15)",
		[varBsBoxShadowInset]: "inset 2px 2px 8px rgba(55, 94, 148, 0.3), inset -3px -2px 5px rgba(255, 255, 255, 0.8)",
		[varBsFocusRingWidth]: "0.25rem",
		[varBsFocusRingOpacity]: 0.25,
		[varBsFocusRingColor]: "rgba(55, 141, 252, 0.25)",
		[varBsBtnCloseFilter]: "",
		[varBsCarouselIndicatorActiveBg]: "#fff",
		[varBsCarouselCaptionColor]: "#fff",
		[varBsCarouselControlIconFilter]: "",
		[varBsFormValidColor]: "#43cc29",
		[varBsFormValidBorderColor]: "#43cc29",
		[varBsFormInvalidColor]: "#e52527",
		[varBsFormInvalidBorderColor]: "#e52527",
	},
})

// ── Root / body styles ────────────────────────────────────────────────────────
// bodyText = typography; bodyFrame = page canvas (Ve2Shell). Do not add padding
// here — baseline screenshots have no padded wrapper around bd-example.

globalStyle(`${morphScope}${bodyText}`, {
	fontFamily: varBsBodyFontFamily,
	fontSize: varBsBodyFontSize,
	fontWeight: varBsBodyFontWeight,
	lineHeight: varBsBodyLineHeight,
	color: varBsBodyColor,
})

globalStyle(`${morphScope}${bodyFrame}`, {
	backgroundColor: varBsBodyBg,
	margin: 0,
	minHeight: '100vh',
})

// Bootstrap Modal JS adds modalOpenHook to <body> without theme scope.
globalStyle(`${modalOpenHook}`, {
	fontFamily: varBsBodyFontFamily,
	fontSize: varBsBodyFontSize,
	fontWeight: varBsBodyFontWeight,
	lineHeight: varBsBodyLineHeight,
	color: varBsBodyColor,
	backgroundColor: varBsBodyBg,
	margin: 0,
})
