// GERADO por scripts/gen-public-vars.mjs — NÃO editar à mão.
import { globalStyle } from '@vanilla-extract/css'
import { slateScope } from './scope.css'
import { varBsBlackRgb, varBsBodyBgRgb, varBsBodyColorRgb, varBsBorderColor, varBsBorderRadius, varBsBorderRadiusLg, varBsBorderRadiusPill, varBsBorderRadiusSm, varBsBorderRadiusXl, varBsBorderRadiusXxl, varBsBorderStyle, varBsBorderWidth, varBsBoxShadow, varBsBoxShadowLg, varBsBoxShadowSm, varBsDangerBgSubtle, varBsDangerBorderSubtle, varBsDangerRgb, varBsDangerTextEmphasis, varBsDarkBgSubtle, varBsDarkBorderSubtle, varBsDarkRgb, varBsDarkTextEmphasis, varBsEmphasisColor, varBsEmphasisColorRgb, varBsFocusRingColor, varBsFocusRingOpacity, varBsFontMonospace, varBsGradient, varBsInfoBgSubtle, varBsInfoBorderSubtle, varBsInfoRgb, varBsInfoTextEmphasis, varBsLightBgSubtle, varBsLightBorderSubtle, varBsLightRgb, varBsLightTextEmphasis, varBsLinkColorRgb, varBsPrimaryBgSubtle, varBsPrimaryBorderSubtle, varBsPrimaryRgb, varBsPrimaryTextEmphasis, varBsSecondaryBgRgb, varBsSecondaryBgSubtle, varBsSecondaryBorderSubtle, varBsSecondaryColor, varBsSecondaryRgb, varBsSecondaryTextEmphasis, varBsSuccessBgSubtle, varBsSuccessBorderSubtle, varBsSuccessRgb, varBsSuccessTextEmphasis, varBsTertiaryBgRgb, varBsTertiaryColor, varBsWarningBgSubtle, varBsWarningBorderSubtle, varBsWarningRgb, varBsWarningTextEmphasis, varBsWhiteRgb } from '../../theme-contract/_public-vars.css'

globalStyle(slateScope, {
	vars: {
		[varBsBlackRgb]: "0, 0, 0",
		[varBsBodyBgRgb]: "39, 43, 48",
		[varBsBodyColorRgb]: "170, 170, 170",
		[varBsBorderColor]: "#dee2e6",
		[varBsBorderRadius]: "0.375rem",
		[varBsBorderRadiusLg]: "0.5rem",
		[varBsBorderRadiusPill]: "50rem",
		[varBsBorderRadiusSm]: "0.25rem",
		[varBsBorderRadiusXl]: "1rem",
		[varBsBorderRadiusXxl]: "2rem",
		[varBsBorderStyle]: "solid",
		[varBsBorderWidth]: "1px",
		[varBsBoxShadow]: "0 0.5rem 1rem rgba(0, 0, 0, 0.15)",
		[varBsBoxShadowLg]: "0 1rem 3rem rgba(0, 0, 0, 0.175)",
		[varBsBoxShadowSm]: "0 0.125rem 0.25rem rgba(0, 0, 0, 0.075)",
		[varBsDangerBgSubtle]: "#fcdfde",
		[varBsDangerBorderSubtle]: "#f8bfbd",
		[varBsDangerRgb]: "238, 95, 91",
		[varBsDangerTextEmphasis]: "#5f2624",
		[varBsDarkBgSubtle]: "#ced4da",
		[varBsDarkBorderSubtle]: "#999",
		[varBsDarkRgb]: "39, 43, 48",
		[varBsDarkTextEmphasis]: "#52575c",
		[varBsEmphasisColor]: "#000",
		[varBsEmphasisColorRgb]: "0, 0, 0",
		[varBsFocusRingColor]: "rgba(58, 63, 68, 0.25)",
		[varBsFocusRingOpacity]: "0.25",
		[varBsFontMonospace]: "SFMono-Regular, Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace",
		[varBsGradient]: "linear-gradient(180deg, rgba(255, 255, 255, 0.15), rgba(255, 255, 255, 0))",
		[varBsInfoBgSubtle]: "#def2f8",
		[varBsInfoBorderSubtle]: "#bde6f2",
		[varBsInfoRgb]: "91, 192, 222",
		[varBsInfoTextEmphasis]: "#244d59",
		[varBsLightBgSubtle]: "#fcfcfd",
		[varBsLightBorderSubtle]: "#e9ecef",
		[varBsLightRgb]: "233, 236, 239",
		[varBsLightTextEmphasis]: "#52575c",
		[varBsLinkColorRgb]: "255, 255, 255",
		[varBsPrimaryBgSubtle]: "#515960",
		[varBsPrimaryBorderSubtle]: "#b0b2b4",
		[varBsPrimaryRgb]: "58, 63, 68",
		[varBsPrimaryTextEmphasis]: "#17191b",
		[varBsSecondaryBgRgb]: "233, 236, 239",
		[varBsSecondaryBgSubtle]: "#e4e6e7",
		[varBsSecondaryBorderSubtle]: "#cacdcf",
		[varBsSecondaryColor]: "rgba(170, 170, 170, 0.75)",
		[varBsSecondaryRgb]: "122, 130, 136",
		[varBsSecondaryTextEmphasis]: "#313436",
		[varBsSuccessBgSubtle]: "#e0f3e0",
		[varBsSuccessBorderSubtle]: "#c0e7c0",
		[varBsSuccessRgb]: "98, 196, 98",
		[varBsSuccessTextEmphasis]: "#274e27",
		[varBsTertiaryBgRgb]: "248, 249, 250",
		[varBsTertiaryColor]: "rgba(170, 170, 170, 0.5)",
		[varBsWarningBgSubtle]: "#feeacd",
		[varBsWarningBorderSubtle]: "#fcd49b",
		[varBsWarningRgb]: "248, 148, 6",
		[varBsWarningTextEmphasis]: "#633b02",
		[varBsWhiteRgb]: "255, 255, 255",
	},
})
