import { globalStyle, style } from '@vanilla-extract/css'
import {
	varBsBlack,
	varBsBlackRgb,
	varBsBlue,
	varBsBodyBg,
	varBsBodyBgRgb,
	varBsBodyColor,
	varBsBodyColorRgb,
	varBsBodyFontFamily,
	varBsBodyFontSize,
	varBsBodyFontWeight,
	varBsBodyLineHeight,
	varBsBorderColor,
	varBsBorderColorTranslucent,
	varBsBorderRadius,
	varBsBorderRadiusLg,
	varBsBorderRadiusPill,
	varBsBorderRadiusSm,
	varBsBorderRadiusXl,
	varBsBorderRadiusXxl,
	varBsBorderStyle,
	varBsBorderWidth,
	varBsBoxShadow,
	varBsBoxShadowInset,
	varBsBoxShadowLg,
	varBsBoxShadowSm,
	varBsCarouselCaptionColor,
	varBsCarouselIndicatorActiveBg,
	varBsCodeColor,
	varBsCyan,
	varBsDanger,
	varBsDangerBgSubtle,
	varBsDangerBorderSubtle,
	varBsDangerRgb,
	varBsDangerTextEmphasis,
	varBsDark,
	varBsDarkBgSubtle,
	varBsDarkBorderSubtle,
	varBsDarkRgb,
	varBsDarkTextEmphasis,
	varBsEmphasisColor,
	varBsEmphasisColorRgb,
	varBsFocusRingColor,
	varBsFocusRingOpacity,
	varBsFocusRingWidth,
	varBsFontMonospace,
	varBsFontSansSerif,
	varBsGradient,
	varBsGray,
	varBsGrayDark,
	varBsGreen,
	varBsHeadingColor,
	varBsHighlightBg,
	varBsHighlightColor,
	varBsIndigo,
	varBsInfo,
	varBsInfoBgSubtle,
	varBsInfoBorderSubtle,
	varBsInfoRgb,
	varBsInfoTextEmphasis,
	varBsLight,
	varBsLightBgSubtle,
	varBsLightBorderSubtle,
	varBsLightRgb,
	varBsLightTextEmphasis,
	varBsLinkColor,
	varBsLinkColorRgb,
	varBsLinkDecoration,
	varBsLinkHoverColor,
	varBsLinkHoverColorRgb,
	varBsOrange,
	varBsPink,
	varBsPrimary,
	varBsPrimaryBgSubtle,
	varBsPrimaryBorderSubtle,
	varBsPrimaryRgb,
	varBsPrimaryTextEmphasis,
	varBsPurple,
	varBsRed,
	varBsSecondary,
	varBsSecondaryBg,
	varBsSecondaryBgSubtle,
	varBsSecondaryBorderSubtle,
	varBsSecondaryColor,
	varBsSecondaryRgb,
	varBsSecondaryTextEmphasis,
	varBsSuccess,
	varBsSuccessBgSubtle,
	varBsSuccessBorderSubtle,
	varBsSuccessRgb,
	varBsSuccessTextEmphasis,
	varBsTeal,
	varBsTertiaryBg,
	varBsTertiaryColor,
	varBsWarning,
	varBsWarningBgSubtle,
	varBsWarningBorderSubtle,
	varBsWarningRgb,
	varBsWarningTextEmphasis,
	varBsWhite,
	varBsWhiteRgb,
	varBsYellow,
} from '../../theme-contract/_vars.css'
import {
	varBsFormInvalidBorderColor,
	varBsFormInvalidColor,
	varBsFormValidBorderColor,
	varBsFormValidColor,
} from '../../theme-contract/forms/_vars.css'
import { bodyFrame, bodyText, vars } from '../../theme-contract/theme-contract.css'
import { modalOpenHook } from '../../theme-contract/ui/modal/contract.css'

// Slate theme scope class.
// Zero-style identifier used as a stable selector prefix.
export const slateScope = style({})

// Global Bootstrap CSS custom properties (`--bs-*`) are assigned on the
// dedicated vars contract class to keep root var hosting separate from body
// layout/background styles.
globalStyle(`${slateScope}${vars}`, {
	vars: {
		[varBsBlue]: "#007bff",
		[varBsIndigo]: "#6610f2",
		[varBsPurple]: "#6f42c1",
		[varBsPink]: "#e83e8c",
		[varBsRed]: "#ee5f5b",
		[varBsOrange]: "#fd7e14",
		[varBsYellow]: "#f89406",
		[varBsGreen]: "#62c462",
		[varBsTeal]: "#20c997",
		[varBsCyan]: "#5bc0de",
		[varBsBlack]: "#000",
		[varBsWhite]: "#fff",
		[varBsGray]: "#7a8288",
		[varBsGrayDark]: "#3a3f44",
		[varBsPrimary]: "#3a3f44",
		[varBsSecondary]: "#7a8288",
		[varBsSuccess]: "#62c462",
		[varBsInfo]: "#5bc0de",
		[varBsWarning]: "#f89406",
		[varBsDanger]: "#ee5f5b",
		[varBsLight]: "#e9ecef",
		[varBsDark]: "#272b30",
		[varBsPrimaryRgb]: "58, 63, 68",
		[varBsSecondaryRgb]: "122, 130, 136",
		[varBsSuccessRgb]: "98, 196, 98",
		[varBsInfoRgb]: "91, 192, 222",
		[varBsWarningRgb]: "248, 148, 6",
		[varBsDangerRgb]: "238, 95, 91",
		[varBsLightRgb]: "233, 236, 239",
		[varBsDarkRgb]: "39, 43, 48",
		[varBsPrimaryTextEmphasis]: "#17191b",
		[varBsSecondaryTextEmphasis]: "#313436",
		[varBsSuccessTextEmphasis]: "#274e27",
		[varBsInfoTextEmphasis]: "#244d59",
		[varBsWarningTextEmphasis]: "#633b02",
		[varBsDangerTextEmphasis]: "#5f2624",
		[varBsLightTextEmphasis]: "#52575c",
		[varBsDarkTextEmphasis]: "#52575c",
		[varBsPrimaryBgSubtle]: "#515960",
		[varBsSecondaryBgSubtle]: "#e4e6e7",
		[varBsSuccessBgSubtle]: "#e0f3e0",
		[varBsInfoBgSubtle]: "#def2f8",
		[varBsWarningBgSubtle]: "#feeacd",
		[varBsDangerBgSubtle]: "#fcdfde",
		[varBsLightBgSubtle]: "#fcfcfd",
		[varBsDarkBgSubtle]: "#ced4da",
		[varBsPrimaryBorderSubtle]: "#b0b2b4",
		[varBsSecondaryBorderSubtle]: "#cacdcf",
		[varBsSuccessBorderSubtle]: "#c0e7c0",
		[varBsInfoBorderSubtle]: "#bde6f2",
		[varBsWarningBorderSubtle]: "#fcd49b",
		[varBsDangerBorderSubtle]: "#f8bfbd",
		[varBsLightBorderSubtle]: "#e9ecef",
		[varBsDarkBorderSubtle]: "#999",
		[varBsWhiteRgb]: "255, 255, 255",
		[varBsBlackRgb]: "0, 0, 0",
		[varBsFontSansSerif]: "system-ui, -apple-system, \"Segoe UI\", Roboto, \"Helvetica Neue\", \"Noto Sans\", \"Liberation Sans\", Arial, sans-serif, \"Apple Color Emoji\", \"Segoe UI Emoji\", \"Segoe UI Symbol\", \"Noto Color Emoji\"",
		[varBsFontMonospace]: "SFMono-Regular, Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace",
		[varBsGradient]: "linear-gradient(180deg, rgba(255, 255, 255, 0.15), rgba(255, 255, 255, 0))",
		[varBsBodyFontFamily]: varBsFontSansSerif,
		[varBsBodyFontSize]: "1rem",
		[varBsBodyFontWeight]: 400,
		[varBsBodyLineHeight]: 1.5,
		[varBsBodyColor]: "#aaa",
		[varBsBodyColorRgb]: "170, 170, 170",
		[varBsBodyBg]: "#272b30",
		[varBsBodyBgRgb]: "39, 43, 48",
		[varBsEmphasisColor]: "#000",
		[varBsEmphasisColorRgb]: "0, 0, 0",
		[varBsSecondaryColor]: "rgba(170, 170, 170, 0.75)",
		[varBsSecondaryBg]: "#e9ecef",
		[varBsTertiaryColor]: "rgba(170, 170, 170, 0.5)",
		[varBsTertiaryBg]: "#f8f9fa",
		[varBsHeadingColor]: "inherit",
		[varBsLinkColor]: "#fff",
		[varBsLinkColorRgb]: "255, 255, 255",
		[varBsLinkDecoration]: "underline",
		[varBsLinkHoverColor]: "#cccccc",
		[varBsLinkHoverColorRgb]: "204, 204, 204",
		[varBsCodeColor]: "#e83e8c",
		[varBsHighlightColor]: "#aaa",
		[varBsHighlightBg]: "#feeacd",
		[varBsBorderWidth]: "1px",
		[varBsBorderStyle]: "solid",
		[varBsBorderColor]: "#dee2e6",
		[varBsBorderColorTranslucent]: "rgba(0, 0, 0, 0.175)",
		[varBsBorderRadius]: "0.375rem",
		[varBsBorderRadiusSm]: "0.25rem",
		[varBsBorderRadiusLg]: "0.5rem",
		[varBsBorderRadiusXl]: "1rem",
		[varBsBorderRadiusXxl]: "2rem",
		[varBsBorderRadiusPill]: "50rem",
		[varBsBoxShadow]: "0 0.5rem 1rem rgba(0, 0, 0, 0.15)",
		[varBsBoxShadowSm]: "0 0.125rem 0.25rem rgba(0, 0, 0, 0.075)",
		[varBsBoxShadowLg]: "0 1rem 3rem rgba(0, 0, 0, 0.175)",
		[varBsBoxShadowInset]: "inset 0 1px 2px rgba(0, 0, 0, 0.075)",
		[varBsFocusRingWidth]: "0.25rem",
		[varBsFocusRingOpacity]: 0.25,
		[varBsFocusRingColor]: "rgba(58, 63, 68, 0.25)",
		[varBsCarouselIndicatorActiveBg]: "#fff",
		[varBsCarouselCaptionColor]: "#fff",
		[varBsFormValidColor]: "#62c462",
		[varBsFormValidBorderColor]: "#62c462",
		[varBsFormInvalidColor]: "#ee5f5b",
		[varBsFormInvalidBorderColor]: "#ee5f5b",
	},
})

// ── Root / body styles ────────────────────────────────────────────────────────
// bodyText = typography; bodyFrame = page canvas (Ve2Shell). Do not add padding
// here — baseline screenshots have no padded wrapper around bd-example.

globalStyle(`${slateScope}${bodyText}`, {
	fontFamily: varBsBodyFontFamily,
	fontSize: varBsBodyFontSize,
	fontWeight: varBsBodyFontWeight,
	lineHeight: varBsBodyLineHeight,
	color: varBsBodyColor,
})

globalStyle(`${slateScope}${bodyFrame}`, {
	backgroundColor: varBsBodyBg,
	margin: 0,
	minHeight: '100vh',
})

// Bootstrap Modal JS adds modalOpenHook to <body> without theme scope.
globalStyle(`${modalOpenHook}`, {
	fontFamily: varBsBodyFontFamily,
	fontSize: varBsBodyFontSize,
	fontWeight: varBsBodyFontWeight,
	lineHeight: varBsBodyLineHeight,
	color: varBsBodyColor,
	backgroundColor: varBsBodyBg,
	margin: 0,
})
